py27 develop-inst-nodeps: /Users/nvcastet/Documents/workspace/pypowervm
py27 installed: astroid==1.3.8,automaton==0.8.0,Babel==2.1.1,cachetools==1.1.5,contextlib2==0.4.0,coverage==4.0.2,debtcollector==0.10.0,decorator==4.0.4,discover==0.4.0,docutils==0.12,enum34==1.0.4,extras==0.0.3,fasteners==0.14.1,fixtures==1.4.0,flake8==2.2.4,funcsigs==0.4,functools32==3.2.3.post2,futures==3.0.3,futurist==0.8.0,hacking==0.10.2,iso8601==0.1.11,Jinja2==2.8,jsonschema==2.5.1,linecache2==1.0.0,logilab-common==1.1.0,lxml==3.5.0,MarkupSafe==0.23,mccabe==0.2.1,mock==1.3.0,monotonic==0.4,msgpack-python==0.4.6,netaddr==0.7.18,netifaces==0.10.4,networkx==1.10,oslo.concurrency==2.8.0,oslo.config==2.7.0,oslo.context==0.9.0,oslo.i18n==2.7.0,oslo.log==1.14.0,oslo.serialization==1.11.0,oslo.utils==2.8.0,oslosphinx==3.4.1,pbr==1.8.1,pep8==1.5.7,prettytable==0.7.2,psutil==1.2.1,pyasn1==0.1.9,pyasn1-modules==0.0.8,pyflakes==0.8.1,Pygments==2.0.2,pylint==1.4.4,-e git+ssh://nvcastet@morpheus.rch.stglabs.ibm.com:29418/pypowervm.git@8f949a33629d9c1d5e122011e89b1b88cc1a9e29#egg=pypowervm-fix_powerOff_flow,python-mimeparse==0.1.4,python-subunit==1.2.0,pytz==2015.7,requests==2.8.1,retrying==1.3.3,six==1.10.0,Sphinx==1.2.3,stevedore==1.9.0,taskflow==1.24.0,testrepository==0.0.20,testscenarios==0.5.0,testtools==1.8.1,traceback2==1.4.0,unittest2==1.1.0,wheel==0.24.0,wrapt==1.10.5
py27 runtests: PYTHONHASHSEED='3892649635'
py27 runtests: commands[0] | find . -type f -name *.pyc -delete
py27 runtests: commands[1] | python setup.py testr --slowest --testr-args=pypowervm.tests.tasks.test_power
running testr
ERROR:pypowervm.tasks.power:Error: The 'HSCL1558' operation failed. PowerOff
Traceback (most recent call last):
  File "pypowervm/tasks/power.py", line 181, in _power_on_off
    synchronous=synchronous)
  File "/Users/nvcastet/Documents/workspace/pypowervm/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1062, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/Users/nvcastet/Documents/workspace/pypowervm/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1118, in _mock_call
    raise effect
JobRequestFailed: The 'HSCL1558' operation failed. PowerOff
ERROR:pypowervm.tasks.power:Error: The 'PVME04000005' operation failed. PowerOff
Traceback (most recent call last):
  File "pypowervm/tasks/power.py", line 181, in _power_on_off
    synchronous=synchronous)
  File "/Users/nvcastet/Documents/workspace/pypowervm/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1062, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/Users/nvcastet/Documents/workspace/pypowervm/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1118, in _mock_call
    raise effect
JobRequestFailed: The 'PVME04000005' operation failed. PowerOff
ERROR:pypowervm.tasks.power:Error: The 'HSCL3681' operation failed. PowerOn
Traceback (most recent call last):
  File "pypowervm/tasks/power.py", line 181, in _power_on_off
    synchronous=synchronous)
  File "/Users/nvcastet/Documents/workspace/pypowervm/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1062, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/Users/nvcastet/Documents/workspace/pypowervm/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1118, in _mock_call
    raise effect
JobRequestFailed: The 'HSCL3681' operation failed. PowerOn
ERROR:pypowervm.tasks.power:Error: The 'PVME01042026' operation failed. PowerOn
Traceback (most recent call last):
  File "pypowervm/tasks/power.py", line 181, in _power_on_off
    synchronous=synchronous)
  File "/Users/nvcastet/Documents/workspace/pypowervm/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1062, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/Users/nvcastet/Documents/workspace/pypowervm/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1118, in _mock_call
    raise effect
JobRequestFailed: The 'PVME01042026' operation failed. PowerOn
ERROR:pypowervm.tasks.power:The 'PowerOff' operation failed. Failed to complete the task in 60 seconds.
Traceback (most recent call last):
  File "pypowervm/tasks/power.py", line 181, in _power_on_off
    synchronous=synchronous)
  File "/Users/nvcastet/Documents/workspace/pypowervm/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1062, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/Users/nvcastet/Documents/workspace/pypowervm/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1118, in _mock_call
    raise effect
JobRequestTimedOut: The 'PowerOff' operation failed. Failed to complete the task in 60 seconds.
ERROR:pypowervm.tasks.power:The 'PowerOff' operation failed. Failed to complete the task in 60 seconds.
Traceback (most recent call last):
  File "pypowervm/tasks/power.py", line 181, in _power_on_off
    synchronous=synchronous)
  File "/Users/nvcastet/Documents/workspace/pypowervm/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1062, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/Users/nvcastet/Documents/workspace/pypowervm/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1118, in _mock_call
    raise effect
JobRequestTimedOut: The 'PowerOff' operation failed. Failed to complete the task in 60 seconds.
ERROR:pypowervm.tasks.power:Error: The 'HSCL0DB4' operation failed. PowerOff
Traceback (most recent call last):
  File "pypowervm/tasks/power.py", line 181, in _power_on_off
    synchronous=synchronous)
  File "/Users/nvcastet/Documents/workspace/pypowervm/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1062, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/Users/nvcastet/Documents/workspace/pypowervm/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1123, in _mock_call
    raise result
JobRequestFailed: The 'HSCL0DB4' operation failed. PowerOff
ERROR:pypowervm.tasks.power:The 'PowerOff' operation failed. Failed to complete the task in 60 seconds.
Traceback (most recent call last):
  File "pypowervm/tasks/power.py", line 181, in _power_on_off
    synchronous=synchronous)
  File "/Users/nvcastet/Documents/workspace/pypowervm/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1062, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/Users/nvcastet/Documents/workspace/pypowervm/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1123, in _mock_call
    raise result
JobRequestTimedOut: The 'PowerOff' operation failed. Failed to complete the task in 60 seconds.
ERROR:pypowervm.tasks.power:The 'PowerOff' operation failed. Failed to complete the task in 60 seconds.
Traceback (most recent call last):
  File "pypowervm/tasks/power.py", line 181, in _power_on_off
    synchronous=synchronous)
  File "/Users/nvcastet/Documents/workspace/pypowervm/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1062, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/Users/nvcastet/Documents/workspace/pypowervm/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1118, in _mock_call
    raise effect
JobRequestTimedOut: The 'PowerOff' operation failed. Failed to complete the task in 60 seconds.
ERROR:pypowervm.tasks.power:Error: The 'HSCL0DB4' operation failed. PowerOff
Traceback (most recent call last):
  File "pypowervm/tasks/power.py", line 181, in _power_on_off
    synchronous=synchronous)
  File "/Users/nvcastet/Documents/workspace/pypowervm/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1062, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/Users/nvcastet/Documents/workspace/pypowervm/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1118, in _mock_call
    raise effect
JobRequestFailed: The 'HSCL0DB4' operation failed. PowerOff
ERROR:pypowervm.tasks.power:Error: The 'HSCL0DB4' operation failed. PowerOff
Traceback (most recent call last):
  File "pypowervm/tasks/power.py", line 181, in _power_on_off
    synchronous=synchronous)
  File "/Users/nvcastet/Documents/workspace/pypowervm/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1062, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/Users/nvcastet/Documents/workspace/pypowervm/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1118, in _mock_call
    raise effect
JobRequestFailed: The 'HSCL0DB4' operation failed. PowerOff
ERROR:pypowervm.tasks.power:Error: The 'HSCL0DB4' operation failed. PowerOff
Traceback (most recent call last):
  File "pypowervm/tasks/power.py", line 181, in _power_on_off
    synchronous=synchronous)
  File "/Users/nvcastet/Documents/workspace/pypowervm/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1062, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/Users/nvcastet/Documents/workspace/pypowervm/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1118, in _mock_call
    raise effect
JobRequestFailed: The 'HSCL0DB4' operation failed. PowerOff
ERROR:pypowervm.tasks.power:Error: The 'PVME01050905' operation failed. PowerOff
Traceback (most recent call last):
  File "pypowervm/tasks/power.py", line 181, in _power_on_off
    synchronous=synchronous)
  File "/Users/nvcastet/Documents/workspace/pypowervm/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1062, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/Users/nvcastet/Documents/workspace/pypowervm/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1118, in _mock_call
    raise effect
JobRequestFailed: The 'PVME01050905' operation failed. PowerOff
ERROR:pypowervm.tasks.power:Error: The 'PVME01050905' operation failed. PowerOff
Traceback (most recent call last):
  File "pypowervm/tasks/power.py", line 181, in _power_on_off
    synchronous=synchronous)
  File "/Users/nvcastet/Documents/workspace/pypowervm/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1062, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/Users/nvcastet/Documents/workspace/pypowervm/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1118, in _mock_call
    raise effect
JobRequestFailed: The 'PVME01050905' operation failed. PowerOff
ERROR:pypowervm.tasks.power:Error: The 'PVME01050905' operation failed. PowerOff
Traceback (most recent call last):
  File "pypowervm/tasks/power.py", line 181, in _power_on_off
    synchronous=synchronous)
  File "/Users/nvcastet/Documents/workspace/pypowervm/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1062, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/Users/nvcastet/Documents/workspace/pypowervm/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1118, in _mock_call
    raise effect
JobRequestFailed: The 'PVME01050905' operation failed. PowerOff
ERROR:pypowervm.tasks.power:Error: The 'PVME01050402' operation failed. PowerOff
Traceback (most recent call last):
  File "pypowervm/tasks/power.py", line 181, in _power_on_off
    synchronous=synchronous)
  File "/Users/nvcastet/Documents/workspace/pypowervm/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1062, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/Users/nvcastet/Documents/workspace/pypowervm/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1118, in _mock_call
    raise effect
JobRequestFailed: The 'PVME01050402' operation failed. PowerOff
ERROR:pypowervm.tasks.power:Error: The 'PVME01050402' operation failed. PowerOff
Traceback (most recent call last):
  File "pypowervm/tasks/power.py", line 181, in _power_on_off
    synchronous=synchronous)
  File "/Users/nvcastet/Documents/workspace/pypowervm/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1062, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/Users/nvcastet/Documents/workspace/pypowervm/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1118, in _mock_call
    raise effect
JobRequestFailed: The 'PVME01050402' operation failed. PowerOff
ERROR:pypowervm.tasks.power:Error: The 'PVME01050402' operation failed. PowerOff
Traceback (most recent call last):
  File "pypowervm/tasks/power.py", line 181, in _power_on_off
    synchronous=synchronous)
  File "/Users/nvcastet/Documents/workspace/pypowervm/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1062, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/Users/nvcastet/Documents/workspace/pypowervm/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1118, in _mock_call
    raise effect
JobRequestFailed: The 'PVME01050402' operation failed. PowerOff
ERROR:pypowervm.tasks.power:Error: The 'HSCL0DB4' operation failed. PowerOff
Traceback (most recent call last):
  File "pypowervm/tasks/power.py", line 181, in _power_on_off
    synchronous=synchronous)
  File "/Users/nvcastet/Documents/workspace/pypowervm/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1062, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/Users/nvcastet/Documents/workspace/pypowervm/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1118, in _mock_call
    raise effect
JobRequestFailed: The 'HSCL0DB4' operation failed. PowerOff
ERROR:pypowervm.tasks.power:Error: The 'HSCL3681' operation failed. PowerOn
Traceback (most recent call last):
  File "pypowervm/tasks/power.py", line 181, in _power_on_off
    synchronous=synchronous)
  File "/Users/nvcastet/Documents/workspace/pypowervm/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1062, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/Users/nvcastet/Documents/workspace/pypowervm/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1118, in _mock_call
    raise effect
JobRequestFailed: The 'HSCL3681' operation failed. PowerOn
ERROR:pypowervm.tasks.power:Error: The 'HSCL0DB4' operation failed. PowerOff
Traceback (most recent call last):
  File "pypowervm/tasks/power.py", line 181, in _power_on_off
    synchronous=synchronous)
  File "/Users/nvcastet/Documents/workspace/pypowervm/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1062, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/Users/nvcastet/Documents/workspace/pypowervm/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1118, in _mock_call
    raise effect
JobRequestFailed: The 'HSCL0DB4' operation failed. PowerOff
ERROR:pypowervm.tasks.power:Error: The 'PVME01042026' operation failed. PowerOn
Traceback (most recent call last):
  File "pypowervm/tasks/power.py", line 181, in _power_on_off
    synchronous=synchronous)
  File "/Users/nvcastet/Documents/workspace/pypowervm/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1062, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/Users/nvcastet/Documents/workspace/pypowervm/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1118, in _mock_call
    raise effect
JobRequestFailed: The 'PVME01042026' operation failed. PowerOn
ERROR:pypowervm.tasks.power:Error: The 'HSCL0DB4' operation failed. PowerOff
Traceback (most recent call last):
  File "pypowervm/tasks/power.py", line 181, in _power_on_off
    synchronous=synchronous)
  File "/Users/nvcastet/Documents/workspace/pypowervm/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1062, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/Users/nvcastet/Documents/workspace/pypowervm/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1118, in _mock_call
    raise effect
JobRequestFailed: The 'HSCL0DB4' operation failed. PowerOff
ERROR:pypowervm.tasks.power:Error: The 'PVME01050905' operation failed. PowerOff
Traceback (most recent call last):
  File "pypowervm/tasks/power.py", line 181, in _power_on_off
    synchronous=synchronous)
  File "/Users/nvcastet/Documents/workspace/pypowervm/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1062, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/Users/nvcastet/Documents/workspace/pypowervm/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1118, in _mock_call
    raise effect
JobRequestFailed: The 'PVME01050905' operation failed. PowerOff
ERROR:pypowervm.tasks.power:Error: The 'PVME01050905' operation failed. PowerOff
Traceback (most recent call last):
  File "pypowervm/tasks/power.py", line 181, in _power_on_off
    synchronous=synchronous)
  File "/Users/nvcastet/Documents/workspace/pypowervm/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1062, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/Users/nvcastet/Documents/workspace/pypowervm/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1118, in _mock_call
    raise effect
JobRequestFailed: The 'PVME01050905' operation failed. PowerOff
ERROR:pypowervm.tasks.power:Error: The 'PVME01050905' operation failed. PowerOff
Traceback (most recent call last):
  File "pypowervm/tasks/power.py", line 181, in _power_on_off
    synchronous=synchronous)
  File "/Users/nvcastet/Documents/workspace/pypowervm/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1062, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/Users/nvcastet/Documents/workspace/pypowervm/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1118, in _mock_call
    raise effect
JobRequestFailed: The 'PVME01050905' operation failed. PowerOff
ERROR:pypowervm.tasks.power:Error: The 'PVME01050402' operation failed. PowerOff
Traceback (most recent call last):
  File "pypowervm/tasks/power.py", line 181, in _power_on_off
    synchronous=synchronous)
  File "/Users/nvcastet/Documents/workspace/pypowervm/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1062, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/Users/nvcastet/Documents/workspace/pypowervm/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1118, in _mock_call
    raise effect
JobRequestFailed: The 'PVME01050402' operation failed. PowerOff
ERROR:pypowervm.tasks.power:Error: The 'PVME01050402' operation failed. PowerOff
Traceback (most recent call last):
  File "pypowervm/tasks/power.py", line 181, in _power_on_off
    synchronous=synchronous)
  File "/Users/nvcastet/Documents/workspace/pypowervm/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1062, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/Users/nvcastet/Documents/workspace/pypowervm/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1118, in _mock_call
    raise effect
JobRequestFailed: The 'PVME01050402' operation failed. PowerOff
ERROR:pypowervm.tasks.power:Error: The 'PVME01050402' operation failed. PowerOff
Traceback (most recent call last):
  File "pypowervm/tasks/power.py", line 181, in _power_on_off
    synchronous=synchronous)
  File "/Users/nvcastet/Documents/workspace/pypowervm/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1062, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/Users/nvcastet/Documents/workspace/pypowervm/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1118, in _mock_call
    raise effect
JobRequestFailed: The 'PVME01050402' operation failed. PowerOff
ERROR:pypowervm.tasks.power:Error: The 'HSCL1558' operation failed. PowerOff
Traceback (most recent call last):
  File "pypowervm/tasks/power.py", line 181, in _power_on_off
    synchronous=synchronous)
  File "/Users/nvcastet/Documents/workspace/pypowervm/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1062, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/Users/nvcastet/Documents/workspace/pypowervm/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1118, in _mock_call
    raise effect
JobRequestFailed: The 'HSCL1558' operation failed. PowerOff
ERROR:pypowervm.tasks.power:Error: The 'PVME04000005' operation failed. PowerOff
Traceback (most recent call last):
  File "pypowervm/tasks/power.py", line 181, in _power_on_off
    synchronous=synchronous)
  File "/Users/nvcastet/Documents/workspace/pypowervm/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1062, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/Users/nvcastet/Documents/workspace/pypowervm/.tox/py27/lib/python2.7/site-packages/mock/mock.py", line 1118, in _mock_call
    raise effect
JobRequestFailed: The 'PVME04000005' operation failed. PowerOff
running=OS_STDOUT_CAPTURE=${OS_STDOUT_CAPTURE:-1} \
OS_STDERR_CAPTURE=${OS_STDERR_CAPTURE:-1} \
OS_TEST_TIMEOUT=${OS_TEST_TIMEOUT:-60} \
${PYTHON:-python} -m subunit.run discover -t ./ . --list 
running=OS_STDOUT_CAPTURE=${OS_STDOUT_CAPTURE:-1} \
OS_STDERR_CAPTURE=${OS_STDERR_CAPTURE:-1} \
OS_TEST_TIMEOUT=${OS_TEST_TIMEOUT:-60} \
${PYTHON:-python} -m subunit.run discover -t ./ .  --load-list /tmp/tmpFaELWr
running=OS_STDOUT_CAPTURE=${OS_STDOUT_CAPTURE:-1} \
OS_STDERR_CAPTURE=${OS_STDERR_CAPTURE:-1} \
OS_TEST_TIMEOUT=${OS_TEST_TIMEOUT:-60} \
${PYTHON:-python} -m subunit.run discover -t ./ .  --load-list /tmp/tmph2Ncd_
running=OS_STDOUT_CAPTURE=${OS_STDOUT_CAPTURE:-1} \
OS_STDERR_CAPTURE=${OS_STDERR_CAPTURE:-1} \
OS_TEST_TIMEOUT=${OS_TEST_TIMEOUT:-60} \
${PYTHON:-python} -m subunit.run discover -t ./ .  --load-list /tmp/tmpLmrvv9
running=OS_STDOUT_CAPTURE=${OS_STDOUT_CAPTURE:-1} \
OS_STDERR_CAPTURE=${OS_STDERR_CAPTURE:-1} \
OS_TEST_TIMEOUT=${OS_TEST_TIMEOUT:-60} \
${PYTHON:-python} -m subunit.run discover -t ./ .  --load-list /tmp/tmpSlKJNv
running=OS_STDOUT_CAPTURE=${OS_STDOUT_CAPTURE:-1} \
OS_STDERR_CAPTURE=${OS_STDERR_CAPTURE:-1} \
OS_TEST_TIMEOUT=${OS_TEST_TIMEOUT:-60} \
${PYTHON:-python} -m subunit.run discover -t ./ .  --load-list /tmp/tmpu9EV2w
running=OS_STDOUT_CAPTURE=${OS_STDOUT_CAPTURE:-1} \
OS_STDERR_CAPTURE=${OS_STDERR_CAPTURE:-1} \
OS_TEST_TIMEOUT=${OS_TEST_TIMEOUT:-60} \
${PYTHON:-python} -m subunit.run discover -t ./ .  --load-list /tmp/tmpUShM8u
running=OS_STDOUT_CAPTURE=${OS_STDOUT_CAPTURE:-1} \
OS_STDERR_CAPTURE=${OS_STDERR_CAPTURE:-1} \
OS_TEST_TIMEOUT=${OS_TEST_TIMEOUT:-60} \
${PYTHON:-python} -m subunit.run discover -t ./ .  --load-list /tmp/tmpkiefqG
running=OS_STDOUT_CAPTURE=${OS_STDOUT_CAPTURE:-1} \
OS_STDERR_CAPTURE=${OS_STDERR_CAPTURE:-1} \
OS_TEST_TIMEOUT=${OS_TEST_TIMEOUT:-60} \
${PYTHON:-python} -m subunit.run discover -t ./ .  --load-list /tmp/tmpgDfWP8
Ran 10 tests in 0.144s (+0.084s)
PASSED (id=32)
Slowest Tests
Test id                                                                       Runtime (s)
----------------------------------------------------------------------------  -----------
pypowervm.tests.tasks.test_power.TestPower.test_power_off_job_failure_vios    0.019
pypowervm.tests.tasks.test_power.TestPower.test_power_off_job_failure         0.016
pypowervm.tests.tasks.test_power.TestPower.test_power_off_timeout_retry       0.015
pypowervm.tests.tasks.test_power.TestPower.test_power_off_timeout_retry_vios  0.009
pypowervm.tests.tasks.test_power.TestPower.test_power_off_sysoff              0.007
pypowervm.tests.tasks.test_power.TestPower.test_power_on_off                  0.007
pypowervm.tests.tasks.test_power.TestPower.test_power_on_off_vios             0.007
pypowervm.tests.tasks.test_power.TestPower.test_power_on_syson_vios           0.006
pypowervm.tests.tasks.test_power.TestPower.test_power_off_sysoff_vios         0.006
pypowervm.tests.tasks.test_power.TestPower.test_power_on_syson                0.005
pep8 develop-inst-nodeps: /Users/nvcastet/Documents/workspace/pypowervm
pep8 installed: astroid==1.3.8,automaton==0.8.0,Babel==2.1.1,cachetools==1.1.5,contextlib2==0.4.0,coverage==4.0.2,debtcollector==0.10.0,decorator==4.0.4,discover==0.4.0,docutils==0.12,enum34==1.0.4,extras==0.0.3,fasteners==0.14.1,fixtures==1.4.0,flake8==2.2.4,funcsigs==0.4,functools32==3.2.3.post2,futures==3.0.3,futurist==0.8.0,hacking==0.10.2,iso8601==0.1.11,Jinja2==2.8,jsonschema==2.5.1,linecache2==1.0.0,logilab-common==1.1.0,lxml==3.5.0,MarkupSafe==0.23,mccabe==0.2.1,mock==1.3.0,monotonic==0.4,msgpack-python==0.4.6,netaddr==0.7.18,netifaces==0.10.4,networkx==1.10,oslo.concurrency==2.8.0,oslo.config==2.7.0,oslo.context==0.9.0,oslo.i18n==2.7.0,oslo.log==1.14.0,oslo.serialization==1.11.0,oslo.utils==2.8.0,oslosphinx==3.4.1,pbr==1.8.1,pep8==1.5.7,prettytable==0.7.2,psutil==1.2.1,pyasn1==0.1.9,pyasn1-modules==0.0.8,pyflakes==0.8.1,Pygments==2.0.2,pylint==1.4.4,-e git+ssh://nvcastet@morpheus.rch.stglabs.ibm.com:29418/pypowervm.git@8f949a33629d9c1d5e122011e89b1b88cc1a9e29#egg=pypowervm-fix_powerOff_flow,python-mimeparse==0.1.4,python-subunit==1.2.0,pytz==2015.7,requests==2.8.1,retrying==1.3.3,six==1.10.0,Sphinx==1.2.3,stevedore==1.9.0,taskflow==1.24.0,testrepository==0.0.20,testscenarios==0.5.0,testtools==1.8.1,traceback2==1.4.0,unittest2==1.1.0,wheel==0.24.0,wrapt==1.10.5
pep8 runtests: PYTHONHASHSEED='3892649635'
pep8 runtests: commands[0] | flake8
___________________________________ summary ____________________________________
  py27: commands succeeded
  pep8: commands succeeded
  congratulations :)
