# Translations template for pypowervm.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the pypowervm project.
# Automatically generated, 2015.
#
msgid ""
msgstr ""
"Project-Id-Version: pypowervm 0.0.3.dev270\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-10-06 13:53-0500\n"
"PO-Revision-Date: 2015-10-06 13:53-0500\n"
"Last-Translator: Automatically generated\n"
"Language-Team: none\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.0\n"

#: pypowervm/exceptions.py:116
#, python-format
msgid ""
"Unable to derive the appropriate physical FC port for WWPN %(wwpn)s.  The"
" VIOS Extended Attribute Groups may have been insufficient.  The VIOS URI"
" for the query was %(vio_uri)s."
msgstr ""
"Impossibile derivare la porta FC fisica appropriata per WWPN %(wwpn)s. I"
"gruppi di attributi estesi VIOS potrebbero essere stati insufficienti. L'URI VIOS"
"per la query era %(vio_uri)s."

#: pypowervm/exceptions.py:122
#, python-format
msgid "Element not found: %(element_type)s %(element)s"
msgstr "Elemento non trovato: %(element_type)s %(element)s"

#: pypowervm/exceptions.py:126
#, python-format
msgid "LPAR not found: %(lpar_name)s"
msgstr "LPAR non trovata: %(lpar_name)s"

#: pypowervm/exceptions.py:130
#, python-format
msgid "The '%(operation_name)s' operation failed. %(error)s"
msgstr "Operazione '%(operation_name)s' non riuscita. %(error)s"

#: pypowervm/exceptions.py:134
#, python-format
msgid ""
"The '%(operation_name)s' operation failed. Failed to complete the task in"
" %(seconds)d seconds."
msgstr ""
"Operazione '%(operation_name)s' non riuscita. Impossibile completare l'attività in"
" %(seconds)d secondi."

#: pypowervm/exceptions.py:139
#, python-format
msgid "Failed to power off Virtual Machine %(lpar_nm)s: %(reason)s"
msgstr "Impossibile spegnere la macchina virtuale %(lpar_nm)s: %(reason)s"

#: pypowervm/exceptions.py:143
#, python-format
msgid "Failed to power on Virtual Machine %(lpar_nm)s: %(reason)s"
msgstr "Impossibile accendere la macchina virtuale %(lpar_nm)s: %(reason)s"

#: pypowervm/exceptions.py:147
#, python-format
msgid ""
"Unable to remove VLAN %(vlan_id)d as it is the Primary VLAN Identifier on"
" a different Network Bridge."
msgstr ""
"Impossibile rimuovere la VLAN %(vlan_id)d poiché è l'identificativo VLAN primario su"
" un altro bridge di rete."

#: pypowervm/exceptions.py:152
#, python-format
msgid ""
"Unable to provision VLAN %(vlan_id)d.  It appears to be contained on "
"device '%(dev_name)s' on Virtual I/O Server %(vios)s.  That device is not"
" connected to any Network Bridge (Shared Ethernet Adapter).  Please "
"manually remove the device or add it to the Network Bridge before "
"continuing."
msgstr ""
"Impossibile eseguire il provisioning della VLAN %(vlan_id)d. Sembra essere contenuta"
"nel dispositivo '%(dev_name)s' sul Virtual I/O Server %(vios)s. Tale dispositivo non è"
"connesso ad alcun bridge di rete (Shared Ethernet Adapter). "
"Rimuovere manualmente il dispositivo o aggiungerlo al bridge di rete prima di "
"continuare."

#: pypowervm/exceptions.py:161
#, python-format
msgid ""
"A Logical Unit with name %(lu_name)s already exists on Shared Storage "
"Pool %(ssp_name)s."
msgstr ""
"Una LU (Logical Unit) con nome %(lu_name)s esiste già sul "
"pool di memoria condiviso %(ssp_name)s."

#: pypowervm/exceptions.py:166
msgid ""
"Unable to find a physical port to map a virtual Fibre Channel port to.  "
"This is due to either a Virtual I/O Server being unavailable, or improper"
" port specification for the physical Fibre Channel ports."
msgstr ""
"Impossibile trovare una porta fisica a cui associare una porta Fibre Channel virtuale.  "
"Questo si verifica a causa di un Virtual I/O Server non disponibile o di una"
" specifica di porta non corretta per le porte Fibre Channel fisiche."

#: pypowervm/exceptions.py:173
msgid ""
"Unable to start the console to the Virtual Machine.  The pypowervm API is"
" running in a non-local mode.  The console can only be deployed when "
"pypowervm is co-located with the PowerVM API."
msgstr ""
"Impossibile avviare la console per la macchina virtuale. L'API pypowervm è "
"in esecuzione in modalità non locale. La console può essere distribuita solo quando"
"pypowervm si trova nella stessa ubicazione dell'API PowerVM."

#: pypowervm/exceptions.py:180
#, python-format
msgid "WrapperTask %(name)s has no subtasks!"
msgstr "WrapperTask %(name)s non ha attività secondarie."

#: pypowervm/exceptions.py:184
msgid "FeedTask can't have an empty feed."
msgstr "FeedTask non può avere un feed vuoto."

#: pypowervm/exceptions.py:188
#, python-format
msgid "OS unable to read file %(access_file)s."
msgstr "Il SO non riesce a leggere il file %(access_file)s."

#: pypowervm/exceptions.py:192
#, python-format
msgid "OS able to read file %(access_file)s, but encountered an access error."
msgstr "Il SO riesce a leggere il file %(access_file)s, ma ha riscontrato un errore di accesso."

#: pypowervm/exceptions.py:197
#, python-format
msgid "The migration task failed. %(error)s"
msgstr "Attività di migrazione non riuscita. %(error)s"

#: pypowervm/exceptions.py:201
#, python-format
msgid "No load source found for VM %(vm_name)s"
msgstr "Nessuna origine di caricamento trovata per VM %(vm_name)s"

#: pypowervm/util.py:122
#, python-format
msgid ""
"Proposed extended attribute group '%(arg_xag)s' doesn't match existing "
"extended attribute group '%(path_xag)s'"
msgstr ""
"Il gruppo di attributi estesi proposto '%(arg_xag)s' non corrisponde al "
"gruppo di attributi estesi esistente '%(path_xag)s'"

#: pypowervm/util.py:391
#, python-format
msgid "Prefix and suffix together may not be more than %d characters."
msgstr "Il prefisso e il suffisso insieme non possono superare i %d caratteri."

#: pypowervm/util.py:396
msgid "Total length must be at least 1 character."
msgstr "La lunghezza totale deve essere di almeno 1 carattere."

#: pypowervm/util.py:419
msgid "The name parameter must be at least one character long."
msgstr "Il parametro del nome deve essere lungo almeno un carattere."

#: pypowervm/util.py:422
#, python-format
msgid "The name parameter must not exceed %d characters when trunk_ok is False."
msgstr "Il parametro del nome non deve superare i %d caratteri quando trunk_ok è False."

#: pypowervm/helpers/log_helper.py:82
#, python-format
msgid "REQUEST: %s"
msgstr "RICHIESTA: %s"

#: pypowervm/helpers/log_helper.py:102
#, python-format
msgid "RESPONSE: %s"
msgstr "RISPOSTA: %s"

#: pypowervm/tasks/cna.py:77
#, python-format
msgid "Unable to find the Virtual Switch %s on the system."
msgstr "Impossibile trovare lo switch virtuale %s sul sistema."

#: pypowervm/tasks/hdisk.py:182
#, python-format
msgid ""
"hdisk discovery failed; will scrub stale storage for LPAR IDs %s and "
"retry."
msgstr ""
"Rilevamento hdisk non riuscito; verrà ripulita la memoria obsoleta per gli ID LPAR %s e "
"viene ritentata l'operazione."

#: pypowervm/tasks/hdisk.py:324
#, python-format
msgid "LUA Recovery Successful. Device Found: %s"
msgstr "Ripristino LUA riuscito. Dispositivo trovato: %s"

#: pypowervm/tasks/hdisk.py:328
#, python-format
msgid "ITL Error encountered: %s"
msgstr "Riscontrato errore ITL: %s"

#: pypowervm/tasks/hdisk.py:330
#, python-format
msgid "%s Device is currently in use."
msgstr "Dispositivo %s correntemente in uso. "

#: pypowervm/tasks/hdisk.py:332
#, python-format
msgid "%s Device discovered with unknown UDID."
msgstr "Dispositivo %s rilevato con UUID sconosciuto. "

#: pypowervm/tasks/hdisk.py:334
#, python-format
msgid "Failed to Discover the Device : %s"
msgstr "Rilevamento del dispositivo non riuscito: %s"

#: pypowervm/tasks/hdisk.py:404
#, python-format
msgid "CLIRunner Error: %s"
msgstr "Errore CLIRunner: %s"

#: pypowervm/tasks/memory.py:101
#, python-format
msgid ""
"Error obtaining host memory overhead for host with UUID '%(host)s': "
"%(error)s."
msgstr ""
"Errore nell'ottenere il sovraccarico di memoria host per l'host con UUID '%(host)s': "
"%(error)s."

#: pypowervm/tasks/power.py:159 pypowervm/tasks/power.py:168
#, python-format
msgid "Error: %s"
msgstr "Errore: %s"

#: pypowervm/tasks/power.py:200
#, python-format
msgid ""
"Error invalidating adapter cache for LPAR  %(lpar_name) with UUID "
"%(lpar_uuid)s: %(exc)s"
msgstr ""
"Errore durante l'invalidazione della cache adattatore per la LPAR  %(lpar_name) con UUID "
"%(lpar_uuid)s: %(exc)s"

#: pypowervm/tasks/scsi_mapper.py:38
msgid "Retrying modification of SCSI Mapping."
msgstr "Nuovo tentativo di modifica dell'associazione SCSI."

#: pypowervm/tasks/scsi_mapper.py:89
#, python-format
msgid ""
"Found existing mapping of %(stg_type)s storage element %(stg_name)s from "
"Virtual I/O Server %(vios_name)s to client LPAR %(lpar_uuid)s."
msgstr ""
"Trovata un'associazione esistente dell'elemento di memoria %(stg_type)s %(stg_name)s "
"dal Virtual I/O Server %(vios_name)s alla LPAR client %(lpar_uuid)s."

#: pypowervm/tasks/scsi_mapper.py:107
#, python-format
msgid ""
"Creating mapping of %(stg_type)s storage element %(stg_name)s from "
"Virtual I/O Server %(vios_name)s to client LPAR %(lpar_uuid)s."
msgstr ""
"Creazione dell'associazione dell'elemento di memoria %(stg_type)s %(stg_name)s "
"dal Virtual I/O Server %(vios_name)s alla LPAR client %(lpar_uuid)s."

#: pypowervm/tasks/scsi_mapper.py:371
msgid "Must not specify both match_func and stg_elem."
msgstr "Non si devono specificare entrambi match_func e stg_elem."

#: pypowervm/tasks/storage.py:287
#, python-format
msgid "Unable to cleanup after file upload. File uuid: %s"
msgstr "Impossibile eseguire il cleanup dopo il caricamento file. uuid file: %s"

#: pypowervm/tasks/storage.py:385
#, python-format
msgid ""
"Linked clone Logical Unit %(luname)s (UDID %(udid)s) has no backing image"
" LU.  It should probably be deleted."
msgstr ""
"L'unità logica clone collegata %(luname)s (UDID %(udid)s) non ha LU immagine di supporto."
"Probabilmente è stata eliminata. "

#: pypowervm/tasks/storage.py:430
msgid "Unable to locate new vDisk on file upload."
msgstr "Impossibile individuare il nuovo vDisk sul caricamento file."

#: pypowervm/tasks/storage.py:480
#, python-format
msgid "Deleting virtual disk %(vdisk)s from volume group %(vg)s"
msgstr "Eliminazione del disco virtuale %(vdisk)s dal gruppo di volumi %(vg)s"

#: pypowervm/tasks/storage.py:504
#, python-format
msgid "Deleting virtual optical device %(vopt)s from volume group %(vg)s"
msgstr "Eliminazione del dispositivo ottico virtuale %(vopt)s dal gruppo di volumi %(vg)s"

#: pypowervm/tasks/storage.py:559
#, python-format
msgid "Removing LU %(lu_name)s from SSP %(ssp_name)s"
msgstr "Rimozione della LU %(lu_name)s dall'SSP %(ssp_name)s"

#: pypowervm/tasks/storage.py:580
#, python-format
msgid ""
"Removing Image LU %(lu_name)s from SSP %(ssp_name)s because it is no "
"longer in use."
msgstr ""
"Rimozione della LU immagine %(lu_name)s dall'SSP %(ssp_name)s poiché non è "
"più in uso."

#: pypowervm/tasks/storage.py:625
#, python-format
msgid ""
"Removing %(num_maps)d orphan %(stg_type)s mappings from VIOS "
"%(vios_name)s."
msgstr ""
"Rimozione %(num_maps)d associazioni orfane %(stg_type)s dal VIOS "
"%(vios_name)s."

#: pypowervm/tasks/storage.py:652
#, python-format
msgid ""
"Removing %(num_maps)d %(stg_type)s mappings associated with LPAR ID "
"%(lpar_id)d from VIOS %(vios_name)s."
msgstr ""
"Rimozione di %(num_maps)d associazioni %(stg_type)s associate all'ID LPAR  "
"%(lpar_id)d dal VIOS %(vios_name)s."

#: pypowervm/tasks/storage.py:725
#, python-format
msgid "Unexpected storage element type %s."
msgstr "Tipo di elemento di memoria imprevisto %s."

#: pypowervm/tasks/storage.py:742
#, python-format
msgid ""
"Scrubbing the following %(vdcount)d Virtual Disks from VIOS %(vios)s: "
"%(vdlist)s"
msgstr ""
"Ripulitura dei seguenti %(vdcount)d dischi virtuali dal VIOS %(vios)s: "
"%(vdlist)s"

#: pypowervm/tasks/storage.py:750
#, python-format
msgid ""
"Scrubbing the following %(vocount)d Virtual Opticals from VIOS %(vios)s: "
"%(volist)s"
msgstr ""
"Ripulitura dei seguenti %(vocount)d dispositivi ottici virtuali dal VIOS %(vios)s: "
"%(volist)s"

#: pypowervm/tasks/storage.py:814
#, python-format
msgid ""
"Skipping scrub of %(stg_type)s mappings from VIOS %(vios_name)s for the "
"following LPAR IDs because those LPARs exist: %(lpar_ids)s"
msgstr ""
"Ignorata ripulitura di associazioni %(stg_type)s dal VIOS %(vios_name)s per "
"i seguenti ID LPAR perché tali LPAR esistono: %(lpar_ids)s"

#: pypowervm/tasks/vfc_mapper.py:379
#, python-format
msgid "Detected a stale mapping for LPAR with UUID %s."
msgstr "Rilevata un'associazione obsoleta per la LPAR con UUID %s."

#: pypowervm/tasks/vfc_mapper.py:583
#, python-format
msgid ""
"Unable to find appropriate VIOS.  The payload provided was likely "
"insufficient.  The payload data is:\n"
" %s)"
msgstr ""
"Impossibile trovare il VIOS appropriato. Il payload fornito era probabilmente "
"insufficiente. I dati payload sono:\n"
" %s)"

#: pypowervm/tasks/vterm.py:61
msgid "Unable to close vterm."
msgstr "Impossibile chiudere vterm."

#: pypowervm/tests/test_i18n.py:33
msgid "This is a test"
msgstr "Questo è un test"

#: pypowervm/tests/test_i18n.py:36
msgid "This is a message for which a translation doesn't exist"
msgstr "Questo è un messaggio per il quale non esiste una traduzione"

#: pypowervm/utils/retry.py:152
#, python-format
msgid ""
"Attempt %(retry)d of total %(total)d for URI %(uri)s.  Error was a known "
"retry response code: %(resp_code)s"
msgstr ""
"Tentativo %(retry)d di %(total)d totali per URI %(uri)s. L'errore era un"
"codice di risposta di nuovo tentativo noto: %(resp_code)s"

#: pypowervm/utils/retry.py:159
#, python-format
msgid ""
"Attempt %(retry)d of %(total)d failed.  Will retry. The exception was:\n"
" %(except)s."
msgstr ""
"Tentativo %(retry)d di %(total)d non riuscito. Si esegue nuovo tentativo. L'eccezione era:\n"
" %(except)s."

#: pypowervm/utils/transaction.py:311
msgid "Must supply either EntryWrapper or EntryWrapperGetter."
msgstr "È necessario fornire EntryWrapper o EntryWrapperGetter."

#: pypowervm/utils/transaction.py:337
msgid "Must supply a valid Subtask."
msgstr "È necessario fornire un'attività secondaria valida."

#: pypowervm/utils/transaction.py:341
#, python-format
msgid "Duplicate 'provides' name %s."
msgstr "Nome 'provides' duplicato %s."

#: pypowervm/utils/transaction.py:416
#, python-format
msgid "WrapperTask %s has no Subtasks; no-op execution."
msgstr "WrapperTask %s non ha attività secondarie; nessuna operazione in esecuzione."

#: pypowervm/utils/transaction.py:541
msgid "Must supply either a list of EntryWrappers or a FeedGetter."
msgstr "È necessario fornire un elenco di EntryWrappers o un FeedGetter."

#: pypowervm/utils/transaction.py:720
#, python-format
msgid "FeedTask %s has no Subtasks; no-op execution."
msgstr "FeedTask %s non ha attività secondarie; nessuna operazione in esecuzione."

#: pypowervm/utils/validation.py:160
#, python-format
msgid ""
"Insufficient available %(res_name)s on host for virtual machine "
"'%(instance_name)s' (%(requested)s requested, %(avail)s available)"
msgstr ""
"%(res_name)s disponibili non sufficienti sull'host per la macchina virtuale "
"'%(instance_name)s' (%(requested)s richiesti, %(avail)s disponibili)"

#: pypowervm/utils/validation.py:187
msgid "memory"
msgstr "di memoria"

#: pypowervm/utils/validation.py:207
#, python-format
msgid ""
"The virtual machine must be powered off before changing the minimum or "
"maximum memory. Power off virtual machine %s and try again."
msgstr ""
"La macchina virtuale deve essere spentaprima di modificare il minimo o "
"il massimo della memoria. Spegnere la macchina virtuale %s e riprovare. "

#: pypowervm/utils/validation.py:292
msgid "CPUs"
msgstr "CPU"

#: pypowervm/utils/validation.py:308
msgid "processing units"
msgstr "unità di elaborazione"

#: pypowervm/utils/validation.py:349
#, python-format
msgid ""
"The virtual machine must be powered off before changing the minimum or "
"maximum processors. Power off virtual machine %s and try again."
msgstr ""
"La macchina virtuale deve essere spentaprima di modificare il minimo o "
"il massimo di processori. Spegnere la macchina virtuale %s e riprovare. "

#: pypowervm/utils/validation.py:359
#, python-format
msgid ""
"The virtual machine must be powered off before changing the minimum or "
"maximum processor units. Power off virtual machine %s and try again."
msgstr ""
"La macchina virtuale deve essere spentaprima di modificare il minimo o "
"il massimo di unità processore. Spegnere la macchina virtuale %s e riprovare. "

#: pypowervm/utils/validation.py:375
#, python-format
msgid ""
"The virtual machine must be powered off before changing the processor "
"compatibility mode. Power off virtual machine %s and try again."
msgstr ""
"La macchina virtuale deve essere spentaprima di modificare la modalità"
"di compatibilità processore. Spegnere la macchina virtuale %s e riprovare."

#: pypowervm/utils/validation.py:383
#, python-format
msgid ""
"The virtual machine must be powered off before changing the processing "
"mode. Power off virtual machine %s and try again."
msgstr ""
"La macchina virtuale deve essere spentaprima di modificare la modalità"
"di elaborazione. Spegnere la macchina virtuale %s e riprovare."

#: pypowervm/utils/validation.py:412
#, python-format
msgid ""
"The desired processors (%(vcpus)d) cannot be above the maximum allowed "
"processors per partition (%(max_allowed)d) for virtual machine "
"'%(instance_name)s'."
msgstr ""
"I processori desiderati (%(vcpus)d) non possono essere più del numero massimo consentito"
"di processori per partizione (%(max_allowed)d) per la macchina virtuale"
"'%(instance_name)s'."

#: pypowervm/utils/validation.py:424
#, python-format
msgid ""
"The maximum processors (%(vcpus)d) cannot be above the maximum system "
"capacity processor limit (%(max_allowed)d) for virtual machine "
"'%(instance_name)s'."
msgstr ""
"Il numero massimo di processori (%(vcpus)d) non può essere superiore al limite massimo "
"di processori della capacità di sistema (%(max_allowed)d) per la macchina virtuale "
"'%(instance_name)s'."

#: pypowervm/utils/validation.py:442
#, python-format
msgid "The shared processor pool for %s must be DefaultPool."
msgstr "Il pool di processori condivisi per %s deve essere DefaultPool. "

#: pypowervm/utils/validation.py:450
#, python-format
msgid "The shared processor pool for %s cannot be changed."
msgstr "Il pool di processori condivisi per %s non può essere modificato. "

#: pypowervm/utils/validation.py:513
#, python-format
msgid ""
"The virtual machine must be powered off before changing the simplified "
"remote restart capability. Power off virtual machine %s and try again."
msgstr ""
"La macchina virtuale deve essere spentaprima di modificare la capacità"
"di riavvio remoto semplificato. Spegnere la macchina virtuale %s e riprovare."

#: pypowervm/wrappers/base_partition.py:470
#, python-format
msgid "Invalid KeylockPos '%s'."
msgstr "KeylockPos non valido '%s'."

#: pypowervm/wrappers/entry_wrapper.py:258
#, python-format
msgid "Cannot convert %(property_name)s='%(value)s' in object %(pvmobject)s"
msgstr "Impossibile convertire %(property_name)s='%(value)s' nell'oggetto %(pvmobject)s"

#: pypowervm/wrappers/entry_wrapper.py:337
#, python-format
msgid "The expected parameter of %(param)s was not found in %(identifier)s"
msgstr "Parametro previsto %(param)s non trovato in %(identifier)s"

#: pypowervm/wrappers/entry_wrapper.py:386
msgid ""
"Refusing set href over multiple links.\n"
"Path: %{path}s\n"
"Number of links found: %{nlinks}d"
msgstr ""
"Rifiuto impostazione di href su più link.\n"
"Percorso: %{path}s\n"
"Numero di link trovati: %{nlinks}d"

#: pypowervm/wrappers/entry_wrapper.py:430
msgid "Refusing to construct and wrap an Element without a tag."
msgstr "Rifiuto di creare e includere un elemento senza tag."

#: pypowervm/wrappers/entry_wrapper.py:554
msgid "Response is missing 'entry' property."
msgstr "Alla risposta manca la proprietà 'entry'."

#: pypowervm/wrappers/entry_wrapper.py:568
#, python-format
msgid "Must supply a Response or Entry to wrap.  Got %s"
msgstr "È necessario fornire una risposta o una voce da includere. Ricevuto %s"

#: pypowervm/wrappers/entry_wrapper.py:667
msgid "Parent UUID specified without parent type."
msgstr "UUID parent specificato senza tipo di parent."

#: pypowervm/wrappers/entry_wrapper.py:670
msgid "The search() method requires exactly one key=value argument."
msgstr "Il metodo search() richiede un solo argomento key=value."

#: pypowervm/wrappers/entry_wrapper.py:698
#, python-format
msgid "Wrapper class %(class)s does not support search key '%(key)s'."
msgstr "La classe wrapper %(class)s non supporta la chiave di ricerca '%(key)s'."

#: pypowervm/wrappers/entry_wrapper.py:774
msgid "Must specify both parent type and UUID, or neither."
msgstr "È necessario specificare sia il tipo di parent che l'UUID, oppure nessuno dei due."

#: pypowervm/wrappers/entry_wrapper.py:851
msgid "Cannot set uuid."
msgstr "Impossibile impostare l'uuid."

#: pypowervm/wrappers/entry_wrapper.py:1041
msgid "No such child element."
msgstr "Nessun elemento child di questo genere."

#: pypowervm/wrappers/entry_wrapper.py:1102
msgid "Cannot set UUID on Wrapper with no Metadata."
msgstr "Impossibile impostare l'UUID sul wrapper senza metadati."

#: pypowervm/wrappers/entry_wrapper.py:1107
#, python-format
msgid "uuid value not valid: %s"
msgstr "il valore uuid non è valido: %s"

#: pypowervm/wrappers/entry_wrapper.py:1155
msgid "Must specify a Wrapper subclass."
msgstr "È necessario specificare una sottoclasse Wrapper. "

#: pypowervm/wrappers/entry_wrapper.py:1162
msgid "Must specify both parent class and parent UUID, or neither."
msgstr "È necessario specificare sia la classe parent che l'UUID parent, o nessuno dei due."

#: pypowervm/wrappers/job.py:281
#, python-format
msgid "Job %(job_id)s failed to cancel after %(timeout)s seconds."
msgstr "Impossibile annullare il lavoro %(job_id)s dopo %(timeout)s secondi."

#: pypowervm/wrappers/job.py:302
#, python-format
msgid "Job %s not deleted. Job is in running state."
msgstr "Lavoro %s non eliminato. Il lavoro è in esecuzione. "

#: pypowervm/wrappers/logical_partition.py:139
#: pypowervm/wrappers/logical_partition.py:208
msgid "LPAR does not have an active RMC connection."
msgstr "La LPAR non ha una connessione RMC attiva."

#: pypowervm/wrappers/logical_partition.py:141
#, python-format
msgid "LPAR does not have an active DLPAR capability for %s."
msgstr "La LPAR non ha una capacità DLPAR attiva per %s."

#: pypowervm/wrappers/logical_partition.py:153
msgid "I/O"
msgstr "I/O"

#: pypowervm/wrappers/logical_partition.py:163
msgid "Memory"
msgstr "Memoria"

#: pypowervm/wrappers/logical_partition.py:173
msgid "Processors"
msgstr "Processori"

#: pypowervm/wrappers/logical_partition.py:190
msgid "LPAR is not in an active state."
msgstr "La LPAR non è in stato Attivo."

#: pypowervm/wrappers/logical_partition.py:196
msgid "IBM i LPAR does not have restricted I/O."
msgstr "La LPAR IBM i non ha I/O limitato."

#: pypowervm/wrappers/logical_partition.py:200
msgid "Source system does not have the IBM i LPAR Mobility Capability."
msgstr "Il sistema di origine non ha la capacità LPAR Mobility IBM i."

#: pypowervm/wrappers/logical_partition.py:205
msgid "IBM i LPAR Live Migration is only supported on POWER7 and higher systems."
msgstr "La migrazione live LPAR IBM i è supportato solo su POWER7 e sistemi superiori."

#: pypowervm/wrappers/logical_partition.py:212
msgid "LPAR is not available for LPM due to missing DLPAR capabilities."
msgstr "La LPAR non è disponibile per LPM a causa di capacità DLPAR mancanti."

#: pypowervm/wrappers/logical_partition.py:273
#, python-format
msgid "Invalid IPLSrc '%s'."
msgstr "IPLSrc non valido '%s'."

#: pypowervm/wrappers/storage.py:437
#, python-format
msgid ""
"PV had encoded pg83 descriptor \"%(pg83_raw)s\", but it failed to decode "
"(%(type_error)s)."
msgstr ""
"PV ha descrittore codificato pg83 \"%(pg83_raw)s\", ma la decodifica non è riuscita"
"(%(type_error)s)."

