# Translations template for pypowervm.
# Copyright (C) 2016 IBM Corp.
# This file is distributed under the same license as the pypowervm project.
# Automatically generated, 2016.
#
msgid ""
msgstr ""
"Project-Id-Version: pypowervm 1.0.1.dev127\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2016-04-14 02:54-0400\n"
"PO-Revision-Date: 2016-04-14 02:54-0400\n"
"Last-Translator: Automatically generated\n"
"Language-Team: none\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.3.2\n"

#: pypowervm/adapter.py:126
#, python-format
msgid "Invalid protocol \"%s\""
msgstr "Protocollo non valido \"%s\""

#: pypowervm/adapter.py:132
msgid "Unencrypted communication with PowerVM! Revert configuration to https."
msgstr "Comunicazioni non codificate con PowerVM! Invertire la configurazione su https."

#: pypowervm/adapter.py:146
msgid "Calculating default audit memento failed, using 'default'."
msgstr "Calcolo memo di controllo predefinito non riuscito, si utilizza 'default'."

#: pypowervm/adapter.py:181
msgid "Local authentication not supported on HMC."
msgstr "Autenticazione locale non supportata sulla HMC."

#: pypowervm/adapter.py:200
#, python-format
msgid "Setting up event listener for %s"
msgstr "Impostazione del listener di eventi per %s"

#: pypowervm/adapter.py:239
#, python-format
msgid "Unexpected filehandle on %s request"
msgstr "Richiesta imprevista di gestione file su %s"

#: pypowervm/adapter.py:292
#, python-format
msgid "Unexpected error for %(meth)s %(url)s"
msgstr "Errore imprevisto per %(meth)s %(url)s"

#: pypowervm/adapter.py:294
#, python-format
msgid "Unexpected error: %(class)s for %(method)s %(url)s: %(excp)s"
msgstr "Errore imprevisto %(class)s per %(method)s %(url)s: %(excp)s"

#: pypowervm/adapter.py:332
msgid ""
"Re-login has been deemed unsafe. This Session instance should no longer "
"be used."
msgstr ""
"Un nuovo login può non essere sicuro, questa istanza sessione non può più "
"essere utilizzata."

#: pypowervm/adapter.py:342
#, python-format
msgid "Attempting re-login %s"
msgstr "Nuovo tentativo di login %s"

#: pypowervm/adapter.py:353
#, python-format
msgid ""
"Re-login 401, response body:\n"
"%s"
msgstr ""
"Nuovo login 401, corpo risposta:\n"
"%s"

#: pypowervm/adapter.py:358
#, python-format
msgid ""
"Re-login failed, resp body:\n"
"%s"
msgstr ""
"Nuovo login non riuscito, corpo risposta:\n"
"%s"

#: pypowervm/adapter.py:362
#, python-format
msgid ""
"Re-login failed:\n"
"%s"
msgstr ""
"Nuovo login non riuscito:\n"
"%s"

#: pypowervm/adapter.py:381
#, python-format
msgid ""
"Re-attempt failed with another 401, response body:\n"
"%s"
msgstr ""
"Nuovo tentativo non riuscito con un altro 401, corpo risposta:\n"
"%s"

#: pypowervm/adapter.py:384
#, python-format
msgid "suspicious HTTP 401 response for %(method)s %(path)s: token is brand new"
msgstr "risposta HTTP 401 sospetta per %(method)s %(path)s: il token è nuovo"

#: pypowervm/adapter.py:416
#, python-format
msgid "Session logging on %s"
msgstr "Login sessione %s"

#: pypowervm/adapter.py:478
msgid "Failed to parse a session token from the PowerVM response."
msgstr "Impossibile analizzare un token sessione dalla risposta PowerVM."

#: pypowervm/adapter.py:480 pypowervm/adapter.py:496
#, python-format
msgid " Body= %s"
msgstr " Corpo= %s"

#: pypowervm/adapter.py:494
msgid "Failed to parse a session file path from the PowerVM response."
msgstr "Impossibile analizzare un percorso file sessione dalla risposta PowerVM."

#: pypowervm/adapter.py:508
#, python-format
msgid "Token file %s didn't contain a readable session token."
msgstr "Il file token %s non contiene un token sessione leggibile."

#: pypowervm/adapter.py:518
#, python-format
msgid "Session logging off %s"
msgstr "Logoff sessione %s"

#: pypowervm/adapter.py:523
msgid "Problem logging off.  Ignoring."
msgstr "Problema nel logoff. Ignorato."

#: pypowervm/adapter.py:561
msgid "Failed to register for events.  Events will not be used."
msgstr "Impossibile registrare per eventi. Gli eventi non verranno utilizzati."

#: pypowervm/adapter.py:642
msgid "job must be a JobRequest element"
msgstr "il lavoro deve essere un elemento JobRequest"

#: pypowervm/adapter.py:646
msgid "JobRequest is missing OperationName"
msgstr "In JobRequest manca OperationName"

#: pypowervm/adapter.py:660 pypowervm/adapter.py:866 pypowervm/adapter.py:926
#: pypowervm/adapter.py:1022
#, python-format
msgid "path=%s is not a PowerVM API reference"
msgstr "il percorso=%s non è un riferimento API PowerVM"

#: pypowervm/adapter.py:1037 pypowervm/adapter.py:1054
msgid "Invalid file descriptor"
msgstr "Descrittore file non valido"

#: pypowervm/adapter.py:1179 pypowervm/adapter.py:1207
#: pypowervm/adapter.py:1222
msgid "Expected root_id"
msgstr "Previsto root_id"

#: pypowervm/adapter.py:1181
msgid "Expected child_type"
msgstr "Previsto child_type"

#: pypowervm/adapter.py:1185 pypowervm/adapter.py:1211
#: pypowervm/adapter.py:1216
#, python-format
msgid "Unexpected suffix_type=%s"
msgstr "suffix_type=%s non previsto"

#: pypowervm/adapter.py:1188 pypowervm/adapter.py:1219
msgid "Expected suffix_parm"
msgstr "Previsto suffix_parm"

#: pypowervm/adapter.py:1190 pypowervm/adapter.py:1209
#: pypowervm/adapter.py:1224
msgid "Expected child_id"
msgstr "Previsto child_id"

#: pypowervm/adapter.py:1193 pypowervm/adapter.py:1202
msgid "Unexpected child_id"
msgstr "child_id non previsto"

#: pypowervm/adapter.py:1195 pypowervm/adapter.py:1204
msgid "Unexpected root_id"
msgstr "root_id non previsto"

#: pypowervm/adapter.py:1226
#, python-format
msgid "Unexpected req_method=%s"
msgstr "req_method=%s non previsto"

#: pypowervm/adapter.py:1345
#, python-format
msgid "Error parsing XML response from PowerVM: %s"
msgstr "Errore durante l'analisi della risposta XML da PowerVM: %s"

#: pypowervm/adapter.py:1358
msgid "Response is not an Atom feed/entry"
msgstr "La risposta non è un feed/voce atom"

#: pypowervm/adapter.py:1369
msgid "Unexpected HTTP 204 for request"
msgstr "Errore HTTP 204 imprevisto per la richiesta"

#: pypowervm/adapter.py:1377
msgid "Unexpectedly empty response body"
msgstr "Corpo della risposta inaspettatamente vuoto"

#: pypowervm/adapter.py:1380
#, python-format
msgid ""
"%(err_reason)s:\n"
"request headers: %(reqheaders)s\n"
"\n"
"request body: %(reqbody)s\n"
"\n"
"response headers: %(respheaders)s\n"
"\n"
"response body: %(respbody)s"
msgstr ""
"%(err_reason)s: \n"
"intestazioni richiesta: %(reqheaders)s\n"
"\n"
"corpo richiesta: %(reqbody)s\n"
"\n"
"intestazioni risposta: %(respheaders)s\n"
"\n"
"corpo risposta: %(respbody)s"

#: pypowervm/adapter.py:1388
#, python-format
msgid "Atom error for %(method)s %(path)s: %(reason)s"
msgstr "Errore atom per %(method)s %(path)s: %(reason)s"

#: pypowervm/adapter.py:1430
msgid "Session must not be None"
msgstr "La sessione non deve essere Nessuno"

#: pypowervm/adapter.py:1432
msgid "An event listener is already active on the session."
msgstr "Un listener di eventi è già attivo nella sessione."

#: pypowervm/adapter.py:1448
#, python-format
msgid "Failed to initialize event feed listener: %s"
msgstr "Impossibile inizializzare il listener feed eventi: %s"

#: pypowervm/adapter.py:1452
#, python-format
msgid "Application id \"%s\" is not unique"
msgstr "L'ID applicazione \"%s\" non è univoco"

#: pypowervm/adapter.py:1461
msgid "Shutting down"
msgstr "In arresto"

#: pypowervm/adapter.py:1464
msgid "This handler is already subscribed"
msgstr "Questo gestore è già sottoscritto"

#: pypowervm/adapter.py:1472
msgid "Handler must be an EventHandler"
msgstr "Il gestore deve essere un gestore eventi"

#: pypowervm/adapter.py:1475
msgid "This handler not found in subscriber list"
msgstr "Gestore non trovato nell'elenco di sottoscrittori"

#: pypowervm/adapter.py:1483
#, python-format
msgid "Shutting down EventListener for %s"
msgstr "Chiusura del listener di eventi per %s"

#: pypowervm/adapter.py:1487
#, python-format
msgid "EventListener shutdown complete for %s"
msgstr "Chiusura listener di eventi completata per %s"

#: pypowervm/adapter.py:1507
msgid "Error while getting PowerVM events"
msgstr "Errore durante il richiamo degli eventi PowerVM"

#: pypowervm/adapter.py:1544
#, python-format
msgid "Unexpected EventType=%s"
msgstr "EventType=%s non previsto"

#: pypowervm/adapter.py:1561
msgid "Error while processing PowerVM events"
msgstr "Errore durante l'elaborazione degli eventi PowerVM"

#: pypowervm/exceptions.py:117
#, python-format
msgid ""
"Unable to derive the appropriate physical FC port for WWPN %(wwpn)s.  The"
" VIOS Extended Attribute Groups may have been insufficient.  The VIOS URI"
" for the query was %(vio_uri)s."
msgstr ""
"Impossibile derivare la porta FC fisica appropriata per WWPN %(wwpn)s."
" I gruppi di attributi estesi VIOS potrebbero essere stati insufficienti. L'URI VIOS"
" per la query era %(vio_uri)s."

#: pypowervm/exceptions.py:123
#, python-format
msgid "Element not found: %(element_type)s %(element)s"
msgstr "Elemento non trovato: %(element_type)s %(element)s"

#: pypowervm/exceptions.py:127
#, python-format
msgid "LPAR not found: %(lpar_name)s"
msgstr "LPAR non trovata: %(lpar_name)s"

#: pypowervm/exceptions.py:131
#, python-format
msgid "The '%(operation_name)s' operation failed. %(error)s"
msgstr "Operazione '%(operation_name)s' non riuscita. %(error)s"

#: pypowervm/exceptions.py:135
#, python-format
msgid ""
"The '%(operation_name)s' operation failed. Failed to complete the task in"
" %(seconds)d seconds."
msgstr ""
"Operazione '%(operation_name)s' non riuscita. Impossibile completare l'attività in"
" %(seconds)d secondi."

#: pypowervm/exceptions.py:140
#, python-format
msgid "Failed to power off Virtual Machine %(lpar_nm)s: %(reason)s"
msgstr "Impossibile spegnere la macchina virtuale %(lpar_nm)s: %(reason)s"

#: pypowervm/exceptions.py:144
#, python-format
msgid "Failed to power on Virtual Machine %(lpar_nm)s: %(reason)s"
msgstr "Impossibile accendere la macchina virtuale %(lpar_nm)s: %(reason)s"

#: pypowervm/exceptions.py:148
#, python-format
msgid ""
"Unable to remove VLAN %(vlan_id)d as it is the Primary VLAN Identifier on"
" a different Network Bridge."
msgstr ""
"Impossibile rimuovere la VLAN %(vlan_id)d poiché è l'identificativo VLAN primario su"
" un altro bridge di rete."

#: pypowervm/exceptions.py:153
#, python-format
msgid ""
"Unable to provision VLAN %(vlan_id)d.  It appears to be contained on "
"device '%(dev_name)s' on Virtual I/O Server %(vios)s.  That device is not"
" connected to any Network Bridge (Shared Ethernet Adapter).  Please "
"manually remove the device or add it to the Network Bridge before "
"continuing."
msgstr ""
"Impossibile eseguire il provisioning della VLAN %(vlan_id)d. Sembra essere contenuta "
"nel dispositivo '%(dev_name)s' sul Virtual I/O Server %(vios)s. Tale dispositivo non è"
" connesso ad alcun bridge di rete (Shared Ethernet Adapter). "
"Rimuovere manualmente il dispositivo o aggiungerlo al bridge di rete prima di "
"continuare."

#: pypowervm/exceptions.py:162
#, python-format
msgid ""
"A Logical Unit with name %(lu_name)s already exists on Shared Storage "
"Pool %(ssp_name)s."
msgstr ""
"Una LU (Logical Unit) con nome %(lu_name)s esiste già sul "
"pool di memoria condiviso %(ssp_name)s."

#: pypowervm/exceptions.py:167
msgid ""
"Unable to find a physical port to map a virtual Fibre Channel port to.  "
"This is due to either a Virtual I/O Server being unavailable, or improper"
" port specification for the physical Fibre Channel ports."
msgstr ""
"Impossibile trovare una porta fisica a cui associare una porta Fibre Channel virtuale.  "
"Questo si verifica a causa di un Virtual I/O Server non disponibile o di una"
" specifica di porta non corretta per le porte Fibre Channel fisiche."

#: pypowervm/exceptions.py:174
msgid ""
"Unable to start the console to the Virtual Machine.  The pypowervm API is"
" running in a non-local mode.  The console can only be deployed when "
"pypowervm is co-located with the PowerVM API."
msgstr ""
"Impossibile avviare la console per la macchina virtuale. L'API pypowervm è"
" in esecuzione in modalità non locale. La console può essere distribuita solo quando "
"pypowervm si trova nella stessa ubicazione dell'API PowerVM."

#: pypowervm/exceptions.py:181
#, python-format
msgid "WrapperTask %(name)s has no subtasks!"
msgstr "WrapperTask %(name)s non ha attività secondarie."

#: pypowervm/exceptions.py:185
msgid "FeedTask can't have an empty feed."
msgstr "FeedTask non può avere un feed vuoto."

#: pypowervm/exceptions.py:189
#, python-format
msgid "OS denied access to file %(access_file)s."
msgstr "L'SO ha negato l'accesso al file %(access_file)s."

#: pypowervm/exceptions.py:193
#, python-format
msgid ""
"OS encountered an I/O error attempting to read file %(access_file)s: "
"%(error)s"
msgstr ""
"L'SO ha rilevato un errore I/O nel tentativo di leggere il file %(access_file)s: "
"%(error)s"

#: pypowervm/exceptions.py:198
#, python-format
msgid "The migration task failed. %(error)s"
msgstr "Attività di migrazione non riuscita. %(error)s"

#: pypowervm/exceptions.py:202
#, python-format
msgid "No load source found for VM %(vm_name)s"
msgstr "Nessuna origine di caricamento trovata per la VM %(vm_name)s"

#: pypowervm/exceptions.py:206
#, python-format
msgid ""
"Unable to derive the pg83 encoding for hdisk %(dev_name)s.  The "
"parent_entry attribute is not set.  This may be due to using a PV "
"obtained through an unsupported property chain.  The PV must be accessed "
"via VIOS.phys_vols, VG.phys_vols, or "
"VIOS.scsi_mappings[n].backing_storage."
msgstr ""
"Impossibile derivare la codifica pg83 per l'hdisk %(dev_name)s. "
"L'attributo parent_entry non è impostato. Può essere causato dall'uso di un PV "
"ottenuto attraverso una catena di proprietà non supportate. È necessario accedere al PV "
"tramite VIOS.phys_vols, VG.phys_vols o "
"VIOS.scsi_mappings[n].backing_storage."

#: pypowervm/exceptions.py:214
#, python-format
msgid ""
"Found device %(devname)s %(count)d times; expected to find it at most "
"once."
msgstr ""
"Trovato dispositivo %(devname)s %(count)d volte, deve essere rilevato al massimo "
"una volta."

#: pypowervm/exceptions.py:231
#, python-format
msgid "Expected to find exactly one management partition; found %(count)d."
msgstr "Era previsto trovare una sola partizione di gestione; trovate %(count)d."

#: pypowervm/exceptions.py:237
#, python-format
msgid ""
"Expected to find exactly one partition with ID %(lpar_id)d; found "
"%(count)d."
msgstr ""
"Era previsto trovare una sola partizione con ID %(lpar_id)d; trovate "
"%(count)d."

#: pypowervm/exceptions.py:243
#, python-format
msgid "Couldn't find the default Tier on Shared Storage Pool %(ssp_name)s"
msgstr "Impossibile trovare il livello predefinito sul pool di memoria condivisa %(ssp_name)s"

#: pypowervm/util.py:122
#, python-format
msgid ""
"Proposed extended attribute group '%(arg_xag)s' doesn't match existing "
"extended attribute group '%(path_xag)s'"
msgstr ""
"Il gruppo di attributi estesi proposto '%(arg_xag)s' non corrisponde al "
"gruppo di attributi estesi esistente '%(path_xag)s'"

#: pypowervm/util.py:258
msgid "Certificate has expired."
msgstr "Il certificato è scaduto."

#: pypowervm/util.py:391
#, python-format
msgid "Prefix and suffix together may not be more than %d characters."
msgstr "Il prefisso e il suffisso insieme non possono superare i %d caratteri."

#: pypowervm/util.py:396
msgid "Total length must be at least 1 character."
msgstr "La lunghezza totale deve essere di almeno 1 carattere."

#: pypowervm/util.py:419
msgid "The name parameter must be at least one character long."
msgstr "Il parametro del nome deve essere lungo almeno un carattere."

#: pypowervm/util.py:422
#, python-format
msgid "The name parameter must not exceed %d characters when trunk_ok is False."
msgstr "Il parametro del nome non deve superare i %d caratteri quando trunk_ok è False."

#: pypowervm/util.py:520
msgid "Developer error: partial parent specification."
msgstr "Errore sviluppatore: specifica parent parziale. "

#: pypowervm/util.py:525
msgid ""
"Developer error: parent_type must be either a string schema type or a "
"Wrapper subclass."
msgstr ""
"Errore sviluppatore: il tipo parent deve essere un tipo schema stringa o"
"una sottoclasse Wrapper."

#: pypowervm/helpers/log_helper.py:83
#, python-format
msgid "REQUEST: %s"
msgstr "RICHIESTA: %s"

#: pypowervm/helpers/log_helper.py:103
#, python-format
msgid "RESPONSE: %s"
msgstr "RISPOSTA: %s"

#: pypowervm/tasks/cluster_ssp.py:106
#, python-format
msgid "Waiting for in-progress upload(s) to complete.  Marker LU(s): %s"
msgstr "In attesa del completamento dei caricamenti in corso. LU indicatori: %s"

#: pypowervm/tasks/cluster_ssp.py:135
msgid "Abdicating in favor of in-progress upload."
msgstr "Interruzione in favore del caricamento in corso."

#: pypowervm/tasks/cluster_ssp.py:145
#, python-format
msgid "Abdicating upload in favor of marker %s."
msgstr "Interruzione caricamento in favore dell'indicatore %s."

#: pypowervm/tasks/cluster_ssp.py:198
#, python-format
msgid "Using already-uploaded image LU %s."
msgstr "Utilizzo della LU immagine già caricata %s."

#: pypowervm/tasks/cluster_ssp.py:208
#, python-format
msgid "Creating marker LU %s"
msgstr "Creazione della LU indicatore %s"

#: pypowervm/tasks/cluster_ssp.py:224
#, python-format
msgid "Uploading to image LU %(lu)s (marker %(mkr)s)."
msgstr "Caricamento della LU immagine %(lu)s (indicatore %(mkr)s)."

#: pypowervm/tasks/cluster_ssp.py:235
#, python-format
msgid "Removing failed LU %s."
msgstr "Rimozione della LU malfunzionante %s."

#: pypowervm/tasks/cna.py:117
#, python-format
msgid "Unable to find the Virtual Switch %s on the system."
msgstr "Impossibile trovare lo switch virtuale %s sul sistema."

#: pypowervm/tasks/cna.py:144
#, python-format
msgid "Unable to find a valid VLAN for Virtual Switch %s."
msgstr "Impossibile trovare una VLAN valida VLAN per lo switch virtuale %s."

#: pypowervm/tasks/hdisk.py:197
#, python-format
msgid ""
"hdisk discovery failed; will scrub stale storage for LPAR IDs %s and "
"retry."
msgstr ""
"Rilevamento hdisk non riuscito; verrà ripulita la memoria obsoleta per gli ID LPAR %s e "
"viene ritentata l'operazione."

#: pypowervm/tasks/hdisk.py:339
#, python-format
msgid "LUA Recovery Successful. Device Found: %s"
msgstr "Ripristino LUA riuscito. Dispositivo trovato: %s"

#: pypowervm/tasks/hdisk.py:343
#, python-format
msgid "ITL Error encountered: %s"
msgstr "Riscontrato errore ITL: %s"

#: pypowervm/tasks/hdisk.py:345
#, python-format
msgid "%s Device is currently in use."
msgstr "Il dispositivo %s è attualmente è in uso."

#: pypowervm/tasks/hdisk.py:347
#, python-format
msgid "%s Device discovered with unknown UDID."
msgstr "Dispositivo %s rilevato con UDID sconosciuto."

#: pypowervm/tasks/hdisk.py:349
#, python-format
msgid "Failed to Discover the Device : %s"
msgstr "Rilevamento del dispositivo non riuscito: %s"

#: pypowervm/tasks/hdisk.py:419
#, python-format
msgid "CLIRunner Error: %s"
msgstr "Errore CLIRunner: %s"

#: pypowervm/tasks/hdisk.py:451
msgid ""
"QUERY_INVENTORY LUARecovery Job succeeded, but result contained neither "
"OutputXML nor StdOut."
msgstr ""
"Lavoro di ripristino QUERY_INVENTORY LUA riuscito ma il risultato non contiene "
"OutputXML né StdOut."

#: pypowervm/tasks/hdisk.py:465
#, python-format
msgid "QUERY_INVENTORY produced invalid chunk of XML (%(chunk)s).  Error: %(err)s"
msgstr "QUERY_INVENTORY ha prodotto un chunk di XML (%(chunk)s) non valido. Errore: %(err)s"

#: pypowervm/tasks/hdisk.py:473
#, python-format
msgid ""
"Failed to find pg83 descriptor in XML output:\n"
"%s"
msgstr ""
"Impossibile trovare il descrittore pg83 nell'output XML:\n"
"%s"

#: pypowervm/tasks/memory.py:102
#, python-format
msgid ""
"Error obtaining host memory overhead for host with UUID '%(host)s': "
"%(error)s."
msgstr ""
"Errore nell'ottenere il sovraccarico di memoria host per l'host con UUID '%(host)s': "
"%(error)s."

#: pypowervm/tasks/power.py:216
#, python-format
msgid "Error: %s"
msgstr "Errore: %s"

#: pypowervm/tasks/power.py:263
#, python-format
msgid ""
"Error invalidating adapter cache for LPAR  %(lpar_name) with UUID "
"%(lpar_uuid)s: %(exc)s"
msgstr ""
"Errore durante l'invalidazione della cache adattatore per la LPAR  %(lpar_name) con UUID "
"%(lpar_uuid)s: %(exc)s"

#: pypowervm/tasks/scsi_mapper.py:38
msgid "Retrying modification of SCSI Mapping."
msgstr "Nuovo tentativo di modifica dell'associazione SCSI."

#: pypowervm/tasks/scsi_mapper.py:89
#, python-format
msgid ""
"Found existing mapping of %(stg_type)s storage element %(stg_name)s from "
"Virtual I/O Server %(vios_name)s to client LPAR %(lpar_uuid)s."
msgstr ""
"Trovata un'associazione esistente dell'elemento di memoria %(stg_type)s %(stg_name)s "
"dal Virtual I/O Server %(vios_name)s alla LPAR client %(lpar_uuid)s."

#: pypowervm/tasks/scsi_mapper.py:107
#, python-format
msgid ""
"Creating mapping of %(stg_type)s storage element %(stg_name)s from "
"Virtual I/O Server %(vios_name)s to client LPAR %(lpar_uuid)s."
msgstr ""
"Creazione dell'associazione dell'elemento di memoria %(stg_type)s %(stg_name)s "
"dal Virtual I/O Server %(vios_name)s alla LPAR client %(lpar_uuid)s."

#: pypowervm/tasks/scsi_mapper.py:402
msgid "Must not specify both match_func and stg_elem."
msgstr "Non si devono specificare entrambi match_func e stg_elem."

#: pypowervm/tasks/storage.py:326
#, python-format
msgid "Unable to cleanup after file upload. File uuid: %s"
msgstr "Impossibile eseguire il cleanup dopo il caricamento file. UUID file: %s"

#: pypowervm/tasks/storage.py:445
#, python-format
msgid "Disk Logical Unit %(luname)s has no backing image LU.  (UDID: %(udid)s) "
msgstr "L'unità logica disco %(luname)s non ha una LU immagine di supporto. (UDID: %(udid)s) "

#: pypowervm/tasks/storage.py:489
msgid "Unable to locate new vDisk on file upload."
msgstr "Impossibile individuare il nuovo vDisk sul caricamento file."

#: pypowervm/tasks/storage.py:537
#, python-format
msgid ""
"Ignoring device because it lacks a UDID:\n"
"%s"
msgstr ""
"Il dispositivo viene ignorato perché manca dell'UDID:\n"
"%s"

#: pypowervm/tasks/storage.py:543
#, python-format
msgid "Device %s not found in list."
msgstr "Dispositivo %s non trovato nell'elenco."

#: pypowervm/tasks/storage.py:572
#, python-format
msgid "Deleting virtual disk %(vdisk)s from volume group %(vg)s"
msgstr "Eliminazione del disco virtuale %(vdisk)s dal gruppo di volumi %(vg)s"

#: pypowervm/tasks/storage.py:595
#, python-format
msgid "Deleting virtual optical device %(vopt)s from volume group %(vg)s"
msgstr "Eliminazione del dispositivo ottico virtuale %(vopt)s dal gruppo di volumi %(vg)s"

#: pypowervm/tasks/storage.py:648
#, python-format
msgid "Removing LU %(lu_name)s (UDID %(lu_udid)s)"
msgstr "Rimozione della LU %(lu_name)s (UDID %(lu_udid)s)"

#: pypowervm/tasks/storage.py:652
#, python-format
msgid ""
"LU %(lu_name)s was not found - it may have been deleted out of band.  "
"(UDID: %(lu_udid)s)"
msgstr ""
"La LU %(lu_name)s non è stata trovata, potrebbe essere stata eliminata fuori banda. "
"(UDID: %(lu_udid)s)"

#: pypowervm/tasks/storage.py:670
#, python-format
msgid ""
"Removing Image LU %(lu_name)s because it is no longer in use.  (UDID: "
"%(lu_udid)s)"
msgstr ""
"Rimozione della LU immagine %(lu_name)s perché non è più in uso.  (UDID: "
"%(lu_udid)s)"

#: pypowervm/tasks/storage.py:675
#, python-format
msgid "Backing LU %(lu_name)s was not found.  (UDID: %(lu_udid)s)"
msgstr "LU di backup %(lu_name)s non trovata. (UDID: %(lu_udid)s)"

#: pypowervm/tasks/storage.py:701
msgid "Developer error: Either tier or lufeed is required."
msgstr "Errore sviluppatore: è richiesto il livello o lufeed. "

#: pypowervm/tasks/storage.py:706
msgid "Developer error: The lufeed parameter must comprise LUEnt EntryWrappers."
msgstr "Errore sviluppatore: il parametro lufeed deve comprendere LUEnt EntryWrappers."

#: pypowervm/tasks/storage.py:713
#, python-format
msgid "Deleting LU %(lu_name)s (UDID: %(lu_udid)s)"
msgstr "Eliminazione LU %(lu_name)s (UDID: %(lu_udid)s)"

#: pypowervm/tasks/storage.py:718
#, python-format
msgid ""
"Ignoring HttpError for LU %(lu_name)s may have been deleted out of band."
"  (UDID: %(lu_udid)s)"
msgstr ""
"Si ignora HttpError per LU %(lu_name)s, potrebbe essere stata eliminata fuori banda. "
"  (UDID: %(lu_udid)s)"

#: pypowervm/tasks/storage.py:771
#, python-format
msgid ""
"Removing %(num_maps)d orphan %(stg_type)s mappings from VIOS "
"%(vios_name)s."
msgstr ""
"Rimozione di %(num_maps)d associazioni %(stg_type)s orfane dal VIOS "
"%(vios_name)s."

#: pypowervm/tasks/storage.py:797
#, python-format
msgid "Removing %(num_maps)d port-less VFC mappings from VIOS %(vios_name)s."
msgstr "Rimozione di %(num_maps)d associazioni VFC senza porta dal VIOS %(vios_name)s."

#: pypowervm/tasks/storage.py:824
#, python-format
msgid ""
"Removing %(num_maps)d %(stg_type)s mappings associated with LPAR ID "
"%(lpar_id)d from VIOS %(vios_name)s."
msgstr ""
"Rimozione di %(num_maps)d associazioni %(stg_type)s associate all'ID LPAR "
"%(lpar_id)d dal VIOS %(vios_name)s."

#: pypowervm/tasks/storage.py:891
#, python-format
msgid ""
"Not removing storage %(stg_name)s of type %(stg_type)s because it cannot "
"be determined whether it is still in use.  Manual verification and "
"cleanup may be necessary."
msgstr ""
"Non viene rimossa la memoria %(stg_name)s di tipo %(stg_type)s perché non può "
"essere determinato se è ancora in uso o meno. Potrebbero essere necessari "
"la verifica e il cleanup manuali."

#: pypowervm/tasks/storage.py:902
#, python-format
msgid ""
"Storage scrub ignoring storage element %(stg_name)s because it is of "
"unexpected type %(stg_type)s."
msgstr ""
"Scrub memoria ignora l'elemento memoria %(stg_name)s perché è "
"del tipo imprevisto %(stg_type)s."

#: pypowervm/tasks/storage.py:920
#, python-format
msgid ""
"Scrubbing the following %(vdcount)d Virtual Disks from VIOS %(vios)s: "
"%(vdlist)s"
msgstr ""
"Ripulitura dei seguenti %(vdcount)d dischi virtuali dal VIOS %(vios)s: "
"%(vdlist)s"

#: pypowervm/tasks/storage.py:928
#, python-format
msgid ""
"Scrubbing the following %(vocount)d Virtual Opticals from VIOS %(vios)s: "
"%(volist)s"
msgstr ""
"Ripulitura dei seguenti %(vocount)d dispositivi ottici virtuali dal VIOS %(vios)s: "
"%(volist)s"

#: pypowervm/tasks/storage.py:991
#, python-format
msgid ""
"Skipping scrub of %(stg_type)s mappings from VIOS %(vios_name)s for the "
"following LPAR IDs because those LPARs exist: %(lpar_ids)s"
msgstr ""
"Ignorato scrub di associazioni %(stg_type)s dal VIOS %(vios_name)s per i "
"seguenti ID LPAR perché tali LPAR esistono: %(lpar_ids)s"

#: pypowervm/tasks/vfc_mapper.py:514
#, python-format
msgid ""
"Unable to find appropriate VIOS.  The payload provided was likely "
"insufficient.  The payload data is:\n"
" %s)"
msgstr ""
"Impossibile trovare il VIOS appropriato. Il payload fornito probabilmente era "
"insufficiente. I dati di payload sono:\n"
" %s)"

#: pypowervm/tasks/vterm.py:74
msgid "Unable to close vterm."
msgstr "Impossibile chiudere vterm."

#: pypowervm/tasks/vterm.py:266
#, python-format
msgid "VNCRepeater Server Listening on ip=%(ip)s port=%(port)s"
msgstr "VNCRepeater Server in ascolto su ip=%(ip)s porta=%(port)s"

#: pypowervm/tasks/monitor/util.py:421
msgid ""
"Metric data is not available.  This may be due to the metrics being "
"recently initialized."
msgstr ""
"Dati metrica non disponibili. Può essere causato dalle metriche "
"recentemente inizializzate."

#: pypowervm/tests/test_i18n.py:33
msgid "This is a test"
msgstr "Questo è un test"

#: pypowervm/tests/test_i18n.py:36
msgid "This is a message for which a translation doesn't exist"
msgstr "Questo è un messaggio per il quale non esiste una traduzione"

#: pypowervm/utils/retry.py:152
#, python-format
msgid ""
"Attempt %(retry)d of total %(total)d for URI %(uri)s.  Error was a known "
"retry response code: %(resp_code)s"
msgstr ""
"Tentativo %(retry)d di %(total)d totali per l'URI %(uri)s. L'errore era un "
"codice di risposta di nuovo tentativo noto: %(resp_code)s"

#: pypowervm/utils/retry.py:159
#, python-format
msgid ""
"Attempt %(retry)d of %(total)d failed.  Will retry. The exception was:\n"
" %(except)s."
msgstr ""
"Tentativo %(retry)d di %(total)d non riuscito. Verrà effettuato un nuovo tentativo. L'eccezione era:\n"
" %(except)s."

#: pypowervm/utils/transaction.py:348
msgid "Must supply either EntryWrapper or EntryWrapperGetter."
msgstr "È necessario fornire EntryWrapper o EntryWrapperGetter."

#: pypowervm/utils/transaction.py:374
msgid "Must supply a valid Subtask."
msgstr "È necessario fornire un'attività secondaria valida."

#: pypowervm/utils/transaction.py:378
#, python-format
msgid "Duplicate 'provides' name %s."
msgstr "Nome 'provides' duplicato %s."

#: pypowervm/utils/transaction.py:453
#, python-format
msgid "WrapperTask %s has no Subtasks; no-op execution."
msgstr "WrapperTask %s non ha attività secondarie; nessuna operazione in esecuzione."

#: pypowervm/utils/transaction.py:585
msgid "Must supply either a list of EntryWrappers or a FeedGetter."
msgstr "È necessario fornire un elenco di EntryWrappers o un FeedGetter."

#: pypowervm/utils/transaction.py:764
#, python-format
msgid "FeedTask %s has no Subtasks; no-op execution."
msgstr "FeedTask %s non ha attività secondarie; nessuna operazione in esecuzione."

#: pypowervm/utils/validation.py:161
#, python-format
msgid ""
"Insufficient available %(res_name)s on host for virtual machine "
"'%(instance_name)s' (%(requested)s requested, %(avail)s available)"
msgstr ""
"%(res_name)s disponibili non sufficienti sull'host per la macchina virtuale "
"'%(instance_name)s' (%(requested)s richiesti, %(avail)s disponibili)"

#: pypowervm/utils/validation.py:189
msgid "memory"
msgstr "di memoria"

#: pypowervm/utils/validation.py:210
#, python-format
msgid ""
"The virtual machine must be powered off before changing the minimum or "
"maximum memory. Power off virtual machine %s and try again."
msgstr ""
"La macchina virtuale deve essere spenta prima di modificare il valore minimo o "
"massimo di memoria. Spegnere la macchina virtuale %s e riprovare."

#: pypowervm/utils/validation.py:215
#, python-format
msgid ""
"The virtual machine must be powered off before changing the expansion "
"factor. Power off virtual machine %s and try again."
msgstr ""
"La macchina virtuale deve essere spenta prima di modificare il "
"fattore di espansione. Spegnere la macchina virtuale %s e riprovare."

#: pypowervm/utils/validation.py:302
msgid "CPUs"
msgstr "CPU"

#: pypowervm/utils/validation.py:318
msgid "processing units"
msgstr "unità di elaborazione"

#: pypowervm/utils/validation.py:359
#, python-format
msgid ""
"The virtual machine must be powered off before changing the minimum or "
"maximum processors. Power off virtual machine %s and try again."
msgstr ""
"La macchina virtuale deve essere spenta prima di modificare il valore minimo o "
"massimo di processori. Spegnere la macchina virtuale %s e riprovare."

#: pypowervm/utils/validation.py:369
#, python-format
msgid ""
"The virtual machine must be powered off before changing the minimum or "
"maximum processor units. Power off virtual machine %s and try again."
msgstr ""
"La macchina virtuale deve essere spenta prima di modificare il valore minimo o "
"massimo di unità processore. Spegnere la macchina virtuale %s e riprovare."

#: pypowervm/utils/validation.py:385
#, python-format
msgid ""
"The virtual machine must be powered off before changing the processor "
"compatibility mode. Power off virtual machine %s and try again."
msgstr ""
"La macchina virtuale deve essere spenta prima di modificare la modalità "
"di compatibilità processore. Spegnere la macchina virtuale %s e riprovare."

#: pypowervm/utils/validation.py:393
#, python-format
msgid ""
"The virtual machine must be powered off before changing the processing "
"mode. Power off virtual machine %s and try again."
msgstr ""
"La macchina virtuale deve essere spenta prima di modificare la modalità "
"di elaborazione. Spegnere la macchina virtuale %s e riprovare."

#: pypowervm/utils/validation.py:422
#, python-format
msgid ""
"The desired processors (%(vcpus)d) cannot be above the maximum allowed "
"processors per partition (%(max_allowed)d) for virtual machine "
"'%(instance_name)s'."
msgstr ""
"I processori desiderati (%(vcpus)d) non possono essere più del numero massimo "
"di processori consentiti per partizione (%(max_allowed)d) per la macchina virtuale "
"'%(instance_name)s'."

#: pypowervm/utils/validation.py:434
#, python-format
msgid ""
"The maximum processors (%(vcpus)d) cannot be above the maximum system "
"capacity processor limit (%(max_allowed)d) for virtual machine "
"'%(instance_name)s'."
msgstr ""
"Il numero massimo di processori (%(vcpus)d) non può essere superiore al limite massimo "
"di processori della capacità di sistema (%(max_allowed)d) per la macchina virtuale "
"'%(instance_name)s'."

#: pypowervm/utils/validation.py:506
#, python-format
msgid ""
"The virtual machine must be powered off before changing the simplified "
"remote restart capability. Power off virtual machine %s and try again."
msgstr ""
"La macchina virtuale deve essere spenta prima di modificare "
"la capacità di reimportazione semplificata. Spegnere la macchina virtuale %s e riprovare."

#: pypowervm/wrappers/base_partition.py:526
#, python-format
msgid "Invalid KeylockPos '%s'."
msgstr "KeylockPos non valido '%s'."

#: pypowervm/wrappers/base_partition.py:537
#, python-format
msgid "Invalid BootMode '%s'."
msgstr "Modalità di avvio non valida '%s'."

#: pypowervm/wrappers/base_partition.py:1299
msgid "IOSlot.adapter is deprecated!  Use IOSlot.io_adapter instead."
msgstr "IOSlot.adapter è obsoleto, utilizzare invece IOSlot.io_adapter."

#: pypowervm/wrappers/enterprise_pool.py:143
#, python-format
msgid ""
"Unable to determine master management console MTMS (machine type, model, "
"serial number) from %(identifier)s because no %(param)s was marked as the"
" master console for the pool."
msgstr ""
"Impossibile determinare la console di gestione master MTMS (tipo macchina, modello, "
"numero di serie) da %(identifier)s perché nessun %(param)s è stato contrassegnato come"
" console master per il pool."

#: pypowervm/wrappers/entry_wrapper.py:371
#, python-format
msgid "Cannot convert %(property_name)s='%(value)s' in object %(pvmobject)s"
msgstr "Impossibile convertire %(property_name)s='%(value)s' nell'oggetto %(pvmobject)s"

#: pypowervm/wrappers/entry_wrapper.py:496
msgid ""
"Refusing set href over multiple links.\n"
"Path: %{path}s\n"
"Number of links found: %{nlinks}d"
msgstr ""
"Rifiuto impostazione di href su più link.\n"
"Percorso: %{path}s\n"
"Numero di link trovati: %{nlinks}d"

#: pypowervm/wrappers/entry_wrapper.py:540
msgid "Refusing to construct and wrap an Element without a tag."
msgstr "Rifiuto di creare e includere un elemento senza tag."

#: pypowervm/wrappers/entry_wrapper.py:665
msgid "Response is missing 'entry' property."
msgstr "Alla risposta manca la proprietà 'entry'."

#: pypowervm/wrappers/entry_wrapper.py:679
#, python-format
msgid "Must supply a Response or Entry to wrap.  Got %s"
msgstr "È necessario fornire una risposta o una voce da includere. Ottenuto %s"

#: pypowervm/wrappers/entry_wrapper.py:766
msgid ""
"Developer error: specify 'parent' or ('parent_type' and 'parent_uuid') to"
" retrieve a CHILD object."
msgstr ""
"Errore sviluppatore: specificare 'parent' o ('parent_type' e 'parent_uuid') per"
"richiamare un oggetto CHILD. "

#: pypowervm/wrappers/entry_wrapper.py:771
msgid "Specify either 'uuid' or 'root_id' when requesting a ROOT object."
msgstr "Specificare 'uuid' o 'root_id' quando si richiede un oggetto ROOT."

#: pypowervm/wrappers/entry_wrapper.py:784
msgid ""
"Both parent_type and parent_uuid are required when retrieving a CHILD "
"feed or entry."
msgstr ""
"Sono richiesti entrambi parent_type e parent_uuid quando si richiama "
"un feed o voce CHILD."

#: pypowervm/wrappers/entry_wrapper.py:787
msgid "Specify the parent's UUID via the parent_uuid parameter."
msgstr "Specificare l'UUID de,l parent tramite il parametro parent_uuid."

#: pypowervm/wrappers/entry_wrapper.py:791
msgid "Specify either 'uuid' or 'child_id' when requesting a CHILD object."
msgstr "Specificare 'uuid' o 'child_id' quando si richiede un oggetto CHILD."

#: pypowervm/wrappers/entry_wrapper.py:885
msgid "Parent UUID specified without parent type."
msgstr "UUID parent specificato senza tipo di parent."

#: pypowervm/wrappers/entry_wrapper.py:888
msgid "The search() method requires exactly one key=value argument."
msgstr "Il metodo search() richiede un solo argomento key=value."

#: pypowervm/wrappers/entry_wrapper.py:919
#, python-format
msgid "Wrapper class %(class)s does not support search key '%(key)s'."
msgstr "La classe wrapper %(class)s non supporta la chiave di ricerca '%(key)s'."

#: pypowervm/wrappers/entry_wrapper.py:1019
msgid ""
"The 'xag' parameter to EntryWrapper.update is deprecated!  At best, using"
" it will result in a no-op.  At worst, it will give you incurable etag "
"mismatch errors."
msgstr ""
"Il parametro 'xag' per EntryWrapper.update è obsoleto; nel caso migliore, utilizzarlo"
" porterà a un no-op. Nel caso peggiore, darà errori "
"di mancata corrispondenza etag irreversibili."

#: pypowervm/wrappers/entry_wrapper.py:1081
msgid "Cannot set uuid."
msgstr "Impossibile impostare l'uuid."

#: pypowervm/wrappers/entry_wrapper.py:1282
msgid "No such child element."
msgstr "Nessun elemento child di questo genere."

#: pypowervm/wrappers/entry_wrapper.py:1343
msgid "Cannot set UUID on Wrapper with no Metadata."
msgstr "Impossibile impostare l'UUID sul wrapper senza metadati."

#: pypowervm/wrappers/entry_wrapper.py:1348
#, python-format
msgid "uuid value not valid: %s"
msgstr "il valore uuid non è valido: %s"

#: pypowervm/wrappers/entry_wrapper.py:1403
msgid "Must specify a Wrapper subclass."
msgstr "È necessario specificare una sottoclasse wrapper."

#: pypowervm/wrappers/entry_wrapper.py:1412
msgid "Must specify both parent class and parent UUID, or neither."
msgstr "È necessario specificare sia la classe parent che l'UUID parent, o nessuno dei due."

#: pypowervm/wrappers/job.py:276
#, python-format
msgid "Job %(job_id)s monitoring for %(time)i seconds."
msgstr "Monitoraggio lavoro %(job_id)s per %(time)i secondi."

#: pypowervm/wrappers/job.py:327
#, python-format
msgid ""
"Issuing cancel request for job %(job_id)s. Will poll the job indefinitely"
" for termination."
msgstr ""
"Viene emessa la richiesta di annullamento del lavoro %(job_id)s. Verrà eseguito il polling del lavoro all'infinito"
" per terminarlo."

#: pypowervm/wrappers/job.py:343
#, python-format
msgid "Job %s not deleted. Job is in running state."
msgstr "Lavoro %s non eliminato. Il lavoro è in esecuzione."

#: pypowervm/wrappers/logical_partition.py:150
#: pypowervm/wrappers/logical_partition.py:230
msgid "LPAR does not have an active RMC connection."
msgstr "La LPAR non ha una connessione RMC attiva."

#: pypowervm/wrappers/logical_partition.py:152
#, python-format
msgid "LPAR does not have an active DLPAR capability for %s."
msgstr "La LPAR non ha una capacità DLPAR attiva per %s."

#: pypowervm/wrappers/logical_partition.py:164
msgid "I/O"
msgstr "I/O"

#: pypowervm/wrappers/logical_partition.py:174
msgid "Memory"
msgstr "Memoria"

#: pypowervm/wrappers/logical_partition.py:184
msgid "Processors"
msgstr "Processori"

#: pypowervm/wrappers/logical_partition.py:208
msgid "LPAR is not in an active state."
msgstr "La LPAR non è in stato Attivo."

#: pypowervm/wrappers/logical_partition.py:218
msgid "Target system does not have the IBM i LPAR Mobility Capability."
msgstr "Il sistema di destinazione non ha la capacità LPAR Mobility IBM i."

#: pypowervm/wrappers/logical_partition.py:222
msgid "IBM i LPAR does not have restricted I/O."
msgstr "La LPAR IBM i non ha I/O limitato."

#: pypowervm/wrappers/logical_partition.py:226
msgid "Source system does not have the IBM i LPAR Mobility Capability."
msgstr "Il sistema di origine non ha la capacità LPAR Mobility IBM i."

#: pypowervm/wrappers/logical_partition.py:234
msgid "LPAR is not available for LPM due to missing DLPAR capabilities."
msgstr "La LPAR non è disponibile per LPM a causa di capacità DLPAR mancanti."

#: pypowervm/wrappers/logical_partition.py:251
#: pypowervm/wrappers/logical_partition.py:260
#: pypowervm/wrappers/logical_partition.py:268
msgid ""
"This is not the property you are looking for.  Use srr_enabled in a "
"NovaLink environment."
msgstr ""
"Questa non è la proprietà che si sta cercando. Utilizzare srr_enabled in"
"un ambiente NovaLink."

#: pypowervm/wrappers/logical_partition.py:304
#, python-format
msgid "Invalid IPLSrc '%s'."
msgstr "IPLSrc non valido '%s'."

#: pypowervm/wrappers/storage.py:489
#, python-format
msgid ""
"PV had encoded pg83 descriptor \"%(pg83_raw)s\", but it failed to decode "
"(%(type_error)s)."
msgstr ""
"PV aveva un descrittore pg83 codificato \"%(pg83_raw)s\", ma non è riuscito a decodificare "
"(%(type_error)s)."

#: pypowervm/wrappers/virtual_io_server.py:143
msgid ""
"The 'xags' property of the VIOS EntryWrapper class is deprecated!  Please"
" use values from pypowervm.const.XAG instead."
msgstr ""
"La proprietà 'xags' della classe VIOS EntryWrapper è obsoleta."
" Utilizzare invece i valori da pypowervm.const.XAG."


# ENGL1SH_VERS10N 47423_39 DO NOT REMOVE OR CHANGE THIS LINE
# T9N_SRC_ID 23
# T9N_SH1P_STR1NG PV131AAP001 3
