# Translations template for pypowervm.
# Copyright 2015, 2017 IBM Corp.
# This file is distributed under the same license as the pypowervm project.
# Automatically generated, 2017.
#
msgid ""
msgstr ""
"Project-Id-Version: pypowervm 1.1.3.dev1\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2017-04-20 10:36-0400\n"
"PO-Revision-Date: 2017-04-20 10:36-0400\n"
"Last-Translator: Automatically generated\n"
"Language-Team: none\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.4.0\n"

#: pypowervm/adapter.py:131
#, python-format
msgid "Invalid protocol \"%s\""
msgstr "Protocolo inválido \"%s\""

#: pypowervm/adapter.py:137
msgid "Unencrypted communication with PowerVM! Revert configuration to https."
msgstr "Comunicação não criptografada com o PowerVM! Reverta a configuração para HTTPS."

#: pypowervm/adapter.py:151
msgid "Calculating default audit memento failed, using 'default'."
msgstr "Falha ao calcular o memento de auditoria padrão, usando 'padrão'."

#: pypowervm/adapter.py:192
msgid "Local authentication not supported on HMC."
msgstr "Autenticação local não suportada no HMC."

#: pypowervm/adapter.py:211
#, python-format
msgid "Setting up event listener for %s"
msgstr "Configurando listener de eventos para %s"

#: pypowervm/adapter.py:281
#, python-format
msgid "Unexpected filehandle on %s request"
msgstr "Manipulação de arquivos inesperada na solicitação %s"

#: pypowervm/adapter.py:327
#, python-format
msgid "Unexpected error for %(meth)s %(url)s"
msgstr "Erro inesperado para %(meth)s %(url)s"

#: pypowervm/adapter.py:329
#, python-format
msgid "Unexpected error: %(class)s for %(method)s %(url)s: %(excp)s"
msgstr "Erro inesperado: %(class)s para %(method)s %(url)s: %(excp)s"

#: pypowervm/adapter.py:367
msgid ""
"Re-login has been deemed unsafe. This Session instance should no longer be "
"used."
msgstr ""
"O novo login foi considerado não seguro. Esta instância de sessão não deve mais ser "
"usada."

#: pypowervm/adapter.py:377
#, python-format
msgid "Attempting re-login %s"
msgstr "Tentando novo login %s"

#: pypowervm/adapter.py:388
#, python-format
msgid ""
"Re-login 401, response body:\n"
"%s"
msgstr ""
"Novo login 401, corpo de resposta:\n"
"%s"

#: pypowervm/adapter.py:393
#, python-format
msgid ""
"Re-login failed, resp body:\n"
"%s"
msgstr ""
"Falha no novo login, corpo de resposta:\n"
"%s"

#: pypowervm/adapter.py:397
#, python-format
msgid ""
"Re-login failed:\n"
"%s"
msgstr ""
"Novo login com falha:\n"
"%s"

#: pypowervm/adapter.py:416
#, python-format
msgid ""
"Re-attempt failed with another 401, response body:\n"
"%s"
msgstr ""
"Falha na nova tentativa com outro 401, corpo de resposta:\n"
"%s"

#: pypowervm/adapter.py:419
#, python-format
msgid ""
"suspicious HTTP 401 response for %(method)s %(path)s: token is brand new"
msgstr ""
"resposta HTTP 401 suspeita para %(method)s %(path)s: o token é completamente novo"

#: pypowervm/adapter.py:461
#, python-format
msgid ""
"Failed to connect to REST server - is the pvm-rest service started?  "
"Retrying %(try_num)d of %(max_tries)d after %(delay)d seconds."
msgstr ""
"Falha ao conectar-se ao servidor REST - o serviço pvm-rest foi iniciado?  "
"Tentando %(try_num)d de %(max_tries)d após %(delay)d segundos."

#: pypowervm/adapter.py:468
#, python-format
msgid "Session logging on %s"
msgstr "Criação de log de sessão ativada %s"

#: pypowervm/adapter.py:532
msgid "Failed to parse a session token from the PowerVM response."
msgstr "Falha ao analisar um token de sessão a partir da resposta do PowerVM."

#: pypowervm/adapter.py:534 pypowervm/adapter.py:550
#, python-format
msgid " Body= %s"
msgstr " Corpo = %s"

#: pypowervm/adapter.py:548
msgid "Failed to parse a session file path from the PowerVM response."
msgstr "Falha ao analisar um caminho de arquivo de sessão a partir da resposta do PowerVM."

#: pypowervm/adapter.py:562
#, python-format
msgid "Token file %s didn't contain a readable session token."
msgstr "O arquivo de token %s não continha um token de sessão legível."

#: pypowervm/adapter.py:572
#, python-format
msgid "Session logging off %s"
msgstr "Criação de log de sessão desativada %s"

#: pypowervm/adapter.py:577
msgid "Problem logging off.  Ignoring."
msgstr "Problema ao efetuar logoff.  Ignorando."

#: pypowervm/adapter.py:671
msgid "job must be a JobRequest element"
msgstr "a tarefa deve ser um elemento JobRequest"

#: pypowervm/adapter.py:675
msgid "JobRequest is missing OperationName"
msgstr "OperationName está ausente de JobRequest"

#: pypowervm/adapter.py:689 pypowervm/adapter.py:807 pypowervm/adapter.py:846
#: pypowervm/adapter.py:903
#, python-format
msgid "path=%s is not a PowerVM API reference"
msgstr "path=%s não é uma referência da API do PowerVM"

#: pypowervm/adapter.py:918 pypowervm/adapter.py:935
msgid "Invalid file descriptor"
msgstr "Descritor de arquivo inválido"

#: pypowervm/adapter.py:1022 pypowervm/adapter.py:1050
#: pypowervm/adapter.py:1065
msgid "Expected root_id"
msgstr "root_id esperado"

#: pypowervm/adapter.py:1024
msgid "Expected child_type"
msgstr "child_type esperado"

#: pypowervm/adapter.py:1028 pypowervm/adapter.py:1054
#: pypowervm/adapter.py:1059
#, python-format
msgid "Unexpected suffix_type=%s"
msgstr "suffix_type=%s inesperado"

#: pypowervm/adapter.py:1031 pypowervm/adapter.py:1062
msgid "Expected suffix_parm"
msgstr "suffix_parm esperado"

#: pypowervm/adapter.py:1033 pypowervm/adapter.py:1052
#: pypowervm/adapter.py:1067
msgid "Expected child_id"
msgstr "child_id esperado"

#: pypowervm/adapter.py:1036 pypowervm/adapter.py:1045
msgid "Unexpected child_id"
msgstr "child_id inesperado"

#: pypowervm/adapter.py:1038 pypowervm/adapter.py:1047
msgid "Unexpected root_id"
msgstr "root_id inesperado"

#: pypowervm/adapter.py:1069
#, python-format
msgid "Unexpected req_method=%s"
msgstr "req_method=%s inesperado"

#: pypowervm/adapter.py:1138
#, python-format
msgid "Error parsing XML response from PowerVM: %s"
msgstr "Erro ao analisar a resposta XML do PowerVM: %s"

#: pypowervm/adapter.py:1151
msgid "Response is not an Atom feed/entry"
msgstr "A resposta não é uma entrada ou um feed Atom"

#: pypowervm/adapter.py:1162
msgid "Unexpected HTTP 204 for request"
msgstr "HTTP 204 inesperado para solicitação"

#: pypowervm/adapter.py:1170
msgid "Unexpectedly empty response body"
msgstr "Corpo de resposta vazio inesperado"

#: pypowervm/adapter.py:1173
#, python-format
msgid ""
"%(err_reason)s:\n"
"request headers: %(reqheaders)s\n"
"\n"
"request body: %(reqbody)s\n"
"\n"
"response headers: %(respheaders)s\n"
"\n"
"response body: %(respbody)s"
msgstr ""
"%(err_reason)s:\n"
"cabeçalhos de solicitação: %(reqheaders)s\n"
"\n"
"corpo da solicitação: %(reqbody)s\n"
"\n"
"cabeçalhos de resposta: %(respheaders)s\n"
"\n"
"corpo de resposta: %(respbody)s"

#: pypowervm/adapter.py:1181
#, python-format
msgid "Atom error for %(method)s %(path)s: %(reason)s"
msgstr "Erro do Atom para %(method)s %(path)s: %(reason)s"

#: pypowervm/adapter.py:1222
msgid "Session must not be None"
msgstr "A sessão não deve ser Nenhuma"

#: pypowervm/adapter.py:1224
msgid "An event listener is already active on the session."
msgstr "Um listener de eventos já está ativo na sessão."

#: pypowervm/adapter.py:1243
#, python-format
msgid "Failed to initialize event feed listener: %s"
msgstr "Falha ao inicializar o listener de feed de eventos: %s"

#: pypowervm/adapter.py:1247
#, python-format
msgid "Application id \"%s\" is not unique"
msgstr "O ID do aplicativo \"%s\" não é exclusivo"

#: pypowervm/adapter.py:1256
msgid "Shutting down"
msgstr "Encerrando"

#: pypowervm/adapter.py:1259
msgid "This handler is already subscribed"
msgstr "Este manipulador já está inscrito"

#: pypowervm/adapter.py:1267
msgid "Handler must be an EventHandler"
msgstr "O manipulador deve ser EventHandler"

#: pypowervm/adapter.py:1270
msgid "This handler not found in subscriber list"
msgstr "Este manipulador não foi localizado na lista de assinantes"

#: pypowervm/adapter.py:1278
#, python-format
msgid "Shutting down EventListener for %s"
msgstr "Encerrando o EventListener para %s"

#: pypowervm/adapter.py:1282
#, python-format
msgid "EventListener shutdown complete for %s"
msgstr "Encerramento de EventListener concluído para %s"

#: pypowervm/adapter.py:1302
#, python-format
msgid ""
"Error while getting PowerVM events: %s.  (Is the pvm-rest service down?)"
msgstr ""
"Erro ao obter eventos do PowerVM: %s.  (O serviço pvm-rest está inativo?)"

#: pypowervm/adapter.py:1345
#, python-format
msgid "Unexpected EventType=%s"
msgstr "EventType=%s inesperado"

#: pypowervm/adapter.py:1373
msgid "Error while processing PowerVM events"
msgstr "Erro ao processar eventos do PowerVM"

#: pypowervm/exceptions.py:117
#, python-format
msgid ""
"Unable to derive the appropriate physical FC port for WWPN %(wwpn)s.  The "
"VIOS Extended Attribute Groups may have been insufficient.  The VIOS URI for "
"the query was %(vio_uri)s."
msgstr ""
"Não é possível derivar uma porta FC física adequada para WWPN %(wwpn)s.  Os "
"Grupos de Atributos Estendidos VIOS podem ter sido insuficientes.  O URI do VIOS (Virtual I/O Server) para a "
"consulta era %(vio_uri)s."

#: pypowervm/exceptions.py:123
#, python-format
msgid "Element not found: %(element_type)s %(element)s"
msgstr "Elemento não localizado: %(element_type)s %(element)s"

#: pypowervm/exceptions.py:127
#, python-format
msgid "LPAR not found: %(lpar_name)s"
msgstr "LPAR não localizado: %(lpar_name)s"

#: pypowervm/exceptions.py:131
#, python-format
msgid "The '%(operation_name)s' operation failed. %(error)s"
msgstr "A operação '%(operation_name)s' falhou. %(error)s"

#: pypowervm/exceptions.py:135
#, python-format
msgid ""
"The '%(operation_name)s' operation failed. Failed to complete the task in "
"%(seconds)d seconds."
msgstr ""
"A operação '%(operation_name)s' falhou. Falha ao concluir a tarefa em "
"%(seconds)d segundos."

#: pypowervm/exceptions.py:140
#, python-format
msgid ""
"Can not perform OS shutdown on Virtual Machine %(lpar_nm)s because its RMC "
"connection is not active."
msgstr ""
"Não é possível executar o encerramento do SO na máquina virtual %(lpar_nm)s devido à sua conexão RMC "
"não estar ativa."

#: pypowervm/exceptions.py:145
#, python-format
msgid "Failed to power off Virtual Machine %(lpar_nm)s: %(reason)s"
msgstr "Falha ao desligar Máquina Virtual %(lpar_nm)s: %(reason)s"

#: pypowervm/exceptions.py:149
#, python-format
msgid ""
"Power off of Virtual Machine %(lpar_nm)s timed out after %(timeout)d seconds."
msgstr ""
"Desligue a máquina virtual %(lpar_nm)s que atingiu o tempo limite após %(timeout)d segundos."

#: pypowervm/exceptions.py:154
#, python-format
msgid "Failed to power on Virtual Machine %(lpar_nm)s: %(reason)s"
msgstr "Falha ao ligar a Máquina Virtual %(lpar_nm)s: %(reason)s"

#: pypowervm/exceptions.py:158
#, python-format
msgid ""
"Power on of Virtual Machine %(lpar_nm)s timed out after %(timeout)d seconds."
msgstr ""
"A energia da máquina virtual %(lpar_nm)s atingiu tempo limite após %(timeout)d segundos."

#: pypowervm/exceptions.py:163
#, python-format
msgid ""
"Unable to remove VLAN %(vlan_id)d as it is the Primary VLAN Identifier on a "
"different Network Bridge."
msgstr ""
"Não é possível remover a VLAN %(vlan_id)d quando ela é o identificador primário de VLAN em uma "
"ponte de rede diferente."

#: pypowervm/exceptions.py:168
#, python-format
msgid ""
"Unable to provision VLAN %(vlan_id)d.  It appears to be contained on device "
"'%(dev_name)s' on Virtual I/O Server %(vios)s.  That device is not connected "
"to any Network Bridge (Shared Ethernet Adapter).  Please manually remove the "
"device or add it to the Network Bridge before continuing."
msgstr ""
"Não é possível provisionar a VLAN %(vlan_id)d.  Ela parece estar contida no dispositivo "
"'%(dev_name)s' no Virtual I/O Server %(vios)s.  Esse dispositivo não está conectado "
"a nenhuma ponte de rede (adaptador Ethernet compartilhado).  Remova manualmente o "
"dispositivo ou inclua-o na ponte de rede antes de continuar."

#: pypowervm/exceptions.py:177
#, python-format
msgid ""
"A Logical Unit with name %(lu_name)s already exists on Shared Storage Pool "
"%(ssp_name)s."
msgstr ""
"Uma unidade lógica com o nome %(lu_name)s já existe no conjunto de armazenamentos compartilhados "
"%(ssp_name)s."

#: pypowervm/exceptions.py:182
msgid ""
"Unable to find a physical port to map a virtual Fibre Channel port to.  This "
"is due to either a Virtual I/O Server being unavailable, or improper port "
"specification for the physical Fibre Channel ports."
msgstr ""
"Não é possível localizar uma porta física para a qual mapear uma porta Fibre Channel virtual.  Isso acontece "
"porque um Virtual I/O Server está indisponível ou porque houve uma especificação de porta incorreta "
"para as portas físicas do Fibre Channel."

#: pypowervm/exceptions.py:189
msgid ""
"Unable to start the console to the Virtual Machine.  The pypowervm API is "
"running in a non-local mode.  The console can only be deployed when "
"pypowervm is co-located with the PowerVM API."
msgstr ""
"Não é possível iniciar o console na Máquina Virtual.  A API pypowervm está "
"em execução em um modo não local.  O console pode ser implementada apenas quando "
"pypowervm estiver colocalizado com a API do PowerVM."

#: pypowervm/exceptions.py:196
#, python-format
msgid "WrapperTask %(name)s has no subtasks!"
msgstr "WrapperTask %(name)s não tem subtarefas!"

#: pypowervm/exceptions.py:200
msgid "FeedTask can't have an empty feed."
msgstr "FeedTask não pode ter um feed vazio."

#: pypowervm/exceptions.py:204
#, python-format
msgid "OS denied access to file %(access_file)s."
msgstr "O OS (sistema operacional) negou acesso ao arquivo %(access_file)s."

#: pypowervm/exceptions.py:208
#, python-format
msgid ""
"OS encountered an I/O error attempting to read file %(access_file)s: "
"%(error)s"
msgstr ""
"O sistema operacional encontrou um erro de E/S ao tentar ler o arquivo %(access_file)s: "
"%(error)s"

#: pypowervm/exceptions.py:213
#, python-format
msgid "The migration task failed. %(error)s"
msgstr "A tarefa de migração falhou. %(error)s"

#: pypowervm/exceptions.py:217
#, python-format
msgid "No load source found for VM %(vm_name)s"
msgstr "Nenhuma origem de carregamento foi localizada para a VM %(vm_name)s"

#: pypowervm/exceptions.py:221
#, python-format
msgid ""
"Unable to derive the pg83 encoding for hdisk %(dev_name)s.  The parent_entry "
"attribute is not set.  This may be due to using a PV obtained through an "
"unsupported property chain.  The PV must be accessed via VIOS.phys_vols, VG."
"phys_vols, or VIOS.scsi_mappings[n].backing_storage."
msgstr ""
"Não é possível derivar a codificação pg83 para o %(dev_name)s.  O atributo parent_entry "
"não está configurado.  Isso pode ser devido o uso de uma PV obtida por meio de uma "
"cadeia de propriedades não suportada.  A PV deve ser acessada por meio de VIOS.phys_vols, VG."
"phys_vols ou VIOS.scsi_mappings[n].backing_storage."

#: pypowervm/exceptions.py:229
#, python-format
msgid ""
"Found device %(devname)s %(count)d times; expected to find it at most once."
msgstr ""
"Dispositivo localizado %(devname)s %(count)d vezes; esperava-se localizá-lo no máximo uma vez."

#: pypowervm/exceptions.py:244
#, python-format
msgid ""
"FeedTask %(ft_name)s experienced multiple exceptions:\n"
"\t%(concat_msgs)s"
msgstr ""
"FeedTask %(ft_name)s experimentou múltiplas exceções:\n"
"\t%(concat_msgs)s"

#: pypowervm/exceptions.py:254
#, python-format
msgid "Expected to find exactly one management partition; found %(count)d."
msgstr "Esperava localizar exatamente uma partição de gerenciamento; localizada %(count)d."

#: pypowervm/exceptions.py:260
#, python-format
msgid ""
"Expected to find exactly one partition with ID %(lpar_id)d; found %(count)d."
msgstr ""
"Esperava-se localizar exatamente uma partição com o ID %(lpar_id)d; %(count)d localizadas."

#: pypowervm/exceptions.py:266
#, python-format
msgid "Couldn't find the default Tier on Shared Storage Pool %(ssp_name)s."
msgstr "Não foi possível localizar a Camada padrão no Conjunto de Armazenamentos Compartilhados %(ssp_name)s."

#: pypowervm/exceptions.py:275
#, python-format
msgid ""
"The device with UDID %(udid)s was not found on any of the Virtual I/O "
"Servers."
msgstr ""
"O dispositivo com UDID %(udid)s não foi localizado em nenhum Virtual I/O "
"Server."

#: pypowervm/exceptions.py:280
#, python-format
msgid ""
"There are not enough Virtual I/O Servers to support the virtual machine's "
"device with UDID %(udid)s."
msgstr ""
"Não há Virtual I/O Servers suficientes para suportar o dispositivo da máquina virtual "
"com UDID %(udid)s."

#: pypowervm/exceptions.py:285
#, python-format
msgid ""
"The expected fabrics (%(fabrics)s) were not found on any of the Virtual I/O "
"Servers."
msgstr ""
"As malhas esperadas (%(fabrics)s) não foram localizadas em nenhum Virtual I/O "
"Server."

#: pypowervm/exceptions.py:290
#, python-format
msgid ""
"Can not rebuild the virtual machine.  It is using an I/O type of %(io_type)s "
"which is not supported for VM rebuild."
msgstr ""
"Não é possível reconstruir a máquina virtual.  Ela está usando um tipo de E/S de %(io_type)s "
"que não é suportado para reconstrução da VM."

#: pypowervm/exceptions.py:295
#, python-format
msgid ""
"The number of VFC slots on the target system (%(rebuild_slots)d) does not "
"match the number of slots on the client system (%(original_slots)d).  Unable "
"to rebuild this virtual machine on this system."
msgstr ""
"O número de slots de VFC no sistema de destino (%(rebuild_slots)d) não "
"corresponde ao número de slots no sistema do cliente (%(original_slots)d).  Não é possível "
"reconstruir esta máquina virtual neste sistema."

#: pypowervm/exceptions.py:302
#, python-format
msgid ""
"To register the slot information of the network device a CNA or VNIC adapter "
"is needed. Instead the following was given: %(wrapper)s."
msgstr ""
"Para registrar as informações do slot do dispositivo de rede, um adaptador CNA ou VNIC "
"é necessário. Em vez disso, o seguinte foi fornecido: %(wrapper)s."

#: pypowervm/exceptions.py:308
#, python-format
msgid ""
"There are not enough active Virtual I/O Servers available. Expected %(exp)d; "
"found %(act)d."
msgstr ""
"Não há Virtual I/O Servers ativos disponíveis suficientes. %(exp)d; esperado; "
"%(act)d localizado."

#: pypowervm/exceptions.py:313
#, python-format
msgid ""
"No Virtual I/O Servers are available.  Attempted to wait for a VIOS to "
"become active for %(wait_time)d seconds.  Please check the RMC connectivity "
"between the PowerVM NovaLink and the Virtual I/O Servers."
msgstr ""
"Nenhum Virtual I/O Server está disponível.  Tentativa de esperar um VIOS para "
"tornar-se ativo por %(wait_time)d segundos.  Verifique a conectividade do RMC "
"entre o PowerVM NovaLink e os Virtual I/O Servers."

#: pypowervm/exceptions.py:323
#, python-format
msgid ""
"Could not find any SR-IOV adapters in Sriov mode and Running state.\n"
"Location | Mode | State\n"
"%(sriov_loc_mode_state)s"
msgstr ""
"Não foi possível localizar nenhum adaptador SR-IOV no modo Sriov e no estado Executando.\n"
"Localização | Modo | Estado\n"
"%(sriov_loc_mode_state)s"

#: pypowervm/exceptions.py:328
#, python-format
msgid ""
"Unable to fulfill redundancy requirement of %(red)d.  Found %(found_vfs)d "
"viable backing device(s)."
msgstr ""
"Não é possível cumprir o requisito de redundância de %(red)d.  Localizado %(found_vfs)d "
"dispositivos auxiliares viáveis."

#: pypowervm/exceptions.py:333
msgid "The Managed System is not vNIC capable."
msgstr "O sistema gerenciado não é compatível com vNIC."

#: pypowervm/exceptions.py:337
msgid "There are no active vNIC-capable VIOSes."
msgstr "Não há vNIC-capable VIOSes ativos."

#: pypowervm/exceptions.py:341
#, python-format
msgid ""
"A redundancy of %(red)d was specified, but the Managed System is not vNIC "
"failover capable."
msgstr ""
"A redundância de %(red)d foi especificada, mas o sistema gerenciado não é capaz de failover de vNIC "
"."

#: pypowervm/exceptions.py:346
#, python-format
msgid ""
"A redundancy of %(red)d was specified, but there are no active vNIC failover-"
"capable VIOSes."
msgstr ""
"A redundância de %(red)d foi especificada, mas não há nenhum VIOS capaz de failover vNIC ativo"
"."

#: pypowervm/exceptions.py:351
#, python-format
msgid ""
"Unable to locate the volume group %(vol_grp)s to store the virtual optical "
"media within.  Unable to create the media repository."
msgstr ""
"Não é possível localizar o grupo de volumes %(vol_grp)s para armazenar a mídia ótica virtual "
"dentro.  Impossível criar o repositório de mídia."

#: pypowervm/exceptions.py:357
#, python-format
msgid ""
"The ManagedSystem update was not attempted because changes were requested to "
"one or more SR-IOV physical ports which are in use by vNICs.\n"
"%(warnings)s"
msgstr ""
"A atualização ManagedSystem não foi tentada porque foram solicitadas mudanças para "
"uma ou mais portas físicas SR-IOV que estão em uso pelos vNICs. \n"
"%(warnings)s"

#: pypowervm/exceptions.py:363
#, python-format
msgid "Unable to create VNC based virtual terminal: %(err)s"
msgstr "Não é possível criar VNC baseado em terminal virtual: %(err)s"

#: pypowervm/exceptions.py:367
msgid "The Adapter cache is not supported."
msgstr "O cache do adaptador não é suportado."

#: pypowervm/exceptions.py:371
#, python-format
msgid ""
"Invalid value '%(value)s' for '%(enum)s'.  Valid values are: %(valid_values)s"
msgstr ""
"Valor inválido '%(value)s' para '%(enum)s'.  Os valores válidos são: %(valid_values)s"

#: pypowervm/exceptions.py:376
#, python-format
msgid "No VIOS found with name %(vios_name)s."
msgstr "Nenhum VIOS localizado com o nome %(vios_name)s."

#: pypowervm/exceptions.py:380
#, python-format
msgid "No volume group found with name %(vg_name)s."
msgstr "Nenhum grupo de volumes localizado com o nome %(vg_name)s."

#: pypowervm/util.py:125
#, python-format
msgid ""
"Proposed extended attribute group '%(arg_xag)s' doesn't match existing "
"extended attribute group '%(path_xag)s'"
msgstr ""
"O grupo de atributos estendido proposto '%(arg_xag)s' não corresponde ao "
"grupo de atributos estendidos existente '%(path_xag)s'"

#: pypowervm/util.py:221
msgid "Certificate has expired."
msgstr "O certificado expirou."

#: pypowervm/util.py:371
#, python-format
msgid "Prefix and suffix together may not be more than %d characters."
msgstr "Prefixo e sufixo juntos não pode ter mais de %d caracteres."

#: pypowervm/util.py:376
msgid "Total length must be at least 1 character."
msgstr "O comprimento total deve ser de pelo menos 1 caractere."

#: pypowervm/util.py:399
msgid "The name parameter must be at least one character long."
msgstr "O parâmetro de nome deve ter pelo menos um caractere de comprimento."

#: pypowervm/util.py:402
#, python-format
msgid ""
"The name parameter must not exceed %d characters when trunk_ok is False."
msgstr ""
"O parâmetro de nome não deve exceder %d caracteres quando o parâmetro trunk_ok for False."

#: pypowervm/util.py:500
msgid "Developer error: partial parent specification."
msgstr "Erro do desenvolvedor: especificação-pai parcial."

#: pypowervm/util.py:505
msgid ""
"Developer error: parent_type must be either a string schema type or a "
"Wrapper subclass."
msgstr ""
"Erro do desenvolvedor: parent_type deve ser um tipo de esquema de sequência ou uma "
"subclasse de Wrapper."

#: pypowervm/util.py:602
#, python-format
msgid "Invalid value '%(bad_val)s'.  Expected one of %(good_vals)s, or a list."
msgstr ""
"Valor inválido '%(bad_val)s'. Esperado um de %(good_vals)s ou uma lista."

#: pypowervm/helpers/log_helper.py:83
#, python-format
msgid "REQUEST: %s"
msgstr "SOLICITAÇÃO: %s"

#: pypowervm/helpers/log_helper.py:103
#, python-format
msgid "RESPONSE: %s"
msgstr "RESPOSTA: %s"

#: pypowervm/tasks/cluster_ssp.py:108
#, python-format
msgid "Waiting for in-progress upload(s) to complete.  Marker LU(s): %s"
msgstr "Esperando a conclusão de upload(s) em andamento. LU(s) (unidade lógica) marcadora(s): %s"

#: pypowervm/tasks/cluster_ssp.py:137
msgid "Abdicating in favor of in-progress upload."
msgstr "Abdicando em favor do upload em andamento."

#: pypowervm/tasks/cluster_ssp.py:147
#, python-format
msgid "Abdicating upload in favor of marker %s."
msgstr "Abdicando do upload em favor do marcador %s."

#: pypowervm/tasks/cluster_ssp.py:202
#, python-format
msgid "Using already-uploaded image LU %s."
msgstr "Usando LU da imagem já transferida por upload %s."

#: pypowervm/tasks/cluster_ssp.py:212
#, python-format
msgid "Creating marker LU %s"
msgstr "Criando LU marcadora %s"

#: pypowervm/tasks/cluster_ssp.py:228
#, python-format
msgid "Uploading to image LU %(lu)s (marker %(mkr)s)."
msgstr "Fazendo upload para a LU da imagem %(lu)s (marcadora %(mkr)s)."

#: pypowervm/tasks/cluster_ssp.py:240
#, python-format
msgid "Removing failed LU %s."
msgstr "Removendo LU (unidade lógica) com falha %s."

#: pypowervm/tasks/cna.py:120
#, python-format
msgid "Unable to find the Virtual Switch %s on the system."
msgstr "Impossível localizar o Comutador Virtual %s no sistema."

#: pypowervm/tasks/cna.py:147
#, python-format
msgid "Unable to find a valid VLAN for Virtual Switch %s."
msgstr "Não é possível localizar uma VLAN válida para o comutador virtual %s."

#: pypowervm/tasks/memory.py:102
#, python-format
msgid ""
"Error obtaining host memory overhead for host with UUID '%(host)s': "
"%(error)s."
msgstr ""
"Erro ao obter a sobrecarga da memória do host para o host com UUID '%(host)s': "
"%(error)s."

#: pypowervm/tasks/partition.py:312
#, python-format
msgid ""
"Timed out waiting for the RMC state of all the powered on Virtual I/O "
"Servers to be active. Wait time was: %(time)d seconds. VIOSes that did not "
"go active were: %(vioses)s."
msgstr ""
"Tempo limite atingido ao aguardar que o estado RMC de todos os Virtual I/O "
"Servidores que devem estar ativos. O tempo de espera foi de: %(time)d segundos. Os VIOSes que não ficaram ativos "
"foram: %(vioses)s."

#: pypowervm/tasks/partition.py:354
#, python-format
msgid "Assuming description-less slot is physical I/O: %s"
msgstr "Assumindo que o slot com menos descrição seja a E/S física: %s"

#: pypowervm/tasks/power.py:88
#, python-format
msgid "Partition %s already powered on."
msgstr "Partição %s já ligada."

#: pypowervm/tasks/power.py:136
#, python-format
msgid "Partition %s already powered off."
msgstr "A partição %s já está desligada."

#: pypowervm/tasks/power.py:199
#, python-format
msgid ""
"Specifying add_parms as a dict is deprecated. Please specify a %s instance "
"instead."
msgstr ""
"Especificar add_parms como um dic foi descontinuado. Especifique uma instância %s "
"em vez disso."

#: pypowervm/tasks/power.py:265
#, python-format
msgid ""
"IBMi OS normal shutdown failed.  Trying OS immediate shutdown.  Partition: %s"
msgstr ""
"Encerramento normal do SO IBMi com falha.  Tentando encerramento imediato do SO.  Partição: %s"

#: pypowervm/tasks/power.py:275
#, python-format
msgid ""
"IBMi OS immediate shutdown failed.  Trying VSP normal shutdown.  Partition: "
"%s"
msgstr ""
"Encerramento imediato do SO IBMi com falha.  Tentando encerramento normal VSP.  Partição: "
"%s"

#: pypowervm/tasks/power.py:284
#, python-format
msgid ""
"IBMi VSP normal shutdown failed.  Trying VSP hard shutdown.  Partition: %s"
msgstr ""
"Encerramento normal do IBMi VSP com falha.  Tentando encerramento forçado VSP.  Partição: %s"

#: pypowervm/tasks/power.py:326
#, python-format
msgid ""
"Non-IBMi OS immediate shutdown timed out.  Trying VSP hard shutdown.  "
"Partition: %s"
msgstr ""
"O encerramento imediato do SO não IBMi atingiu o tempo limite.  Tentando encerramento forçado VSP.  "
"Partição: %s"

#: pypowervm/tasks/power.py:330
#, python-format
msgid ""
"Non-IBMi OS immediate shutdown failed.  Trying VSP normal shutdown.  "
"Partition: %s"
msgstr ""
"Encerramento imediato de SO não IBMi com falha.  Tentando encerramento normal VSP.  "
"Partição: %s"

#: pypowervm/tasks/power.py:343
#, python-format
msgid ""
"Non-IBMi VSP normal shutdown failed.  Trying VSP hard shutdown.  Partition: "
"%s"
msgstr ""
"Encerramento normal VSP de não IBMi com falha.  Tentando encerramento forçado VSP.  Partição: "
"%s"

#: pypowervm/tasks/power.py:437
#, python-format
msgid "VSP hard shutdown with default timeout.  Partition: %s"
msgstr "Encerramento forçado VSP com tempo limite padrão.  Partição: %s"

#: pypowervm/tasks/scsi_mapper.py:38
msgid "Retrying modification of SCSI Mapping."
msgstr "Tentando a modificação do Mapeamento SCSI novamente."

#: pypowervm/tasks/scsi_mapper.py:98
#, python-format
msgid ""
"Found existing mapping of %(stg_type)s storage element %(stg_name)s from "
"Virtual I/O Server %(vios_name)s to client LPAR %(lpar_uuid)s."
msgstr ""
"Localizado o mapeamento existente do elemento de armazenamento %(stg_type)s %(stg_name)s do "
"Virtual I/O Server %(vios_name)s para clientes da LPAR %(lpar_uuid)s."

#: pypowervm/tasks/scsi_mapper.py:117
#, python-format
msgid ""
"Creating mapping of %(stg_type)s storage element %(stg_name)s from Virtual I/"
"O Server %(vios_name)s to client LPAR %(lpar_uuid)s."
msgstr ""
"Criando mapeamento de %(stg_type)s elemento de armazenamento %(stg_name)s do Virtual I/"
"O Server %(vios_name)s para a LPAR (partição lógica) cliente %(lpar_uuid)s."

#: pypowervm/tasks/scsi_mapper.py:433
msgid "Must not specify both match_func and stg_elem."
msgstr "Não deve especificar match_func e stg_elem."

#: pypowervm/tasks/slot_map.py:194
msgid ""
"The register_cna method is deprecated! Please use the register_vnet method."
msgstr ""
"O método register_cna foi descontinuado! Use o método register_vnet."

#: pypowervm/tasks/slot_map.py:204
msgid "The drop_cna method is deprecated! Please use the drop_vnet method."
msgstr "O método drop_cna foi descontinuado! Use o método drop_vnet."

#: pypowervm/tasks/sriov.py:379
#, python-format
msgid ""
"SR-IOV Physical Port at location %(loc_code)s is backing a vNIC belonging to "
"LPAR %(lpar_name)s (LPAR UUID: %(lpar_uuid)s; vNIC UUID: %(vnic_uuid)s)."
msgstr ""
"A porta física de SR-IOV no local %(loc_code)s está dando suporte a um vNIC que pertence à "
"LPAR %(lpar_name)s (UUID de LPAR: %(lpar_uuid)s; UUID de vNIC: %(vnic_uuid)s)."

#: pypowervm/tasks/sriov.py:496
msgid ""
"Making changes to the following SR-IOV physical port labels even though they "
"are in use by vNICs:"
msgstr ""
"Fazendo mudanças nos rótulos das seguintes portas físicas SR-IOV, embora "
"estejam em uso pelos vNICs:"

#: pypowervm/tasks/storage.py:96
#, python-format
msgid "Failed to delete vio_file with UUID %s.  It must be manually deleted."
msgstr "Falha ao excluir vio_file com UUID %s.  Ele deve ser excluído manualmente."

#: pypowervm/tasks/storage.py:348
msgid "Encountered an issue while uploading. Will retry."
msgstr "Foi encontrado um problema ao fazer upload. Tentará novamente."

#: pypowervm/tasks/storage.py:522
msgid ""
"The crt_lu_linked_clone method is deprecated!  Please use the crt_lu method "
"(clone=src_lu, size=lu_size_gb)."
msgstr ""
"O método crt_lu_linked_clone foi descontinuado!  Use o método crt_lu "
"(clone=src_lu, size=lu_size_gb)."

#: pypowervm/tasks/storage.py:573
#, python-format
msgid ""
"Disk Logical Unit %(luname)s has no backing image LU.  (UDID: %(udid)s) "
msgstr ""
"A unidade lógica de disco %(luname)s não tem nenhuma LU (unidade lógica) de imagem auxiliar.  (UDID: %(udid)s) "

#: pypowervm/tasks/storage.py:654
msgid "Unable to locate new vDisk on file upload."
msgstr "Não é possível localizar novo vDisk no upload do arquivo."

#: pypowervm/tasks/storage.py:703
#, python-format
msgid ""
"Ignoring device because it lacks a UDID:\n"
"%s"
msgstr ""
"Ignorando dispositivo porque um UDID está ausente:\n"
"%s"

#: pypowervm/tasks/storage.py:709
#, python-format
msgid "Device %s not found in list."
msgstr "Dispositivo %s não localizado na lista."

#: pypowervm/tasks/storage.py:738
#, python-format
msgid "Deleting virtual disk %(vdisk)s from volume group %(vg)s"
msgstr "Excluindo disco virtual %(vdisk)s do grupo de volume %(vg)s"

#: pypowervm/tasks/storage.py:761
#, python-format
msgid "Deleting virtual optical device %(vopt)s from volume group %(vg)s"
msgstr "Excluindo dispositivo ótico virtual %(vopt)s do grupo de volume %(vg)s"

#: pypowervm/tasks/storage.py:817
#, python-format
msgid "Removing LU %(lu_name)s (UDID %(lu_udid)s)"
msgstr "Removendo unidade lógica %(lu_name)s (UDID %(lu_udid)s)"

#: pypowervm/tasks/storage.py:821
#, python-format
msgid ""
"LU %(lu_name)s was not found - it may have been deleted out of band.  (UDID: "
"%(lu_udid)s)"
msgstr ""
"A unidade lógica %(lu_name)s não foi localizada - ela pode ter sido excluída fora da banda.  (UDID: "
"%(lu_udid)s)"

#: pypowervm/tasks/storage.py:839
#, python-format
msgid ""
"Removing Image LU %(lu_name)s because it is no longer in use.  (UDID: "
"%(lu_udid)s)"
msgstr ""
"Removendo LU da imagem %(lu_name)s porque ela não está mais em uso.  (UDID: "
"%(lu_udid)s)"

#: pypowervm/tasks/storage.py:844
#, python-format
msgid "Backing LU %(lu_name)s was not found.  (UDID: %(lu_udid)s)"
msgstr "A LU (unidade lógica) auxiliar %(lu_name)s não foi localizada.  (UDID: %(lu_udid)s)"

#: pypowervm/tasks/storage.py:870
msgid "Developer error: Either tier or lufeed is required."
msgstr "Erro do desenvolvedor: camada ou lufeed é necessária."

#: pypowervm/tasks/storage.py:875
msgid ""
"Developer error: The lufeed parameter must comprise LUEnt EntryWrappers."
msgstr ""
"Erro do desenvolvedor: o parâmetro lufeed deve incluir LUEnt EntryWrappers."

#: pypowervm/tasks/storage.py:882
#, python-format
msgid "Deleting LU %(lu_name)s (UDID: %(lu_udid)s)"
msgstr "Excluindo a unidade lógica %(lu_name)s (UDID: %(lu_udid)s)"

#: pypowervm/tasks/storage.py:887
#, python-format
msgid ""
"Ignoring HttpError for LU %(lu_name)s may have been deleted out of band.  "
"(UDID: %(lu_udid)s)"
msgstr ""
"Ignorando o HttpError para a LU (unidade lógica) %(lu_name)s que pode ter sido excluída fora da banda.  "
"(UDID: %(lu_udid)s)"

#: pypowervm/tasks/storage.py:940
#, python-format
msgid ""
"Removing %(num_maps)d orphan %(stg_type)s mappings from VIOS %(vios_name)s."
msgstr ""
"Removendo o %(num_maps)d mapeamentos %(stg_type)s órfãos do VIOS (Virtual I/O Server) %(vios_name)s."

#: pypowervm/tasks/storage.py:966
#, python-format
msgid "Removing %(num_maps)d port-less VFC mappings from VIOS %(vios_name)s."
msgstr "Removendo %(num_maps)d mapeamentos de VFC sem porta do VIOS %(vios_name)s."

#: pypowervm/tasks/storage.py:993
#, python-format
msgid ""
"Removing %(num_maps)d %(stg_type)s mappings associated with LPAR ID "
"%(lpar_id)d from VIOS %(vios_name)s."
msgstr ""
"Removendo mapeamentos %(num_maps)d %(stg_type)s associados ao ID da LPAR "
"%(lpar_id)d do VIOS %(vios_name)s."

#: pypowervm/tasks/storage.py:1060
#, python-format
msgid ""
"Not removing storage %(stg_name)s of type %(stg_type)s because it cannot be "
"determined whether it is still in use.  Manual verification and cleanup may "
"be necessary."
msgstr ""
"Não removendo o armazenamento %(stg_name)s do tipo %(stg_type)s porque não é possível "
"determinar se ele ainda está em uso.  Podem ser necessárias verificação e "
"limpeza manuais."

#: pypowervm/tasks/storage.py:1071
#, python-format
msgid ""
"Storage scrub ignoring storage element %(stg_name)s because it is of "
"unexpected type %(stg_type)s."
msgstr ""
"Limpeza de armazenamento ignorando elemento de armazenamento %(stg_name)s porque ele é do "
"tipo inesperado %(stg_type)s."

#: pypowervm/tasks/storage.py:1089
#, python-format
msgid ""
"Scrubbing the following %(vdcount)d Virtual Disks from VIOS %(vios)s: "
"%(vdlist)s"
msgstr ""
"Limpando os seguintes %(vdcount)d discos virtuais do VIOS%(vios)s: "
"%(vdlist)s"

#: pypowervm/tasks/storage.py:1097
#, python-format
msgid ""
"Scrubbing the following %(vocount)d Virtual Opticals from VIOS %(vios)s: "
"%(volist)s"
msgstr ""
"Limpando as seguintes %(vocount)d unidades óticas virtuais do VIOS%(vios)s: "
"%(volist)s"

#: pypowervm/tasks/storage.py:1168
#, python-format
msgid ""
"Skipping scrub of %(stg_type)s mappings from VIOS %(vios_name)s for the "
"following LPAR IDs because those LPARs exist: %(lpar_ids)s"
msgstr ""
"Ignorando a limpeza dos mapeamentos %(stg_type)s do VIOS %(vios_name)s para os "
"seguintes IDs da LPAR, pois essas LPARs existem: %(lpar_ids)s"

#: pypowervm/tasks/vfc_mapper.py:529
#, python-format
msgid ""
"Unable to find appropriate VIOS.  The payload provided was likely "
"insufficient.  The payload data is:\n"
" %s)"
msgstr ""
"Não é possível localizar VIOS apropriado.  A carga útil fornecido provavelmente era "
"insuficiente.  Os dados de carga útil são:\n"
" %s)"

#: pypowervm/tasks/vfc_mapper.py:558
#, python-format
msgid ""
"The matched VFC port map has no backing port set. Adding %(port)s to mapping "
"for client wwpns: %(wwpns)s"
msgstr ""
"O mapa da porta VFC correspondente não possui porta auxiliar configurada. Incluindo %(port)s para mapeamento do "
"do cliente wwpns: %(wwpns)s"

#: pypowervm/tasks/vopt.py:73
msgid ""
"An error occurred querying the virtual optical media repository.  Attempting "
"to re-establish connection with a virtual optical media repository"
msgstr ""
"Ocorreu um erro ao consultar o repositório de mídia ótica virtual.  Tentando "
"reestabelecer conexão com um repositório de mídia ótica virtual"

#: pypowervm/tasks/vterm.py:85
msgid "Unable to close vterm."
msgstr "Impossível fechar vterm."

#: pypowervm/tasks/vterm.py:137
#, python-format
msgid "Invalid output on vterm open.  Trying to reset the vterm.  Error was %s"
msgstr ""
"Saída inválida no vterm aberto. Tentando reconfigurar o vterm. O erro foi %s"

#: pypowervm/tasks/vterm.py:345
#, python-format
msgid "VNCSocket Listener Listening on ip=%(ip)s port=%(port)s"
msgstr "Listener VNCSocket atendendo no IP=%(ip)s, porta=%(port)s"

#: pypowervm/tasks/vterm.py:474
#, python-format
msgid "Error negotiating SSL for VNC Repeater: %s"
msgstr "Erro na negociação do SSL para o repetidor VNC: %s"

#: pypowervm/tasks/hdisk/_fc.py:197
#, python-format
msgid ""
"hdisk discovery failed; will scrub stale storage for LPAR IDs %s and retry."
msgstr ""
"A descoberta de hdisk falhou; limpe os IDs de LPAR (partição lógica) do armazenamento antigo %s e tente novamente."

#: pypowervm/tasks/hdisk/_fc.py:339
#, python-format
msgid "LUA Recovery Successful. Device Found: %s"
msgstr "Recuperação de LUA com sucesso. Dispositivo localizado: %s"

#: pypowervm/tasks/hdisk/_fc.py:343
#, python-format
msgid "ITL Error encountered: %s"
msgstr "Erro de ITL encontrado: %s"

#: pypowervm/tasks/hdisk/_fc.py:345
#, python-format
msgid "%s Device is currently in use."
msgstr "O dispositivo %s está atualmente em uso."

#: pypowervm/tasks/hdisk/_fc.py:347
#, python-format
msgid "%s Device discovered with unknown UDID."
msgstr "Dispositivo %s descoberto com UDID desconhecido."

#: pypowervm/tasks/hdisk/_fc.py:349
#, python-format
msgid "Failed to Discover the Device : %s"
msgstr "Falha ao descobrir o dispositivo: %s"

#: pypowervm/tasks/hdisk/_fc.py:419
#, python-format
msgid "CLIRunner Error: %s"
msgstr "Erro no CLIRunner: %s"

#: pypowervm/tasks/hdisk/_fc.py:451
msgid ""
"QUERY_INVENTORY LUARecovery Job succeeded, but result contained neither "
"OutputXML nor StdOut."
msgstr ""
"A tarefa LUARecovery de QUERY_INVENTORY foi bem-sucedida, mas o resultado não contém "
"OutputXML nem StdOut (saída padrão)."

#: pypowervm/tasks/hdisk/_fc.py:475
#, python-format
msgid ""
"QUERY_INVENTORY produced invalid chunk of XML (%(chunk)s).  Error: %(err)s"
msgstr ""
"QUERY_INVENTORY produziu um chunk inválido de XML (%(chunk)s). Erro: %(err)s"

#: pypowervm/tasks/hdisk/_fc.py:483
#, python-format
msgid ""
"Failed to find pg83 descriptor in XML output:\n"
"%s"
msgstr ""
"Falha ao localizar o descritor pg83 na saída XML:\n"
"%s"

#: pypowervm/tasks/hdisk/_iscsi.py:73
#, python-format
msgid "Invalid device output: %(dev)s"
msgstr "Saída de dispositivo inválida: %(dev)s"

#: pypowervm/tasks/hdisk/_iscsi.py:78
#, python-format
msgid "Expected IQN: %(IQN)s not found on iscsi target %(host_ip)s"
msgstr "IQN esperado: %(IQN)s não localizado no destino iscsi %(host_ip)s"

#: pypowervm/tasks/monitor/util.py:421
msgid ""
"Metric data is not available.  This may be due to the metrics being recently "
"initialized."
msgstr ""
"Os dados de métrica não estão disponíveis.  Isso pode ser devido às métricas terem sido recentemente "
"inicializadas."

#: pypowervm/tests/test_i18n.py:33
msgid "This is a test"
msgstr "Isso é um teste"

#: pypowervm/tests/test_i18n.py:36
msgid "This is a message for which a translation doesn't exist"
msgstr "Esta é uma mensagem para a qual uma tradução não existe"

#: pypowervm/utils/retry.py:203
#, python-format
msgid ""
"Attempt %(retry)d of total %(total)d for URI %(uri)s.  Error was a known "
"retry response code: %(resp_code)s"
msgstr ""
"Tentativa %(retry)d do total de %(total)d para URI %(uri)s.  O erro foi um "
"um código de resposta de nova tentativa conhecido: %(resp_code)s"

#: pypowervm/utils/retry.py:210
#, python-format
msgid ""
"Attempt %(retry)d of %(total)d failed.  Will retry. The exception was:\n"
" %(except)s."
msgstr ""
"A tentativa %(retry)d de %(total)d falhou.  Tentará novamente. A exceção foi:\n"
" %(except)s."

#: pypowervm/utils/transaction.py:348
msgid "Must supply either EntryWrapper or EntryWrapperGetter."
msgstr "Deve fornecer EntryWrapper ou EntryWrapperGetter."

#: pypowervm/utils/transaction.py:374
msgid "Must supply a valid Subtask."
msgstr "Deve fornecer um subtarefa válida."

#: pypowervm/utils/transaction.py:378
#, python-format
msgid "Duplicate 'provides' name %s."
msgstr "Duplicar 'fornece' nome %s."

#: pypowervm/utils/transaction.py:453
#, python-format
msgid "WrapperTask %s has no Subtasks; no-op execution."
msgstr "WrapperTask %s não tem subtarefas; execução sem operação."

#: pypowervm/utils/transaction.py:585
msgid "Must supply either a list of EntryWrappers or a FeedGetter."
msgstr "Deve fornecer uma lista de EntryWrappers ou FeedGetter."

#: pypowervm/utils/transaction.py:764
#, python-format
msgid "FeedTask %s has no Subtasks; no-op execution."
msgstr "FeedTask %s não tem subtarefas; execução sem operação."

#: pypowervm/utils/transaction.py:789
#, python-format
msgid ""
"FeedTask %s experienced multiple exceptions. They are logged individually "
"below."
msgstr ""
"FeedTask %s experimentou múltiplas exceções. Elas são registradas individualmente "
"abaixo."

#: pypowervm/utils/validation.py:161
#, python-format
msgid ""
"Insufficient available %(res_name)s on host for virtual machine "
"'%(instance_name)s' (%(requested)s requested, %(avail)s available)"
msgstr ""
"%(res_name)s disponíveis insuficientes no host para a máquina virtual "
"'%(instance_name)s' (%(requested)s solicitado, %(avail)s disponível)"

#: pypowervm/utils/validation.py:189
msgid "memory"
msgstr "memória"

#: pypowervm/utils/validation.py:210
#, python-format
msgid ""
"The virtual machine must be powered off before changing the minimum or "
"maximum memory. Power off virtual machine %s and try again."
msgstr ""
"A máquina virtual deverá ser desligada antes de mudar as unidades do processador mínima ou "
"memória máxima. Desligue a máquina virtual %s e tente novamente."

#: pypowervm/utils/validation.py:215
#, python-format
msgid ""
"The virtual machine must be powered off before changing the expansion "
"factor. Power off virtual machine %s and try again."
msgstr ""
"A máquina virtual deverá ser desligada antes de mudar o fator de "
"fator. Desligue a máquina virtual %s e tente novamente."

#: pypowervm/utils/validation.py:302
msgid "CPUs"
msgstr "CPUs"

#: pypowervm/utils/validation.py:318
msgid "processing units"
msgstr "unidades de processamento"

#: pypowervm/utils/validation.py:359
#, python-format
msgid ""
"The virtual machine must be powered off before changing the minimum or "
"maximum processors. Power off virtual machine %s and try again."
msgstr ""
"A máquina virtual deverá ser desligada antes de mudar as unidades do processador mínima ou "
"processadores máximos. Desligue a máquina virtual %s e tente novamente."

#: pypowervm/utils/validation.py:369
#, python-format
msgid ""
"The virtual machine must be powered off before changing the minimum or "
"maximum processor units. Power off virtual machine %s and try again."
msgstr ""
"A máquina virtual deverá ser desligada antes de mudar as unidades do processador mínima ou "
"máximo de unidades de processador. Desligue a máquina virtual %s e tente novamente."

#: pypowervm/utils/validation.py:385
#, python-format
msgid ""
"The virtual machine must be powered off before changing the processor "
"compatibility mode. Power off virtual machine %s and try again."
msgstr ""
"A máquina virtual deverá ser desligada antes de mudar o modo "
"modo de compatibilidade. Desligue a máquina virtual %s e tente novamente."

#: pypowervm/utils/validation.py:393
#, python-format
msgid ""
"The virtual machine must be powered off before changing the processing mode. "
"Power off virtual machine %s and try again."
msgstr ""
"A máquina virtual deve ser desligada antes de mudar o modo de processamento. "
"Desligue a máquina virtual %s e tente novamente."

#: pypowervm/utils/validation.py:422
#, python-format
msgid ""
"The desired processors (%(vcpus)d) cannot be above the maximum allowed "
"processors per partition (%(max_allowed)d) for virtual machine "
"'%(instance_name)s'."
msgstr ""
"Os processadores desejados (%(vcpus)d) não podem estar acima do máximo permitido "
"processadores por partição (%(max_allowed)d) para a máquina virtual "
"'%(instance_name)s'."

#: pypowervm/utils/validation.py:434
#, python-format
msgid ""
"The maximum processors (%(vcpus)d) cannot be above the maximum system "
"capacity processor limit (%(max_allowed)d) for virtual machine "
"'%(instance_name)s'."
msgstr ""
"O máximo de processadores (%(vcpus)d) não pode estar acima do "
"limite do processador de capacidade (%(max_allowed)d) para a máquina virtual "
"'%(instance_name)s'."

#: pypowervm/utils/validation.py:506
#, python-format
msgid ""
"The virtual machine must be powered off before changing the simplified "
"remote restart capability. Power off virtual machine %s and try again."
msgstr ""
"A máquina virtual deverá ser desligada antes de mudar o recurso "
"recurso de reinicialização remota. Desligue a máquina virtual %s e tente novamente."

#: pypowervm/wrappers/base_partition.py:424
msgid "Partition does not have an active RMC connection."
msgstr "A partição não tem uma conexão RMC ativa."

#: pypowervm/wrappers/base_partition.py:427
#, python-format
msgid "Partition does not have an active DLPAR capability for %s."
msgstr "A partição não tem uma capacidade DLPAR ativa para %s."

#: pypowervm/wrappers/base_partition.py:439
msgid "I/O"
msgstr "E/S"

#: pypowervm/wrappers/base_partition.py:449
msgid "Memory"
msgstr "Memória"

#: pypowervm/wrappers/base_partition.py:459
msgid "Processors"
msgstr "Processadores"

#: pypowervm/wrappers/base_partition.py:639
#, python-format
msgid "Invalid KeylockPos '%s'."
msgstr "KeylockPos '%s' inválido."

#: pypowervm/wrappers/base_partition.py:650
#, python-format
msgid "Invalid BootMode '%s'."
msgstr "BootMode '%s' inválido."

#: pypowervm/wrappers/base_partition.py:1436
msgid "IOSlot.adapter is deprecated!  Use IOSlot.io_adapter instead."
msgstr "O IOSlot.adapter foi descontinuado! Use o IOSlot.io_adapter."

#: pypowervm/wrappers/enterprise_pool.py:143
#, python-format
msgid ""
"Unable to determine master management console MTMS (machine type, model, "
"serial number) from %(identifier)s because no %(param)s was marked as the "
"master console for the pool."
msgstr ""
"Não é possível determinar o MTMS (tipo de máquina, modelo, número de série) do console de gerenciamento principal "
"a partir do %(identifier)s porque nenhum %(param)s foi marcado como o "
"console principal para o conjunto."

#: pypowervm/wrappers/entry_wrapper.py:251
msgid "Cannot set uuid."
msgstr "Não é possível configurar uuid."

#: pypowervm/wrappers/entry_wrapper.py:443
#, python-format
msgid "Cannot convert %(property_name)s='%(value)s' in object %(pvmobject)s"
msgstr "Não é possível converter %(property_name)s='%(value)s' no objeto %(pvmobject)s"

#: pypowervm/wrappers/entry_wrapper.py:586
msgid ""
"Refusing set href over multiple links.\n"
"Path: %{path}s\n"
"Number of links found: %{nlinks}d"
msgstr ""
"Recusando definição de href sobre vários links.\n"
"Caminho: %{path}s\n"
"Número de links encontrados: %{nlinks}d"

#: pypowervm/wrappers/entry_wrapper.py:635
msgid "Refusing to construct and wrap an Element without a tag."
msgstr "Recusando-se a construir e agrupar um Elemento sem uma identificação."

#: pypowervm/wrappers/entry_wrapper.py:760
msgid "Response is missing 'entry' property."
msgstr "A resposta está sem a propriedade 'entrada'."

#: pypowervm/wrappers/entry_wrapper.py:774
#, python-format
msgid "Must supply a Response or Entry to wrap.  Got %s"
msgstr "Deve fornecer um Resposta ou Entrada para agrupar.  Obteve %s"

#: pypowervm/wrappers/entry_wrapper.py:861
msgid ""
"Developer error: specify 'parent' or ('parent_type' and 'parent_uuid') to "
"retrieve a CHILD object."
msgstr ""
"Erro do desenvolvedor: especifique 'parent' ou ('parent_type' e 'parent_uuid') para "
"recuperar um objeto CHILD."

#: pypowervm/wrappers/entry_wrapper.py:866
msgid "Specify either 'uuid' or 'root_id' when requesting a ROOT object."
msgstr "Especifique 'uuid' ou 'root_id' ao solicitar um objeto ROOT."

#: pypowervm/wrappers/entry_wrapper.py:879
msgid ""
"Both parent_type and parent_uuid are required when retrieving a CHILD feed "
"or entry."
msgstr ""
"Tanto parent_type como parent_uuid são necessários ao recuperar um feed ou entrada "
"CHILD."

#: pypowervm/wrappers/entry_wrapper.py:882
msgid "Specify the parent's UUID via the parent_uuid parameter."
msgstr "Especifique o UUID do pai por meio do parâmetro parent_uuid."

#: pypowervm/wrappers/entry_wrapper.py:886
msgid "Specify either 'uuid' or 'child_id' when requesting a CHILD object."
msgstr "Especifique 'uuid' ou 'child_id' ao solicitar um objeto CHILD."

#: pypowervm/wrappers/entry_wrapper.py:1001
msgid "Parent UUID specified without parent type."
msgstr "UUID pai especificado sem tipo pai."

#: pypowervm/wrappers/entry_wrapper.py:1004
msgid "The search() method requires exactly one key=value argument."
msgstr "O método de pesquisa () requer exatamente um argumento de chave=valor."

#: pypowervm/wrappers/entry_wrapper.py:1035
#, python-format
msgid "Wrapper class %(class)s does not support search key '%(key)s'."
msgstr "A classe do wrapper %(class)s não suporta a chave de procura '%(key)s'."

#: pypowervm/wrappers/entry_wrapper.py:1135
msgid ""
"The 'xag' parameter to EntryWrapper.update is deprecated!  At best, using it "
"will result in a no-op.  At worst, it will give you incurable etag mismatch "
"errors."
msgstr ""
"O parâmetro 'xag' para EntryWrapper.update foi descontinuado!  Na melhor das hipóteses, usá-lo "
"resultará em um no-op (não operacional).  Na pior das hipóteses, serão fornecidos erros irrecuperáveis de incompatibilidade "
"de etag."

#: pypowervm/wrappers/entry_wrapper.py:1403
msgid "No such child element."
msgstr "Não existe esse elemento-filho."

#: pypowervm/wrappers/entry_wrapper.py:1464
msgid "Cannot set UUID on Wrapper with no Metadata."
msgstr "Não é possível configurar o UUID no Wrapper sem Metadados."

#: pypowervm/wrappers/entry_wrapper.py:1469
#, python-format
msgid "uuid value not valid: %s"
msgstr "valor de uuid inválido: %s"

#: pypowervm/wrappers/entry_wrapper.py:1524
msgid "Must specify a Wrapper subclass."
msgstr "Deve-se especificar uma subclasse de Wrapper."

#: pypowervm/wrappers/entry_wrapper.py:1533
msgid "Must specify both parent class and parent UUID, or neither."
msgstr "Deve-se especificar a classe-pai e o UUID pai ou nenhum."

#: pypowervm/wrappers/job.py:276
#, python-format
msgid "Job %(job_id)s monitoring for %(time)i seconds."
msgstr "Tarefa %(job_id)s monitorando por %(time)i segundos."

#: pypowervm/wrappers/job.py:327
#, python-format
msgid ""
"Issuing cancel request for job %(job_id)s. Will poll the job indefinitely "
"for termination."
msgstr ""
"Emitindo solicitação de cancelamento para a tarefa %(job_id)s. Pesquisará a tarefa indefinidamente "
"para finalização."

#: pypowervm/wrappers/job.py:343
#, python-format
msgid "Job %s not deleted. Job is in running state."
msgstr "Tarefa %s não excluída. Tarefa em estado de execução."

#: pypowervm/wrappers/logical_partition.py:169
msgid "LPAR is not in an active state."
msgstr "LPAR não está em um estado ativo."

#: pypowervm/wrappers/logical_partition.py:179
msgid "Target system does not have the IBM i LPAR Mobility Capability."
msgstr "O sistema de destino não tem a capacidade de mobilidade da LPAR do IBM i."

#: pypowervm/wrappers/logical_partition.py:183
msgid "IBM i LPAR does not have restricted I/O."
msgstr "IBM i LPAR não tem E/S restrita."

#: pypowervm/wrappers/logical_partition.py:187
msgid "Source system does not have the IBM i LPAR Mobility Capability."
msgstr "Sistema de origem não tem Capacidade de Mobilidade do IBM i LPAR."

#: pypowervm/wrappers/logical_partition.py:191
msgid "LPAR does not have an active RMC connection."
msgstr "LPAR não tem uma conexão RMC ativa."

#: pypowervm/wrappers/logical_partition.py:194
msgid "LPAR is the management partition"
msgstr "LPAR é a partição de gerenciamento"

#: pypowervm/wrappers/logical_partition.py:198
msgid "LPAR is not available for LPM due to missing DLPAR capabilities."
msgstr "LPAR não está disponível para LPM devido a recursos DLPAR ausente."

#: pypowervm/wrappers/logical_partition.py:215
#: pypowervm/wrappers/logical_partition.py:224
#: pypowervm/wrappers/logical_partition.py:232
msgid ""
"This is not the property you are looking for.  Use srr_enabled in a NovaLink "
"environment."
msgstr ""
"Esta não é a propriedade que você está procurando.  Use srr_enabled em um ambiente NovaLink "
"."

#: pypowervm/wrappers/logical_partition.py:268
#, python-format
msgid "Invalid IPLSrc '%s'."
msgstr "IPLSrc '%s' inválido."

#: pypowervm/wrappers/managed_system.py:428
msgid "This property is deprecated!. Use pci_subsys_dev_id instead."
msgstr "Esta propriedade está descontinuada! Use pci_subsys_dev_id no lugar."

#: pypowervm/wrappers/managed_system.py:440
msgid "This property is deprecated!. Use pci_rev_id instead."
msgstr "Esta propriedade está descontinuada! Use pci_rev_id no lugar."

#: pypowervm/wrappers/managed_system.py:456
msgid "This property is deprecated!. Use pci_subsys_vendor_id instead."
msgstr "Esta propriedade está descontinuada! Use pci_subsys_vendor_id no lugar."

#: pypowervm/wrappers/managed_system.py:468
msgid "This property is deprecated!. Use drc_index instead."
msgstr "Esta propriedade está descontinuada! Use drc_index no lugar."

#: pypowervm/wrappers/managed_system.py:480
msgid "This property is deprecated!. Use drc_name instead."
msgstr "Esta propriedade está descontinuada! Use drc_name no lugar."

#: pypowervm/wrappers/storage.py:651
#, python-format
msgid ""
"PV had encoded pg83 descriptor \"%(pg83_raw)s\", but it failed to decode "
"(%(type_error)s)."
msgstr ""
"PV codificou o descritor pg83 \"%(pg83_raw)s\", mas falhou ao decodificar "
"(%(type_error)s)."

#: pypowervm/wrappers/virtual_io_server.py:163
msgid ""
"The 'xags' property of the VIOS EntryWrapper class is deprecated!  Please "
"use values from pypowervm.const.XAG instead."
msgstr ""
"A propriedade 'xags' da classe EntryWrapper do VIOS foi descontinuada! "
"use os valores do pypowervm.const.XAG."

#: pypowervm/wrappers/virtual_io_server.py:400
msgid "Partition of VIOS type is not LPM capable"
msgstr "A partição do tipo VIOS não é compatível com LPM"

#: pypowervm/wrappers/virtual_io_server.py:655
msgid "Can't specify target device LUA without a backing storage device!"
msgstr "Não é possível especificar o dispositivo LUA de destino sem um dispositivo de armazenamento auxiliar."

# ENGL1SH_VERS10N 13712_53 DO NOT REMOVE OR CHANGE THIS LINE
# T9N_SRC_ID 23
# T9N_SH1P_STR1NG PV133AAP001 2
