# Translations template for pypowervm.
# Copyright (C) 2016 IBM Corp.
# This file is distributed under the same license as the pypowervm project.
# Automatically generated, 2016.
#
msgid ""
msgstr ""
"Project-Id-Version: pypowervm 1.0.1.dev127\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2016-04-14 02:54-0400\n"
"PO-Revision-Date: 2016-04-14 02:54-0400\n"
"Last-Translator: Automatically generated\n"
"Language-Team: none\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.3.2\n"

#: pypowervm/adapter.py:126
#, python-format
msgid "Invalid protocol \"%s\""
msgstr "Protocolo inválido \"%s\""

#: pypowervm/adapter.py:132
msgid "Unencrypted communication with PowerVM! Revert configuration to https."
msgstr "Comunicação não criptografada com o PowerVM! Reverta a configuração para HTTPS."

#: pypowervm/adapter.py:146
msgid "Calculating default audit memento failed, using 'default'."
msgstr "Falha ao calcular o memento de auditoria padrão, usando 'padrão'."

#: pypowervm/adapter.py:181
msgid "Local authentication not supported on HMC."
msgstr "Autenticação local não suportada no HMC."

#: pypowervm/adapter.py:200
#, python-format
msgid "Setting up event listener for %s"
msgstr "Configurando listener de eventos para %s"

#: pypowervm/adapter.py:239
#, python-format
msgid "Unexpected filehandle on %s request"
msgstr "Manipulação de arquivos inesperada na solicitação %s"

#: pypowervm/adapter.py:292
#, python-format
msgid "Unexpected error for %(meth)s %(url)s"
msgstr "Erro inesperado para %(meth)s %(url)s"

#: pypowervm/adapter.py:294
#, python-format
msgid "Unexpected error: %(class)s for %(method)s %(url)s: %(excp)s"
msgstr "Erro inesperado: %(class)s para %(method)s %(url)s: %(excp)s"

#: pypowervm/adapter.py:332
msgid ""
"Re-login has been deemed unsafe. This Session instance should no longer "
"be used."
msgstr ""
"O novo login foi considerado não seguro. Esta instância de sessão não deve mais "
"ser usada."

#: pypowervm/adapter.py:342
#, python-format
msgid "Attempting re-login %s"
msgstr "Tentando novo login %s"

#: pypowervm/adapter.py:353
#, python-format
msgid ""
"Re-login 401, response body:\n"
"%s"
msgstr ""
"Novo login 401, corpo de resposta:\n"
"%s"

#: pypowervm/adapter.py:358
#, python-format
msgid ""
"Re-login failed, resp body:\n"
"%s"
msgstr ""
"Falha no novo login, corpo de resposta:\n"
"%s"

#: pypowervm/adapter.py:362
#, python-format
msgid ""
"Re-login failed:\n"
"%s"
msgstr ""
"Novo login com falha:\n"
"%s"

#: pypowervm/adapter.py:381
#, python-format
msgid ""
"Re-attempt failed with another 401, response body:\n"
"%s"
msgstr ""
"Falha na nova tentativa com outro 401, corpo de resposta:\n"
"%s"

#: pypowervm/adapter.py:384
#, python-format
msgid "suspicious HTTP 401 response for %(method)s %(path)s: token is brand new"
msgstr "resposta HTTP 401 suspeita para %(method)s %(path)s: o token é completamente novo"

#: pypowervm/adapter.py:416
#, python-format
msgid "Session logging on %s"
msgstr "Criação de log de sessão ativada %s"

#: pypowervm/adapter.py:478
msgid "Failed to parse a session token from the PowerVM response."
msgstr "Falha ao analisar um token de sessão a partir da resposta do PowerVM."

#: pypowervm/adapter.py:480 pypowervm/adapter.py:496
#, python-format
msgid " Body= %s"
msgstr " Corpo = %s"

#: pypowervm/adapter.py:494
msgid "Failed to parse a session file path from the PowerVM response."
msgstr "Falha ao analisar um caminho de arquivo de sessão a partir da resposta do PowerVM."

#: pypowervm/adapter.py:508
#, python-format
msgid "Token file %s didn't contain a readable session token."
msgstr "O arquivo de token %s não continha um token de sessão legível."

#: pypowervm/adapter.py:518
#, python-format
msgid "Session logging off %s"
msgstr "Criação de log de sessão desativada %s"

#: pypowervm/adapter.py:523
msgid "Problem logging off.  Ignoring."
msgstr "Problema ao efetuar logoff. Ignorando."

#: pypowervm/adapter.py:561
msgid "Failed to register for events.  Events will not be used."
msgstr "Falha ao registrar-se para eventos. Os eventos não serão usados."

#: pypowervm/adapter.py:642
msgid "job must be a JobRequest element"
msgstr "a tarefa deve ser um elemento JobRequest"

#: pypowervm/adapter.py:646
msgid "JobRequest is missing OperationName"
msgstr "OperationName está ausente de JobRequest"

#: pypowervm/adapter.py:660 pypowervm/adapter.py:866 pypowervm/adapter.py:926
#: pypowervm/adapter.py:1022
#, python-format
msgid "path=%s is not a PowerVM API reference"
msgstr "path=%s não é uma referência da API do PowerVM"

#: pypowervm/adapter.py:1037 pypowervm/adapter.py:1054
msgid "Invalid file descriptor"
msgstr "Descritor de arquivo inválido"

#: pypowervm/adapter.py:1179 pypowervm/adapter.py:1207
#: pypowervm/adapter.py:1222
msgid "Expected root_id"
msgstr "root_id esperado"

#: pypowervm/adapter.py:1181
msgid "Expected child_type"
msgstr "child_type esperado"

#: pypowervm/adapter.py:1185 pypowervm/adapter.py:1211
#: pypowervm/adapter.py:1216
#, python-format
msgid "Unexpected suffix_type=%s"
msgstr "suffix_type=%s inesperado"

#: pypowervm/adapter.py:1188 pypowervm/adapter.py:1219
msgid "Expected suffix_parm"
msgstr "suffix_parm esperado"

#: pypowervm/adapter.py:1190 pypowervm/adapter.py:1209
#: pypowervm/adapter.py:1224
msgid "Expected child_id"
msgstr "child_id esperado"

#: pypowervm/adapter.py:1193 pypowervm/adapter.py:1202
msgid "Unexpected child_id"
msgstr "child_id inesperado"

#: pypowervm/adapter.py:1195 pypowervm/adapter.py:1204
msgid "Unexpected root_id"
msgstr "root_id inesperado"

#: pypowervm/adapter.py:1226
#, python-format
msgid "Unexpected req_method=%s"
msgstr "req_method=%s inesperado"

#: pypowervm/adapter.py:1345
#, python-format
msgid "Error parsing XML response from PowerVM: %s"
msgstr "Erro ao analisar a resposta XML do PowerVM: %s"

#: pypowervm/adapter.py:1358
msgid "Response is not an Atom feed/entry"
msgstr "A resposta não é uma entrada ou um feed Atom"

#: pypowervm/adapter.py:1369
msgid "Unexpected HTTP 204 for request"
msgstr "HTTP 204 inesperado para solicitação"

#: pypowervm/adapter.py:1377
msgid "Unexpectedly empty response body"
msgstr "Corpo de resposta vazio inesperado"

#: pypowervm/adapter.py:1380
#, python-format
msgid ""
"%(err_reason)s:\n"
"request headers: %(reqheaders)s\n"
"\n"
"request body: %(reqbody)s\n"
"\n"
"response headers: %(respheaders)s\n"
"\n"
"response body: %(respbody)s"
msgstr ""
"%(err_reason)s: \n"
"cabeçalhos de solicitação: %(reqheaders)s\n"
"\n"
"corpo da solicitação: %(reqbody)s\n"
"\n"
"cabeçalhos de resposta: %(respheaders)s\n"
"\n"
"corpo de resposta: %(respbody)s"

#: pypowervm/adapter.py:1388
#, python-format
msgid "Atom error for %(method)s %(path)s: %(reason)s"
msgstr "Erro do Atom para %(method)s %(path)s: %(reason)s"

#: pypowervm/adapter.py:1430
msgid "Session must not be None"
msgstr "A sessão não deve ser Nenhuma"

#: pypowervm/adapter.py:1432
msgid "An event listener is already active on the session."
msgstr "Um listener de eventos já está ativo na sessão."

#: pypowervm/adapter.py:1448
#, python-format
msgid "Failed to initialize event feed listener: %s"
msgstr "Falha ao inicializar o listener de feed de eventos: %s"

#: pypowervm/adapter.py:1452
#, python-format
msgid "Application id \"%s\" is not unique"
msgstr "O ID do aplicativo \"%s\" não é exclusivo"

#: pypowervm/adapter.py:1461
msgid "Shutting down"
msgstr "Encerrando"

#: pypowervm/adapter.py:1464
msgid "This handler is already subscribed"
msgstr "Este manipulador já está inscrito"

#: pypowervm/adapter.py:1472
msgid "Handler must be an EventHandler"
msgstr "O manipulador deve ser EventHandler"

#: pypowervm/adapter.py:1475
msgid "This handler not found in subscriber list"
msgstr "Este manipulador não foi localizado na lista de assinantes"

#: pypowervm/adapter.py:1483
#, python-format
msgid "Shutting down EventListener for %s"
msgstr "Encerrando o EventListener para %s"

#: pypowervm/adapter.py:1487
#, python-format
msgid "EventListener shutdown complete for %s"
msgstr "Encerramento de EventListener concluído para %s"

#: pypowervm/adapter.py:1507
msgid "Error while getting PowerVM events"
msgstr "Erro ao obter eventos do PowerVM"

#: pypowervm/adapter.py:1544
#, python-format
msgid "Unexpected EventType=%s"
msgstr "EventType=%s inesperado"

#: pypowervm/adapter.py:1561
msgid "Error while processing PowerVM events"
msgstr "Erro ao processar eventos do PowerVM"

#: pypowervm/exceptions.py:117
#, python-format
msgid ""
"Unable to derive the appropriate physical FC port for WWPN %(wwpn)s.  The"
" VIOS Extended Attribute Groups may have been insufficient.  The VIOS URI"
" for the query was %(vio_uri)s."
msgstr ""
"Não é possível derivar uma porta FC física adequada para o WWPN %(wwpn)s. Os"
" Grupos de Atributos Estendidos VIOS podem ter sido insuficientes. O URI do VIOS"
" para a consulta era %(vio_uri)s."

#: pypowervm/exceptions.py:123
#, python-format
msgid "Element not found: %(element_type)s %(element)s"
msgstr "Elemento não localizado: %(element_type)s %(element)s"

#: pypowervm/exceptions.py:127
#, python-format
msgid "LPAR not found: %(lpar_name)s"
msgstr "LPAR não localizado: %(lpar_name)s"

#: pypowervm/exceptions.py:131
#, python-format
msgid "The '%(operation_name)s' operation failed. %(error)s"
msgstr "A operação '%(operation_name)s' falhou. %(error)s"

#: pypowervm/exceptions.py:135
#, python-format
msgid ""
"The '%(operation_name)s' operation failed. Failed to complete the task in"
" %(seconds)d seconds."
msgstr ""
"A operação '%(operation_name)s' falhou. Falha ao concluir a tarefa em"
" %(seconds)d segundos."

#: pypowervm/exceptions.py:140
#, python-format
msgid "Failed to power off Virtual Machine %(lpar_nm)s: %(reason)s"
msgstr "Falha ao desligar Máquina Virtual %(lpar_nm)s: %(reason)s"

#: pypowervm/exceptions.py:144
#, python-format
msgid "Failed to power on Virtual Machine %(lpar_nm)s: %(reason)s"
msgstr "Falha ao ligar a Máquina Virtual %(lpar_nm)s: %(reason)s"

#: pypowervm/exceptions.py:148
#, python-format
msgid ""
"Unable to remove VLAN %(vlan_id)d as it is the Primary VLAN Identifier on"
" a different Network Bridge."
msgstr ""
"Não é possível remover %(vlan_id)d, pois ele é o Identificador Primário da VLAN em"
" uma ponte de rede diferente."

#: pypowervm/exceptions.py:153
#, python-format
msgid ""
"Unable to provision VLAN %(vlan_id)d.  It appears to be contained on "
"device '%(dev_name)s' on Virtual I/O Server %(vios)s.  That device is not"
" connected to any Network Bridge (Shared Ethernet Adapter).  Please "
"manually remove the device or add it to the Network Bridge before "
"continuing."
msgstr ""
"Não é possível provisionar o VLAN %(vlan_id)d. Ele parece estar contido em "
"um dispositivo '%(dev_name)s' no Virtual I/O Server %(vios)s.  Este dispositivo não é"
" conectado a qualquer Ponte de rede (adaptador Ethernet compartilhado). "
"remova manualmente o dispositivo ou inclua-o na Ponte de rede antes "
"de continuar."

#: pypowervm/exceptions.py:162
#, python-format
msgid ""
"A Logical Unit with name %(lu_name)s already exists on Shared Storage "
"Pool %(ssp_name)s."
msgstr ""
"Uma Unidade Lógica com o nome %(lu_name)s já existe no conjunto de armazenamento compartilhado "
"%(ssp_name)s."

#: pypowervm/exceptions.py:167
msgid ""
"Unable to find a physical port to map a virtual Fibre Channel port to.  "
"This is due to either a Virtual I/O Server being unavailable, or improper"
" port specification for the physical Fibre Channel ports."
msgstr ""
"Não é possível localizar uma porta física para a qual mapear uma porta Fibre Channel virtual.  "
"Isto ocorre devido a um Virtual I/O Server estar indisponível ou a uma"
" especificação das portas incorreta para as portas do fibre channel físicas."

#: pypowervm/exceptions.py:174
msgid ""
"Unable to start the console to the Virtual Machine.  The pypowervm API is"
" running in a non-local mode.  The console can only be deployed when "
"pypowervm is co-located with the PowerVM API."
msgstr ""
"Não é possível iniciar o console para a Máquina virtual. A API pypowervm está"
" em execução em um modo não local. O console somente poderá ser implementado quando "
"pypowervm estiver colocalizado com a API do PowerVM."

#: pypowervm/exceptions.py:181
#, python-format
msgid "WrapperTask %(name)s has no subtasks!"
msgstr "WrapperTask %(name)s não tem subtarefas!"

#: pypowervm/exceptions.py:185
msgid "FeedTask can't have an empty feed."
msgstr "FeedTask não pode ter um feed vazio."

#: pypowervm/exceptions.py:189
#, python-format
msgid "OS denied access to file %(access_file)s."
msgstr "O OS (sistema operacional) negou acesso ao arquivo %(access_file)s."

#: pypowervm/exceptions.py:193
#, python-format
msgid ""
"OS encountered an I/O error attempting to read file %(access_file)s: "
"%(error)s"
msgstr ""
"O sistema operacional encontrou um erro de E/S ao tentar ler o arquivo %(access_file)s: "
"%(error)s"

#: pypowervm/exceptions.py:198
#, python-format
msgid "The migration task failed. %(error)s"
msgstr "A tarefa de migração falhou. %(error)s"

#: pypowervm/exceptions.py:202
#, python-format
msgid "No load source found for VM %(vm_name)s"
msgstr "Nenhuma origem de carregamento foi localizada para a VM %(vm_name)s"

#: pypowervm/exceptions.py:206
#, python-format
msgid ""
"Unable to derive the pg83 encoding for hdisk %(dev_name)s.  The "
"parent_entry attribute is not set.  This may be due to using a PV "
"obtained through an unsupported property chain.  The PV must be accessed "
"via VIOS.phys_vols, VG.phys_vols, or "
"VIOS.scsi_mappings[n].backing_storage."
msgstr ""
"Não é possível derivar a codificação pg83 para o hdisk %(dev_name)s. O "
"atributo parent_entry não está configurado. O motivo pode ser o uso de uma PV (entrada-pai) "
"obtida por meio de uma cadeia de propriedade não suportada. A PV deve ser acessada "
"por meio de VIOS.phys_vols, VG.phys_vols ou "
"VIOS.scsi_mappings[n].backing_storage."

#: pypowervm/exceptions.py:214
#, python-format
msgid ""
"Found device %(devname)s %(count)d times; expected to find it at most "
"once."
msgstr ""
"Localizado dispositivo %(devname)s %(count)d vezes. Era esperado localizá-lo no máximo "
"uma vez."

#: pypowervm/exceptions.py:231
#, python-format
msgid "Expected to find exactly one management partition; found %(count)d."
msgstr "Esperava localizar exatamente uma partição de gerenciamento; localizada %(count)d."

#: pypowervm/exceptions.py:237
#, python-format
msgid ""
"Expected to find exactly one partition with ID %(lpar_id)d; found "
"%(count)d."
msgstr ""
"Era esperado localizar exatamente uma partição com o ID %(lpar_id)d. Localizou-se "
"%(count)d."

#: pypowervm/exceptions.py:243
#, python-format
msgid "Couldn't find the default Tier on Shared Storage Pool %(ssp_name)s"
msgstr "Não foi possível localizar a Camada no conjunto de armazenamento compartilhado padrão %(ssp_name)s"

#: pypowervm/util.py:122
#, python-format
msgid ""
"Proposed extended attribute group '%(arg_xag)s' doesn't match existing "
"extended attribute group '%(path_xag)s'"
msgstr ""
"O grupo de atributos estendido proposto '%(arg_xag)s' não corresponde ao "
"grupo de atributos estendidos existente '%(path_xag)s'"

#: pypowervm/util.py:258
msgid "Certificate has expired."
msgstr "O certificado expirou."

#: pypowervm/util.py:391
#, python-format
msgid "Prefix and suffix together may not be more than %d characters."
msgstr "Prefixo e sufixo juntos não pode ter mais de %d caracteres."

#: pypowervm/util.py:396
msgid "Total length must be at least 1 character."
msgstr "O comprimento total deve ser de pelo menos 1 caractere."

#: pypowervm/util.py:419
msgid "The name parameter must be at least one character long."
msgstr "O parâmetro de nome deve ter pelo menos um caractere de comprimento."

#: pypowervm/util.py:422
#, python-format
msgid "The name parameter must not exceed %d characters when trunk_ok is False."
msgstr "O parâmetro de nome não deve exceder %d caracteres quando o parâmetro trunk_ok for False."

#: pypowervm/util.py:520
msgid "Developer error: partial parent specification."
msgstr "Erro do desenvolvedor: especificação-pai parcial."

#: pypowervm/util.py:525
msgid ""
"Developer error: parent_type must be either a string schema type or a "
"Wrapper subclass."
msgstr ""
"Erro do desenvolvedor: parent_type deve ser um tipo de esquema de sequência ou uma "
"subclasse de Wrapper."

#: pypowervm/helpers/log_helper.py:83
#, python-format
msgid "REQUEST: %s"
msgstr "SOLICITAÇÃO: %s"

#: pypowervm/helpers/log_helper.py:103
#, python-format
msgid "RESPONSE: %s"
msgstr "RESPOSTA: %s"

#: pypowervm/tasks/cluster_ssp.py:106
#, python-format
msgid "Waiting for in-progress upload(s) to complete.  Marker LU(s): %s"
msgstr "Esperando a conclusão de upload(s) em andamento. LU(s) (unidade lógica) marcadora(s): %s"

#: pypowervm/tasks/cluster_ssp.py:135
msgid "Abdicating in favor of in-progress upload."
msgstr "Abdicando em favor do upload em andamento."

#: pypowervm/tasks/cluster_ssp.py:145
#, python-format
msgid "Abdicating upload in favor of marker %s."
msgstr "Abdicando do upload em favor do marcador %s."

#: pypowervm/tasks/cluster_ssp.py:198
#, python-format
msgid "Using already-uploaded image LU %s."
msgstr "Usando LU da imagem já transferida por upload %s."

#: pypowervm/tasks/cluster_ssp.py:208
#, python-format
msgid "Creating marker LU %s"
msgstr "Criando LU marcadora %s"

#: pypowervm/tasks/cluster_ssp.py:224
#, python-format
msgid "Uploading to image LU %(lu)s (marker %(mkr)s)."
msgstr "Fazendo upload para a LU da imagem %(lu)s (marcadora %(mkr)s)."

#: pypowervm/tasks/cluster_ssp.py:235
#, python-format
msgid "Removing failed LU %s."
msgstr "Removendo LU (unidade lógica) com falha %s."

#: pypowervm/tasks/cna.py:117
#, python-format
msgid "Unable to find the Virtual Switch %s on the system."
msgstr "Impossível localizar o Comutador Virtual %s no sistema."

#: pypowervm/tasks/cna.py:144
#, python-format
msgid "Unable to find a valid VLAN for Virtual Switch %s."
msgstr "Não é possível localizar uma VLAN válida para o comutador virtual %s."

#: pypowervm/tasks/hdisk.py:197
#, python-format
msgid ""
"hdisk discovery failed; will scrub stale storage for LPAR IDs %s and "
"retry."
msgstr ""
"descoberta de hdisk falhou; irá limpar o armazenamento antigo para IDs de LPAR %s e "
"tentar novamente."

#: pypowervm/tasks/hdisk.py:339
#, python-format
msgid "LUA Recovery Successful. Device Found: %s"
msgstr "Recuperação de LUA com sucesso. Dispositivo localizado: %s"

#: pypowervm/tasks/hdisk.py:343
#, python-format
msgid "ITL Error encountered: %s"
msgstr "Erro de ITL encontrado: %s"

#: pypowervm/tasks/hdisk.py:345
#, python-format
msgid "%s Device is currently in use."
msgstr "O dispositivo %s está atualmente em uso."

#: pypowervm/tasks/hdisk.py:347
#, python-format
msgid "%s Device discovered with unknown UDID."
msgstr "Dispositivo %s descoberto com UDID desconhecido."

#: pypowervm/tasks/hdisk.py:349
#, python-format
msgid "Failed to Discover the Device : %s"
msgstr "Falha ao descobrir o dispositivo: %s"

#: pypowervm/tasks/hdisk.py:419
#, python-format
msgid "CLIRunner Error: %s"
msgstr "Erro no CLIRunner: %s"

#: pypowervm/tasks/hdisk.py:451
msgid ""
"QUERY_INVENTORY LUARecovery Job succeeded, but result contained neither "
"OutputXML nor StdOut."
msgstr ""
"A tarefa LUARecovery de QUERY_INVENTORY foi bem-sucedida, mas o resultado não contém "
"OutputXML nem StdOut (saída padrão)."

#: pypowervm/tasks/hdisk.py:465
#, python-format
msgid "QUERY_INVENTORY produced invalid chunk of XML (%(chunk)s).  Error: %(err)s"
msgstr "QUERY_INVENTORY produziu um chunk inválido de XML (%(chunk)s). Erro: %(err)s"

#: pypowervm/tasks/hdisk.py:473
#, python-format
msgid ""
"Failed to find pg83 descriptor in XML output:\n"
"%s"
msgstr ""
"Falha ao localizar o descritor pg83 na saída XML:\n"
"%s"

#: pypowervm/tasks/memory.py:102
#, python-format
msgid ""
"Error obtaining host memory overhead for host with UUID '%(host)s': "
"%(error)s."
msgstr ""
"Erro ao obter a sobrecarga da memória do host para o host com UUID '%(host)s': "
"%(error)s."

#: pypowervm/tasks/power.py:216
#, python-format
msgid "Error: %s"
msgstr "Erro: %s"

#: pypowervm/tasks/power.py:263
#, python-format
msgid ""
"Error invalidating adapter cache for LPAR  %(lpar_name) with UUID "
"%(lpar_uuid)s: %(exc)s"
msgstr ""
"Erro ao invalidar o cache do adaptador para LPAR %(lpar_name) com UUID "
"%(lpar_uuid)s: %(exc)s"

#: pypowervm/tasks/scsi_mapper.py:38
msgid "Retrying modification of SCSI Mapping."
msgstr "Tentando a modificação do Mapeamento SCSI novamente."

#: pypowervm/tasks/scsi_mapper.py:89
#, python-format
msgid ""
"Found existing mapping of %(stg_type)s storage element %(stg_name)s from "
"Virtual I/O Server %(vios_name)s to client LPAR %(lpar_uuid)s."
msgstr ""
"Localizado o mapeamento existente do elemento de armazenamento %(stg_type)s %(stg_name)s do "
"Virtual I/O Server %(vios_name)s para clientes da LPAR %(lpar_uuid)s."

#: pypowervm/tasks/scsi_mapper.py:107
#, python-format
msgid ""
"Creating mapping of %(stg_type)s storage element %(stg_name)s from "
"Virtual I/O Server %(vios_name)s to client LPAR %(lpar_uuid)s."
msgstr ""
"Criando Mapeamento do elemento de armazenamento %(stg_type)s %(stg_name)s do "
"Virtual I/O Server %(vios_name)s para clientes da LPAR %(lpar_uuid)s."

#: pypowervm/tasks/scsi_mapper.py:402
msgid "Must not specify both match_func and stg_elem."
msgstr "Não deve especificar match_func e stg_elem."

#: pypowervm/tasks/storage.py:326
#, python-format
msgid "Unable to cleanup after file upload. File uuid: %s"
msgstr "Não será possível a limpeza após o upload de arquivo. uuid de arquivo: %s"

#: pypowervm/tasks/storage.py:445
#, python-format
msgid "Disk Logical Unit %(luname)s has no backing image LU.  (UDID: %(udid)s) "
msgstr "A unidade lógica de disco %(luname)s não possui unidade lógica de imagem auxiliar.  (UDID: %(udid)s) "

#: pypowervm/tasks/storage.py:489
msgid "Unable to locate new vDisk on file upload."
msgstr "Não é possível localizar novo vDisk no upload do arquivo."

#: pypowervm/tasks/storage.py:537
#, python-format
msgid ""
"Ignoring device because it lacks a UDID:\n"
"%s"
msgstr ""
"Ignorando dispositivo porque um UDID está ausente:\n"
"%s"

#: pypowervm/tasks/storage.py:543
#, python-format
msgid "Device %s not found in list."
msgstr "Dispositivo %s não localizado na lista."

#: pypowervm/tasks/storage.py:572
#, python-format
msgid "Deleting virtual disk %(vdisk)s from volume group %(vg)s"
msgstr "Excluindo disco virtual %(vdisk)s do grupo de volume %(vg)s"

#: pypowervm/tasks/storage.py:595
#, python-format
msgid "Deleting virtual optical device %(vopt)s from volume group %(vg)s"
msgstr "Excluindo dispositivo ótico virtual %(vopt)s do grupo de volume %(vg)s"

#: pypowervm/tasks/storage.py:648
#, python-format
msgid "Removing LU %(lu_name)s (UDID %(lu_udid)s)"
msgstr "Removendo unidade lógica %(lu_name)s (UDID %(lu_udid)s)"

#: pypowervm/tasks/storage.py:652
#, python-format
msgid ""
"LU %(lu_name)s was not found - it may have been deleted out of band.  "
"(UDID: %(lu_udid)s)"
msgstr ""
"A unidade lógica %(lu_name)s não foi localizada - ela pode ter sido excluída fora da banda.  "
"(UDID: %(lu_udid)s)"

#: pypowervm/tasks/storage.py:670
#, python-format
msgid ""
"Removing Image LU %(lu_name)s because it is no longer in use.  (UDID: "
"%(lu_udid)s)"
msgstr ""
"Removendo a unidade lógica da imagem %(lu_name)s porque ela não está mais em uso.  (UDID: "
"%(lu_udid)s)"

#: pypowervm/tasks/storage.py:675
#, python-format
msgid "Backing LU %(lu_name)s was not found.  (UDID: %(lu_udid)s)"
msgstr "A unidade lógica auxiliar %(lu_name)s não foi localizada.  (UDID: %(lu_udid)s)"

#: pypowervm/tasks/storage.py:701
msgid "Developer error: Either tier or lufeed is required."
msgstr "Erro do desenvolvedor: camada ou lufeed é necessária."

#: pypowervm/tasks/storage.py:706
msgid "Developer error: The lufeed parameter must comprise LUEnt EntryWrappers."
msgstr "Erro do desenvolvedor: o parâmetro lufeed deve incluir LUEnt EntryWrappers."

#: pypowervm/tasks/storage.py:713
#, python-format
msgid "Deleting LU %(lu_name)s (UDID: %(lu_udid)s)"
msgstr "Excluindo a unidade lógica %(lu_name)s (UDID: %(lu_udid)s)"

#: pypowervm/tasks/storage.py:718
#, python-format
msgid ""
"Ignoring HttpError for LU %(lu_name)s may have been deleted out of band."
"  (UDID: %(lu_udid)s)"
msgstr ""
"Ignorando HttpError para a unidade lógica %(lu_name)s pode ter sido excluído fora da banda."
"  (UDID: %(lu_udid)s)"

#: pypowervm/tasks/storage.py:771
#, python-format
msgid ""
"Removing %(num_maps)d orphan %(stg_type)s mappings from VIOS "
"%(vios_name)s."
msgstr ""
"Removendo %(num_maps)d mapeamentos %(stg_type)s órfãos do VIOS "
"%(vios_name)s."

#: pypowervm/tasks/storage.py:797
#, python-format
msgid "Removing %(num_maps)d port-less VFC mappings from VIOS %(vios_name)s."
msgstr "Removendo %(num_maps)d mapeamentos de VFC sem porta do VIOS %(vios_name)s."

#: pypowervm/tasks/storage.py:824
#, python-format
msgid ""
"Removing %(num_maps)d %(stg_type)s mappings associated with LPAR ID "
"%(lpar_id)d from VIOS %(vios_name)s."
msgstr ""
"Removendo mapeamentos %(num_maps)d %(stg_type)s associados ao ID da LPAR "
"%(lpar_id)d do VIOS %(vios_name)s."

#: pypowervm/tasks/storage.py:891
#, python-format
msgid ""
"Not removing storage %(stg_name)s of type %(stg_type)s because it cannot "
"be determined whether it is still in use.  Manual verification and "
"cleanup may be necessary."
msgstr ""
"Não removendo armazenamento %(stg_name)s do tipo %(stg_type)s porque não é possível "
"Determinar se ele ainda está em uso. Verificação e "
"limpeza manuais podem ser necessárias."

#: pypowervm/tasks/storage.py:902
#, python-format
msgid ""
"Storage scrub ignoring storage element %(stg_name)s because it is of "
"unexpected type %(stg_type)s."
msgstr ""
"Limpeza de armazenamento ignorando elemento de armazenamento %(stg_name)s porque ele é do "
"tipo inesperado %(stg_type)s."

#: pypowervm/tasks/storage.py:920
#, python-format
msgid ""
"Scrubbing the following %(vdcount)d Virtual Disks from VIOS %(vios)s: "
"%(vdlist)s"
msgstr ""
"Limpando os seguintes %(vdcount)d discos virtuais do VIOS%(vios)s: "
"%(vdlist)s"

#: pypowervm/tasks/storage.py:928
#, python-format
msgid ""
"Scrubbing the following %(vocount)d Virtual Opticals from VIOS %(vios)s: "
"%(volist)s"
msgstr ""
"Limpando as seguintes %(vocount)d unidades óticas virtuais do VIOS%(vios)s: "
"%(volist)s"

#: pypowervm/tasks/storage.py:991
#, python-format
msgid ""
"Skipping scrub of %(stg_type)s mappings from VIOS %(vios_name)s for the "
"following LPAR IDs because those LPARs exist: %(lpar_ids)s"
msgstr ""
"Ignorando a limpeza dos mapeamentos %(stg_type)s do VIOS %(vios_name)s para os "
"seguintes IDs da LPAR, pois essas LPARs existem: %(lpar_ids)s"

#: pypowervm/tasks/vfc_mapper.py:514
#, python-format
msgid ""
"Unable to find appropriate VIOS.  The payload provided was likely "
"insufficient.  The payload data is:\n"
" %s)"
msgstr ""
"Não é possível localizar o VIOS apropriado. A carga útil fornecida provavelmente era "
"insuficiente. Os dados de carga útil são:\n"
" %s)"

#: pypowervm/tasks/vterm.py:74
msgid "Unable to close vterm."
msgstr "Impossível fechar vterm."

#: pypowervm/tasks/vterm.py:266
#, python-format
msgid "VNCRepeater Server Listening on ip=%(ip)s port=%(port)s"
msgstr "Servidor VNCRepeater atendendo em ip=%(ip)s port=%(port)s"

#: pypowervm/tasks/monitor/util.py:421
msgid ""
"Metric data is not available.  This may be due to the metrics being "
"recently initialized."
msgstr ""
"Os dados da métrica não estão disponíveis. O motivo pode ser que as métricas foram "
"inicializadas recentemente."

#: pypowervm/tests/test_i18n.py:33
msgid "This is a test"
msgstr "Isso é um teste"

#: pypowervm/tests/test_i18n.py:36
msgid "This is a message for which a translation doesn't exist"
msgstr "Esta é uma mensagem para a qual uma tradução não existe"

#: pypowervm/utils/retry.py:152
#, python-format
msgid ""
"Attempt %(retry)d of total %(total)d for URI %(uri)s.  Error was a known "
"retry response code: %(resp_code)s"
msgstr ""
"Tentativa %(retry)d de total %(total)d para o URI %(uri)s. O erro era "
"um código de resposta de nova tentativa conhecido: %(resp_code)s"

#: pypowervm/utils/retry.py:159
#, python-format
msgid ""
"Attempt %(retry)d of %(total)d failed.  Will retry. The exception was:\n"
" %(except)s."
msgstr ""
"Tentativa %(retry)d de %(total)d falhou. Tentará novamente. A exceção foi:\n"
" %(except)s."

#: pypowervm/utils/transaction.py:348
msgid "Must supply either EntryWrapper or EntryWrapperGetter."
msgstr "Deve fornecer EntryWrapper ou EntryWrapperGetter."

#: pypowervm/utils/transaction.py:374
msgid "Must supply a valid Subtask."
msgstr "Deve fornecer um subtarefa válida."

#: pypowervm/utils/transaction.py:378
#, python-format
msgid "Duplicate 'provides' name %s."
msgstr "Duplicar 'fornece' nome %s."

#: pypowervm/utils/transaction.py:453
#, python-format
msgid "WrapperTask %s has no Subtasks; no-op execution."
msgstr "WrapperTask %s não tem subtarefas; execução sem operação."

#: pypowervm/utils/transaction.py:585
msgid "Must supply either a list of EntryWrappers or a FeedGetter."
msgstr "Deve fornecer uma lista de EntryWrappers ou FeedGetter."

#: pypowervm/utils/transaction.py:764
#, python-format
msgid "FeedTask %s has no Subtasks; no-op execution."
msgstr "FeedTask %s não tem subtarefas; execução sem operação."

#: pypowervm/utils/validation.py:161
#, python-format
msgid ""
"Insufficient available %(res_name)s on host for virtual machine "
"'%(instance_name)s' (%(requested)s requested, %(avail)s available)"
msgstr ""
"%(res_name)s disponíveis insuficientes no host para a máquina virtual "
"'%(instance_name)s' (%(requested)s solicitado, %(avail)s disponível)"

#: pypowervm/utils/validation.py:189
msgid "memory"
msgstr "memória"

#: pypowervm/utils/validation.py:210
#, python-format
msgid ""
"The virtual machine must be powered off before changing the minimum or "
"maximum memory. Power off virtual machine %s and try again."
msgstr ""
"A máquina virtual deverá ser desligada antes de mudar as unidades do processador mínima ou "
"máxima. Desligue a máquina virtual %s e tente novamente."

#: pypowervm/utils/validation.py:215
#, python-format
msgid ""
"The virtual machine must be powered off before changing the expansion "
"factor. Power off virtual machine %s and try again."
msgstr ""
"A máquina virtual deverá ser desligada antes de mudar o fator de "
"expansão. Desligue a máquina virtual %s e tente novamente."

#: pypowervm/utils/validation.py:302
msgid "CPUs"
msgstr "CPUs"

#: pypowervm/utils/validation.py:318
msgid "processing units"
msgstr "unidades de processamento"

#: pypowervm/utils/validation.py:359
#, python-format
msgid ""
"The virtual machine must be powered off before changing the minimum or "
"maximum processors. Power off virtual machine %s and try again."
msgstr ""
"A máquina virtual deverá ser desligada antes de mudar as unidades do processador mínima ou "
"máximos. Desligue a máquina virtual %s e tente novamente."

#: pypowervm/utils/validation.py:369
#, python-format
msgid ""
"The virtual machine must be powered off before changing the minimum or "
"maximum processor units. Power off virtual machine %s and try again."
msgstr ""
"A máquina virtual deverá ser desligada antes de mudar as unidades do processador mínima ou "
"máxima. Desligue a máquina virtual %s e tente novamente."

#: pypowervm/utils/validation.py:385
#, python-format
msgid ""
"The virtual machine must be powered off before changing the processor "
"compatibility mode. Power off virtual machine %s and try again."
msgstr ""
"A máquina virtual deverá ser desligada antes de mudar o modo "
"de compatibilidade do processador. Desligue a máquina virtual %s e tente novamente."

#: pypowervm/utils/validation.py:393
#, python-format
msgid ""
"The virtual machine must be powered off before changing the processing "
"mode. Power off virtual machine %s and try again."
msgstr ""
"A máquina virtual deverá ser desligada antes de mudar o modo "
"de processamento. Desligue a máquina virtual %s e tente novamente."

#: pypowervm/utils/validation.py:422
#, python-format
msgid ""
"The desired processors (%(vcpus)d) cannot be above the maximum allowed "
"processors per partition (%(max_allowed)d) for virtual machine "
"'%(instance_name)s'."
msgstr ""
"Os processadores desejados (%(vcpus)d) não podem estar acima do máximo permitido "
"processadores por partição (%(max_allowed)d) para a máquina virtual "
"'%(instance_name)s'."

#: pypowervm/utils/validation.py:434
#, python-format
msgid ""
"The maximum processors (%(vcpus)d) cannot be above the maximum system "
"capacity processor limit (%(max_allowed)d) for virtual machine "
"'%(instance_name)s'."
msgstr ""
"O máximo de processadores (%(vcpus)d) não pode estar acima do "
"limite do processador de capacidade (%(max_allowed)d) para a máquina virtual "
"'%(instance_name)s'."

#: pypowervm/utils/validation.py:506
#, python-format
msgid ""
"The virtual machine must be powered off before changing the simplified "
"remote restart capability. Power off virtual machine %s and try again."
msgstr ""
"A máquina virtual deverá ser desligada antes de mudar o recurso "
"de reinicialização remota simplificado. Desligue a máquina virtual %s e tente novamente."

#: pypowervm/wrappers/base_partition.py:526
#, python-format
msgid "Invalid KeylockPos '%s'."
msgstr "KeylockPos '%s' inválido."

#: pypowervm/wrappers/base_partition.py:537
#, python-format
msgid "Invalid BootMode '%s'."
msgstr "BootMode '%s' inválido."

#: pypowervm/wrappers/base_partition.py:1299
msgid "IOSlot.adapter is deprecated!  Use IOSlot.io_adapter instead."
msgstr "O IOSlot.adapter foi descontinuado! Use o IOSlot.io_adapter."

#: pypowervm/wrappers/enterprise_pool.py:143
#, python-format
msgid ""
"Unable to determine master management console MTMS (machine type, model, "
"serial number) from %(identifier)s because no %(param)s was marked as the"
" master console for the pool."
msgstr ""
"Não é possível determinar o MTMS (tipo de máquina, modelo, número de série) do console de gerenciamento principal "
"a partir de %(identifier)s porque nenhum %(param)s foi marcado como o"
" console principal para o conjunto."

#: pypowervm/wrappers/entry_wrapper.py:371
#, python-format
msgid "Cannot convert %(property_name)s='%(value)s' in object %(pvmobject)s"
msgstr "Não é possível converter %(property_name)s='%(value)s' no objeto %(pvmobject)s"

#: pypowervm/wrappers/entry_wrapper.py:496
msgid ""
"Refusing set href over multiple links.\n"
"Path: %{path}s\n"
"Number of links found: %{nlinks}d"
msgstr ""
"Recusando definição de href sobre vários links.\n"
"Caminho: %{path}s\n"
"Número de links localizados: %{nlinks}d"

#: pypowervm/wrappers/entry_wrapper.py:540
msgid "Refusing to construct and wrap an Element without a tag."
msgstr "Recusando-se a construir e agrupar um Elemento sem uma identificação."

#: pypowervm/wrappers/entry_wrapper.py:665
msgid "Response is missing 'entry' property."
msgstr "A resposta está sem a propriedade 'entrada'."

#: pypowervm/wrappers/entry_wrapper.py:679
#, python-format
msgid "Must supply a Response or Entry to wrap.  Got %s"
msgstr "Deve-se fornecer um Resposta ou Entrada para agrupar. Obtido %s"

#: pypowervm/wrappers/entry_wrapper.py:766
msgid ""
"Developer error: specify 'parent' or ('parent_type' and 'parent_uuid') to"
" retrieve a CHILD object."
msgstr ""
"Erro do desenvolvedor: especifique 'parent' ou ('parent_type' e 'parent_uuid') para"
" recuperar um objeto CHILD."

#: pypowervm/wrappers/entry_wrapper.py:771
msgid "Specify either 'uuid' or 'root_id' when requesting a ROOT object."
msgstr "Especifique 'uuid' ou 'root_id' ao solicitar um objeto ROOT."

#: pypowervm/wrappers/entry_wrapper.py:784
msgid ""
"Both parent_type and parent_uuid are required when retrieving a CHILD "
"feed or entry."
msgstr ""
"O parent_type e o parent_uuid são necessários ao recuperar um "
"feed ou entrada CHILD."

#: pypowervm/wrappers/entry_wrapper.py:787
msgid "Specify the parent's UUID via the parent_uuid parameter."
msgstr "Especifique o UUID do pai por meio do parâmetro parent_uuid."

#: pypowervm/wrappers/entry_wrapper.py:791
msgid "Specify either 'uuid' or 'child_id' when requesting a CHILD object."
msgstr "Especifique 'uuid' ou 'child_id' ao solicitar um objeto CHILD."

#: pypowervm/wrappers/entry_wrapper.py:885
msgid "Parent UUID specified without parent type."
msgstr "UUID pai especificado sem tipo pai."

#: pypowervm/wrappers/entry_wrapper.py:888
msgid "The search() method requires exactly one key=value argument."
msgstr "O método de pesquisa () requer exatamente um argumento de chave=valor."

#: pypowervm/wrappers/entry_wrapper.py:919
#, python-format
msgid "Wrapper class %(class)s does not support search key '%(key)s'."
msgstr "A classe do wrapper %(class)s não suporta a chave de procura '%(key)s'."

#: pypowervm/wrappers/entry_wrapper.py:1019
msgid ""
"The 'xag' parameter to EntryWrapper.update is deprecated!  At best, using"
" it will result in a no-op.  At worst, it will give you incurable etag "
"mismatch errors."
msgstr ""
"O parâmetro 'xag' para EntryWrapper.update foi descontinuado! Na melhor das hipóteses, seu uso"
" resultará em um no-op. Na pior, fornecerá erros de incompatibilidade de "
"etag irreparáveis."

#: pypowervm/wrappers/entry_wrapper.py:1081
msgid "Cannot set uuid."
msgstr "Não é possível configurar uuid."

#: pypowervm/wrappers/entry_wrapper.py:1282
msgid "No such child element."
msgstr "Não existe esse elemento-filho."

#: pypowervm/wrappers/entry_wrapper.py:1343
msgid "Cannot set UUID on Wrapper with no Metadata."
msgstr "Não é possível configurar o UUID no Wrapper sem Metadados."

#: pypowervm/wrappers/entry_wrapper.py:1348
#, python-format
msgid "uuid value not valid: %s"
msgstr "valor de uuid inválido: %s"

#: pypowervm/wrappers/entry_wrapper.py:1403
msgid "Must specify a Wrapper subclass."
msgstr "Deve-se especificar uma subclasse de Wrapper."

#: pypowervm/wrappers/entry_wrapper.py:1412
msgid "Must specify both parent class and parent UUID, or neither."
msgstr "Deve-se especificar a classe-pai e o UUID pai ou nenhum."

#: pypowervm/wrappers/job.py:276
#, python-format
msgid "Job %(job_id)s monitoring for %(time)i seconds."
msgstr "Tarefa %(job_id)s monitorando por %(time)i segundos."

#: pypowervm/wrappers/job.py:327
#, python-format
msgid ""
"Issuing cancel request for job %(job_id)s. Will poll the job indefinitely"
" for termination."
msgstr ""
"Emitindo solicitação de cancelamento para tarefa %(job_id)s. Pesquisará a tarefa indefinidamente"
" para finalização."

#: pypowervm/wrappers/job.py:343
#, python-format
msgid "Job %s not deleted. Job is in running state."
msgstr "Tarefa %s não foi excluída. Ela está no estado de execução."

#: pypowervm/wrappers/logical_partition.py:150
#: pypowervm/wrappers/logical_partition.py:230
msgid "LPAR does not have an active RMC connection."
msgstr "LPAR não tem uma conexão RMC ativa."

#: pypowervm/wrappers/logical_partition.py:152
#, python-format
msgid "LPAR does not have an active DLPAR capability for %s."
msgstr "LPAR não tem uma capacidade DLPAR ativa para %s."

#: pypowervm/wrappers/logical_partition.py:164
msgid "I/O"
msgstr "E/S"

#: pypowervm/wrappers/logical_partition.py:174
msgid "Memory"
msgstr "Memória"

#: pypowervm/wrappers/logical_partition.py:184
msgid "Processors"
msgstr "Processadores"

#: pypowervm/wrappers/logical_partition.py:208
msgid "LPAR is not in an active state."
msgstr "LPAR não está em um estado ativo."

#: pypowervm/wrappers/logical_partition.py:218
msgid "Target system does not have the IBM i LPAR Mobility Capability."
msgstr "O sistema de destino não tem a capacidade de mobilidade da LPAR do IBM i."

#: pypowervm/wrappers/logical_partition.py:222
msgid "IBM i LPAR does not have restricted I/O."
msgstr "IBM i LPAR não tem E/S restrita."

#: pypowervm/wrappers/logical_partition.py:226
msgid "Source system does not have the IBM i LPAR Mobility Capability."
msgstr "Sistema de origem não tem Capacidade de Mobilidade do IBM i LPAR."

#: pypowervm/wrappers/logical_partition.py:234
msgid "LPAR is not available for LPM due to missing DLPAR capabilities."
msgstr "LPAR não está disponível para LPM devido a recursos DLPAR ausente."

#: pypowervm/wrappers/logical_partition.py:251
#: pypowervm/wrappers/logical_partition.py:260
#: pypowervm/wrappers/logical_partition.py:268
msgid ""
"This is not the property you are looking for.  Use srr_enabled in a "
"NovaLink environment."
msgstr ""
"Essa não é a propriedade que você está procurando. Use srr_enabled em um "
"ambiente NovaLink."

#: pypowervm/wrappers/logical_partition.py:304
#, python-format
msgid "Invalid IPLSrc '%s'."
msgstr "IPLSrc '%s' inválido."

#: pypowervm/wrappers/storage.py:489
#, python-format
msgid ""
"PV had encoded pg83 descriptor \"%(pg83_raw)s\", but it failed to decode "
"(%(type_error)s)."
msgstr ""
"PV codificou o descritor pg83 \"%(pg83_raw)s\", mas falhou ao decodificar "
"(%(type_error)s)."

#: pypowervm/wrappers/virtual_io_server.py:143
msgid ""
"The 'xags' property of the VIOS EntryWrapper class is deprecated!  Please"
" use values from pypowervm.const.XAG instead."
msgstr ""
"A propriedade 'xags' da classe EntryWrapper do VIOS foi descontinuada!"
" use os valores do pypowervm.const.XAG."


# ENGL1SH_VERS10N 47423_39 DO NOT REMOVE OR CHANGE THIS LINE
# T9N_SRC_ID 23
# T9N_SH1P_STR1NG PV131AAP001 3
