# Translations template for pypowervm.
# Copyright 2015, 2017 IBM Corp.
# This file is distributed under the same license as the pypowervm project.
# Automatically generated, 2017.
#
msgid ""
msgstr ""
"Project-Id-Version: pypowervm 1.1.3.dev1\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2017-04-20 10:36-0400\n"
"PO-Revision-Date: 2017-04-20 10:36-0400\n"
"Last-Translator: Automatically generated\n"
"Language-Team: none\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.4.0\n"

#: pypowervm/adapter.py:131
#, python-format
msgid "Invalid protocol \"%s\""
msgstr "無效的通訊協定 \"%s\""

#: pypowervm/adapter.py:137
msgid "Unencrypted communication with PowerVM! Revert configuration to https."
msgstr "與 PowerVM 的通訊未加密！請將配置回復為 HTTPS。"

#: pypowervm/adapter.py:151
msgid "Calculating default audit memento failed, using 'default'."
msgstr "計算預設審核備忘錄失敗，將使用 'default'。"

#: pypowervm/adapter.py:192
msgid "Local authentication not supported on HMC."
msgstr "本端鑑別在 HMC 上不受支援。"

#: pypowervm/adapter.py:211
#, python-format
msgid "Setting up event listener for %s"
msgstr "正在設定 %s 的事件接聽器"

#: pypowervm/adapter.py:281
#, python-format
msgid "Unexpected filehandle on %s request"
msgstr "在 %s 要求上發現非預期的檔案控點"

#: pypowervm/adapter.py:327
#, python-format
msgid "Unexpected error for %(meth)s %(url)s"
msgstr "%(meth)s %(url)s 的非預期錯誤"

#: pypowervm/adapter.py:329
#, python-format
msgid "Unexpected error: %(class)s for %(method)s %(url)s: %(excp)s"
msgstr "非預期的錯誤：%(method)s %(url)s 的 %(class)s：%(excp)s"

#: pypowervm/adapter.py:367
msgid ""
"Re-login has been deemed unsafe. This Session instance should no longer be "
"used."
msgstr ""
"重新登入被視作不安全。應該不再使用此階段作業"
"實例。"

#: pypowervm/adapter.py:377
#, python-format
msgid "Attempting re-login %s"
msgstr "正在嘗試重新登入 %s"

#: pypowervm/adapter.py:388
#, python-format
msgid ""
"Re-login 401, response body:\n"
"%s"
msgstr ""
"重新登入 401，回應主體：\n"
"%s"

#: pypowervm/adapter.py:393
#, python-format
msgid ""
"Re-login failed, resp body:\n"
"%s"
msgstr ""
"重新登入失敗，回應主體：\n"
"%s"

#: pypowervm/adapter.py:397
#, python-format
msgid ""
"Re-login failed:\n"
"%s"
msgstr ""
"重新登入失敗：\n"
"%s"

#: pypowervm/adapter.py:416
#, python-format
msgid ""
"Re-attempt failed with another 401, response body:\n"
"%s"
msgstr ""
"重新嘗試失敗，發生另一個 401，回應主體：\n"
"%s"

#: pypowervm/adapter.py:419
#, python-format
msgid ""
"suspicious HTTP 401 response for %(method)s %(path)s: token is brand new"
msgstr ""
"%(method)s %(path)s 的可疑 HTTP 401 回應：記號是全新的"

#: pypowervm/adapter.py:461
#, python-format
msgid ""
"Failed to connect to REST server - is the pvm-rest service started?  "
"Retrying %(try_num)d of %(max_tries)d after %(delay)d seconds."
msgstr ""
"無法連接 REST 伺服器 - pvm-rest 服務是否已啟動？"
"在 %(delay)d 秒之後，正在重試第 %(try_num)d 次（共重試 %(max_tries)d 次）。"

#: pypowervm/adapter.py:468
#, python-format
msgid "Session logging on %s"
msgstr "階段作業正在登入 %s"

#: pypowervm/adapter.py:532
msgid "Failed to parse a session token from the PowerVM response."
msgstr "無法剖析來自 PowerVM 回應的階段作業記號。"

#: pypowervm/adapter.py:534 pypowervm/adapter.py:550
#, python-format
msgid " Body= %s"
msgstr " 主體 = %s"

#: pypowervm/adapter.py:548
msgid "Failed to parse a session file path from the PowerVM response."
msgstr "無法剖析來自 PowerVM 回應的階段作業檔案路徑。"

#: pypowervm/adapter.py:562
#, python-format
msgid "Token file %s didn't contain a readable session token."
msgstr "記號檔案 %s 不包含可讀的階段作業記號。"

#: pypowervm/adapter.py:572
#, python-format
msgid "Session logging off %s"
msgstr "階段作業正在從 %s 登出"

#: pypowervm/adapter.py:577
msgid "Problem logging off.  Ignoring."
msgstr "登出時發生問題。將忽略。"

#: pypowervm/adapter.py:671
msgid "job must be a JobRequest element"
msgstr "工作必須是 JobRequest 元素"

#: pypowervm/adapter.py:675
msgid "JobRequest is missing OperationName"
msgstr "JobRequest 遺漏了 OperationName"

#: pypowervm/adapter.py:689 pypowervm/adapter.py:807 pypowervm/adapter.py:846
#: pypowervm/adapter.py:903
#, python-format
msgid "path=%s is not a PowerVM API reference"
msgstr "路徑 = %s 不是 PowerVM API 參照"

#: pypowervm/adapter.py:918 pypowervm/adapter.py:935
msgid "Invalid file descriptor"
msgstr "檔案描述子無效"

#: pypowervm/adapter.py:1022 pypowervm/adapter.py:1050
#: pypowervm/adapter.py:1065
msgid "Expected root_id"
msgstr "預期的 root_id"

#: pypowervm/adapter.py:1024
msgid "Expected child_type"
msgstr "預期的 child_type"

#: pypowervm/adapter.py:1028 pypowervm/adapter.py:1054
#: pypowervm/adapter.py:1059
#, python-format
msgid "Unexpected suffix_type=%s"
msgstr "非預期的 suffix_type=%s"

#: pypowervm/adapter.py:1031 pypowervm/adapter.py:1062
msgid "Expected suffix_parm"
msgstr "預期的 suffix_parm"

#: pypowervm/adapter.py:1033 pypowervm/adapter.py:1052
#: pypowervm/adapter.py:1067
msgid "Expected child_id"
msgstr "預期的 child_id"

#: pypowervm/adapter.py:1036 pypowervm/adapter.py:1045
msgid "Unexpected child_id"
msgstr "非預期的 child_id"

#: pypowervm/adapter.py:1038 pypowervm/adapter.py:1047
msgid "Unexpected root_id"
msgstr "非預期的 root_id"

#: pypowervm/adapter.py:1069
#, python-format
msgid "Unexpected req_method=%s"
msgstr "非預期的 req_method=%s"

#: pypowervm/adapter.py:1138
#, python-format
msgid "Error parsing XML response from PowerVM: %s"
msgstr "剖析來自 PowerVM 的 XML 回應時發生錯誤：%s"

#: pypowervm/adapter.py:1151
msgid "Response is not an Atom feed/entry"
msgstr "回應不是 Atom 資訊來源/項目"

#: pypowervm/adapter.py:1162
msgid "Unexpected HTTP 204 for request"
msgstr "要求的非預期 HTTP 204"

#: pypowervm/adapter.py:1170
msgid "Unexpectedly empty response body"
msgstr "非預期的空白回應主體"

#: pypowervm/adapter.py:1173
#, python-format
msgid ""
"%(err_reason)s:\n"
"request headers: %(reqheaders)s\n"
"\n"
"request body: %(reqbody)s\n"
"\n"
"response headers: %(respheaders)s\n"
"\n"
"response body: %(respbody)s"
msgstr ""
"%(err_reason)s:\n"
"要求標頭：%(reqheaders)s\n"
"\n"
"要求內文：%(reqbody)s\n"
"\n"
"回應標頭：%(respheaders)s\n"
"\n"
"回應主體：%(respbody)s"

#: pypowervm/adapter.py:1181
#, python-format
msgid "Atom error for %(method)s %(path)s: %(reason)s"
msgstr "%(method)s %(path)s 的 Atom 錯誤：%(reason)s"

#: pypowervm/adapter.py:1222
msgid "Session must not be None"
msgstr "階段作業不得為「無」"

#: pypowervm/adapter.py:1224
msgid "An event listener is already active on the session."
msgstr "階段作業上，某個事件接聽器已經在作用中。"

#: pypowervm/adapter.py:1243
#, python-format
msgid "Failed to initialize event feed listener: %s"
msgstr "無法起始設定事件資訊來源接聽器：%s"

#: pypowervm/adapter.py:1247
#, python-format
msgid "Application id \"%s\" is not unique"
msgstr "應用程式 ID \"%s\" 不唯一"

#: pypowervm/adapter.py:1256
msgid "Shutting down"
msgstr "關機中"

#: pypowervm/adapter.py:1259
msgid "This handler is already subscribed"
msgstr "已經訂閱此處理程式"

#: pypowervm/adapter.py:1267
msgid "Handler must be an EventHandler"
msgstr "處理程式必須是 EventHandler"

#: pypowervm/adapter.py:1270
msgid "This handler not found in subscriber list"
msgstr "在訂閱者清單中找不到此處理程式"

#: pypowervm/adapter.py:1278
#, python-format
msgid "Shutting down EventListener for %s"
msgstr "正在關閉 %s 的 EventListener"

#: pypowervm/adapter.py:1282
#, python-format
msgid "EventListener shutdown complete for %s"
msgstr "%s 的 EventListener 關閉已完成"

#: pypowervm/adapter.py:1302
#, python-format
msgid ""
"Error while getting PowerVM events: %s.  (Is the pvm-rest service down?)"
msgstr ""
"取得 PowerVM 事件時發生錯誤：%s。（pvm-rest 服務是否已關閉？）"

#: pypowervm/adapter.py:1345
#, python-format
msgid "Unexpected EventType=%s"
msgstr "非預期的 EventType=%s"

#: pypowervm/adapter.py:1373
msgid "Error while processing PowerVM events"
msgstr "處理 PowerVM 事件時發生錯誤"

#: pypowervm/exceptions.py:117
#, python-format
msgid ""
"Unable to derive the appropriate physical FC port for WWPN %(wwpn)s.  The "
"VIOS Extended Attribute Groups may have been insufficient.  The VIOS URI for "
"the query was %(vio_uri)s."
msgstr ""
"無法衍生 WWPN %(wwpn)s 的適當實體 FC 埠。「VIOS"
"延伸屬性群組」可能不足。查詢的 VIOS URI 是"
"%(vio_uri)s。"

#: pypowervm/exceptions.py:123
#, python-format
msgid "Element not found: %(element_type)s %(element)s"
msgstr "找不到元素：%(element_type)s %(element)s"

#: pypowervm/exceptions.py:127
#, python-format
msgid "LPAR not found: %(lpar_name)s"
msgstr "找不到 LPAR：%(lpar_name)s"

#: pypowervm/exceptions.py:131
#, python-format
msgid "The '%(operation_name)s' operation failed. %(error)s"
msgstr "'%(operation_name)s' 作業失敗。%(error)s"

#: pypowervm/exceptions.py:135
#, python-format
msgid ""
"The '%(operation_name)s' operation failed. Failed to complete the task in "
"%(seconds)d seconds."
msgstr ""
"'%(operation_name)s' 作業失敗。無法在 %(seconds)d 秒內完成"
"作業。"

#: pypowervm/exceptions.py:140
#, python-format
msgid ""
"Can not perform OS shutdown on Virtual Machine %(lpar_nm)s because its RMC "
"connection is not active."
msgstr ""
"無法在虛擬機器 %(lpar_nm)s 上執行作業系統關閉，因為其 RMC "
"連線處於非作用中。"

#: pypowervm/exceptions.py:145
#, python-format
msgid "Failed to power off Virtual Machine %(lpar_nm)s: %(reason)s"
msgstr "無法關閉虛擬機器 %(lpar_nm)s 的電源：%(reason)s"

#: pypowervm/exceptions.py:149
#, python-format
msgid ""
"Power off of Virtual Machine %(lpar_nm)s timed out after %(timeout)d seconds."
msgstr ""
"關閉虛擬機器 %(lpar_nm)s 的電源在 %(timeout)d 秒後逾時。"

#: pypowervm/exceptions.py:154
#, python-format
msgid "Failed to power on Virtual Machine %(lpar_nm)s: %(reason)s"
msgstr "無法開啟虛擬機器 %(lpar_nm)s 的電源：%(reason)s"

#: pypowervm/exceptions.py:158
#, python-format
msgid ""
"Power on of Virtual Machine %(lpar_nm)s timed out after %(timeout)d seconds."
msgstr ""
"開啟虛擬機器 %(lpar_nm)s 的電源在 %(timeout)d 秒後逾時。"

#: pypowervm/exceptions.py:163
#, python-format
msgid ""
"Unable to remove VLAN %(vlan_id)d as it is the Primary VLAN Identifier on a "
"different Network Bridge."
msgstr ""
"無法移除 VLAN %(vlan_id)d，因為它是另一個網路橋接器上的"
"主要 VLAN ID。"

#: pypowervm/exceptions.py:168
#, python-format
msgid ""
"Unable to provision VLAN %(vlan_id)d.  It appears to be contained on device "
"'%(dev_name)s' on Virtual I/O Server %(vios)s.  That device is not connected "
"to any Network Bridge (Shared Ethernet Adapter).  Please manually remove the "
"device or add it to the Network Bridge before continuing."
msgstr ""
"無法供應 VLAN %(vlan_id)d。它似乎包含在"
"Virtual I/O Server %(vios)s 上的裝置 '%(dev_name)s' 中。該裝置未連接"
"至任何網路橋接器（共用乙太網路配接卡）。請手動移除該"
"裝置，或者先將其新增至網路橋接器，然後再繼續。"

#: pypowervm/exceptions.py:177
#, python-format
msgid ""
"A Logical Unit with name %(lu_name)s already exists on Shared Storage Pool "
"%(ssp_name)s."
msgstr ""
"名為 %(lu_name)s 的邏輯單元已經存在於下列共用儲存區上："
"%(ssp_name)s."

#: pypowervm/exceptions.py:182
msgid ""
"Unable to find a physical port to map a virtual Fibre Channel port to.  This "
"is due to either a Virtual I/O Server being unavailable, or improper port "
"specification for the physical Fibre Channel ports."
msgstr ""
"找不到要將虛擬光纖通道埠對映至的實體埠。這"
"是由於無法使用 Virtual I/O Server，或者"
"實體光纖通道埠的埠規格不適當。"

#: pypowervm/exceptions.py:189
msgid ""
"Unable to start the console to the Virtual Machine.  The pypowervm API is "
"running in a non-local mode.  The console can only be deployed when "
"pypowervm is co-located with the PowerVM API."
msgstr ""
"無法對虛擬機器啟動主控台。pypowervm API "
"正在以非本端模式執行。僅當 "
"pypowervm 與 PowerVM API 存在於相同位置時，才能部署主控台。"

#: pypowervm/exceptions.py:196
#, python-format
msgid "WrapperTask %(name)s has no subtasks!"
msgstr "WrapperTask %(name)s 沒有子作業！"

#: pypowervm/exceptions.py:200
msgid "FeedTask can't have an empty feed."
msgstr "FeedTask 不能有空的資訊來源。"

#: pypowervm/exceptions.py:204
#, python-format
msgid "OS denied access to file %(access_file)s."
msgstr "作業系統拒絕存取檔案 %(access_file)s。"

#: pypowervm/exceptions.py:208
#, python-format
msgid ""
"OS encountered an I/O error attempting to read file %(access_file)s: "
"%(error)s"
msgstr ""
"作業系統在嘗試讀取檔案 %(access_file)s 時遇到 I/O 錯誤："
"%(error)s"

#: pypowervm/exceptions.py:213
#, python-format
msgid "The migration task failed. %(error)s"
msgstr "移轉作業失敗。%(error)s"

#: pypowervm/exceptions.py:217
#, python-format
msgid "No load source found for VM %(vm_name)s"
msgstr "找不到 VM %(vm_name)s 的載入來源"

#: pypowervm/exceptions.py:221
#, python-format
msgid ""
"Unable to derive the pg83 encoding for hdisk %(dev_name)s.  The parent_entry "
"attribute is not set.  This may be due to using a PV obtained through an "
"unsupported property chain.  The PV must be accessed via VIOS.phys_vols, VG."
"phys_vols, or VIOS.scsi_mappings[n].backing_storage."
msgstr ""
"無法衍生硬碟 %(dev_name)s 的 pg83 編碼。未設定 parent_entry "
"屬性。這可能是由於使用了透過不受支援之內容鏈"
"所取得的 PV。必須透過 VIOS.phys_vols、"
"VG.phys_vols 或 VIOS.scsi_mappings[n].backing_storage 來存取 PV。"

#: pypowervm/exceptions.py:229
#, python-format
msgid ""
"Found device %(devname)s %(count)d times; expected to find it at most once."
msgstr ""
"找到裝置 %(devname)s %(count)d 次；預期最多找到該裝置一次。"

#: pypowervm/exceptions.py:244
#, python-format
msgid ""
"FeedTask %(ft_name)s experienced multiple exceptions:\n"
"\t%(concat_msgs)s"
msgstr ""
"FeedTask %(ft_name)s 遇到多個異常狀況：\n"
"\t%(concat_msgs)s"

#: pypowervm/exceptions.py:254
#, python-format
msgid "Expected to find exactly one management partition; found %(count)d."
msgstr "預期只找到一個管理分割區；但找到 %(count)d 個。"

#: pypowervm/exceptions.py:260
#, python-format
msgid ""
"Expected to find exactly one partition with ID %(lpar_id)d; found %(count)d."
msgstr ""
"預期只找到一個 ID 為 %(lpar_id)d 的分割區；但卻找到 %(count)d 個。"

#: pypowervm/exceptions.py:266
#, python-format
msgid "Couldn't find the default Tier on Shared Storage Pool %(ssp_name)s."
msgstr "在共用儲存區 %(ssp_name)s 上找不到預設層級。"

#: pypowervm/exceptions.py:275
#, python-format
msgid ""
"The device with UDID %(udid)s was not found on any of the Virtual I/O "
"Servers."
msgstr ""
"在任何 Virtual I/O Server 上，都找不到 UDID 為 %(udid)s 的"
"裝置。"

#: pypowervm/exceptions.py:280
#, python-format
msgid ""
"There are not enough Virtual I/O Servers to support the virtual machine's "
"device with UDID %(udid)s."
msgstr ""
"Virtual I/O Server 不足，無法支援虛擬機器的"
"裝置（UDID 為 %(udid)s）。"

#: pypowervm/exceptions.py:285
#, python-format
msgid ""
"The expected fabrics (%(fabrics)s) were not found on any of the Virtual I/O "
"Servers."
msgstr ""
"在任何 Virtual I/O Server 上，都找不到預期的"
"光纖 (%(fabrics)s)。"

#: pypowervm/exceptions.py:290
#, python-format
msgid ""
"Can not rebuild the virtual machine.  It is using an I/O type of %(io_type)s "
"which is not supported for VM rebuild."
msgstr ""
"無法重建虛擬機器。它正在使用的 I/O 類型為 %(io_type)s，"
"虛擬機器重建不支援這種 I/O 類型。"

#: pypowervm/exceptions.py:295
#, python-format
msgid ""
"The number of VFC slots on the target system (%(rebuild_slots)d) does not "
"match the number of slots on the client system (%(original_slots)d).  Unable "
"to rebuild this virtual machine on this system."
msgstr ""
"目標系統上的 VFC 插槽數目 (%(rebuild_slots)d) 與"
"用戶端系統上的插槽數目 (%(original_slots)d) 不符。無法"
"在這個系統上重建此虛擬機器。"

#: pypowervm/exceptions.py:302
#, python-format
msgid ""
"To register the slot information of the network device a CNA or VNIC adapter "
"is needed. Instead the following was given: %(wrapper)s."
msgstr ""
"如果要登錄網路裝置的插槽資訊，則需要 CNA 或"
"VNIC 配接卡。但卻提供了以下項目：%(wrapper)s。"

#: pypowervm/exceptions.py:308
#, python-format
msgid ""
"There are not enough active Virtual I/O Servers available. Expected %(exp)d; "
"found %(act)d."
msgstr ""
"沒有足夠的作用中 Virtual I/O Server 可用。預期為 %(exp)d；"
"但卻找到 %(act)d。"

#: pypowervm/exceptions.py:313
#, python-format
msgid ""
"No Virtual I/O Servers are available.  Attempted to wait for a VIOS to "
"become active for %(wait_time)d seconds.  Please check the RMC connectivity "
"between the PowerVM NovaLink and the Virtual I/O Servers."
msgstr ""
"沒有 Virtual I/O Server 可用。已嘗試等待 VIOS 變成"
"作用中狀態達 %(wait_time)d 秒。請檢查 PowerVM NovaLink 與"
"Virtual I/O Server 之間的 RMC 連線。"

#: pypowervm/exceptions.py:323
#, python-format
msgid ""
"Could not find any SR-IOV adapters in Sriov mode and Running state.\n"
"Location | Mode | State\n"
"%(sriov_loc_mode_state)s"
msgstr ""
"找不到任何 SR-IOV 配接卡處於 Sriov 模式及執行中狀態。\n"
"位置 | 模式 | 狀態\n"
"%(sriov_loc_mode_state)s"

#: pypowervm/exceptions.py:328
#, python-format
msgid ""
"Unable to fulfill redundancy requirement of %(red)d.  Found %(found_vfs)d "
"viable backing device(s)."
msgstr ""
"無法滿足備援需求（%(red)d 個）。找到 %(found_vfs)d "
"個可行的支持裝置。"

#: pypowervm/exceptions.py:333
msgid "The Managed System is not vNIC capable."
msgstr "受管理系統不支援 vNIC。"

#: pypowervm/exceptions.py:337
msgid "There are no active vNIC-capable VIOSes."
msgstr "沒有處於作用中狀態且支援 vNIC 的 VIOS。"

#: pypowervm/exceptions.py:341
#, python-format
msgid ""
"A redundancy of %(red)d was specified, but the Managed System is not vNIC "
"failover capable."
msgstr ""
"指定了 %(red)d 個備援，但受管理系統不具備 vNIC "
"失效接手功能。"

#: pypowervm/exceptions.py:346
#, python-format
msgid ""
"A redundancy of %(red)d was specified, but there are no active vNIC failover-"
"capable VIOSes."
msgstr ""
"指定了 %(red)d 個備援，但沒有作用中的具備 vNIC 失效接手功能的 "
"VIOS。"

#: pypowervm/exceptions.py:351
#, python-format
msgid ""
"Unable to locate the volume group %(vol_grp)s to store the virtual optical "
"media within.  Unable to create the media repository."
msgstr ""
"找不到在其中儲存虛擬光學媒體的磁區群組"
"%(vol_grp)s。無法建立媒體儲存庫。"

#: pypowervm/exceptions.py:357
#, python-format
msgid ""
"The ManagedSystem update was not attempted because changes were requested to "
"one or more SR-IOV physical ports which are in use by vNICs.\n"
"%(warnings)s"
msgstr ""
"未嘗試進行受管理系統更新，因為已要求對其進行變更的"
"一個以上 SR-IOV 實體埠正在由 vNIC 使用。\n"
"%(warnings)s"

#: pypowervm/exceptions.py:363
#, python-format
msgid "Unable to create VNC based virtual terminal: %(err)s"
msgstr "無法建立 VNC 型虛擬終端機：%(err)s"

#: pypowervm/exceptions.py:367
msgid "The Adapter cache is not supported."
msgstr "不支援配接卡快取。"

#: pypowervm/exceptions.py:371
#, python-format
msgid ""
"Invalid value '%(value)s' for '%(enum)s'.  Valid values are: %(valid_values)s"
msgstr ""
"'%(enum)s' 的值 '%(value)s' 無效。有效值為：%(valid_values)s"

#: pypowervm/exceptions.py:376
#, python-format
msgid "No VIOS found with name %(vios_name)s."
msgstr "找不到名稱為 %(vios_name)s 的 VIOS。"

#: pypowervm/exceptions.py:380
#, python-format
msgid "No volume group found with name %(vg_name)s."
msgstr "找不到名稱為 %(vg_name)s 的磁區群組。"

#: pypowervm/util.py:125
#, python-format
msgid ""
"Proposed extended attribute group '%(arg_xag)s' doesn't match existing "
"extended attribute group '%(path_xag)s'"
msgstr ""
"所提出的延伸屬性群組 '%(arg_xag)s' 與下列現有延伸屬性群組不符："
"'%(path_xag)s'"

#: pypowervm/util.py:221
msgid "Certificate has expired."
msgstr "憑證已過期。"

#: pypowervm/util.py:371
#, python-format
msgid "Prefix and suffix together may not be more than %d characters."
msgstr "字首及字尾總共不能超過 %d 個字元。"

#: pypowervm/util.py:376
msgid "Total length must be at least 1 character."
msgstr "總長度必須至少是 1 個字元。"

#: pypowervm/util.py:399
msgid "The name parameter must be at least one character long."
msgstr "名稱參數的長度必須至少是一個字元。"

#: pypowervm/util.py:402
#, python-format
msgid ""
"The name parameter must not exceed %d characters when trunk_ok is False."
msgstr ""
"當 trunk_ok 為 False 時，名稱參數不得超過 %d 個字元。"

#: pypowervm/util.py:500
msgid "Developer error: partial parent specification."
msgstr "開發者錯誤：局部母項規範。"

#: pypowervm/util.py:505
msgid ""
"Developer error: parent_type must be either a string schema type or a "
"Wrapper subclass."
msgstr ""
"開發者錯誤：parent_type 必須為字串綱目類型或 "
"封套子類別。"

#: pypowervm/util.py:602
#, python-format
msgid "Invalid value '%(bad_val)s'.  Expected one of %(good_vals)s, or a list."
msgstr ""
"無效值 '%(bad_val)s'。預期為 %(good_vals)s 中的一個或一個清單。"

#: pypowervm/helpers/log_helper.py:83
#, python-format
msgid "REQUEST: %s"
msgstr "要求：%s"

#: pypowervm/helpers/log_helper.py:103
#, python-format
msgid "RESPONSE: %s"
msgstr "回應：%s"

#: pypowervm/tasks/cluster_ssp.py:108
#, python-format
msgid "Waiting for in-progress upload(s) to complete.  Marker LU(s): %s"
msgstr "正在等待進行中的上傳作業完成。標記 LU：%s"

#: pypowervm/tasks/cluster_ssp.py:137
msgid "Abdicating in favor of in-progress upload."
msgstr "正在放棄支援進行中的上傳。"

#: pypowervm/tasks/cluster_ssp.py:147
#, python-format
msgid "Abdicating upload in favor of marker %s."
msgstr "正在放棄上傳，轉為支援標記 %s。"

#: pypowervm/tasks/cluster_ssp.py:202
#, python-format
msgid "Using already-uploaded image LU %s."
msgstr "正在使用已經上傳的映像檔 LU %s。"

#: pypowervm/tasks/cluster_ssp.py:212
#, python-format
msgid "Creating marker LU %s"
msgstr "正在建立標記 LU %s"

#: pypowervm/tasks/cluster_ssp.py:228
#, python-format
msgid "Uploading to image LU %(lu)s (marker %(mkr)s)."
msgstr "正在上傳至映像檔 LU %(lu)s（標記 %(mkr)s）。"

#: pypowervm/tasks/cluster_ssp.py:240
#, python-format
msgid "Removing failed LU %s."
msgstr "正在移除失敗的 LU %s。"

#: pypowervm/tasks/cna.py:120
#, python-format
msgid "Unable to find the Virtual Switch %s on the system."
msgstr "在系統上找不到虛擬交換器 %s。"

#: pypowervm/tasks/cna.py:147
#, python-format
msgid "Unable to find a valid VLAN for Virtual Switch %s."
msgstr "找不到虛擬交換器 %s 的有效 VLAN。"

#: pypowervm/tasks/memory.py:102
#, python-format
msgid ""
"Error obtaining host memory overhead for host with UUID '%(host)s': "
"%(error)s."
msgstr ""
"取得主機（UUID 為 '%(host)s'）的主機記憶體額外負擔時發生錯誤："
"%(error)s."

#: pypowervm/tasks/partition.py:312
#, python-format
msgid ""
"Timed out waiting for the RMC state of all the powered on Virtual I/O "
"Servers to be active. Wait time was: %(time)d seconds. VIOSes that did not "
"go active were: %(vioses)s."
msgstr ""
"等待所有已開啟電源之 Virtual I/O Server 的 RMC 狀態"
"變成作用中時逾時。等待時間為 %(time)d 秒。未變成"
"作用中的 VIOS 為：%(vioses)s。"

#: pypowervm/tasks/partition.py:354
#, python-format
msgid "Assuming description-less slot is physical I/O: %s"
msgstr "假定無說明的插槽是實體 I/O：%s"

#: pypowervm/tasks/power.py:88
#, python-format
msgid "Partition %s already powered on."
msgstr "分割區 %s 已開啟。"

#: pypowervm/tasks/power.py:136
#, python-format
msgid "Partition %s already powered off."
msgstr "分割區 %s 已關閉。"

#: pypowervm/tasks/power.py:199
#, python-format
msgid ""
"Specifying add_parms as a dict is deprecated. Please specify a %s instance "
"instead."
msgstr ""
"已淘汰將 add_parms 指定為 dict 這一做法。請指定 %s 實例 "
"lxml。"

#: pypowervm/tasks/power.py:265
#, python-format
msgid ""
"IBMi OS normal shutdown failed.  Trying OS immediate shutdown.  Partition: %s"
msgstr ""
"IBMi 作業系統正常關閉失敗。正在嘗試立即關閉作業系統。分割區：%s"

#: pypowervm/tasks/power.py:275
#, python-format
msgid ""
"IBMi OS immediate shutdown failed.  Trying VSP normal shutdown.  Partition: "
"%s"
msgstr ""
"IBMi 作業系統立即關閉失敗。正在嘗試正常關閉 VSP。分割區："
"%s"

#: pypowervm/tasks/power.py:284
#, python-format
msgid ""
"IBMi VSP normal shutdown failed.  Trying VSP hard shutdown.  Partition: %s"
msgstr ""
"IBMi VSP 正常關閉失敗。正在嘗試強迫關閉 VSP。分割區：%s"

#: pypowervm/tasks/power.py:326
#, python-format
msgid ""
"Non-IBMi OS immediate shutdown timed out.  Trying VSP hard shutdown.  "
"Partition: %s"
msgstr ""
"非 IBMi 作業系統立即關閉已逾時。正在嘗試強迫關閉 VSP。"
"分割區：%s"

#: pypowervm/tasks/power.py:330
#, python-format
msgid ""
"Non-IBMi OS immediate shutdown failed.  Trying VSP normal shutdown.  "
"Partition: %s"
msgstr ""
"非 IBMi 作業系統立即關閉失敗。正在嘗試正常關閉 VSP。"
"分割區：%s"

#: pypowervm/tasks/power.py:343
#, python-format
msgid ""
"Non-IBMi VSP normal shutdown failed.  Trying VSP hard shutdown.  Partition: "
"%s"
msgstr ""
"非 IBMi VSP 正常關閉失敗。正在嘗試強迫關閉 VSP。分割區："
"%s"

#: pypowervm/tasks/power.py:437
#, python-format
msgid "VSP hard shutdown with default timeout.  Partition: %s"
msgstr "強迫關閉 VSP，發生預設逾時。分割區：%s"

#: pypowervm/tasks/scsi_mapper.py:38
msgid "Retrying modification of SCSI Mapping."
msgstr "正在重試修改 SCSI 對映。"

#: pypowervm/tasks/scsi_mapper.py:98
#, python-format
msgid ""
"Found existing mapping of %(stg_type)s storage element %(stg_name)s from "
"Virtual I/O Server %(vios_name)s to client LPAR %(lpar_uuid)s."
msgstr ""
"找到 %(stg_type)s 儲存體元素 %(stg_name)s 的現有對映：從"
"Virtual I/O Server %(vios_name)s 至用戶端 LPAR %(lpar_uuid)s。"

#: pypowervm/tasks/scsi_mapper.py:117
#, python-format
msgid ""
"Creating mapping of %(stg_type)s storage element %(stg_name)s from Virtual I/"
"O Server %(vios_name)s to client LPAR %(lpar_uuid)s."
msgstr ""
"正在建立下列 %(stg_type)s 儲存體元素 %(stg_name)s 對映：從 Virtual I/O Server"
"%(vios_name)s 到用戶端 LPAR %(lpar_uuid)s。"

#: pypowervm/tasks/scsi_mapper.py:433
msgid "Must not specify both match_func and stg_elem."
msgstr "不得同時指定 match_func 和 stg_elem。"

#: pypowervm/tasks/slot_map.py:194
msgid ""
"The register_cna method is deprecated! Please use the register_vnet method."
msgstr ""
"register_cna 方法已遭到淘汰！請使用 register_vnet 方法。"

#: pypowervm/tasks/slot_map.py:204
msgid "The drop_cna method is deprecated! Please use the drop_vnet method."
msgstr "drop_cna 方法已遭到淘汰。請使用 drop_vnet 方法。"

#: pypowervm/tasks/sriov.py:379
#, python-format
msgid ""
"SR-IOV Physical Port at location %(loc_code)s is backing a vNIC belonging to "
"LPAR %(lpar_name)s (LPAR UUID: %(lpar_uuid)s; vNIC UUID: %(vnic_uuid)s)."
msgstr ""
"位置 %(loc_code)s 處的 SR-IOV 實體埠支援屬於下列 LPAR 的 vNIC："
"%(lpar_name)s（LPAR UUID：%(lpar_uuid)s；vNIC UUID：%(vnic_uuid)s）。"

#: pypowervm/tasks/sriov.py:496
msgid ""
"Making changes to the following SR-IOV physical port labels even though they "
"are in use by vNICs:"
msgstr ""
"正在變更下列 SR-IOV 實體埠標籤，即使它們正在由"
"vNIC 使用，亦是如此："

#: pypowervm/tasks/storage.py:96
#, python-format
msgid "Failed to delete vio_file with UUID %s.  It must be manually deleted."
msgstr "無法刪除 UUID 為 %s 的 vio_file。必須將其手動刪除。"

#: pypowervm/tasks/storage.py:348
msgid "Encountered an issue while uploading. Will retry."
msgstr "上傳時遇到問題。將重試。"

#: pypowervm/tasks/storage.py:522
msgid ""
"The crt_lu_linked_clone method is deprecated!  Please use the crt_lu method "
"(clone=src_lu, size=lu_size_gb)."
msgstr ""
"crt_lu_linked_clone 方法已遭到淘汰！請使用 crt_lu 方法"
"（clone=src_lu，size=lu_size_gb）。"

#: pypowervm/tasks/storage.py:573
#, python-format
msgid ""
"Disk Logical Unit %(luname)s has no backing image LU.  (UDID: %(udid)s) "
msgstr ""
"磁碟邏輯單元 %(luname)s 沒有支援的映像檔 LU。（UDID：%(udid)s）"

#: pypowervm/tasks/storage.py:654
msgid "Unable to locate new vDisk on file upload."
msgstr "在檔案上傳時，找不到新的 vDisk。"

#: pypowervm/tasks/storage.py:703
#, python-format
msgid ""
"Ignoring device because it lacks a UDID:\n"
"%s"
msgstr ""
"忽略裝置，因為該裝置缺少 UDID：\n"
"%s"

#: pypowervm/tasks/storage.py:709
#, python-format
msgid "Device %s not found in list."
msgstr "在清單中找不到裝置 %s。"

#: pypowervm/tasks/storage.py:738
#, python-format
msgid "Deleting virtual disk %(vdisk)s from volume group %(vg)s"
msgstr "正在從磁區群組 %(vg)s 刪除虛擬磁碟 %(vdisk)s"

#: pypowervm/tasks/storage.py:761
#, python-format
msgid "Deleting virtual optical device %(vopt)s from volume group %(vg)s"
msgstr "正在從磁區群組 %(vg)s 刪除虛擬光學裝置 %(vopt)s"

#: pypowervm/tasks/storage.py:817
#, python-format
msgid "Removing LU %(lu_name)s (UDID %(lu_udid)s)"
msgstr "正在移除 LU %(lu_name)s (UDID %(lu_udid)s)"

#: pypowervm/tasks/storage.py:821
#, python-format
msgid ""
"LU %(lu_name)s was not found - it may have been deleted out of band.  (UDID: "
"%(lu_udid)s)"
msgstr ""
"找不到 LU %(lu_name)s - 可能已在頻帶外將其刪除。（UDID："
"%(lu_udid)s)"

#: pypowervm/tasks/storage.py:839
#, python-format
msgid ""
"Removing Image LU %(lu_name)s because it is no longer in use.  (UDID: "
"%(lu_udid)s)"
msgstr ""
"正在移除映像檔 LU %(lu_name)s，因為不再使用它。（UDID："
"%(lu_udid)s)"

#: pypowervm/tasks/storage.py:844
#, python-format
msgid "Backing LU %(lu_name)s was not found.  (UDID: %(lu_udid)s)"
msgstr "找不到支援的 LU %(lu_name)s。（UDID：%(lu_udid)s）"

#: pypowervm/tasks/storage.py:870
msgid "Developer error: Either tier or lufeed is required."
msgstr "開發者錯誤：需要層級或 lufeed。"

#: pypowervm/tasks/storage.py:875
msgid ""
"Developer error: The lufeed parameter must comprise LUEnt EntryWrappers."
msgstr ""
"開發者錯誤：lufeed 參數必須包含 LUEnt EntryWrappers。"

#: pypowervm/tasks/storage.py:882
#, python-format
msgid "Deleting LU %(lu_name)s (UDID: %(lu_udid)s)"
msgstr "正在刪除 LU %(lu_name)s（UDID：%(lu_udid)s）"

#: pypowervm/tasks/storage.py:887
#, python-format
msgid ""
"Ignoring HttpError for LU %(lu_name)s may have been deleted out of band.  "
"(UDID: %(lu_udid)s)"
msgstr ""
"忽略 HttpError，可能已在頻帶外刪除 LU %(lu_name)s。"
"（UDID：%(lu_udid)s）"

#: pypowervm/tasks/storage.py:940
#, python-format
msgid ""
"Removing %(num_maps)d orphan %(stg_type)s mappings from VIOS %(vios_name)s."
msgstr ""
"正在從 VIOS %(vios_name)s 移除 %(num_maps)d 個段落遺留字串 %(stg_type)s 對映。"

#: pypowervm/tasks/storage.py:966
#, python-format
msgid "Removing %(num_maps)d port-less VFC mappings from VIOS %(vios_name)s."
msgstr "正在從 VIOS %(vios_name)s 中移除 %(num_maps)d 個缺少埠的 VFC 對映。"

#: pypowervm/tasks/storage.py:993
#, python-format
msgid ""
"Removing %(num_maps)d %(stg_type)s mappings associated with LPAR ID "
"%(lpar_id)d from VIOS %(vios_name)s."
msgstr ""
"正在將 %(num_maps)d 個與 LPAR ID "
"%(lpar_id)d 相關聯的 %(stg_type)s 對映從 VIOS %(vios_name)s 中移除。"

#: pypowervm/tasks/storage.py:1060
#, python-format
msgid ""
"Not removing storage %(stg_name)s of type %(stg_type)s because it cannot be "
"determined whether it is still in use.  Manual verification and cleanup may "
"be necessary."
msgstr ""
"未移除類型為 %(stg_type)s 的儲存體 %(stg_name)s，因為它無法"
"判定它是否仍在使用中。可能需要手動驗證和"
"清除。"

#: pypowervm/tasks/storage.py:1071
#, python-format
msgid ""
"Storage scrub ignoring storage element %(stg_name)s because it is of "
"unexpected type %(stg_type)s."
msgstr ""
"儲存體清除忽略儲存體元素 %(stg_name)s，因為它是"
"非預期的類型 %(stg_type)s。"

#: pypowervm/tasks/storage.py:1089
#, python-format
msgid ""
"Scrubbing the following %(vdcount)d Virtual Disks from VIOS %(vios)s: "
"%(vdlist)s"
msgstr ""
"正在從 VIOS %(vios)s 清除以下 %(vdcount)d 個虛擬磁碟："
"%(vdlist)s"

#: pypowervm/tasks/storage.py:1097
#, python-format
msgid ""
"Scrubbing the following %(vocount)d Virtual Opticals from VIOS %(vios)s: "
"%(volist)s"
msgstr ""
"正在從 VIOS %(vios)s 清除以下 %(vocount)d 個虛擬光學裝置："
"%(volist)s"

#: pypowervm/tasks/storage.py:1168
#, python-format
msgid ""
"Skipping scrub of %(stg_type)s mappings from VIOS %(vios_name)s for the "
"following LPAR IDs because those LPARs exist: %(lpar_ids)s"
msgstr ""
"正在從 VIOS %(vios_name)s 跳過下列 LPAR ID 的 %(stg_type)s 對映清除，"
"原因是已存在這些 LPAR：%(lpar_ids)s"

#: pypowervm/tasks/vfc_mapper.py:529
#, python-format
msgid ""
"Unable to find appropriate VIOS.  The payload provided was likely "
"insufficient.  The payload data is:\n"
" %s)"
msgstr ""
"找不到適當的 VIOS。提供的有效負載可能"
"不足。有效負載資料為：\n"
" %s)"

#: pypowervm/tasks/vfc_mapper.py:558
#, python-format
msgid ""
"The matched VFC port map has no backing port set. Adding %(port)s to mapping "
"for client wwpns: %(wwpns)s"
msgstr ""
"相符的 VFC 埠對映未設定支援埠。正在將 %(port)s 新增至"
"用戶端 WWPN %(wwpns)s 的對映"

#: pypowervm/tasks/vopt.py:73
msgid ""
"An error occurred querying the virtual optical media repository.  Attempting "
"to re-establish connection with a virtual optical media repository"
msgstr ""
"查詢虛擬光學媒體儲存庫時發生錯誤。正在嘗試"
"重新建立與虛擬光學媒體儲存庫的連線"

#: pypowervm/tasks/vterm.py:85
msgid "Unable to close vterm."
msgstr "無法關閉 vterm。"

#: pypowervm/tasks/vterm.py:137
#, python-format
msgid "Invalid output on vterm open.  Trying to reset the vterm.  Error was %s"
msgstr ""
"vterm 開啟時的輸出無效。正在嘗試重設 vterm。錯誤為 %s"

#: pypowervm/tasks/vterm.py:345
#, python-format
msgid "VNCSocket Listener Listening on ip=%(ip)s port=%(port)s"
msgstr "VNCSocket 接聽器正在於 IP %(ip)s 埠 %(port)s 上接聽"

#: pypowervm/tasks/vterm.py:474
#, python-format
msgid "Error negotiating SSL for VNC Repeater: %s"
msgstr "對 VNC 轉送站協議 SSL 時發生錯誤：%s"

#: pypowervm/tasks/hdisk/_fc.py:197
#, python-format
msgid ""
"hdisk discovery failed; will scrub stale storage for LPAR IDs %s and retry."
msgstr ""
"硬碟探索失敗；將清除 LPAR ID %s 的陳舊儲存體，然後重試。"

#: pypowervm/tasks/hdisk/_fc.py:339
#, python-format
msgid "LUA Recovery Successful. Device Found: %s"
msgstr "LUA 回復成功。找到裝置：%s"

#: pypowervm/tasks/hdisk/_fc.py:343
#, python-format
msgid "ITL Error encountered: %s"
msgstr "遇到 ITL 錯誤：%s"

#: pypowervm/tasks/hdisk/_fc.py:345
#, python-format
msgid "%s Device is currently in use."
msgstr "%s 裝置目前在使用中。"

#: pypowervm/tasks/hdisk/_fc.py:347
#, python-format
msgid "%s Device discovered with unknown UDID."
msgstr "探索到具有不明 UDID 的 %s 裝置。"

#: pypowervm/tasks/hdisk/_fc.py:349
#, python-format
msgid "Failed to Discover the Device : %s"
msgstr "無法探索裝置：%s"

#: pypowervm/tasks/hdisk/_fc.py:419
#, python-format
msgid "CLIRunner Error: %s"
msgstr "CLIRunner 錯誤：%s"

#: pypowervm/tasks/hdisk/_fc.py:451
msgid ""
"QUERY_INVENTORY LUARecovery Job succeeded, but result contained neither "
"OutputXML nor StdOut."
msgstr ""
"QUERY_INVENTORY LUARecovery 工作成功，但結果不包含"
"OutputXML 和標準輸出。"

#: pypowervm/tasks/hdisk/_fc.py:475
#, python-format
msgid ""
"QUERY_INVENTORY produced invalid chunk of XML (%(chunk)s).  Error: %(err)s"
msgstr ""
"QUERY_INVENTORY 產生了 XML (%(chunk)s) 的無效區塊。錯誤：%(err)s"

#: pypowervm/tasks/hdisk/_fc.py:483
#, python-format
msgid ""
"Failed to find pg83 descriptor in XML output:\n"
"%s"
msgstr ""
"在 XML 輸出中找不到 pg83 描述子：\n"
"%s"

#: pypowervm/tasks/hdisk/_iscsi.py:73
#, python-format
msgid "Invalid device output: %(dev)s"
msgstr "裝置輸出無效：%(dev)s"

#: pypowervm/tasks/hdisk/_iscsi.py:78
#, python-format
msgid "Expected IQN: %(IQN)s not found on iscsi target %(host_ip)s"
msgstr "在 iSCSI 目標 %(host_ip)s 上找不到預期的 IQN：%(IQN)s"

#: pypowervm/tasks/monitor/util.py:421
msgid ""
"Metric data is not available.  This may be due to the metrics being recently "
"initialized."
msgstr ""
"無法使用度量資料。這可能是由於最近正在"
"起始設定度量。"

#: pypowervm/tests/test_i18n.py:33
msgid "This is a test"
msgstr "這是測試"

#: pypowervm/tests/test_i18n.py:36
msgid "This is a message for which a translation doesn't exist"
msgstr "一則訊息，針對此訊息不存在轉換"

#: pypowervm/utils/retry.py:203
#, python-format
msgid ""
"Attempt %(retry)d of total %(total)d for URI %(uri)s.  Error was a known "
"retry response code: %(resp_code)s"
msgstr ""
"對 URI %(uri)s 嘗試第 %(retry)d 次（總計 %(total)d 次）。錯誤是一個已知的"
"重試回應碼：%(resp_code)s"

#: pypowervm/utils/retry.py:210
#, python-format
msgid ""
"Attempt %(retry)d of %(total)d failed.  Will retry. The exception was:\n"
" %(except)s."
msgstr ""
"第 %(retry)d 次（總共 %(total)d 次）嘗試失敗。將重試。異常狀況為：\n"
" %(except)s."

#: pypowervm/utils/transaction.py:348
msgid "Must supply either EntryWrapper or EntryWrapperGetter."
msgstr "必須提供 EntryWrapper 或 EntryWrapperGetter。"

#: pypowervm/utils/transaction.py:374
msgid "Must supply a valid Subtask."
msgstr "必須提供有效的子作業。"

#: pypowervm/utils/transaction.py:378
#, python-format
msgid "Duplicate 'provides' name %s."
msgstr "「提供項目」名稱 %s 重複。"

#: pypowervm/utils/transaction.py:453
#, python-format
msgid "WrapperTask %s has no Subtasks; no-op execution."
msgstr "WrapperTask  %s 沒有子作業；沒有作業執行。"

#: pypowervm/utils/transaction.py:585
msgid "Must supply either a list of EntryWrappers or a FeedGetter."
msgstr "必須提供 EntryWrapper 的清單，或者提供 FeedGetter。"

#: pypowervm/utils/transaction.py:764
#, python-format
msgid "FeedTask %s has no Subtasks; no-op execution."
msgstr "FeedTask %s 沒有子作業；沒有作業執行。"

#: pypowervm/utils/transaction.py:789
#, python-format
msgid ""
"FeedTask %s experienced multiple exceptions. They are logged individually "
"below."
msgstr ""
"FeedTask %s 遇到多個異常狀況。下面逐個記載了"
"這些異常狀況。"

#: pypowervm/utils/validation.py:161
#, python-format
msgid ""
"Insufficient available %(res_name)s on host for virtual machine "
"'%(instance_name)s' (%(requested)s requested, %(avail)s available)"
msgstr ""
"針對下列虛擬機器，主機上可用的 %(res_name)s 不足："
"'%(instance_name)s'（要求 %(requested)s 個，但只有 %(avail)s 個可用）"

#: pypowervm/utils/validation.py:189
msgid "memory"
msgstr "記憶體）"

#: pypowervm/utils/validation.py:210
#, python-format
msgid ""
"The virtual machine must be powered off before changing the minimum or "
"maximum memory. Power off virtual machine %s and try again."
msgstr ""
"必須先關閉虛擬機器電源，然後才能變更"
"記憶體下限或上限。請關閉虛擬機器 %s 的電源，然後再試一次。"

#: pypowervm/utils/validation.py:215
#, python-format
msgid ""
"The virtual machine must be powered off before changing the expansion "
"factor. Power off virtual machine %s and try again."
msgstr ""
"必須先關閉虛擬機器電源，然後再變更"
"擴充因數。請關閉虛擬機器 %s 的電源，然後再試一次。"

#: pypowervm/utils/validation.py:302
msgid "CPUs"
msgstr "CPU 數目"

#: pypowervm/utils/validation.py:318
msgid "processing units"
msgstr "處理裝置數目"

#: pypowervm/utils/validation.py:359
#, python-format
msgid ""
"The virtual machine must be powered off before changing the minimum or "
"maximum processors. Power off virtual machine %s and try again."
msgstr ""
"必須先關閉虛擬機器電源，然後才能變更"
"處理器數目下限或上限。請關閉虛擬機器 %s 的電源，然後再試一次。"

#: pypowervm/utils/validation.py:369
#, python-format
msgid ""
"The virtual machine must be powered off before changing the minimum or "
"maximum processor units. Power off virtual machine %s and try again."
msgstr ""
"必須先關閉虛擬機器電源，然後才能變更"
"處理器裝置數目下限或上限。請關閉虛擬機器 %s 的電源，然後再試一次。"

#: pypowervm/utils/validation.py:385
#, python-format
msgid ""
"The virtual machine must be powered off before changing the processor "
"compatibility mode. Power off virtual machine %s and try again."
msgstr ""
"必須先關閉虛擬機器電源，然後才能變更"
"處理器相容模式。請關閉虛擬機器 %s 的電源，然後再試一次。"

#: pypowervm/utils/validation.py:393
#, python-format
msgid ""
"The virtual machine must be powered off before changing the processing mode. "
"Power off virtual machine %s and try again."
msgstr ""
"必須先關閉虛擬機器電源，然後才能變更處理模式。"
"請關閉虛擬機器 %s 的電源，然後再試一次。"

#: pypowervm/utils/validation.py:422
#, python-format
msgid ""
"The desired processors (%(vcpus)d) cannot be above the maximum allowed "
"processors per partition (%(max_allowed)d) for virtual machine "
"'%(instance_name)s'."
msgstr ""
"想要的處理器數目 (%(vcpus)d) 不能超過"
"下列虛擬機器之每個分割區容許的處理器數目上限 (%(max_allowed)d)："
"'%(instance_name)s'."

#: pypowervm/utils/validation.py:434
#, python-format
msgid ""
"The maximum processors (%(vcpus)d) cannot be above the maximum system "
"capacity processor limit (%(max_allowed)d) for virtual machine "
"'%(instance_name)s'."
msgstr ""
"處理器數目上限 (%(vcpus)d) 不得超過"
"下列虛擬機器的系統容量處理器上限 (%(max_allowed)d)："
"'%(instance_name)s'."

#: pypowervm/utils/validation.py:506
#, python-format
msgid ""
"The virtual machine must be powered off before changing the simplified "
"remote restart capability. Power off virtual machine %s and try again."
msgstr ""
"必須先關閉虛擬機器電源，然後才能變更"
"已簡化的遠端重新啟動功能。請關閉虛擬機器 %s 的電源，然後再試一次。"

#: pypowervm/wrappers/base_partition.py:424
msgid "Partition does not have an active RMC connection."
msgstr "分割區沒有作用中的 RMC 連線。"

#: pypowervm/wrappers/base_partition.py:427
#, python-format
msgid "Partition does not have an active DLPAR capability for %s."
msgstr "分割區沒有作用中的 DLPAR 功能適用於 %s。"

#: pypowervm/wrappers/base_partition.py:439
msgid "I/O"
msgstr "I/O"

#: pypowervm/wrappers/base_partition.py:449
msgid "Memory"
msgstr "記憶體"

#: pypowervm/wrappers/base_partition.py:459
msgid "Processors"
msgstr "處理器"

#: pypowervm/wrappers/base_partition.py:639
#, python-format
msgid "Invalid KeylockPos '%s'."
msgstr "KeylockPos '%s' 無效。"

#: pypowervm/wrappers/base_partition.py:650
#, python-format
msgid "Invalid BootMode '%s'."
msgstr "無效的 BootMode '%s'。"

#: pypowervm/wrappers/base_partition.py:1436
msgid "IOSlot.adapter is deprecated!  Use IOSlot.io_adapter instead."
msgstr "IOSlot.adapter 已遭到淘汰！請改用 IOSlot.io_adapter。"

#: pypowervm/wrappers/enterprise_pool.py:143
#, python-format
msgid ""
"Unable to determine master management console MTMS (machine type, model, "
"serial number) from %(identifier)s because no %(param)s was marked as the "
"master console for the pool."
msgstr ""
"無法根據 %(identifier)s 判定主要管理主控台 MTMS（機型、模型、"
"序號），因為未將任何 %(param)s 標示為"
"儲存區的主要主控台。"

#: pypowervm/wrappers/entry_wrapper.py:251
msgid "Cannot set uuid."
msgstr "無法設定 UUID。"

#: pypowervm/wrappers/entry_wrapper.py:443
#, python-format
msgid "Cannot convert %(property_name)s='%(value)s' in object %(pvmobject)s"
msgstr "在物件 %(pvmobject)s 中，無法轉換 %(property_name)s='%(value)s'"

#: pypowervm/wrappers/entry_wrapper.py:586
msgid ""
"Refusing set href over multiple links.\n"
"Path: %{path}s\n"
"Number of links found: %{nlinks}d"
msgstr ""
"拒絕透過多重鏈結設定 href。\n"
"路徑：%{path}s\n"
"找到的鏈結數目：%{nlinks}d"

#: pypowervm/wrappers/entry_wrapper.py:635
msgid "Refusing to construct and wrap an Element without a tag."
msgstr "拒絕建構及覆蓋不含標記的元素。"

#: pypowervm/wrappers/entry_wrapper.py:760
msgid "Response is missing 'entry' property."
msgstr "回應遺漏了 'entry' 內容。"

#: pypowervm/wrappers/entry_wrapper.py:774
#, python-format
msgid "Must supply a Response or Entry to wrap.  Got %s"
msgstr "必須提供 Response 或 Entry 才能覆蓋。取得 %s"

#: pypowervm/wrappers/entry_wrapper.py:861
msgid ""
"Developer error: specify 'parent' or ('parent_type' and 'parent_uuid') to "
"retrieve a CHILD object."
msgstr ""
"開發者錯誤：指定 'parent' 或 ('parent_type' and 'parent_uuid') 以"
"擷取 CHILD 物件。"

#: pypowervm/wrappers/entry_wrapper.py:866
msgid "Specify either 'uuid' or 'root_id' when requesting a ROOT object."
msgstr "在要求根物件時，指定 'uuid' 或 'root_id'。"

#: pypowervm/wrappers/entry_wrapper.py:879
msgid ""
"Both parent_type and parent_uuid are required when retrieving a CHILD feed "
"or entry."
msgstr ""
"擷取子項資訊來源或項目時，需要 parent_type 及"
"parent_uuid。"

#: pypowervm/wrappers/entry_wrapper.py:882
msgid "Specify the parent's UUID via the parent_uuid parameter."
msgstr "透過 parent_uuid 參數指定母項的 UUID。"

#: pypowervm/wrappers/entry_wrapper.py:886
msgid "Specify either 'uuid' or 'child_id' when requesting a CHILD object."
msgstr "在要求子物件時，指定 'uuid' 或 'child_id'。"

#: pypowervm/wrappers/entry_wrapper.py:1001
msgid "Parent UUID specified without parent type."
msgstr "指定的母項 UUID 不含親項類型。"

#: pypowervm/wrappers/entry_wrapper.py:1004
msgid "The search() method requires exactly one key=value argument."
msgstr "search() 方法只需要一個 key=value 引數。"

#: pypowervm/wrappers/entry_wrapper.py:1035
#, python-format
msgid "Wrapper class %(class)s does not support search key '%(key)s'."
msgstr "封套類別 %(class)s 不支援搜尋關鍵字 '%(key)s'。"

#: pypowervm/wrappers/entry_wrapper.py:1135
msgid ""
"The 'xag' parameter to EntryWrapper.update is deprecated!  At best, using it "
"will result in a no-op.  At worst, it will give you incurable etag mismatch "
"errors."
msgstr ""
"EntryWrapper.update 的 'xag' 參數已遭到淘汰！使用它的最好結果是"
"導致空作業。使用它的最差結果是將導致無法更正的 etag 不符"
"錯誤。"

#: pypowervm/wrappers/entry_wrapper.py:1403
msgid "No such child element."
msgstr "沒有此類子元素。"

#: pypowervm/wrappers/entry_wrapper.py:1464
msgid "Cannot set UUID on Wrapper with no Metadata."
msgstr "無法在沒有 meta 資料的封套上設定 UUID。"

#: pypowervm/wrappers/entry_wrapper.py:1469
#, python-format
msgid "uuid value not valid: %s"
msgstr "UUID 值無效：%s"

#: pypowervm/wrappers/entry_wrapper.py:1524
msgid "Must specify a Wrapper subclass."
msgstr "必須指定封套子類別。"

#: pypowervm/wrappers/entry_wrapper.py:1533
msgid "Must specify both parent class and parent UUID, or neither."
msgstr "必須同時指定母類別及母項 UUID，或者兩者皆不指定。"

#: pypowervm/wrappers/job.py:276
#, python-format
msgid "Job %(job_id)s monitoring for %(time)i seconds."
msgstr "正在監視工作 %(job_id)s %(time)i 秒。"

#: pypowervm/wrappers/job.py:327
#, python-format
msgid ""
"Issuing cancel request for job %(job_id)s. Will poll the job indefinitely "
"for termination."
msgstr ""
"正在對工作 %(job_id)s 發出取消要求。將無限期地輪詢工作"
"以進行終止。"

#: pypowervm/wrappers/job.py:343
#, python-format
msgid "Job %s not deleted. Job is in running state."
msgstr "未刪除工作 %s。工作處於執行中狀態。"

#: pypowervm/wrappers/logical_partition.py:169
msgid "LPAR is not in an active state."
msgstr "LPAR 未處於作用中狀態。"

#: pypowervm/wrappers/logical_partition.py:179
msgid "Target system does not have the IBM i LPAR Mobility Capability."
msgstr "目標系統沒有 IBM i LPAR 行動性功能。"

#: pypowervm/wrappers/logical_partition.py:183
msgid "IBM i LPAR does not have restricted I/O."
msgstr "IBM i LPAR 沒有受限的 I/O。"

#: pypowervm/wrappers/logical_partition.py:187
msgid "Source system does not have the IBM i LPAR Mobility Capability."
msgstr "來源系統沒有 IBM i LPAR 行動性功能。"

#: pypowervm/wrappers/logical_partition.py:191
msgid "LPAR does not have an active RMC connection."
msgstr "LPAR 沒有作用中的 RMC 連線。"

#: pypowervm/wrappers/logical_partition.py:194
msgid "LPAR is the management partition"
msgstr "LPAR 是管理分割區"

#: pypowervm/wrappers/logical_partition.py:198
msgid "LPAR is not available for LPM due to missing DLPAR capabilities."
msgstr "由於遺漏 DLPAR 功能，LPM 無法使用 LPAR。"

#: pypowervm/wrappers/logical_partition.py:215
#: pypowervm/wrappers/logical_partition.py:224
#: pypowervm/wrappers/logical_partition.py:232
msgid ""
"This is not the property you are looking for.  Use srr_enabled in a NovaLink "
"environment."
msgstr ""
"這不是您要尋找的內容。請在 NovaLink 環境中使用"
"srr_enabled。"

#: pypowervm/wrappers/logical_partition.py:268
#, python-format
msgid "Invalid IPLSrc '%s'."
msgstr "IPLSrc '%s' 無效。"

#: pypowervm/wrappers/managed_system.py:428
msgid "This property is deprecated!. Use pci_subsys_dev_id instead."
msgstr "此內容已淘汰！請改為使用 pci_subsys_dev_id。"

#: pypowervm/wrappers/managed_system.py:440
msgid "This property is deprecated!. Use pci_rev_id instead."
msgstr "此內容已淘汰！請改為使用 pci_rev_id。"

#: pypowervm/wrappers/managed_system.py:456
msgid "This property is deprecated!. Use pci_subsys_vendor_id instead."
msgstr "此內容已淘汰！請改為使用 pci_subsys_vendor_id。"

#: pypowervm/wrappers/managed_system.py:468
msgid "This property is deprecated!. Use drc_index instead."
msgstr "此內容已淘汰！請改為使用 drc_index。"

#: pypowervm/wrappers/managed_system.py:480
msgid "This property is deprecated!. Use drc_name instead."
msgstr "此內容已淘汰！請改為使用 drc_name。"

#: pypowervm/wrappers/storage.py:651
#, python-format
msgid ""
"PV had encoded pg83 descriptor \"%(pg83_raw)s\", but it failed to decode "
"(%(type_error)s)."
msgstr ""
"PV 具有已編碼的 pg83 描述子 \"%(pg83_raw)s\"，但無法解碼 "
"(%(type_error)s)."

#: pypowervm/wrappers/virtual_io_server.py:163
msgid ""
"The 'xags' property of the VIOS EntryWrapper class is deprecated!  Please "
"use values from pypowervm.const.XAG instead."
msgstr ""
"VIOS EntryWrapper 類別的 'xags' 內容已遭到淘汰！"
"請改用 pypowervm.const.XAG 中的值。"

#: pypowervm/wrappers/virtual_io_server.py:400
msgid "Partition of VIOS type is not LPM capable"
msgstr "VIOS 類型的分割區不支援 LPM"

#: pypowervm/wrappers/virtual_io_server.py:655
msgid "Can't specify target device LUA without a backing storage device!"
msgstr "在沒有支援儲存裝置的情況下，無法指定目標裝置 LUA！"

# ENGL1SH_VERS10N 13712_53 DO NOT REMOVE OR CHANGE THIS LINE
# T9N_SRC_ID 23
# T9N_SH1P_STR1NG PV133AAP001 2
