# Translations template for pypowervm.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the pypowervm project.
# Automatically generated, 2015.
#
msgid ""
msgstr ""
"Project-Id-Version: pypowervm 0.0.3.dev270\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-10-06 13:53-0500\n"
"PO-Revision-Date: 2015-10-06 13:53-0500\n"
"Last-Translator: Automatically generated\n"
"Language-Team: none\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.0\n"

#: pypowervm/exceptions.py:116
#, python-format
msgid ""
"Unable to derive the appropriate physical FC port for WWPN %(wwpn)s.  The"
" VIOS Extended Attribute Groups may have been insufficient.  The VIOS URI"
" for the query was %(vio_uri)s."
msgstr ""
"Не удалось получить подходящий физический порт FC для WWPN %(wwpn)s. Возможно,"
" недостаточно расширенных групп атрибутов VIOS. URI VIOS "
" для запроса: %(vio_uri)s."

#: pypowervm/exceptions.py:122
#, python-format
msgid "Element not found: %(element_type)s %(element)s"
msgstr "Не найден элемент: %(element_type)s %(element)s"

#: pypowervm/exceptions.py:126
#, python-format
msgid "LPAR not found: %(lpar_name)s"
msgstr "Не найден LPAR: %(lpar_name)s"

#: pypowervm/exceptions.py:130
#, python-format
msgid "The '%(operation_name)s' operation failed. %(error)s"
msgstr "Сбой операции %(operation_name)s. %(error)s"

#: pypowervm/exceptions.py:134
#, python-format
msgid ""
"The '%(operation_name)s' operation failed. Failed to complete the task in"
" %(seconds)d seconds."
msgstr ""
"Сбой операции '%(operation_name)s'. Не удалось выполнить задачу за "
" %(seconds)d сек."

#: pypowervm/exceptions.py:139
#, python-format
msgid "Failed to power off Virtual Machine %(lpar_nm)s: %(reason)s"
msgstr "Не удалось выключить виртуальную машину %(lpar_nm)s: %(reason)s"

#: pypowervm/exceptions.py:143
#, python-format
msgid "Failed to power on Virtual Machine %(lpar_nm)s: %(reason)s"
msgstr "Не удалось включить виртуальную машину %(lpar_nm)s: %(reason)s"

#: pypowervm/exceptions.py:147
#, python-format
msgid ""
"Unable to remove VLAN %(vlan_id)d as it is the Primary VLAN Identifier on"
" a different Network Bridge."
msgstr ""
"Не удалось удалить VLAN %(vlan_id)d, поскольку это идентификатор основной VLAN"
" в другом сетевом мосте."

#: pypowervm/exceptions.py:152
#, python-format
msgid ""
"Unable to provision VLAN %(vlan_id)d.  It appears to be contained on "
"device '%(dev_name)s' on Virtual I/O Server %(vios)s.  That device is not"
" connected to any Network Bridge (Shared Ethernet Adapter).  Please "
"manually remove the device or add it to the Network Bridge before "
"continuing."
msgstr ""
"Не удалось предоставить VLAN %(vlan_id)d. Возможно, она содержится на "
"устройстве '%(dev_name)s' на виртуальном сервере ввода-вывода %(vios)s. Это устройство не"
"подключено ни к какому сетевому мосту (общий адаптер Ethernet). "
"Удалите устройство вручную или добавьте его к сетевому мосту для "
"продолжения."

#: pypowervm/exceptions.py:161
#, python-format
msgid ""
"A Logical Unit with name %(lu_name)s already exists on Shared Storage "
"Pool %(ssp_name)s."
msgstr ""
"Логический накопитель с именем %(lu_name)s уже существует в общем пуле "
"памяти %(ssp_name)s."

#: pypowervm/exceptions.py:166
msgid ""
"Unable to find a physical port to map a virtual Fibre Channel port to.  "
"This is due to either a Virtual I/O Server being unavailable, or improper"
" port specification for the physical Fibre Channel ports."
msgstr ""
"Не удалось найти физический порт для связывания виртуального порта Fibre Channel.  "
"Возможные причины: нет доступа к VIOS или неправильная"
" спецификация физических портов Fibre Channel."

#: pypowervm/exceptions.py:173
msgid ""
"Unable to start the console to the Virtual Machine.  The pypowervm API is"
" running in a non-local mode.  The console can only be deployed when "
"pypowervm is co-located with the PowerVM API."
msgstr ""
"Не удалось запустить консоль на виртуальной машине.  API pypowervm работает"
" не в локальном режиме. Развернуть консоль можно только если "
"pypowervm работает вместе с API PowerVM."

#: pypowervm/exceptions.py:180
#, python-format
msgid "WrapperTask %(name)s has no subtasks!"
msgstr "WrapperTask %(name)s не имеет подзадач!"

#: pypowervm/exceptions.py:184
msgid "FeedTask can't have an empty feed."
msgstr "FeedTask не может содержать пустую ленту."

#: pypowervm/exceptions.py:188
#, python-format
msgid "OS unable to read file %(access_file)s."
msgstr "ОС не удалось прочитать файл %(access_file)s."

#: pypowervm/exceptions.py:192
#, python-format
msgid "OS able to read file %(access_file)s, but encountered an access error."
msgstr "При чтении файла %(access_file)s операционной системой произошла ошибка доступа."

#: pypowervm/exceptions.py:197
#, python-format
msgid "The migration task failed. %(error)s"
msgstr "Сбой задачи миграции. %(error)s"

#: pypowervm/exceptions.py:201
#, python-format
msgid "No load source found for VM %(vm_name)s"
msgstr "Не найден источник загрузки для ВМ %(vm_name)s"

#: pypowervm/util.py:122
#, python-format
msgid ""
"Proposed extended attribute group '%(arg_xag)s' doesn't match existing "
"extended attribute group '%(path_xag)s'"
msgstr ""
"Предложенная группа расширенных атрибутов '%(arg_xag)s' не совпадает с существующей "
"группой расширенных атрибутов '%(path_xag)s'"

#: pypowervm/util.py:391
#, python-format
msgid "Prefix and suffix together may not be more than %d characters."
msgstr "Общая длина префикса и суффикса не может превышать %d символов."

#: pypowervm/util.py:396
msgid "Total length must be at least 1 character."
msgstr "Общая длина должна быть не меньше 1 символа."

#: pypowervm/util.py:419
msgid "The name parameter must be at least one character long."
msgstr "Длина параметра имени должна быть не меньше одного символа."

#: pypowervm/util.py:422
#, python-format
msgid "The name parameter must not exceed %d characters when trunk_ok is False."
msgstr "Длина параметра имени не должна превышать %d символов, если для параметра trunk_ok указано значение False."

#: pypowervm/helpers/log_helper.py:82
#, python-format
msgid "REQUEST: %s"
msgstr "ЗАПРОС: %s"

#: pypowervm/helpers/log_helper.py:102
#, python-format
msgid "RESPONSE: %s"
msgstr "ОТВЕТ: %s"

#: pypowervm/tasks/cna.py:77
#, python-format
msgid "Unable to find the Virtual Switch %s on the system."
msgstr "Не удалось найти виртуальный коммутатор %s в системе."

#: pypowervm/tasks/hdisk.py:182
#, python-format
msgid ""
"hdisk discovery failed; will scrub stale storage for LPAR IDs %s and "
"retry."
msgstr ""
"Ошибка поиска жестких дисков; будет очищена старая память для ИД LPAR %s и "
"выполнена повторная попытка."

#: pypowervm/tasks/hdisk.py:324
#, python-format
msgid "LUA Recovery Successful. Device Found: %s"
msgstr "Восстановление LUA успешно завершено. Найденное устройство: %s"

#: pypowervm/tasks/hdisk.py:328
#, python-format
msgid "ITL Error encountered: %s"
msgstr "Ошибка ITL: %s"

#: pypowervm/tasks/hdisk.py:330
#, python-format
msgid "%s Device is currently in use."
msgstr "Устройство %s в данный момент занято."

#: pypowervm/tasks/hdisk.py:332
#, python-format
msgid "%s Device discovered with unknown UDID."
msgstr "Обнаружено устройство %s с неизвестным UDID."

#: pypowervm/tasks/hdisk.py:334
#, python-format
msgid "Failed to Discover the Device : %s"
msgstr "Не удалось найти устройство: %s"

#: pypowervm/tasks/hdisk.py:404
#, python-format
msgid "CLIRunner Error: %s"
msgstr "Ошибка CLIRunner: %s"

#: pypowervm/tasks/memory.py:101
#, python-format
msgid ""
"Error obtaining host memory overhead for host with UUID '%(host)s': "
"%(error)s."
msgstr ""
"Ошибка получения дополнительной нагрузки для памяти хоста с UUID '%(host)s': "
"%(error)s."

#: pypowervm/tasks/power.py:159 pypowervm/tasks/power.py:168
#, python-format
msgid "Error: %s"
msgstr "Ошибка: %s"

#: pypowervm/tasks/power.py:200
#, python-format
msgid ""
"Error invalidating adapter cache for LPAR  %(lpar_name) with UUID "
"%(lpar_uuid)s: %(exc)s"
msgstr ""
"Ошибка при аннулировании кэша адаптера для LPAR  %(lpar_name) с UUID "
"%(lpar_uuid)s: %(exc)s"

#: pypowervm/tasks/scsi_mapper.py:38
msgid "Retrying modification of SCSI Mapping."
msgstr "Повторная попытка изменения связей SCSI."

#: pypowervm/tasks/scsi_mapper.py:89
#, python-format
msgid ""
"Found existing mapping of %(stg_type)s storage element %(stg_name)s from "
"Virtual I/O Server %(vios_name)s to client LPAR %(lpar_uuid)s."
msgstr ""
"Обнаружена существующая привязка элемента хранения данных %(stg_type)s с именем %(stg_name)s из "
"VIOS %(vios_name)s с клиентским LPAR %(lpar_uuid)s."

#: pypowervm/tasks/scsi_mapper.py:107
#, python-format
msgid ""
"Creating mapping of %(stg_type)s storage element %(stg_name)s from "
"Virtual I/O Server %(vios_name)s to client LPAR %(lpar_uuid)s."
msgstr ""
"Создание привязки элемента хранения данных %(stg_type)s с именем %(stg_name)s из "
"VIOS %(vios_name)s с клиентским LPAR %(lpar_uuid)s."

#: pypowervm/tasks/scsi_mapper.py:371
msgid "Must not specify both match_func and stg_elem."
msgstr "Одновременно нельзя указывать match_func и stg_elem."

#: pypowervm/tasks/storage.py:287
#, python-format
msgid "Unable to cleanup after file upload. File uuid: %s"
msgstr "Не удается выполнить очистку после передачи файла. uuid файла: %s"

#: pypowervm/tasks/storage.py:385
#, python-format
msgid ""
"Linked clone Logical Unit %(luname)s (UDID %(udid)s) has no backing image"
" LU.  It should probably be deleted."
msgstr ""
"Связанный дубликат логического накопителя %(luname)s (UDID %(udid)s) не содержит образа базового "
"логического накопителя. Возможно, он будет удален."

#: pypowervm/tasks/storage.py:430
msgid "Unable to locate new vDisk on file upload."
msgstr "Не удалось найти новый vDisk при передаче файла."

#: pypowervm/tasks/storage.py:480
#, python-format
msgid "Deleting virtual disk %(vdisk)s from volume group %(vg)s"
msgstr "Удаление виртуального диска %(vdisk)s из группы томов %(vg)s"

#: pypowervm/tasks/storage.py:504
#, python-format
msgid "Deleting virtual optical device %(vopt)s from volume group %(vg)s"
msgstr "Удаление виртуального оптического накопителя %(vopt)s из группы томов %(vg)s"

#: pypowervm/tasks/storage.py:559
#, python-format
msgid "Removing LU %(lu_name)s from SSP %(ssp_name)s"
msgstr "Удаление LU %(lu_name)s из SSP %(ssp_name)s"

#: pypowervm/tasks/storage.py:580
#, python-format
msgid ""
"Removing Image LU %(lu_name)s from SSP %(ssp_name)s because it is no "
"longer in use."
msgstr ""
"Удаление LU образа %(lu_name)s из SSP %(ssp_name)s, поскольку он "
"больше не используется."

#: pypowervm/tasks/storage.py:625
#, python-format
msgid ""
"Removing %(num_maps)d orphan %(stg_type)s mappings from VIOS "
"%(vios_name)s."
msgstr ""
"Удаление %(num_maps)d изолированных связей %(stg_type)s из VIOS "
"%(vios_name)s."

#: pypowervm/tasks/storage.py:652
#, python-format
msgid ""
"Removing %(num_maps)d %(stg_type)s mappings associated with LPAR ID "
"%(lpar_id)d from VIOS %(vios_name)s."
msgstr ""
"Удаление %(num_maps)d %(stg_type)s связей, связанных с ИД LPAR "
"%(lpar_id)d, из VIOS %(vios_name)s."

#: pypowervm/tasks/storage.py:725
#, python-format
msgid "Unexpected storage element type %s."
msgstr "Непредвиденный тип элемента хранения данных %s."

#: pypowervm/tasks/storage.py:742
#, python-format
msgid ""
"Scrubbing the following %(vdcount)d Virtual Disks from VIOS %(vios)s: "
"%(vdlist)s"
msgstr ""
"Удаление следующих %(vdcount)d виртуальных дисков из VIOS %(vios)s: "
"%(vdlist)s"

#: pypowervm/tasks/storage.py:750
#, python-format
msgid ""
"Scrubbing the following %(vocount)d Virtual Opticals from VIOS %(vios)s: "
"%(volist)s"
msgstr ""
"Удаление следующих %(vocount)d виртуальных оптических накопителей из VIOS %(vios)s: "
"%(volist)s"

#: pypowervm/tasks/storage.py:814
#, python-format
msgid ""
"Skipping scrub of %(stg_type)s mappings from VIOS %(vios_name)s for the "
"following LPAR IDs because those LPARs exist: %(lpar_ids)s"
msgstr ""
"Пропуск очистки связей %(stg_type)s из VIOS %(vios_name)s для "
"следующих ИД LPAR, так как эти LPAR существуют: %(lpar_ids)s"

#: pypowervm/tasks/vfc_mapper.py:379
#, python-format
msgid "Detected a stale mapping for LPAR with UUID %s."
msgstr "Обнаружена устаревшая связь для LPAR с UUID %s."

#: pypowervm/tasks/vfc_mapper.py:583
#, python-format
msgid ""
"Unable to find appropriate VIOS.  The payload provided was likely "
"insufficient.  The payload data is:\n"
" %s)"
msgstr ""
"Не удалось найти подходящий VIOS. Возможно, полезная нагрузка оказалась "
"недостаточной. Данные полезной нагрузки:\n"
" %s)"

#: pypowervm/tasks/vterm.py:61
msgid "Unable to close vterm."
msgstr "Не удалось закрыть vterm."

#: pypowervm/tests/test_i18n.py:33
msgid "This is a test"
msgstr "Это тест"

#: pypowervm/tests/test_i18n.py:36
msgid "This is a message for which a translation doesn't exist"
msgstr "Это сообщение, для которого не существует перевод"

#: pypowervm/utils/retry.py:152
#, python-format
msgid ""
"Attempt %(retry)d of total %(total)d for URI %(uri)s.  Error was a known "
"retry response code: %(resp_code)s"
msgstr ""
"Попытка %(retry)d из %(total)d для URI %(uri)s. Ошибка: "
"известный код ответа повторной попытки: %(resp_code)s"

#: pypowervm/utils/retry.py:159
#, python-format
msgid ""
"Attempt %(retry)d of %(total)d failed.  Will retry. The exception was:\n"
" %(except)s."
msgstr ""
"Попытка %(retry)d из %(total)d не удалась. Будет выполнен повтор операции. Исключительная ситуация:\n"
" %(except)s."

#: pypowervm/utils/transaction.py:311
msgid "Must supply either EntryWrapper or EntryWrapperGetter."
msgstr "Следует указать EntryWrapper или EntryWrapperGetter."

#: pypowervm/utils/transaction.py:337
msgid "Must supply a valid Subtask."
msgstr "Необходимо указать допустимую подзадачу."

#: pypowervm/utils/transaction.py:341
#, python-format
msgid "Duplicate 'provides' name %s."
msgstr "Повторяющееся имя 'provides' %s."

#: pypowervm/utils/transaction.py:416
#, python-format
msgid "WrapperTask %s has no Subtasks; no-op execution."
msgstr "WrapperTask %s не имеет подзадач; выполнение пустой операции."

#: pypowervm/utils/transaction.py:541
msgid "Must supply either a list of EntryWrappers or a FeedGetter."
msgstr "Необходимо указать список EntryWrappers или FeedGetter."

#: pypowervm/utils/transaction.py:720
#, python-format
msgid "FeedTask %s has no Subtasks; no-op execution."
msgstr "FeedTask %s не имеет подзадач; выполнение пустой операции."

#: pypowervm/utils/validation.py:160
#, python-format
msgid ""
"Insufficient available %(res_name)s on host for virtual machine "
"'%(instance_name)s' (%(requested)s requested, %(avail)s available)"
msgstr ""
"Недостаточно %(res_name)s на хосте для виртуальной машины "
"'%(instance_name)s' (запрошено %(requested)s, доступно %(avail)s)"

#: pypowervm/utils/validation.py:187
msgid "memory"
msgstr "память"

#: pypowervm/utils/validation.py:207
#, python-format
msgid ""
"The virtual machine must be powered off before changing the minimum or "
"maximum memory. Power off virtual machine %s and try again."
msgstr ""
"Прежде чем изменять минимальный или максимальный объем "
"памяти, виртуальную машину следует выключить. Выключите виртуальную машину %s и повторите попытку."

#: pypowervm/utils/validation.py:292
msgid "CPUs"
msgstr "Процессоры"

#: pypowervm/utils/validation.py:308
msgid "processing units"
msgstr "логические процессоры"

#: pypowervm/utils/validation.py:349
#, python-format
msgid ""
"The virtual machine must be powered off before changing the minimum or "
"maximum processors. Power off virtual machine %s and try again."
msgstr ""
"Прежде чем изменять минимальное или максимальное количество "
"процессоров, следует выключить виртуальную машину. Выключите виртуальную машину %s и повторите попытку."

#: pypowervm/utils/validation.py:359
#, python-format
msgid ""
"The virtual machine must be powered off before changing the minimum or "
"maximum processor units. Power off virtual machine %s and try again."
msgstr ""
"Прежде чем изменять минимальное или максимальное количество "
"логических процессоров, виртуальную машину следует выключить. Выключите виртуальную машину %s и повторите попытку."

#: pypowervm/utils/validation.py:375
#, python-format
msgid ""
"The virtual machine must be powered off before changing the processor "
"compatibility mode. Power off virtual machine %s and try again."
msgstr ""
"Прежде чем изменять режим совместимости процессора, виртуальную машину "
"следует выключить. Выключите виртуальную машину %s и повторите попытку."

#: pypowervm/utils/validation.py:383
#, python-format
msgid ""
"The virtual machine must be powered off before changing the processing "
"mode. Power off virtual machine %s and try again."
msgstr ""
"Прежде чем изменять режим процессора, виртуальную машину "
"следует выключить. Выключите виртуальную машину %s и повторите попытку."

#: pypowervm/utils/validation.py:412
#, python-format
msgid ""
"The desired processors (%(vcpus)d) cannot be above the maximum allowed "
"processors per partition (%(max_allowed)d) for virtual machine "
"'%(instance_name)s'."
msgstr ""
"Предпочитаемое количество процессоров (%(vcpus)d) не должно превышать максимально допустимое "
"количество процессоров на раздел (%(max_allowed)d) для виртуальной машины "
"'%(instance_name)s'."

#: pypowervm/utils/validation.py:424
#, python-format
msgid ""
"The maximum processors (%(vcpus)d) cannot be above the maximum system "
"capacity processor limit (%(max_allowed)d) for virtual machine "
"'%(instance_name)s'."
msgstr ""
"Максимальное количество процессоров (%(vcpus)d) не должно превышать "
"ограничение на количество процессоров (%(max_allowed)d) для виртуальной машины "
"'%(instance_name)s'."

#: pypowervm/utils/validation.py:442
#, python-format
msgid "The shared processor pool for %s must be DefaultPool."
msgstr "В качестве общего пула процессоров для %s должен выступать DefaultPool."

#: pypowervm/utils/validation.py:450
#, python-format
msgid "The shared processor pool for %s cannot be changed."
msgstr "Изменять общий пул процессоров для %s нельзя."

#: pypowervm/utils/validation.py:513
#, python-format
msgid ""
"The virtual machine must be powered off before changing the simplified "
"remote restart capability. Power off virtual machine %s and try again."
msgstr ""
"Прежде чем изменять функцию упрощенного удаленного перезапуска, "
"виртуальную машину следует выключить. Выключите виртуальную машину %s и повторите попытку."

#: pypowervm/wrappers/base_partition.py:470
#, python-format
msgid "Invalid KeylockPos '%s'."
msgstr "Недопустимый KeylockPos '%s'."

#: pypowervm/wrappers/entry_wrapper.py:258
#, python-format
msgid "Cannot convert %(property_name)s='%(value)s' in object %(pvmobject)s"
msgstr "Не удалось преобразовать %(property_name)s='%(value)s' в объект %(pvmobject)s"

#: pypowervm/wrappers/entry_wrapper.py:337
#, python-format
msgid "The expected parameter of %(param)s was not found in %(identifier)s"
msgstr "Не найден ожидаемый параметр %(param)s в %(identifier)s"

#: pypowervm/wrappers/entry_wrapper.py:386
msgid ""
"Refusing set href over multiple links.\n"
"Path: %{path}s\n"
"Number of links found: %{nlinks}d"
msgstr ""
"Нельзя указать href для нескольких ссылок. \n"
"Путь: %{path}s\n"
"Количество найденных ссылок: %{nlinks}d"

#: pypowervm/wrappers/entry_wrapper.py:430
msgid "Refusing to construct and wrap an Element without a tag."
msgstr "Нельзя создать и добавить в оболочку без тега."

#: pypowervm/wrappers/entry_wrapper.py:554
msgid "Response is missing 'entry' property."
msgstr "В ответе отсутствует свойство 'entry'."

#: pypowervm/wrappers/entry_wrapper.py:568
#, python-format
msgid "Must supply a Response or Entry to wrap.  Got %s"
msgstr "Необходимо указать ответ или сущностный объект для размещения. Получено %s"

#: pypowervm/wrappers/entry_wrapper.py:667
msgid "Parent UUID specified without parent type."
msgstr "Родительский UUID указан без родительского типа."

#: pypowervm/wrappers/entry_wrapper.py:670
msgid "The search() method requires exactly one key=value argument."
msgstr "Для метода search() требуется один аргумент ключ=значение."

#: pypowervm/wrappers/entry_wrapper.py:698
#, python-format
msgid "Wrapper class %(class)s does not support search key '%(key)s'."
msgstr "Класс оболочки %(class)s не поддерживает ключ поиска '%(key)s'."

#: pypowervm/wrappers/entry_wrapper.py:774
msgid "Must specify both parent type and UUID, or neither."
msgstr "Необходимо указать родительский тип и UUID либо ни одно из этих значений."

#: pypowervm/wrappers/entry_wrapper.py:851
msgid "Cannot set uuid."
msgstr "Не удалось указать uuid."

#: pypowervm/wrappers/entry_wrapper.py:1041
msgid "No such child element."
msgstr "Нет такого дочернего элемента."

#: pypowervm/wrappers/entry_wrapper.py:1102
msgid "Cannot set UUID on Wrapper with no Metadata."
msgstr "Невозможно указать UUID для оболочки без метаданных."

#: pypowervm/wrappers/entry_wrapper.py:1107
#, python-format
msgid "uuid value not valid: %s"
msgstr "Недопустимое значение uuid: %s"

#: pypowervm/wrappers/entry_wrapper.py:1155
msgid "Must specify a Wrapper subclass."
msgstr "Необходимо указать подкласс Wrapper."

#: pypowervm/wrappers/entry_wrapper.py:1162
msgid "Must specify both parent class and parent UUID, or neither."
msgstr "Необходимо указать и родительский класс, и родительский UUID, или не указывать ни одного из этих значений."

#: pypowervm/wrappers/job.py:281
#, python-format
msgid "Job %(job_id)s failed to cancel after %(timeout)s seconds."
msgstr "Не удалось отменить задание %(job_id)s через %(timeout)s с."

#: pypowervm/wrappers/job.py:302
#, python-format
msgid "Job %s not deleted. Job is in running state."
msgstr "Задание %s не удалено. Задание находится в состоянии выполнения."

#: pypowervm/wrappers/logical_partition.py:139
#: pypowervm/wrappers/logical_partition.py:208
msgid "LPAR does not have an active RMC connection."
msgstr "В LPAR нет активных соединений RMC."

#: pypowervm/wrappers/logical_partition.py:141
#, python-format
msgid "LPAR does not have an active DLPAR capability for %s."
msgstr "В LPAR отсутствует активная функция DLPAR для %s."

#: pypowervm/wrappers/logical_partition.py:153
msgid "I/O"
msgstr "Ресурсы ввода-вывода"

#: pypowervm/wrappers/logical_partition.py:163
msgid "Memory"
msgstr "Память"

#: pypowervm/wrappers/logical_partition.py:173
msgid "Processors"
msgstr "Процессоры"

#: pypowervm/wrappers/logical_partition.py:190
msgid "LPAR is not in an active state."
msgstr "LPAR не находится в активном состоянии."

#: pypowervm/wrappers/logical_partition.py:196
msgid "IBM i LPAR does not have restricted I/O."
msgstr "В LPAR IBM i нет ограниченных ресурсов ввода-вывода."

#: pypowervm/wrappers/logical_partition.py:200
msgid "Source system does not have the IBM i LPAR Mobility Capability."
msgstr "Исходная система не поддерживает мобильные LPAR IBM i."

#: pypowervm/wrappers/logical_partition.py:205
msgid "IBM i LPAR Live Migration is only supported on POWER7 and higher systems."
msgstr "Оперативная миграция LPAR IBM i поддерживается только в системах POWER7 и выше."

#: pypowervm/wrappers/logical_partition.py:212
msgid "LPAR is not available for LPM due to missing DLPAR capabilities."
msgstr "LPAR недоступен для LPM, поскольку он не поддерживает DLPAR."

#: pypowervm/wrappers/logical_partition.py:273
#, python-format
msgid "Invalid IPLSrc '%s'."
msgstr "Недопустимое значение IPLSrc '%s'."

#: pypowervm/wrappers/storage.py:437
#, python-format
msgid ""
"PV had encoded pg83 descriptor \"%(pg83_raw)s\", but it failed to decode "
"(%(type_error)s)."
msgstr ""
"PV содержал зашифрованный дескриптор pg83 \"%(pg83_raw)s\", но его не удалось расшифровать "
"(%(type_error)s)."

