# Translations template for pypowervm.
# Copyright (C) 2016 IBM Corp.
# This file is distributed under the same license as the pypowervm project.
# Automatically generated, 2016.
#
msgid ""
msgstr ""
"Project-Id-Version: pypowervm 1.0.1.dev127\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2016-04-14 02:54-0400\n"
"PO-Revision-Date: 2016-04-14 02:54-0400\n"
"Last-Translator: Automatically generated\n"
"Language-Team: none\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.3.2\n"

#: pypowervm/adapter.py:126
#, python-format
msgid "Invalid protocol \"%s\""
msgstr "Protocolo no válido \"%s\""

#: pypowervm/adapter.py:132
msgid "Unencrypted communication with PowerVM! Revert configuration to https."
msgstr "Comunicación sin cifrar con PowerVM. Revierta la configuración ahttps."

#: pypowervm/adapter.py:146
msgid "Calculating default audit memento failed, using 'default'."
msgstr "Se ha encontrado un error en el cálculo del memento de auditoría predeterminado, se va a utilizar 'default'."

#: pypowervm/adapter.py:181
msgid "Local authentication not supported on HMC."
msgstr "La autenticación local no está soportada en la HMC."

#: pypowervm/adapter.py:200
#, python-format
msgid "Setting up event listener for %s"
msgstr "Configurando el escucha de sucesos para %s"

#: pypowervm/adapter.py:239
#, python-format
msgid "Unexpected filehandle on %s request"
msgstr "Descriptor de archivo inesperado en la solicitud %s."

#: pypowervm/adapter.py:292
#, python-format
msgid "Unexpected error for %(meth)s %(url)s"
msgstr "Error inesperado para %(meth)s %(url)s."

#: pypowervm/adapter.py:294
#, python-format
msgid "Unexpected error: %(class)s for %(method)s %(url)s: %(excp)s"
msgstr "Error inesperado %(class)s para %(method)s %(url)s: %(excp)s"

#: pypowervm/adapter.py:332
msgid ""
"Re-login has been deemed unsafe. This Session instance should no longer "
"be used."
msgstr ""
"El nuevo inicio de sesión se ha considerado inseguro. Esta instancia de la sesión no debe "
"utilizarse más."

#: pypowervm/adapter.py:342
#, python-format
msgid "Attempting re-login %s"
msgstr "Intentando volver a iniciar sesión %s"

#: pypowervm/adapter.py:353
#, python-format
msgid ""
"Re-login 401, response body:\n"
"%s"
msgstr ""
"401 de reinicio de sesión, cuerpo de respuesta:\n"
"%s"

#: pypowervm/adapter.py:358
#, python-format
msgid ""
"Re-login failed, resp body:\n"
"%s"
msgstr ""
"Se ha encontrado un error en el reinicio de sesión, cuerpo de respuesta:\n"
"%s"

#: pypowervm/adapter.py:362
#, python-format
msgid ""
"Re-login failed:\n"
"%s"
msgstr ""
"Se ha encontrado un error en el reinicio de sesión:\n"
"%s"

#: pypowervm/adapter.py:381
#, python-format
msgid ""
"Re-attempt failed with another 401, response body:\n"
"%s"
msgstr ""
"Se ha encontrado un error en el reinicio de sesión con otro 401, cuerpo de respuesta:\n"
"%s"

#: pypowervm/adapter.py:384
#, python-format
msgid "suspicious HTTP 401 response for %(method)s %(path)s: token is brand new"
msgstr "respuesta HTTP 401 sospechosa para %(method)s %(path)s: la señal es completamente nueva"

#: pypowervm/adapter.py:416
#, python-format
msgid "Session logging on %s"
msgstr "Iniciando sesión en %s"

#: pypowervm/adapter.py:478
msgid "Failed to parse a session token from the PowerVM response."
msgstr "Se ha encontrado un error en el análisis de una señal de sesión procedente de la respuesta de PowerVM."

#: pypowervm/adapter.py:480 pypowervm/adapter.py:496
#, python-format
msgid " Body= %s"
msgstr " Cuerpo = %s"

#: pypowervm/adapter.py:494
msgid "Failed to parse a session file path from the PowerVM response."
msgstr "Se ha encontrado un error en el análisis de una ruta de archivo de sesión procedente de la respuesta de PowerVM."

#: pypowervm/adapter.py:508
#, python-format
msgid "Token file %s didn't contain a readable session token."
msgstr "El archivo de señal %s no contenía ninguna señal de sesión legible."

#: pypowervm/adapter.py:518
#, python-format
msgid "Session logging off %s"
msgstr "Cerrando sesión de %s"

#: pypowervm/adapter.py:523
msgid "Problem logging off.  Ignoring."
msgstr "Problema al cerrar sesión. Se ignorará."

#: pypowervm/adapter.py:561
msgid "Failed to register for events.  Events will not be used."
msgstr "Se ha encontrado un error en el registro de sucesos. Los sucesos no se utilizarán."

#: pypowervm/adapter.py:642
msgid "job must be a JobRequest element"
msgstr "el trabajo debe ser un elemento JobRequest"

#: pypowervm/adapter.py:646
msgid "JobRequest is missing OperationName"
msgstr "a JobRequest le falta OperationName"

#: pypowervm/adapter.py:660 pypowervm/adapter.py:866 pypowervm/adapter.py:926
#: pypowervm/adapter.py:1022
#, python-format
msgid "path=%s is not a PowerVM API reference"
msgstr "la ruta=%s no es una referencia de API de PowerVM"

#: pypowervm/adapter.py:1037 pypowervm/adapter.py:1054
msgid "Invalid file descriptor"
msgstr "Descriptor de archivo no válido"

#: pypowervm/adapter.py:1179 pypowervm/adapter.py:1207
#: pypowervm/adapter.py:1222
msgid "Expected root_id"
msgstr "root_id esperado"

#: pypowervm/adapter.py:1181
msgid "Expected child_type"
msgstr "child_type esperado"

#: pypowervm/adapter.py:1185 pypowervm/adapter.py:1211
#: pypowervm/adapter.py:1216
#, python-format
msgid "Unexpected suffix_type=%s"
msgstr "suffix_type inesperado=%s"

#: pypowervm/adapter.py:1188 pypowervm/adapter.py:1219
msgid "Expected suffix_parm"
msgstr "suffix_parm esperado"

#: pypowervm/adapter.py:1190 pypowervm/adapter.py:1209
#: pypowervm/adapter.py:1224
msgid "Expected child_id"
msgstr "child_id esperado"

#: pypowervm/adapter.py:1193 pypowervm/adapter.py:1202
msgid "Unexpected child_id"
msgstr "child_id inesperado"

#: pypowervm/adapter.py:1195 pypowervm/adapter.py:1204
msgid "Unexpected root_id"
msgstr "root_id inesperado"

#: pypowervm/adapter.py:1226
#, python-format
msgid "Unexpected req_method=%s"
msgstr "req_method inesperado=%s"

#: pypowervm/adapter.py:1345
#, python-format
msgid "Error parsing XML response from PowerVM: %s"
msgstr "Error en el análisis de la respuesta XML procedente de PowerVM: %s"

#: pypowervm/adapter.py:1358
msgid "Response is not an Atom feed/entry"
msgstr "La respuesta no es un feed ni una entrada Atom."

#: pypowervm/adapter.py:1369
msgid "Unexpected HTTP 204 for request"
msgstr "HTTP 204 inesperado para la solicitud"

#: pypowervm/adapter.py:1377
msgid "Unexpectedly empty response body"
msgstr "Cuerpo de respuesta vacío de forma inesperada"

#: pypowervm/adapter.py:1380
#, python-format
msgid ""
"%(err_reason)s:\n"
"request headers: %(reqheaders)s\n"
"\n"
"request body: %(reqbody)s\n"
"\n"
"response headers: %(respheaders)s\n"
"\n"
"response body: %(respbody)s"
msgstr ""
"%(err_reason)s: \n"
"cabeceras de solicitud: %(reqheaders)s\n"
"\n"
"cuerpo de solicitud: %(reqbody)s\n"
"\n"
"cabeceras de respuesta: %(respheaders)s\n"
"\n"
"cuerpo de respuesta: %(respbody)s"

#: pypowervm/adapter.py:1388
#, python-format
msgid "Atom error for %(method)s %(path)s: %(reason)s"
msgstr "Error Atom para %(method)s %(path)s: %(reason)s"

#: pypowervm/adapter.py:1430
msgid "Session must not be None"
msgstr "La sesión no debe ser None (ninguna)."

#: pypowervm/adapter.py:1432
msgid "An event listener is already active on the session."
msgstr "Ya hay un escucha de sucesos activo en la sesión."

#: pypowervm/adapter.py:1448
#, python-format
msgid "Failed to initialize event feed listener: %s"
msgstr "Se ha encontrado un error en la inicialización del escucha de feeds de sucesos: %s"

#: pypowervm/adapter.py:1452
#, python-format
msgid "Application id \"%s\" is not unique"
msgstr "El ID de aplicación \"%s\" no es exclusivo."

#: pypowervm/adapter.py:1461
msgid "Shutting down"
msgstr "Concluyendo"

#: pypowervm/adapter.py:1464
msgid "This handler is already subscribed"
msgstr "Este manejador ya está suscrito."

#: pypowervm/adapter.py:1472
msgid "Handler must be an EventHandler"
msgstr "El manejador debe ser un EventHandler."

#: pypowervm/adapter.py:1475
msgid "This handler not found in subscriber list"
msgstr "Este manejador no se ha encontrado en la lista de suscriptores."

#: pypowervm/adapter.py:1483
#, python-format
msgid "Shutting down EventListener for %s"
msgstr "Cerrando EventListener de %s"

#: pypowervm/adapter.py:1487
#, python-format
msgid "EventListener shutdown complete for %s"
msgstr "Se ha completado el cierre de EventListener para %s"

#: pypowervm/adapter.py:1507
msgid "Error while getting PowerVM events"
msgstr "Error al obtener los sucesos de PowerVM."

#: pypowervm/adapter.py:1544
#, python-format
msgid "Unexpected EventType=%s"
msgstr "EventType inesperado=%s"

#: pypowervm/adapter.py:1561
msgid "Error while processing PowerVM events"
msgstr "Error al procesar los sucesos de PowerVM."

#: pypowervm/exceptions.py:117
#, python-format
msgid ""
"Unable to derive the appropriate physical FC port for WWPN %(wwpn)s.  The"
" VIOS Extended Attribute Groups may have been insufficient.  The VIOS URI"
" for the query was %(vio_uri)s."
msgstr ""
"No se puede derivar el puerto de canal de fibra físico adecuado para WWPN %(wwpn)s. Es"
" posible que los grupos de atributos ampliados del VIOS no fueran suficientes. El URI del VIOS"
" para la consulta ha sido %(vio_uri)s."

#: pypowervm/exceptions.py:123
#, python-format
msgid "Element not found: %(element_type)s %(element)s"
msgstr "No se ha encontrado el elemento: %(element_type)s %(element)s"

#: pypowervm/exceptions.py:127
#, python-format
msgid "LPAR not found: %(lpar_name)s"
msgstr "No se ha encontrado la LPAR: %(lpar_name)s"

#: pypowervm/exceptions.py:131
#, python-format
msgid "The '%(operation_name)s' operation failed. %(error)s"
msgstr "La operación '%(operation_name)s' ha fallado. %(error)s"

#: pypowervm/exceptions.py:135
#, python-format
msgid ""
"The '%(operation_name)s' operation failed. Failed to complete the task in"
" %(seconds)d seconds."
msgstr ""
"La operación '%(operation_name)s' ha fallado. No se ha podido completar la tarea en"
" en %(seconds)d segundos."

#: pypowervm/exceptions.py:140
#, python-format
msgid "Failed to power off Virtual Machine %(lpar_nm)s: %(reason)s"
msgstr "No se ha podido apagar la máquina virtual %(lpar_nm)s: %(reason)s"

#: pypowervm/exceptions.py:144
#, python-format
msgid "Failed to power on Virtual Machine %(lpar_nm)s: %(reason)s"
msgstr "No se ha podido encender la máquina virtual %(lpar_nm)s: %(reason)s"

#: pypowervm/exceptions.py:148
#, python-format
msgid ""
"Unable to remove VLAN %(vlan_id)d as it is the Primary VLAN Identifier on"
" a different Network Bridge."
msgstr ""
"No se puede eliminar al VLAN %(vlan_id)d ya que es el identificador de VLAN primaria"
" en otro puente de red."

#: pypowervm/exceptions.py:153
#, python-format
msgid ""
"Unable to provision VLAN %(vlan_id)d.  It appears to be contained on "
"device '%(dev_name)s' on Virtual I/O Server %(vios)s.  That device is not"
" connected to any Network Bridge (Shared Ethernet Adapter).  Please "
"manually remove the device or add it to the Network Bridge before "
"continuing."
msgstr ""
"No se puede aprovisionar la VLAN %(vlan_id)d. Parece ser que está contenida en "
"el dispositivo '%(dev_name)s' en el servidor de E/S virtual %(vios)s. Ese dispositivo no está"
" conectado con ningún puente de red (adaptador Ethernet compartido). Elimine "
"manualmente el dispositivo o añádalo al puente de red antes de "
"continuar."

#: pypowervm/exceptions.py:162
#, python-format
msgid ""
"A Logical Unit with name %(lu_name)s already exists on Shared Storage "
"Pool %(ssp_name)s."
msgstr ""
"Ya existe una unidad lógica con el nombre %(lu_name)s en la agrupación de "
"almacenamiento compartido %(ssp_name)s."

#: pypowervm/exceptions.py:167
msgid ""
"Unable to find a physical port to map a virtual Fibre Channel port to.  "
"This is due to either a Virtual I/O Server being unavailable, or improper"
" port specification for the physical Fibre Channel ports."
msgstr ""
"No se puede encontrar un puerto físico con el que correlacionar un puerto de canal de fibra virtual.  "
"Esto se debe a que el servidor de E/S virtual no está disponible, o a una especificación de puerto"
" incorrecta para los puertos de canal de fibra físicos."

#: pypowervm/exceptions.py:174
msgid ""
"Unable to start the console to the Virtual Machine.  The pypowervm API is"
" running in a non-local mode.  The console can only be deployed when "
"pypowervm is co-located with the PowerVM API."
msgstr ""
"No se puede iniciar la consola en la máquina virtual. La API pypowervm se"
" ejecuta en una modalidad no local. La consola sólo se puede desplegar cuando "
"pypowervm está ubicado conjuntamente con la API PowerVM."

#: pypowervm/exceptions.py:181
#, python-format
msgid "WrapperTask %(name)s has no subtasks!"
msgstr "WrapperTask %(name)s no tiene ninguna subtarea."

#: pypowervm/exceptions.py:185
msgid "FeedTask can't have an empty feed."
msgstr "FeedTask no puede tener un canal de información vacío."

#: pypowervm/exceptions.py:189
#, python-format
msgid "OS denied access to file %(access_file)s."
msgstr "El sistema operativo ha denegado el acceso al archivo %(access_file)s."

#: pypowervm/exceptions.py:193
#, python-format
msgid ""
"OS encountered an I/O error attempting to read file %(access_file)s: "
"%(error)s"
msgstr ""
"El sistema operativo ha encontrado un error de E/S al intentar leer el archivo %(access_file)s: "
"%(error)s"

#: pypowervm/exceptions.py:198
#, python-format
msgid "The migration task failed. %(error)s"
msgstr "La tarea de migración ha fallado. %(error)s"

#: pypowervm/exceptions.py:202
#, python-format
msgid "No load source found for VM %(vm_name)s"
msgstr "No se ha encontrado ningún origen de carga para la máquina virtual %(vm_name)s"

#: pypowervm/exceptions.py:206
#, python-format
msgid ""
"Unable to derive the pg83 encoding for hdisk %(dev_name)s.  The "
"parent_entry attribute is not set.  This may be due to using a PV "
"obtained through an unsupported property chain.  The PV must be accessed "
"via VIOS.phys_vols, VG.phys_vols, or "
"VIOS.scsi_mappings[n].backing_storage."
msgstr ""
"No se ha podido derivar la codificación pg83 para el hdisk %(dev_name)s. El "
"atributo parent_entry no está establecido. Esto puede deberse al uso de un volumen físico (PV) "
"obtenido a través de una cadena de propiedades no soportada. El acceso al PV debe realizarse "
"a través de VIOS.phys_vols, VG.phys_vols o "
"VIOS.scsi_mappings[n].backing_storage."

#: pypowervm/exceptions.py:214
#, python-format
msgid ""
"Found device %(devname)s %(count)d times; expected to find it at most "
"once."
msgstr ""
"El dispositivo %(devname)s se ha encontrado %(count)d veces; se esperaba encontrarlo como máximo "
"una vez."

#: pypowervm/exceptions.py:231
#, python-format
msgid "Expected to find exactly one management partition; found %(count)d."
msgstr "Se esperaba encontrar una única partición de gestión; se han encontrado %(count)d."

#: pypowervm/exceptions.py:237
#, python-format
msgid ""
"Expected to find exactly one partition with ID %(lpar_id)d; found "
"%(count)d."
msgstr ""
"Se esperaba encontrar exactamente una partición con el ID %(lpar_id)d; se han encontrado "
"%(count)d."

#: pypowervm/exceptions.py:243
#, python-format
msgid "Couldn't find the default Tier on Shared Storage Pool %(ssp_name)s"
msgstr "No se ha podido encontrar el nivel predeterminado en la agrupación de almacenamiento compartido %(ssp_name)s"

#: pypowervm/util.py:122
#, python-format
msgid ""
"Proposed extended attribute group '%(arg_xag)s' doesn't match existing "
"extended attribute group '%(path_xag)s'"
msgstr ""
"El grupo de atributos ampliados propuesto '%(arg_xag)s' no coincide con el grupo de "
"atributos ampliados existente '%(path_xag)s'"

#: pypowervm/util.py:258
msgid "Certificate has expired."
msgstr "El certificado ha caducado."

#: pypowervm/util.py:391
#, python-format
msgid "Prefix and suffix together may not be more than %d characters."
msgstr "El prefijo y sufijo juntos no pueden tener más de %d caracteres."

#: pypowervm/util.py:396
msgid "Total length must be at least 1 character."
msgstr "La longitud total debe ser al menos de 1 carácter."

#: pypowervm/util.py:419
msgid "The name parameter must be at least one character long."
msgstr "El parámetro de nombre debe tener al menos un carácter de longitud."

#: pypowervm/util.py:422
#, python-format
msgid "The name parameter must not exceed %d characters when trunk_ok is False."
msgstr "El parámetro de nombre no debe sobrepasar de %d caracteres cuando trunk_ok es False."

#: pypowervm/util.py:520
msgid "Developer error: partial parent specification."
msgstr "Error de desarrollador: especificación de padre parcial. "

#: pypowervm/util.py:525
msgid ""
"Developer error: parent_type must be either a string schema type or a "
"Wrapper subclass."
msgstr ""
"Error de desarrollador: parent_type puede ser un tipo de esquema de serie o una "
"subclase de derivador."

#: pypowervm/helpers/log_helper.py:83
#, python-format
msgid "REQUEST: %s"
msgstr "SOLICITUD: %s"

#: pypowervm/helpers/log_helper.py:103
#, python-format
msgid "RESPONSE: %s"
msgstr "RESPUESTA: %s"

#: pypowervm/tasks/cluster_ssp.py:106
#, python-format
msgid "Waiting for in-progress upload(s) to complete.  Marker LU(s): %s"
msgstr "Esperando a que se completen las subidas en curso. LU de marcador: %s"

#: pypowervm/tasks/cluster_ssp.py:135
msgid "Abdicating in favor of in-progress upload."
msgstr "Renunciando en favor de la cargar en curso."

#: pypowervm/tasks/cluster_ssp.py:145
#, python-format
msgid "Abdicating upload in favor of marker %s."
msgstr "Renunciando a la carga en favor del marcador %s."

#: pypowervm/tasks/cluster_ssp.py:198
#, python-format
msgid "Using already-uploaded image LU %s."
msgstr "Utilizando LU de imagen ya cargada %s."

#: pypowervm/tasks/cluster_ssp.py:208
#, python-format
msgid "Creating marker LU %s"
msgstr "Creando LU de marcador %s"

#: pypowervm/tasks/cluster_ssp.py:224
#, python-format
msgid "Uploading to image LU %(lu)s (marker %(mkr)s)."
msgstr "Cargando en LU de imagen %(lu)s (marcador %(mkr)s)."

#: pypowervm/tasks/cluster_ssp.py:235
#, python-format
msgid "Removing failed LU %s."
msgstr "Eliminando LU con fallos %s."

#: pypowervm/tasks/cna.py:117
#, python-format
msgid "Unable to find the Virtual Switch %s on the system."
msgstr "No se puede encontrar el conmutador virtual %s en el sistema."

#: pypowervm/tasks/cna.py:144
#, python-format
msgid "Unable to find a valid VLAN for Virtual Switch %s."
msgstr "No se ha podido encontrar una VLAN válida para el conmutador virtual %s. "

#: pypowervm/tasks/hdisk.py:197
#, python-format
msgid ""
"hdisk discovery failed; will scrub stale storage for LPAR IDs %s and "
"retry."
msgstr ""
"El descubrimiento de hdisk ha fallado; se depurará el almacenamiento obsoleto de los ID de LPAR %s y "
"se volverá a intentar."

#: pypowervm/tasks/hdisk.py:339
#, python-format
msgid "LUA Recovery Successful. Device Found: %s"
msgstr "Recuperación de LUA realizada correctamente. Dispositivo encontrado: %s"

#: pypowervm/tasks/hdisk.py:343
#, python-format
msgid "ITL Error encountered: %s"
msgstr "Se ha encontrado el error de ITL: %s"

#: pypowervm/tasks/hdisk.py:345
#, python-format
msgid "%s Device is currently in use."
msgstr "El dispositivo %s está en uso actualmente."

#: pypowervm/tasks/hdisk.py:347
#, python-format
msgid "%s Device discovered with unknown UDID."
msgstr "Se ha descubierto un dispositivo %s con UDID desconocido."

#: pypowervm/tasks/hdisk.py:349
#, python-format
msgid "Failed to Discover the Device : %s"
msgstr "No se ha podido descubrir el dispositivo: %s"

#: pypowervm/tasks/hdisk.py:419
#, python-format
msgid "CLIRunner Error: %s"
msgstr "Error de CLIRunner: %s"

#: pypowervm/tasks/hdisk.py:451
msgid ""
"QUERY_INVENTORY LUARecovery Job succeeded, but result contained neither "
"OutputXML nor StdOut."
msgstr ""
"El trabajo QUERY_INVENTORY LUARecovery se ha ejecutado con éxito pero el resultado no contenía ni "
"OutputXML ni StdOut."

#: pypowervm/tasks/hdisk.py:465
#, python-format
msgid "QUERY_INVENTORY produced invalid chunk of XML (%(chunk)s).  Error: %(err)s"
msgstr "QUERY_INVENTORY ha producido un bloque no válido de XML (%(chunk)s). Error: %(err)s"

#: pypowervm/tasks/hdisk.py:473
#, python-format
msgid ""
"Failed to find pg83 descriptor in XML output:\n"
"%s"
msgstr ""
"Se ha encontrado un error en la búsqueda del descriptor pg83 en la salida XML:\n"
"%s"

#: pypowervm/tasks/memory.py:102
#, python-format
msgid ""
"Error obtaining host memory overhead for host with UUID '%(host)s': "
"%(error)s."
msgstr ""
"Error al obtener la sobrecarga de memoria de host para el host con el UUID '%(host)s': "
"%(error)s."

#: pypowervm/tasks/power.py:216
#, python-format
msgid "Error: %s"
msgstr "Error: %s"

#: pypowervm/tasks/power.py:263
#, python-format
msgid ""
"Error invalidating adapter cache for LPAR  %(lpar_name) with UUID "
"%(lpar_uuid)s: %(exc)s"
msgstr ""
"Error al invalidar la memoria caché de adaptador para la LPAR %(lpar_name) con el UUID "
"%(lpar_uuid)s: %(exc)s"

#: pypowervm/tasks/scsi_mapper.py:38
msgid "Retrying modification of SCSI Mapping."
msgstr "Se está reintentando la modificación de la correlación SCSI."

#: pypowervm/tasks/scsi_mapper.py:89
#, python-format
msgid ""
"Found existing mapping of %(stg_type)s storage element %(stg_name)s from "
"Virtual I/O Server %(vios_name)s to client LPAR %(lpar_uuid)s."
msgstr ""
"Se ha encontrado la correlación existente del elemento de almacenamiento de %(stg_type)s %(stg_name)s del "
"servidor de E/S virtual %(vios_name)s a la LPAR de cliente %(lpar_uuid)s."

#: pypowervm/tasks/scsi_mapper.py:107
#, python-format
msgid ""
"Creating mapping of %(stg_type)s storage element %(stg_name)s from "
"Virtual I/O Server %(vios_name)s to client LPAR %(lpar_uuid)s."
msgstr ""
"Creando correlación del elemento de almacenamiento %(stg_type)s %(stg_name)s del "
"servidor de E/S virtual %(vios_name)s a la LPAR de cliente %(lpar_uuid)s."

#: pypowervm/tasks/scsi_mapper.py:402
msgid "Must not specify both match_func and stg_elem."
msgstr "No se debe especificar match_func y stg_elem simultáneamente."

#: pypowervm/tasks/storage.py:326
#, python-format
msgid "Unable to cleanup after file upload. File uuid: %s"
msgstr "No se puede realizar la limpieza tras la carga de archivo. Uuid de archivo: %s"

#: pypowervm/tasks/storage.py:445
#, python-format
msgid "Disk Logical Unit %(luname)s has no backing image LU.  (UDID: %(udid)s) "
msgstr "La unidad lógica de disco %(luname)s no tiene LU de imagen de refuerzo.  (UDID: %(udid)s) "

#: pypowervm/tasks/storage.py:489
msgid "Unable to locate new vDisk on file upload."
msgstr "No se puede localizar el nuevo vDisk durante la carga de archivo."

#: pypowervm/tasks/storage.py:537
#, python-format
msgid ""
"Ignoring device because it lacks a UDID:\n"
"%s"
msgstr ""
"El dispositivo se ignorará porque carece de UDID:\n"
"%s"

#: pypowervm/tasks/storage.py:543
#, python-format
msgid "Device %s not found in list."
msgstr "El dispositivo %s no se ha encontrado en la lista."

#: pypowervm/tasks/storage.py:572
#, python-format
msgid "Deleting virtual disk %(vdisk)s from volume group %(vg)s"
msgstr "Se está suprimiendo el disco virtual %(vdisk)s del grupo de volúmenes %(vg)s"

#: pypowervm/tasks/storage.py:595
#, python-format
msgid "Deleting virtual optical device %(vopt)s from volume group %(vg)s"
msgstr "Se está suprimiendo el dispositivo óptico virtual %(vopt)s del grupo de volúmenes %(vg)s"

#: pypowervm/tasks/storage.py:648
#, python-format
msgid "Removing LU %(lu_name)s (UDID %(lu_udid)s)"
msgstr "Eliminando LU %(lu_name)s (UDID %(lu_udid)s)"

#: pypowervm/tasks/storage.py:652
#, python-format
msgid ""
"LU %(lu_name)s was not found - it may have been deleted out of band.  "
"(UDID: %(lu_udid)s)"
msgstr ""
"La LU %(lu_name)s no se ha encontrado: podrían haber suprimido fuera de banda. "
"(UDID: %(lu_udid)s)"

#: pypowervm/tasks/storage.py:670
#, python-format
msgid ""
"Removing Image LU %(lu_name)s because it is no longer in use.  (UDID: "
"%(lu_udid)s)"
msgstr ""
"Eliminando la LU de imagen %(lu_name)s porque ya no está en uso.  (UDID: "
"%(lu_udid)s)"

#: pypowervm/tasks/storage.py:675
#, python-format
msgid "Backing LU %(lu_name)s was not found.  (UDID: %(lu_udid)s)"
msgstr "La LU de refuerzo %(lu_name)s no se ha encontrado. (UDID: %(lu_udid)s) "

#: pypowervm/tasks/storage.py:701
msgid "Developer error: Either tier or lufeed is required."
msgstr "Error de desarrollador: es necesario tier o lufeed. "

#: pypowervm/tasks/storage.py:706
msgid "Developer error: The lufeed parameter must comprise LUEnt EntryWrappers."
msgstr "Error de desarrollador: el parámetro lufeed debe incluir LUEnt EntryWrappers. "

#: pypowervm/tasks/storage.py:713
#, python-format
msgid "Deleting LU %(lu_name)s (UDID: %(lu_udid)s)"
msgstr "Suprimiendo LU %(lu_name)s (UDID: %(lu_udid)s)"

#: pypowervm/tasks/storage.py:718
#, python-format
msgid ""
"Ignoring HttpError for LU %(lu_name)s may have been deleted out of band."
"  (UDID: %(lu_udid)s)"
msgstr ""
"Si se omite HttpError para LU %(lu_name)s podría haberse suprimido fuera de banda. "
"  (UDID: %(lu_udid)s)"

#: pypowervm/tasks/storage.py:771
#, python-format
msgid ""
"Removing %(num_maps)d orphan %(stg_type)s mappings from VIOS "
"%(vios_name)s."
msgstr ""
"Se están eliminando %(num_maps)d correlaciones de %(stg_type)s huérfano del VIOS "
"%(vios_name)s."

#: pypowervm/tasks/storage.py:797
#, python-format
msgid "Removing %(num_maps)d port-less VFC mappings from VIOS %(vios_name)s."
msgstr "Eliminando %(num_maps)d correlaciones de VFC sin puerto del servidor de E/S virtual %(vios_name)s."

#: pypowervm/tasks/storage.py:824
#, python-format
msgid ""
"Removing %(num_maps)d %(stg_type)s mappings associated with LPAR ID "
"%(lpar_id)d from VIOS %(vios_name)s."
msgstr ""
"Se están eliminando %(num_maps)d %(stg_type)s correlaciones asociadas con el ID de LPAR "
"%(lpar_id)d del VIOS %(vios_name)s."

#: pypowervm/tasks/storage.py:891
#, python-format
msgid ""
"Not removing storage %(stg_name)s of type %(stg_type)s because it cannot "
"be determined whether it is still in use.  Manual verification and "
"cleanup may be necessary."
msgstr ""
"No se va a eliminar el almacenamiento %(stg_name)s del tipo %(stg_type)s porque no es posible "
"determinar si sigue en uso. Puede que sean necesarias "
"una verificación y una limpieza manuales."

#: pypowervm/tasks/storage.py:902
#, python-format
msgid ""
"Storage scrub ignoring storage element %(stg_name)s because it is of "
"unexpected type %(stg_type)s."
msgstr ""
"La depuración del almacenamiento ignorará el elemento del almacenamiento %(stg_name)s porque es de "
"un tipo inesperado: %(stg_type)s."

#: pypowervm/tasks/storage.py:920
#, python-format
msgid ""
"Scrubbing the following %(vdcount)d Virtual Disks from VIOS %(vios)s: "
"%(vdlist)s"
msgstr ""
"Se están depurando los siguientes %(vdcount)d discos virtuales del VIOS %(vios)s: "
"%(vdlist)s"

#: pypowervm/tasks/storage.py:928
#, python-format
msgid ""
"Scrubbing the following %(vocount)d Virtual Opticals from VIOS %(vios)s: "
"%(volist)s"
msgstr ""
"Se están depurando los siguientes %(vocount)d discos ópticos virtuales del VIOS %(vios)s: "
"%(volist)s"

#: pypowervm/tasks/storage.py:991
#, python-format
msgid ""
"Skipping scrub of %(stg_type)s mappings from VIOS %(vios_name)s for the "
"following LPAR IDs because those LPARs exist: %(lpar_ids)s"
msgstr ""
"Se omite la depuración de las correlaciones %(stg_type)s del VIOS %(vios_name)s para los "
"siguientes ID de LPAR porque dichas LPAR existen: %(lpar_ids)s"

#: pypowervm/tasks/vfc_mapper.py:514
#, python-format
msgid ""
"Unable to find appropriate VIOS.  The payload provided was likely "
"insufficient.  The payload data is:\n"
" %s)"
msgstr ""
"No se encuentra el VIOS adecuado. Es probable que la carga útil proporcionada "
"fuera insuficiente. Los datos de carga útil son:\n"
" %s)"

#: pypowervm/tasks/vterm.py:74
msgid "Unable to close vterm."
msgstr "No se puede cerrar vterm."

#: pypowervm/tasks/vterm.py:266
#, python-format
msgid "VNCRepeater Server Listening on ip=%(ip)s port=%(port)s"
msgstr "El servidor VNCRepeater está escuchando en la IP=%(ip)s puerto=%(port)s"

#: pypowervm/tasks/monitor/util.py:421
msgid ""
"Metric data is not available.  This may be due to the metrics being "
"recently initialized."
msgstr ""
"Los datos de medida no están disponibles. Puede deberse a que las medidas se hayan "
"inicializado recientemente."

#: pypowervm/tests/test_i18n.py:33
msgid "This is a test"
msgstr "Esto es una prueba"

#: pypowervm/tests/test_i18n.py:36
msgid "This is a message for which a translation doesn't exist"
msgstr "Este es un mensaje para el que no existe una traducción"

#: pypowervm/utils/retry.py:152
#, python-format
msgid ""
"Attempt %(retry)d of total %(total)d for URI %(uri)s.  Error was a known "
"retry response code: %(resp_code)s"
msgstr ""
"Intento %(retry)d de un total de %(total)d para el URI %(uri)s. El error es un "
"código de respuesta de reintento conocido: %(resp_code)s"

#: pypowervm/utils/retry.py:159
#, python-format
msgid ""
"Attempt %(retry)d of %(total)d failed.  Will retry. The exception was:\n"
" %(except)s."
msgstr ""
"Intento %(retry)d de %(total)d erróneo. Se volverá a intentar. La excepción es:\n"
" %(except)s."

#: pypowervm/utils/transaction.py:348
msgid "Must supply either EntryWrapper or EntryWrapperGetter."
msgstr "Debe proporcionar EntryWrapper o EntryWrapperGetter."

#: pypowervm/utils/transaction.py:374
msgid "Must supply a valid Subtask."
msgstr "Debe proporcionar una subtarea válida."

#: pypowervm/utils/transaction.py:378
#, python-format
msgid "Duplicate 'provides' name %s."
msgstr "Nombre 'provides' duplicado %s."

#: pypowervm/utils/transaction.py:453
#, python-format
msgid "WrapperTask %s has no Subtasks; no-op execution."
msgstr "WrapperTask %s no tiene ninguna subtarea; no se ejecuta ninguna operación."

#: pypowervm/utils/transaction.py:585
msgid "Must supply either a list of EntryWrappers or a FeedGetter."
msgstr "Debe proporcionar una lista de EntryWrappers o un FeedGetter."

#: pypowervm/utils/transaction.py:764
#, python-format
msgid "FeedTask %s has no Subtasks; no-op execution."
msgstr "FeedTask %s no tiene ninguna subtarea; no se ejecuta ninguna operación."

#: pypowervm/utils/validation.py:161
#, python-format
msgid ""
"Insufficient available %(res_name)s on host for virtual machine "
"'%(instance_name)s' (%(requested)s requested, %(avail)s available)"
msgstr ""
"%(res_name)s disponibles insuficientes en el host para la máquina virtual "
"'%(instance_name)s' (%(requested)s solicitados, %(avail)s disponibles)"

#: pypowervm/utils/validation.py:189
msgid "memory"
msgstr "memoria"

#: pypowervm/utils/validation.py:210
#, python-format
msgid ""
"The virtual machine must be powered off before changing the minimum or "
"maximum memory. Power off virtual machine %s and try again."
msgstr ""
"La máquina virtual se debe apagar antes de cambiar la memoria mínima o "
"máxima. Apague la máquina virtual %s y vuelva a intentarlo."

#: pypowervm/utils/validation.py:215
#, python-format
msgid ""
"The virtual machine must be powered off before changing the expansion "
"factor. Power off virtual machine %s and try again."
msgstr ""
"La máquina virtual se debe apagar antes de cambiar el factor de "
"expansión. Apague la máquina virtual %s y vuelva a intentarlo."

#: pypowervm/utils/validation.py:302
msgid "CPUs"
msgstr "CPU"

#: pypowervm/utils/validation.py:318
msgid "processing units"
msgstr "unidades de proceso"

#: pypowervm/utils/validation.py:359
#, python-format
msgid ""
"The virtual machine must be powered off before changing the minimum or "
"maximum processors. Power off virtual machine %s and try again."
msgstr ""
"La máquina virtual se debe apagar antes de cambiar el mínimo o "
"o máximo de procesadores. Apague la máquina virtual %s y vuelva a intentarlo."

#: pypowervm/utils/validation.py:369
#, python-format
msgid ""
"The virtual machine must be powered off before changing the minimum or "
"maximum processor units. Power off virtual machine %s and try again."
msgstr ""
"La máquina virtual se debe apagar antes de cambiar el mínimo o "
"máximo de unidades de procesador. Apague la máquina virtual %s y vuelva a intentarlo."

#: pypowervm/utils/validation.py:385
#, python-format
msgid ""
"The virtual machine must be powered off before changing the processor "
"compatibility mode. Power off virtual machine %s and try again."
msgstr ""
"La máquina virtual se debe apagar antes de cambiar la modalidad de compatibilidad "
"del procesador. Apague la máquina virtual %s y vuelva a intentarlo."

#: pypowervm/utils/validation.py:393
#, python-format
msgid ""
"The virtual machine must be powered off before changing the processing "
"mode. Power off virtual machine %s and try again."
msgstr ""
"La máquina virtual se debe apagar antes de cambiar la modalidad de "
"procesamiento. Apague la máquina virtual %s y vuelva a intentarlo."

#: pypowervm/utils/validation.py:422
#, python-format
msgid ""
"The desired processors (%(vcpus)d) cannot be above the maximum allowed "
"processors per partition (%(max_allowed)d) for virtual machine "
"'%(instance_name)s'."
msgstr ""
"El número deseado de procesadores (%(vcpus)d) no puede ser mayor que el número máximo de procesadores "
"permitidos por partición (%(max_allowed)d) para la máquina virtual "
"la máquina virtual '%(instance_name)s'."

#: pypowervm/utils/validation.py:434
#, python-format
msgid ""
"The maximum processors (%(vcpus)d) cannot be above the maximum system "
"capacity processor limit (%(max_allowed)d) for virtual machine "
"'%(instance_name)s'."
msgstr ""
"El número máximo de procesadores (%(vcpus)d) no puede ser mayor que el límite máximo "
"de capacidad del procesador (%(max_allowed)d) para la máquina virtual "
"la máquina virtual '%(instance_name)s'."

#: pypowervm/utils/validation.py:506
#, python-format
msgid ""
"The virtual machine must be powered off before changing the simplified "
"remote restart capability. Power off virtual machine %s and try again."
msgstr ""
"La máquina virtual se debe apagar antes de cambiar la capacidad "
"de reinicio remoto simplificado. Apague la máquina virtual %s y vuelva a intentarlo."

#: pypowervm/wrappers/base_partition.py:526
#, python-format
msgid "Invalid KeylockPos '%s'."
msgstr "KeylockPos no válido '%s'."

#: pypowervm/wrappers/base_partition.py:537
#, python-format
msgid "Invalid BootMode '%s'."
msgstr "BootMode no válido '%s'."

#: pypowervm/wrappers/base_partition.py:1299
msgid "IOSlot.adapter is deprecated!  Use IOSlot.io_adapter instead."
msgstr "IOSlot.adapter está en desuso. Utilice IOSlot.io_adapter en su lugar."

#: pypowervm/wrappers/enterprise_pool.py:143
#, python-format
msgid ""
"Unable to determine master management console MTMS (machine type, model, "
"serial number) from %(identifier)s because no %(param)s was marked as the"
" master console for the pool."
msgstr ""
"No se ha podido determinar el MTMS (tipo de máquina, modelo, número de serie) de la consola "
"de gestión maestra a partir de %(identifier)s porque ninguna %(param)s estaba marcada como la"
" consola maestra de la agrupación."

#: pypowervm/wrappers/entry_wrapper.py:371
#, python-format
msgid "Cannot convert %(property_name)s='%(value)s' in object %(pvmobject)s"
msgstr "No se puede convertir %(property_name)s='%(value)s' en el objeto %(pvmobject)s"

#: pypowervm/wrappers/entry_wrapper.py:496
msgid ""
"Refusing set href over multiple links.\n"
"Path: %{path}s\n"
"Number of links found: %{nlinks}d"
msgstr ""
"Se rechaza establecer href en varios enlaces.\n"
"Vía de acceso: %{path}s\n"
"Número de enlaces encontrados: %{nlinks}d"

#: pypowervm/wrappers/entry_wrapper.py:540
msgid "Refusing to construct and wrap an Element without a tag."
msgstr "Se rechaza construir y recalcular un elemento sin un código."

#: pypowervm/wrappers/entry_wrapper.py:665
msgid "Response is missing 'entry' property."
msgstr "Falta la propiedad 'entry' en la respuesta."

#: pypowervm/wrappers/entry_wrapper.py:679
#, python-format
msgid "Must supply a Response or Entry to wrap.  Got %s"
msgstr "Debe proporcionar una respuesta o entrada para ajustar. Se obtuvo %s"

#: pypowervm/wrappers/entry_wrapper.py:766
msgid ""
"Developer error: specify 'parent' or ('parent_type' and 'parent_uuid') to"
" retrieve a CHILD object."
msgstr ""
"Error de desarrollador: especifique 'parent' o ('parent_type' y 'parent_uuid') para "
" recuperar un objeto CHILD. "

#: pypowervm/wrappers/entry_wrapper.py:771
msgid "Specify either 'uuid' or 'root_id' when requesting a ROOT object."
msgstr "Especifique 'uuid' o 'root_id' al solicitar un objeto ROOT."

#: pypowervm/wrappers/entry_wrapper.py:784
msgid ""
"Both parent_type and parent_uuid are required when retrieving a CHILD "
"feed or entry."
msgstr ""
"Tanto parent_type como parent_uuid son necesarios al recuperar un feed "
"o una entrada CHILD."

#: pypowervm/wrappers/entry_wrapper.py:787
msgid "Specify the parent's UUID via the parent_uuid parameter."
msgstr "Especifique el UUID del padre mediante el parámetro parent_uuid."

#: pypowervm/wrappers/entry_wrapper.py:791
msgid "Specify either 'uuid' or 'child_id' when requesting a CHILD object."
msgstr "Especifique 'uuid' o 'child_id' al solicitar un objeto CHILD."

#: pypowervm/wrappers/entry_wrapper.py:885
msgid "Parent UUID specified without parent type."
msgstr "Se ha especificado el UUID sin un tipo padre."

#: pypowervm/wrappers/entry_wrapper.py:888
msgid "The search() method requires exactly one key=value argument."
msgstr "El método search() requiere exactamente un argumento clave=valor."

#: pypowervm/wrappers/entry_wrapper.py:919
#, python-format
msgid "Wrapper class %(class)s does not support search key '%(key)s'."
msgstr "La clase de derivador %(class)s no da soporte a la clave de búsqueda '%(key)s'."

#: pypowervm/wrappers/entry_wrapper.py:1019
msgid ""
"The 'xag' parameter to EntryWrapper.update is deprecated!  At best, using"
" it will result in a no-op.  At worst, it will give you incurable etag "
"mismatch errors."
msgstr ""
"El parámetro 'xag' para EntryWrapper.update está en desuso. En el mejor de los casos, utilizarlo"
"dará como resultado una falta de operación. En el peor, le proporcionará errores de no coincidencia "
"de tag irresolubles."

#: pypowervm/wrappers/entry_wrapper.py:1081
msgid "Cannot set uuid."
msgstr "No se puede establecer el UUID."

#: pypowervm/wrappers/entry_wrapper.py:1282
msgid "No such child element."
msgstr "No existe ningún elemento hijo de este tipo."

#: pypowervm/wrappers/entry_wrapper.py:1343
msgid "Cannot set UUID on Wrapper with no Metadata."
msgstr "No se puede establecer el UUID en el derivador sin metadatos."

#: pypowervm/wrappers/entry_wrapper.py:1348
#, python-format
msgid "uuid value not valid: %s"
msgstr "El valor del UUID no es válido: %s"

#: pypowervm/wrappers/entry_wrapper.py:1403
msgid "Must specify a Wrapper subclass."
msgstr "Debe especificar una subclase de derivador."

#: pypowervm/wrappers/entry_wrapper.py:1412
msgid "Must specify both parent class and parent UUID, or neither."
msgstr "Debe especificar una clase padre y un UUID padre, o ninguno de los dos."

#: pypowervm/wrappers/job.py:276
#, python-format
msgid "Job %(job_id)s monitoring for %(time)i seconds."
msgstr "El trabajo %(job_id)s supervisará durante %(time)i segundos."

#: pypowervm/wrappers/job.py:327
#, python-format
msgid ""
"Issuing cancel request for job %(job_id)s. Will poll the job indefinitely"
" for termination."
msgstr ""
"Emitiendo una solicitud de cancelación para el trabajo %(job_id)s. Sondeará el trabajo de forma indefinida"
" para comprobar si ha terminado."

#: pypowervm/wrappers/job.py:343
#, python-format
msgid "Job %s not deleted. Job is in running state."
msgstr "El trabajo %s no se ha suprimido. El trabajo está en estado de ejecución."

#: pypowervm/wrappers/logical_partition.py:150
#: pypowervm/wrappers/logical_partition.py:230
msgid "LPAR does not have an active RMC connection."
msgstr "La LPAR no tiene una conexión RMC activa."

#: pypowervm/wrappers/logical_partition.py:152
#, python-format
msgid "LPAR does not have an active DLPAR capability for %s."
msgstr "La LPAR no tiene una prestación DLPAR activa para %s."

#: pypowervm/wrappers/logical_partition.py:164
msgid "I/O"
msgstr "E/S"

#: pypowervm/wrappers/logical_partition.py:174
msgid "Memory"
msgstr "Memoria"

#: pypowervm/wrappers/logical_partition.py:184
msgid "Processors"
msgstr "Procesadores"

#: pypowervm/wrappers/logical_partition.py:208
msgid "LPAR is not in an active state."
msgstr "La LPAR no está en un estado activo."

#: pypowervm/wrappers/logical_partition.py:218
msgid "Target system does not have the IBM i LPAR Mobility Capability."
msgstr "El sistema de destino no tiene la prestación IBM i LPAR Mobility."

#: pypowervm/wrappers/logical_partition.py:222
msgid "IBM i LPAR does not have restricted I/O."
msgstr "La LPAR de IBM i no tiene E/S restringida."

#: pypowervm/wrappers/logical_partition.py:226
msgid "Source system does not have the IBM i LPAR Mobility Capability."
msgstr "El sistema de origen no tiene la prestación de movilidad de LPAR de IBM i."

#: pypowervm/wrappers/logical_partition.py:234
msgid "LPAR is not available for LPM due to missing DLPAR capabilities."
msgstr "La LPAR no está disponible para LPM debido a que faltan prestaciones DLPAR."

#: pypowervm/wrappers/logical_partition.py:251
#: pypowervm/wrappers/logical_partition.py:260
#: pypowervm/wrappers/logical_partition.py:268
msgid ""
"This is not the property you are looking for.  Use srr_enabled in a "
"NovaLink environment."
msgstr ""
"Esta no es la propiedad que busca. Use srr_enabled en un "
"entorno NovaLink."

#: pypowervm/wrappers/logical_partition.py:304
#, python-format
msgid "Invalid IPLSrc '%s'."
msgstr "IPLSrc no válido '%s'."

#: pypowervm/wrappers/storage.py:489
#, python-format
msgid ""
"PV had encoded pg83 descriptor \"%(pg83_raw)s\", but it failed to decode "
"(%(type_error)s)."
msgstr ""
"PV había codificado el descriptor pg83 \"%(pg83_raw)s\", pero no lo ha podido decodificar "
"(%(type_error)s)."

#: pypowervm/wrappers/virtual_io_server.py:143
msgid ""
"The 'xags' property of the VIOS EntryWrapper class is deprecated!  Please"
" use values from pypowervm.const.XAG instead."
msgstr ""
"La propiedad 'xags' de la clase VIOS EntryWrapper está obsoleta. "
" En su lugar, use valores de pypowervm.const.XAG. "


# ENGL1SH_VERS10N 47423_39 DO NOT REMOVE OR CHANGE THIS LINE
# T9N_SRC_ID 23
# T9N_SH1P_STR1NG PV131AAP001 3
