# Translations template for pypowervm.
# Copyright 2015, 2017 IBM Corp.
# This file is distributed under the same license as the pypowervm project.
# Automatically generated, 2017.
#
msgid ""
msgstr ""
"Project-Id-Version: pypowervm 1.1.3.dev1\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2017-04-20 10:36-0400\n"
"PO-Revision-Date: 2017-04-20 10:36-0400\n"
"Last-Translator: Automatically generated\n"
"Language-Team: none\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.4.0\n"

#: pypowervm/adapter.py:131
#, python-format
msgid "Invalid protocol \"%s\""
msgstr "无效协议“%s”"

#: pypowervm/adapter.py:137
msgid "Unencrypted communication with PowerVM! Revert configuration to https."
msgstr "与 PowerVM 的通信未加密！将配置还原为 https。"

#: pypowervm/adapter.py:151
msgid "Calculating default audit memento failed, using 'default'."
msgstr "计算缺省审计 memento 失败，将使用“default”。"

#: pypowervm/adapter.py:192
msgid "Local authentication not supported on HMC."
msgstr "在 HMC 上，不支持本地认证。"

#: pypowervm/adapter.py:211
#, python-format
msgid "Setting up event listener for %s"
msgstr "正在为 %s 设置事件侦听器"

#: pypowervm/adapter.py:281
#, python-format
msgid "Unexpected filehandle on %s request"
msgstr "在 %s 请求中发现意外文件句柄"

#: pypowervm/adapter.py:327
#, python-format
msgid "Unexpected error for %(meth)s %(url)s"
msgstr "%(meth)s %(url)s 的意外错误"

#: pypowervm/adapter.py:329
#, python-format
msgid "Unexpected error: %(class)s for %(method)s %(url)s: %(excp)s"
msgstr "%(method)s %(url)s 的意外错误 %(class)s：%(excp)s"

#: pypowervm/adapter.py:367
msgid ""
"Re-login has been deemed unsafe. This Session instance should no longer be "
"used."
msgstr ""
"重新登录被认为不安全。不应该再使用此会话"
"实例。"

#: pypowervm/adapter.py:377
#, python-format
msgid "Attempting re-login %s"
msgstr "正在尝试重新登录 %s"

#: pypowervm/adapter.py:388
#, python-format
msgid ""
"Re-login 401, response body:\n"
"%s"
msgstr ""
"重新登录 401，响应主体：\n"
"%s"

#: pypowervm/adapter.py:393
#, python-format
msgid ""
"Re-login failed, resp body:\n"
"%s"
msgstr ""
"重新登录失败，响应主体：\n"
"%s"

#: pypowervm/adapter.py:397
#, python-format
msgid ""
"Re-login failed:\n"
"%s"
msgstr ""
"重新登录失败：\n"
"%s"

#: pypowervm/adapter.py:416
#, python-format
msgid ""
"Re-attempt failed with another 401, response body:\n"
"%s"
msgstr ""
"重新尝试登录 401 失败，响应主体：\n"
"%s"

#: pypowervm/adapter.py:419
#, python-format
msgid ""
"suspicious HTTP 401 response for %(method)s %(path)s: token is brand new"
msgstr ""
"%(method)s %(path)s 的可疑 HTTP 401 响应：令牌是全新的"

#: pypowervm/adapter.py:461
#, python-format
msgid ""
"Failed to connect to REST server - is the pvm-rest service started?  "
"Retrying %(try_num)d of %(max_tries)d after %(delay)d seconds."
msgstr ""
"无法连接至 REST 服务器 - pvm-rest 服务是否已启动？"
"正在 %(delay)d 后进行第 %(try_num)d 次（共 %(max_tries)d 次）重试。"

#: pypowervm/adapter.py:468
#, python-format
msgid "Session logging on %s"
msgstr "会话正在登录 %s"

#: pypowervm/adapter.py:532
msgid "Failed to parse a session token from the PowerVM response."
msgstr "未能解析来自 PowerVM 响应的会话令牌。"

#: pypowervm/adapter.py:534 pypowervm/adapter.py:550
#, python-format
msgid " Body= %s"
msgstr " 主体 = %s"

#: pypowervm/adapter.py:548
msgid "Failed to parse a session file path from the PowerVM response."
msgstr "未能解析来自 PowerVM 响应的会话文件路径。"

#: pypowervm/adapter.py:562
#, python-format
msgid "Token file %s didn't contain a readable session token."
msgstr "令牌文件 %s 不包含可读的会话令牌。"

#: pypowervm/adapter.py:572
#, python-format
msgid "Session logging off %s"
msgstr "会话正在从 %s 注销"

#: pypowervm/adapter.py:577
msgid "Problem logging off.  Ignoring."
msgstr "注销时发生问题。正在忽略。"

#: pypowervm/adapter.py:671
msgid "job must be a JobRequest element"
msgstr "作业必须是 JobRequest 元素"

#: pypowervm/adapter.py:675
msgid "JobRequest is missing OperationName"
msgstr "JobRequest 缺少 OperationName"

#: pypowervm/adapter.py:689 pypowervm/adapter.py:807 pypowervm/adapter.py:846
#: pypowervm/adapter.py:903
#, python-format
msgid "path=%s is not a PowerVM API reference"
msgstr "路径 = %s 不是 PowerVM API 引用"

#: pypowervm/adapter.py:918 pypowervm/adapter.py:935
msgid "Invalid file descriptor"
msgstr "文件描述符无效"

#: pypowervm/adapter.py:1022 pypowervm/adapter.py:1050
#: pypowervm/adapter.py:1065
msgid "Expected root_id"
msgstr "期望的 root_id"

#: pypowervm/adapter.py:1024
msgid "Expected child_type"
msgstr "期望的 child_type"

#: pypowervm/adapter.py:1028 pypowervm/adapter.py:1054
#: pypowervm/adapter.py:1059
#, python-format
msgid "Unexpected suffix_type=%s"
msgstr "意外的 suffix_type=%s"

#: pypowervm/adapter.py:1031 pypowervm/adapter.py:1062
msgid "Expected suffix_parm"
msgstr "期望的 suffix_parm"

#: pypowervm/adapter.py:1033 pypowervm/adapter.py:1052
#: pypowervm/adapter.py:1067
msgid "Expected child_id"
msgstr "期望的 child_id"

#: pypowervm/adapter.py:1036 pypowervm/adapter.py:1045
msgid "Unexpected child_id"
msgstr "意外的 child_id"

#: pypowervm/adapter.py:1038 pypowervm/adapter.py:1047
msgid "Unexpected root_id"
msgstr "意外的 root_id"

#: pypowervm/adapter.py:1069
#, python-format
msgid "Unexpected req_method=%s"
msgstr "意外的 req_method=%s"

#: pypowervm/adapter.py:1138
#, python-format
msgid "Error parsing XML response from PowerVM: %s"
msgstr "解析来自 PowerVM 的 XML 响应时发生错误：%s"

#: pypowervm/adapter.py:1151
msgid "Response is not an Atom feed/entry"
msgstr "响应不是 Atom 订阅源/条目"

#: pypowervm/adapter.py:1162
msgid "Unexpected HTTP 204 for request"
msgstr "请求的意外 HTTP 204"

#: pypowervm/adapter.py:1170
msgid "Unexpectedly empty response body"
msgstr "意外的空响应主体"

#: pypowervm/adapter.py:1173
#, python-format
msgid ""
"%(err_reason)s:\n"
"request headers: %(reqheaders)s\n"
"\n"
"request body: %(reqbody)s\n"
"\n"
"response headers: %(respheaders)s\n"
"\n"
"response body: %(respbody)s"
msgstr ""
"%(err_reason)s:\n"
"请求头：%(reqheaders)s\n"
"\n"
"请求主体：%(reqbody)s\n"
"\n"
"响应头：%(respheaders)s\n"
"\n"
"响应主体：%(respbody)s"

#: pypowervm/adapter.py:1181
#, python-format
msgid "Atom error for %(method)s %(path)s: %(reason)s"
msgstr "%(method)s %(path)s 的 Atom 错误：%(reason)s"

#: pypowervm/adapter.py:1222
msgid "Session must not be None"
msgstr "会话不得是“无”"

#: pypowervm/adapter.py:1224
msgid "An event listener is already active on the session."
msgstr "某个事件侦听器在会话上已经处于活动状态。"

#: pypowervm/adapter.py:1243
#, python-format
msgid "Failed to initialize event feed listener: %s"
msgstr "未能初始化事件订阅源侦听器：%s"

#: pypowervm/adapter.py:1247
#, python-format
msgid "Application id \"%s\" is not unique"
msgstr "应用程序标识“%s”不唯一"

#: pypowervm/adapter.py:1256
msgid "Shutting down"
msgstr "正在关闭"

#: pypowervm/adapter.py:1259
msgid "This handler is already subscribed"
msgstr "已经订阅此处理程序"

#: pypowervm/adapter.py:1267
msgid "Handler must be an EventHandler"
msgstr "处理程序必须是 EventHandler"

#: pypowervm/adapter.py:1270
msgid "This handler not found in subscriber list"
msgstr "在订户列表中找不到此处理程序"

#: pypowervm/adapter.py:1278
#, python-format
msgid "Shutting down EventListener for %s"
msgstr "正在关闭 %s 的 EventListener"

#: pypowervm/adapter.py:1282
#, python-format
msgid "EventListener shutdown complete for %s"
msgstr "%s 的 EventListener 关闭已完成"

#: pypowervm/adapter.py:1302
#, python-format
msgid ""
"Error while getting PowerVM events: %s.  (Is the pvm-rest service down?)"
msgstr ""
"获取 PowerVM 事件时出错：%s。（pvm-rest 服务是否已关闭？）"

#: pypowervm/adapter.py:1345
#, python-format
msgid "Unexpected EventType=%s"
msgstr "意外的 EventType=%s"

#: pypowervm/adapter.py:1373
msgid "Error while processing PowerVM events"
msgstr "处理 PowerVM 事件时发生错误"

#: pypowervm/exceptions.py:117
#, python-format
msgid ""
"Unable to derive the appropriate physical FC port for WWPN %(wwpn)s.  The "
"VIOS Extended Attribute Groups may have been insufficient.  The VIOS URI for "
"the query was %(vio_uri)s."
msgstr ""
"无法为 WWPN %(wwpn)s 生成相应物理 FC 端口。VIOS 扩展属性组"
"可能不够用。查询的 VIOS URI 为"
"%(vio_uri)s。"

#: pypowervm/exceptions.py:123
#, python-format
msgid "Element not found: %(element_type)s %(element)s"
msgstr "找不到元素：%(element_type)s %(element)s"

#: pypowervm/exceptions.py:127
#, python-format
msgid "LPAR not found: %(lpar_name)s"
msgstr "找不到 LPAR：%(lpar_name)s"

#: pypowervm/exceptions.py:131
#, python-format
msgid "The '%(operation_name)s' operation failed. %(error)s"
msgstr "“%(operation_name)s”操作失败。%(error)s"

#: pypowervm/exceptions.py:135
#, python-format
msgid ""
"The '%(operation_name)s' operation failed. Failed to complete the task in "
"%(seconds)d seconds."
msgstr ""
"“%(operation_name)s”操作失败。无法在"
"%(seconds)d 秒钟之内完成该任务。"

#: pypowervm/exceptions.py:140
#, python-format
msgid ""
"Can not perform OS shutdown on Virtual Machine %(lpar_nm)s because its RMC "
"connection is not active."
msgstr ""
"在虚拟机 %(lpar_nm)s 上无法执行操作系统关闭，"
"因为它的 RMC 连接处于不活动状态。"

#: pypowervm/exceptions.py:145
#, python-format
msgid "Failed to power off Virtual Machine %(lpar_nm)s: %(reason)s"
msgstr "未能关闭虚拟机 %(lpar_nm)s：%(reason)s"

#: pypowervm/exceptions.py:149
#, python-format
msgid ""
"Power off of Virtual Machine %(lpar_nm)s timed out after %(timeout)d seconds."
msgstr ""
"关闭虚拟机 %(lpar_nm)s 在 %(timeout)d 秒之后超时。"

#: pypowervm/exceptions.py:154
#, python-format
msgid "Failed to power on Virtual Machine %(lpar_nm)s: %(reason)s"
msgstr "未能开启虚拟机 %(lpar_nm)s：%(reason)s"

#: pypowervm/exceptions.py:158
#, python-format
msgid ""
"Power on of Virtual Machine %(lpar_nm)s timed out after %(timeout)d seconds."
msgstr ""
"开启虚拟机 %(lpar_nm)s 在 %(timeout)d 秒之后超时。"

#: pypowervm/exceptions.py:163
#, python-format
msgid ""
"Unable to remove VLAN %(vlan_id)d as it is the Primary VLAN Identifier on a "
"different Network Bridge."
msgstr ""
"无法移除 VLAN %(vlan_id)d，因为它是另一网桥上的主 VLAN"
"标识。"

#: pypowervm/exceptions.py:168
#, python-format
msgid ""
"Unable to provision VLAN %(vlan_id)d.  It appears to be contained on device "
"'%(dev_name)s' on Virtual I/O Server %(vios)s.  That device is not connected "
"to any Network Bridge (Shared Ethernet Adapter).  Please manually remove the "
"device or add it to the Network Bridge before continuing."
msgstr ""
"无法提供 VLAN %(vlan_id)d。它好像包含在"
"Virtual I/O Server %(vios)s 上的设备 %(dev_name)s 中。该设备未连接至"
"任何网桥（共享以太网适配器）。请手动移除"
"该设备或将其添加至网桥，然后继续。"

#: pypowervm/exceptions.py:177
#, python-format
msgid ""
"A Logical Unit with name %(lu_name)s already exists on Shared Storage Pool "
"%(ssp_name)s."
msgstr ""
"名称为 %(lu_name)s 的逻辑单元已存在于共享存储池"
"%(ssp_name)s."

#: pypowervm/exceptions.py:182
msgid ""
"Unable to find a physical port to map a virtual Fibre Channel port to.  This "
"is due to either a Virtual I/O Server being unavailable, or improper port "
"specification for the physical Fibre Channel ports."
msgstr ""
"找不到要将虚拟光纤通道端口映射至的物理端口。这是因为"
"Virtual I/O Server 不可用，或对物理光纤通道端口指定的端口"
"不适合。"

#: pypowervm/exceptions.py:189
msgid ""
"Unable to start the console to the Virtual Machine.  The pypowervm API is "
"running in a non-local mode.  The console can only be deployed when "
"pypowervm is co-located with the PowerVM API."
msgstr ""
"无法对虚拟机启动控制台。pypowervm API"
"正在以非本地方式运行。仅当 pypowervm 与 PowerVM API 位于同一位置时，"
"才能部署控制台。"

#: pypowervm/exceptions.py:196
#, python-format
msgid "WrapperTask %(name)s has no subtasks!"
msgstr "WrapperTask %(name)s 没有子任务！"

#: pypowervm/exceptions.py:200
msgid "FeedTask can't have an empty feed."
msgstr "FeedTask 不能具有空的订阅源。"

#: pypowervm/exceptions.py:204
#, python-format
msgid "OS denied access to file %(access_file)s."
msgstr "操作系统拒绝访问文件 %(access_file)s。"

#: pypowervm/exceptions.py:208
#, python-format
msgid ""
"OS encountered an I/O error attempting to read file %(access_file)s: "
"%(error)s"
msgstr ""
"操作系统在尝试读取文件 %(access_file)s 时遇到 I/O 错误："
"%(error)s"

#: pypowervm/exceptions.py:213
#, python-format
msgid "The migration task failed. %(error)s"
msgstr "迁移任务失败。%(error)s"

#: pypowervm/exceptions.py:217
#, python-format
msgid "No load source found for VM %(vm_name)s"
msgstr "找不到 VM %(vm_name)s 的装入源"

#: pypowervm/exceptions.py:221
#, python-format
msgid ""
"Unable to derive the pg83 encoding for hdisk %(dev_name)s.  The parent_entry "
"attribute is not set.  This may be due to using a PV obtained through an "
"unsupported property chain.  The PV must be accessed via VIOS.phys_vols, VG."
"phys_vols, or VIOS.scsi_mappings[n].backing_storage."
msgstr ""
"无法为 hdisk %(dev_name)s 派生 pg83 编码。未设置 parent_entry"
"属性。这可能是因为使用了通过不受支持的属性链生成的 PV。"
"该 PV 必须通过以下项进行访问：VIOS.phys_vols、VG."
"phys_vols 或 VIOS.scsi_mappings[n].backing_storage。"

#: pypowervm/exceptions.py:229
#, python-format
msgid ""
"Found device %(devname)s %(count)d times; expected to find it at most once."
msgstr ""
"发现设备 %(devname)s %(count)d 次；应该最多发现一次。"

#: pypowervm/exceptions.py:244
#, python-format
msgid ""
"FeedTask %(ft_name)s experienced multiple exceptions:\n"
"\t%(concat_msgs)s"
msgstr ""
"FeedTask %(ft_name)s 遇到多个异常：\n"
"\t%(concat_msgs)s"

#: pypowervm/exceptions.py:254
#, python-format
msgid "Expected to find exactly one management partition; found %(count)d."
msgstr "应该有且仅有一个管理分区；但是找到 %(count)d 个管理分区。"

#: pypowervm/exceptions.py:260
#, python-format
msgid ""
"Expected to find exactly one partition with ID %(lpar_id)d; found %(count)d."
msgstr ""
"期望正好找到一个标识为 %(lpar_id)d 的分区；但发现 %(count)d 个。"

#: pypowervm/exceptions.py:266
#, python-format
msgid "Couldn't find the default Tier on Shared Storage Pool %(ssp_name)s."
msgstr "在共享存储池 %(ssp_name)s 上找不到缺省层。"

#: pypowervm/exceptions.py:275
#, python-format
msgid ""
"The device with UDID %(udid)s was not found on any of the Virtual I/O "
"Servers."
msgstr ""
"在任何 Virtual I/O Server 上找不到 UDID 为 %(udid)s 的"
"设备。"

#: pypowervm/exceptions.py:280
#, python-format
msgid ""
"There are not enough Virtual I/O Servers to support the virtual machine's "
"device with UDID %(udid)s."
msgstr ""
"没有足够的 Virtual I/O Server 来支持"
"UDID 为 %(udid)s 的虚拟机设备。"

#: pypowervm/exceptions.py:285
#, python-format
msgid ""
"The expected fabrics (%(fabrics)s) were not found on any of the Virtual I/O "
"Servers."
msgstr ""
"在任何 Virtual I/O Server 上找不到期望的光纤网"
"%(fabrics)s。"

#: pypowervm/exceptions.py:290
#, python-format
msgid ""
"Can not rebuild the virtual machine.  It is using an I/O type of %(io_type)s "
"which is not supported for VM rebuild."
msgstr ""
"无法重建虚拟机。它正在使用 I/O 类型 %(io_type)s，"
"VM 重建不支持此类型。"

#: pypowervm/exceptions.py:295
#, python-format
msgid ""
"The number of VFC slots on the target system (%(rebuild_slots)d) does not "
"match the number of slots on the client system (%(original_slots)d).  Unable "
"to rebuild this virtual machine on this system."
msgstr ""
"目标系统上的 VFC 插槽数 (%(rebuild_slots)d) 与"
"客户机系统 (%(original_slots)d) 上的插槽数不匹配。无法"
"在此系统上重建此虚拟机。"

#: pypowervm/exceptions.py:302
#, python-format
msgid ""
"To register the slot information of the network device a CNA or VNIC adapter "
"is needed. Instead the following was given: %(wrapper)s."
msgstr ""
"要注册网络设备的插槽信息，需要 CNA 或 VNIC 适配器。"
"改为给出以下信息：%(wrapper)s。"

#: pypowervm/exceptions.py:308
#, python-format
msgid ""
"There are not enough active Virtual I/O Servers available. Expected %(exp)d; "
"found %(act)d."
msgstr ""
"没有足够的可用活动 Virtual I/O Server。期望有 %(exp)d 个；"
"但发现 %(act)d 个。"

#: pypowervm/exceptions.py:313
#, python-format
msgid ""
"No Virtual I/O Servers are available.  Attempted to wait for a VIOS to "
"become active for %(wait_time)d seconds.  Please check the RMC connectivity "
"between the PowerVM NovaLink and the Virtual I/O Servers."
msgstr ""
"没有可用 Virtual I/O Server。已尝试等待 %(wait_time)d 秒以便 VIOS"
"变为活动状态。请检查"
"PowerVM NovaLink 与 Virtual I/O Server 之间的 RMC 连接。"

#: pypowervm/exceptions.py:323
#, python-format
msgid ""
"Could not find any SR-IOV adapters in Sriov mode and Running state.\n"
"Location | Mode | State\n"
"%(sriov_loc_mode_state)s"
msgstr ""
"在 SR-IOV 方式和运行状态下找不到任何 SR-IOV 适配器。\n"
"位置 | 方式 | 状态\n"
"%(sriov_loc_mode_state)s"

#: pypowervm/exceptions.py:328
#, python-format
msgid ""
"Unable to fulfill redundancy requirement of %(red)d.  Found %(found_vfs)d "
"viable backing device(s)."
msgstr ""
"无法满足 %(red)d 的冗余需求。找到了 %(found_vfs)d 个"
"可行的支持设备。"

#: pypowervm/exceptions.py:333
msgid "The Managed System is not vNIC capable."
msgstr "受管系统不支持 vNIC。"

#: pypowervm/exceptions.py:337
msgid "There are no active vNIC-capable VIOSes."
msgstr "没有活动的支持 vNIC 的 VIOS。"

#: pypowervm/exceptions.py:341
#, python-format
msgid ""
"A redundancy of %(red)d was specified, but the Managed System is not vNIC "
"failover capable."
msgstr ""
"指定了冗余 %(red)d，但是受管系统不支持"
"vNIC 故障转移。"

#: pypowervm/exceptions.py:346
#, python-format
msgid ""
"A redundancy of %(red)d was specified, but there are no active vNIC failover-"
"capable VIOSes."
msgstr ""
"指定了冗余 %(red)d，但是没有活动的"
"支持 vNIC 故障转移的 VIOS。"

#: pypowervm/exceptions.py:351
#, python-format
msgid ""
"Unable to locate the volume group %(vol_grp)s to store the virtual optical "
"media within.  Unable to create the media repository."
msgstr ""
"找不到用于存储虚拟光学介质的卷组 %(vol_grp)s。"
"无法创建介质存储库。"

#: pypowervm/exceptions.py:357
#, python-format
msgid ""
"The ManagedSystem update was not attempted because changes were requested to "
"one or more SR-IOV physical ports which are in use by vNICs.\n"
"%(warnings)s"
msgstr ""
"未尝试 ManagedSystem 更新，因为已请求更改"
"vNIC 正在使用的一个或多个 SR-IOV 物理端口。\n"
"%(warnings)s"

#: pypowervm/exceptions.py:363
#, python-format
msgid "Unable to create VNC based virtual terminal: %(err)s"
msgstr "无法创建基于 VNC 的虚拟终端：%(err)s"

#: pypowervm/exceptions.py:367
msgid "The Adapter cache is not supported."
msgstr "适配器高速缓存不受支持。"

#: pypowervm/exceptions.py:371
#, python-format
msgid ""
"Invalid value '%(value)s' for '%(enum)s'.  Valid values are: %(valid_values)s"
msgstr ""
"“%(enum)s”的值“%(value)s”无效。有效值为：%(valid_values)s"

#: pypowervm/exceptions.py:376
#, python-format
msgid "No VIOS found with name %(vios_name)s."
msgstr "找不到名称为 %(vios_name)s 的 VIOS。"

#: pypowervm/exceptions.py:380
#, python-format
msgid "No volume group found with name %(vg_name)s."
msgstr "找不到名称为 %(vg_name)s 的卷组。"

#: pypowervm/util.py:125
#, python-format
msgid ""
"Proposed extended attribute group '%(arg_xag)s' doesn't match existing "
"extended attribute group '%(path_xag)s'"
msgstr ""
"建议的扩展属性组“%(arg_xag)s”"
"与现有的扩展属性组“%(path_xag)s”不匹配"

#: pypowervm/util.py:221
msgid "Certificate has expired."
msgstr "证书已到期。"

#: pypowervm/util.py:371
#, python-format
msgid "Prefix and suffix together may not be more than %d characters."
msgstr "前缀和后缀一共不能超过 %d  个字符。"

#: pypowervm/util.py:376
msgid "Total length must be at least 1 character."
msgstr "总长度必须至少为 1 个字符。"

#: pypowervm/util.py:399
msgid "The name parameter must be at least one character long."
msgstr "name 参数的长度必须至少为 1 个字符。"

#: pypowervm/util.py:402
#, python-format
msgid ""
"The name parameter must not exceed %d characters when trunk_ok is False."
msgstr ""
"当 trunk_ok 为 False 时，name 参数不得超过 %d 个字符。"

#: pypowervm/util.py:500
msgid "Developer error: partial parent specification."
msgstr "开发者错误：部分父级规范。"

#: pypowervm/util.py:505
msgid ""
"Developer error: parent_type must be either a string schema type or a "
"Wrapper subclass."
msgstr ""
"开发者错误：parent_type 必须为字符串模式类型或"
"包装程序子类。"

#: pypowervm/util.py:602
#, python-format
msgid "Invalid value '%(bad_val)s'.  Expected one of %(good_vals)s, or a list."
msgstr ""
"无效值“%(bad_val)s”。需要一个或一列 %(good_vals)s。"

#: pypowervm/helpers/log_helper.py:83
#, python-format
msgid "REQUEST: %s"
msgstr "请求：%s"

#: pypowervm/helpers/log_helper.py:103
#, python-format
msgid "RESPONSE: %s"
msgstr "响应：%s"

#: pypowervm/tasks/cluster_ssp.py:108
#, python-format
msgid "Waiting for in-progress upload(s) to complete.  Marker LU(s): %s"
msgstr "正在等待进行中的上载操作完成。标记 LU：%s"

#: pypowervm/tasks/cluster_ssp.py:137
msgid "Abdicating in favor of in-progress upload."
msgstr "正在放弃支持进行中的上载操作。"

#: pypowervm/tasks/cluster_ssp.py:147
#, python-format
msgid "Abdicating upload in favor of marker %s."
msgstr "正在放弃上载操作，转为支持标记 %s。"

#: pypowervm/tasks/cluster_ssp.py:202
#, python-format
msgid "Using already-uploaded image LU %s."
msgstr "正在使用已上载的映像 LU %s。"

#: pypowervm/tasks/cluster_ssp.py:212
#, python-format
msgid "Creating marker LU %s"
msgstr "正在创建标记 LU %s"

#: pypowervm/tasks/cluster_ssp.py:228
#, python-format
msgid "Uploading to image LU %(lu)s (marker %(mkr)s)."
msgstr "正在上载至映像 LU %(lu)s（标记 %(mkr)s）。"

#: pypowervm/tasks/cluster_ssp.py:240
#, python-format
msgid "Removing failed LU %s."
msgstr "正在移除失败的 LU %s。"

#: pypowervm/tasks/cna.py:120
#, python-format
msgid "Unable to find the Virtual Switch %s on the system."
msgstr "在系统上找不到虚拟交换机 %s。"

#: pypowervm/tasks/cna.py:147
#, python-format
msgid "Unable to find a valid VLAN for Virtual Switch %s."
msgstr "找不到虚拟交换机 %s 的有效 VLAN。"

#: pypowervm/tasks/memory.py:102
#, python-format
msgid ""
"Error obtaining host memory overhead for host with UUID '%(host)s': "
"%(error)s."
msgstr ""
"获取 UUID 为“%(host)s”的主机的主机内存开销时发生错误："
"%(error)s."

#: pypowervm/tasks/partition.py:312
#, python-format
msgid ""
"Timed out waiting for the RMC state of all the powered on Virtual I/O "
"Servers to be active. Wait time was: %(time)d seconds. VIOSes that did not "
"go active were: %(vioses)s."
msgstr ""
"等待所有已通电 Virtual I/O Server 的 RMC 状态变为活动时超时。"
"等待时间为 %(time)d 秒。未变为活动的 VIOS"
"为：%(vioses)s。"

#: pypowervm/tasks/partition.py:354
#, python-format
msgid "Assuming description-less slot is physical I/O: %s"
msgstr "假定无描述的插槽是物理 I/O：%s"

#: pypowervm/tasks/power.py:88
#, python-format
msgid "Partition %s already powered on."
msgstr "已开启分区 %s。"

#: pypowervm/tasks/power.py:136
#, python-format
msgid "Partition %s already powered off."
msgstr "已关闭分区 %s。"

#: pypowervm/tasks/power.py:199
#, python-format
msgid ""
"Specifying add_parms as a dict is deprecated. Please specify a %s instance "
"instead."
msgstr ""
"建议不要将 add_parms 指定为字典。请改为指定 %s 实例"
"。"

#: pypowervm/tasks/power.py:265
#, python-format
msgid ""
"IBMi OS normal shutdown failed.  Trying OS immediate shutdown.  Partition: %s"
msgstr ""
"IBMi 操作系统正常关闭失败。尝试立即关闭操作系统。分区：%s"

#: pypowervm/tasks/power.py:275
#, python-format
msgid ""
"IBMi OS immediate shutdown failed.  Trying VSP normal shutdown.  Partition: "
"%s"
msgstr ""
"IBMi 操作系统立即关闭失败。尝试正常关闭 VSP。分区："
"%s"

#: pypowervm/tasks/power.py:284
#, python-format
msgid ""
"IBMi VSP normal shutdown failed.  Trying VSP hard shutdown.  Partition: %s"
msgstr ""
"IBMi VSP 正常关闭失败。尝试硬关闭 VSP。分区：%s"

#: pypowervm/tasks/power.py:326
#, python-format
msgid ""
"Non-IBMi OS immediate shutdown timed out.  Trying VSP hard shutdown.  "
"Partition: %s"
msgstr ""
"非 IBMi 操作系统立即关闭已超时。尝试硬关闭 VSP。"
"分区：%s"

#: pypowervm/tasks/power.py:330
#, python-format
msgid ""
"Non-IBMi OS immediate shutdown failed.  Trying VSP normal shutdown.  "
"Partition: %s"
msgstr ""
"非 IBMi 操作系统立即关闭失败。尝试正常关闭 VSP。"
"分区：%s"

#: pypowervm/tasks/power.py:343
#, python-format
msgid ""
"Non-IBMi VSP normal shutdown failed.  Trying VSP hard shutdown.  Partition: "
"%s"
msgstr ""
"非 IBMi VSP 正常关闭失败。尝试硬关闭 VSP。分区："
"%s"

#: pypowervm/tasks/power.py:437
#, python-format
msgid "VSP hard shutdown with default timeout.  Partition: %s"
msgstr "VSP 硬关闭，返回缺省超时。分区：%s"

#: pypowervm/tasks/scsi_mapper.py:38
msgid "Retrying modification of SCSI Mapping."
msgstr "重试修改 SCSI 映射。"

#: pypowervm/tasks/scsi_mapper.py:98
#, python-format
msgid ""
"Found existing mapping of %(stg_type)s storage element %(stg_name)s from "
"Virtual I/O Server %(vios_name)s to client LPAR %(lpar_uuid)s."
msgstr ""
"找到 %(stg_type)s 存储元素 %(stg_name)s 的"
"从 Virtual I/O Server %(vios_name)s 到客户机 LPAR %(lpar_uuid)s 的现有映射。"

#: pypowervm/tasks/scsi_mapper.py:117
#, python-format
msgid ""
"Creating mapping of %(stg_type)s storage element %(stg_name)s from Virtual I/"
"O Server %(vios_name)s to client LPAR %(lpar_uuid)s."
msgstr ""
"正在创建 %(stg_type)s 存储器元素 %(stg_name)s 的从 Virtual I/"
"O Server %(vios_name)s 至客户机 LPAR %(lpar_uuid)s 的映射。"

#: pypowervm/tasks/scsi_mapper.py:433
msgid "Must not specify both match_func and stg_elem."
msgstr "不得同时指定 match_func 和 stg_elem。"

#: pypowervm/tasks/slot_map.py:194
msgid ""
"The register_cna method is deprecated! Please use the register_vnet method."
msgstr ""
"建议不要使用 register_cna 方法！请使用 register_vnet 方法。"

#: pypowervm/tasks/slot_map.py:204
msgid "The drop_cna method is deprecated! Please use the drop_vnet method."
msgstr "建议不要使用 drop_cna 方法！请使用 drop_vnet 方法。"

#: pypowervm/tasks/sriov.py:379
#, python-format
msgid ""
"SR-IOV Physical Port at location %(loc_code)s is backing a vNIC belonging to "
"LPAR %(lpar_name)s (LPAR UUID: %(lpar_uuid)s; vNIC UUID: %(vnic_uuid)s)."
msgstr ""
"位置 %(loc_code)s 中的 SR-IOV 物理端口支持属于"
"LPAR %(lpar_name)s（LPAR UUID：%(lpar_uuid)s；vNIC UUID：%(vnic_uuid)s）的 vNIC。"

#: pypowervm/tasks/sriov.py:496
msgid ""
"Making changes to the following SR-IOV physical port labels even though they "
"are in use by vNICs:"
msgstr ""
"正在更改以下 SR-IOV 物理端口标签，即使它们正被"
"vNIC 使用："

#: pypowervm/tasks/storage.py:96
#, python-format
msgid "Failed to delete vio_file with UUID %s.  It must be manually deleted."
msgstr "未能删除 UUID 为 %s 的 vio_file。必须将其手动删除。"

#: pypowervm/tasks/storage.py:348
msgid "Encountered an issue while uploading. Will retry."
msgstr "上载时遇到问题。将重试。"

#: pypowervm/tasks/storage.py:522
msgid ""
"The crt_lu_linked_clone method is deprecated!  Please use the crt_lu method "
"(clone=src_lu, size=lu_size_gb)."
msgstr ""
"建议不要使用 crt_lu_linked_clone 方法！请使用 crt_lu 方法"
"(clone=src_lu, size=lu_size_gb)。"

#: pypowervm/tasks/storage.py:573
#, python-format
msgid ""
"Disk Logical Unit %(luname)s has no backing image LU.  (UDID: %(udid)s) "
msgstr ""
"磁盘逻辑单元 %(luname)s 没有支持映像 LU。（UDID：%(udid)s）"

#: pypowervm/tasks/storage.py:654
msgid "Unable to locate new vDisk on file upload."
msgstr "上载文件时找不到新的 vDisk。"

#: pypowervm/tasks/storage.py:703
#, python-format
msgid ""
"Ignoring device because it lacks a UDID:\n"
"%s"
msgstr ""
"正在忽略设备，因为它缺少 UDID：\n"
"%s"

#: pypowervm/tasks/storage.py:709
#, python-format
msgid "Device %s not found in list."
msgstr "在列表中找不到设备 %s。"

#: pypowervm/tasks/storage.py:738
#, python-format
msgid "Deleting virtual disk %(vdisk)s from volume group %(vg)s"
msgstr "正在从卷组 %(vg)s 中删除虚拟盘 %(vdisk)s"

#: pypowervm/tasks/storage.py:761
#, python-format
msgid "Deleting virtual optical device %(vopt)s from volume group %(vg)s"
msgstr "正在从卷组 %(vg)s 中删除虚拟光学设备 %(vopt)s"

#: pypowervm/tasks/storage.py:817
#, python-format
msgid "Removing LU %(lu_name)s (UDID %(lu_udid)s)"
msgstr "正在除去 LU %(lu_name)s (UDID %(lu_udid)s)"

#: pypowervm/tasks/storage.py:821
#, python-format
msgid ""
"LU %(lu_name)s was not found - it may have been deleted out of band.  (UDID: "
"%(lu_udid)s)"
msgstr ""
"找不到 LU %(lu_name)s - 可能已被带外删除。（UDID：）"
"%(lu_udid)s)"

#: pypowervm/tasks/storage.py:839
#, python-format
msgid ""
"Removing Image LU %(lu_name)s because it is no longer in use.  (UDID: "
"%(lu_udid)s)"
msgstr ""
"正在移除映像 LU %(lu_name)s，因为不再对它进行使用。（UDID：）"
"%(lu_udid)s)"

#: pypowervm/tasks/storage.py:844
#, python-format
msgid "Backing LU %(lu_name)s was not found.  (UDID: %(lu_udid)s)"
msgstr "找不到支持 LU %(lu_name)s。（UDID：%(lu_udid)s）"

#: pypowervm/tasks/storage.py:870
msgid "Developer error: Either tier or lufeed is required."
msgstr "开发者错误：需要层或 lufeed。"

#: pypowervm/tasks/storage.py:875
msgid ""
"Developer error: The lufeed parameter must comprise LUEnt EntryWrappers."
msgstr ""
"开发者错误：lufeed 参数必须包含 LUEnt EntryWrappers。"

#: pypowervm/tasks/storage.py:882
#, python-format
msgid "Deleting LU %(lu_name)s (UDID: %(lu_udid)s)"
msgstr "正在删除 LU %(lu_name)s（UDID：%(lu_udid)s）"

#: pypowervm/tasks/storage.py:887
#, python-format
msgid ""
"Ignoring HttpError for LU %(lu_name)s may have been deleted out of band.  "
"(UDID: %(lu_udid)s)"
msgstr ""
"LU %(lu_name)s 的忽略 HttpError 可能已被带外删除。"
"（UDID：%(lu_udid)s）"

#: pypowervm/tasks/storage.py:940
#, python-format
msgid ""
"Removing %(num_maps)d orphan %(stg_type)s mappings from VIOS %(vios_name)s."
msgstr ""
"正从 VIOS %(vios_name)s 移除 %(num_maps)d 孤线程 %(stg_type)s 映射。"

#: pypowervm/tasks/storage.py:966
#, python-format
msgid "Removing %(num_maps)d port-less VFC mappings from VIOS %(vios_name)s."
msgstr "正在从 VIOS %(vios_name)s 中移除 %(num_maps)d 个缺少端口的 VFC 映射。"

#: pypowervm/tasks/storage.py:993
#, python-format
msgid ""
"Removing %(num_maps)d %(stg_type)s mappings associated with LPAR ID "
"%(lpar_id)d from VIOS %(vios_name)s."
msgstr ""
"正在从 VIOS %(vios_name)s 除去与 LPAR 标识 "
"%(lpar_id)d 相关联的 %(num_maps)d 个 %(stg_type)s 映射。"

#: pypowervm/tasks/storage.py:1060
#, python-format
msgid ""
"Not removing storage %(stg_name)s of type %(stg_type)s because it cannot be "
"determined whether it is still in use.  Manual verification and cleanup may "
"be necessary."
msgstr ""
"未移除类型为 %(stg_type)s 的存储器 %(stg_name)s，因为不能确定"
"它是否仍在使用中。可能需要手动验证"
"和清除。"

#: pypowervm/tasks/storage.py:1071
#, python-format
msgid ""
"Storage scrub ignoring storage element %(stg_name)s because it is of "
"unexpected type %(stg_type)s."
msgstr ""
"存储器擦除正在忽略存储元素 %(stg_name)s，因为它是"
"意外类型 %(stg_type)s。"

#: pypowervm/tasks/storage.py:1089
#, python-format
msgid ""
"Scrubbing the following %(vdcount)d Virtual Disks from VIOS %(vios)s: "
"%(vdlist)s"
msgstr ""
"正在从 VIOS %(vios)s 中擦除下列 %(vdcount)d 个虚拟盘："
"%(vdlist)s"

#: pypowervm/tasks/storage.py:1097
#, python-format
msgid ""
"Scrubbing the following %(vocount)d Virtual Opticals from VIOS %(vios)s: "
"%(volist)s"
msgstr ""
"正在从 VIOS %(vios)s 中擦除下列 %(vocount)d 个虚拟光学设备："
"%(volist)s"

#: pypowervm/tasks/storage.py:1168
#, python-format
msgid ""
"Skipping scrub of %(stg_type)s mappings from VIOS %(vios_name)s for the "
"following LPAR IDs because those LPARs exist: %(lpar_ids)s"
msgstr ""
"正在为下列 LPAR 标识跳过从 VIOS %(vios_name)s 擦除 %(stg_type)s 映射，"
"因为这些 LPAR 已存在：%(lpar_ids)s"

#: pypowervm/tasks/vfc_mapper.py:529
#, python-format
msgid ""
"Unable to find appropriate VIOS.  The payload provided was likely "
"insufficient.  The payload data is:\n"
" %s)"
msgstr ""
"找不到相应的 VIOS。所提供的有效内容可能"
"不足。有效内容数据为：\n"
" %s)"

#: pypowervm/tasks/vfc_mapper.py:558
#, python-format
msgid ""
"The matched VFC port map has no backing port set. Adding %(port)s to mapping "
"for client wwpns: %(wwpns)s"
msgstr ""
"所匹配 VFC 端口映射未设置支持端口。正将 %(port)s 添加至"
"客户机 wwpn 的映射：%(wwpns)s"

#: pypowervm/tasks/vopt.py:73
msgid ""
"An error occurred querying the virtual optical media repository.  Attempting "
"to re-establish connection with a virtual optical media repository"
msgstr ""
"查询虚拟光学介质存储库时发生错误。正在尝试"
"重新建立与虚拟光学介质存储库的连接"

#: pypowervm/tasks/vterm.py:85
msgid "Unable to close vterm."
msgstr "无法关闭 vterm。"

#: pypowervm/tasks/vterm.py:137
#, python-format
msgid "Invalid output on vterm open.  Trying to reset the vterm.  Error was %s"
msgstr ""
"已打开 vterm 上的输出无效。正尝试重置 vterm。错误为 %s"

#: pypowervm/tasks/vterm.py:345
#, python-format
msgid "VNCSocket Listener Listening on ip=%(ip)s port=%(port)s"
msgstr "VNCSocket 侦听器正在侦听 ip=%(ip)s port=%(port)s"

#: pypowervm/tasks/vterm.py:474
#, python-format
msgid "Error negotiating SSL for VNC Repeater: %s"
msgstr "针对 VNC 转发器协商 SSL 时出错：%s"

#: pypowervm/tasks/hdisk/_fc.py:197
#, python-format
msgid ""
"hdisk discovery failed; will scrub stale storage for LPAR IDs %s and retry."
msgstr ""
"hdisk 发现失败；将擦除 LPAR 标识 %s 的旧存储器并重试。"

#: pypowervm/tasks/hdisk/_fc.py:339
#, python-format
msgid "LUA Recovery Successful. Device Found: %s"
msgstr "LUA 恢复成功。找到的设备为：%s"

#: pypowervm/tasks/hdisk/_fc.py:343
#, python-format
msgid "ITL Error encountered: %s"
msgstr "遇到了 ITL 错误：%s"

#: pypowervm/tasks/hdisk/_fc.py:345
#, python-format
msgid "%s Device is currently in use."
msgstr "%s 设备当前正在使用中。"

#: pypowervm/tasks/hdisk/_fc.py:347
#, python-format
msgid "%s Device discovered with unknown UDID."
msgstr "发现了具有未知 UUID 的 %s 设备。"

#: pypowervm/tasks/hdisk/_fc.py:349
#, python-format
msgid "Failed to Discover the Device : %s"
msgstr "未能发现设备：%s"

#: pypowervm/tasks/hdisk/_fc.py:419
#, python-format
msgid "CLIRunner Error: %s"
msgstr "CLIRunner 错误：%s"

#: pypowervm/tasks/hdisk/_fc.py:451
msgid ""
"QUERY_INVENTORY LUARecovery Job succeeded, but result contained neither "
"OutputXML nor StdOut."
msgstr ""
"QUERY_INVENTORY LUARecovery 作业已成功，但结果既不包含"
"OutputXML，也不包含标准输出。"

#: pypowervm/tasks/hdisk/_fc.py:475
#, python-format
msgid ""
"QUERY_INVENTORY produced invalid chunk of XML (%(chunk)s).  Error: %(err)s"
msgstr ""
"QUERY_INVENTORY 生成了无效 XML 区块 (%(chunk)s)。错误：%(err)s"

#: pypowervm/tasks/hdisk/_fc.py:483
#, python-format
msgid ""
"Failed to find pg83 descriptor in XML output:\n"
"%s"
msgstr ""
"未能在 XML 输出中找到 pg83 描述符：\n"
"%s"

#: pypowervm/tasks/hdisk/_iscsi.py:73
#, python-format
msgid "Invalid device output: %(dev)s"
msgstr "设备输出无效：%(dev)s"

#: pypowervm/tasks/hdisk/_iscsi.py:78
#, python-format
msgid "Expected IQN: %(IQN)s not found on iscsi target %(host_ip)s"
msgstr "在 iscsi 目标 %(host_ip)s 上找不到预期 IQN %(IQN)s"

#: pypowervm/tasks/monitor/util.py:421
msgid ""
"Metric data is not available.  This may be due to the metrics being recently "
"initialized."
msgstr ""
"指标数据不可用。这可能是因为指标最近"
"被初始化。"

#: pypowervm/tests/test_i18n.py:33
msgid "This is a test"
msgstr "这是一个测试"

#: pypowervm/tests/test_i18n.py:36
msgid "This is a message for which a translation doesn't exist"
msgstr "这是一条未进行翻译的消息"

#: pypowervm/utils/retry.py:203
#, python-format
msgid ""
"Attempt %(retry)d of total %(total)d for URI %(uri)s.  Error was a known "
"retry response code: %(resp_code)s"
msgstr ""
"对 URI %(uri)s 尝试第 %(retry)d 次（共 %(total)d 次）。错误为"
"一个已知的重试响应代码：%(resp_code)s"

#: pypowervm/utils/retry.py:210
#, python-format
msgid ""
"Attempt %(retry)d of %(total)d failed.  Will retry. The exception was:\n"
" %(except)s."
msgstr ""
"尝试了 %(retry)d 次（总共 %(total)d 次）都失败。将重试。异常为：\n"
" %(except)s."

#: pypowervm/utils/transaction.py:348
msgid "Must supply either EntryWrapper or EntryWrapperGetter."
msgstr "必须提供 EntryWrapper 或 EntryWrapperGetter。"

#: pypowervm/utils/transaction.py:374
msgid "Must supply a valid Subtask."
msgstr "必须提供有效子任务。"

#: pypowervm/utils/transaction.py:378
#, python-format
msgid "Duplicate 'provides' name %s."
msgstr "重复的“provides”名称 %s。"

#: pypowervm/utils/transaction.py:453
#, python-format
msgid "WrapperTask %s has no Subtasks; no-op execution."
msgstr "WrapperTask %s 没有子任务；执行空操作。"

#: pypowervm/utils/transaction.py:585
msgid "Must supply either a list of EntryWrappers or a FeedGetter."
msgstr "必须提供 EntryWrappers 或 FeedGetter 的列表。"

#: pypowervm/utils/transaction.py:764
#, python-format
msgid "FeedTask %s has no Subtasks; no-op execution."
msgstr "FeedTask %s 没有子任务；执行空操作。"

#: pypowervm/utils/transaction.py:789
#, python-format
msgid ""
"FeedTask %s experienced multiple exceptions. They are logged individually "
"below."
msgstr ""
"FeedTask %s 遇到多个异常。下面逐个记录了"
"这些异常。"

#: pypowervm/utils/validation.py:161
#, python-format
msgid ""
"Insufficient available %(res_name)s on host for virtual machine "
"'%(instance_name)s' (%(requested)s requested, %(avail)s available)"
msgstr ""
"在主机上，没有足够的 %(res_name)s 可用于虚拟机"
"“%(instance_name)s”（请求的是 %(requested)s，而实际 %(avail)s 可用）"

#: pypowervm/utils/validation.py:189
msgid "memory"
msgstr "内存"

#: pypowervm/utils/validation.py:210
#, python-format
msgid ""
"The virtual machine must be powered off before changing the minimum or "
"maximum memory. Power off virtual machine %s and try again."
msgstr ""
"更改最小内存或最大内存之前，"
"必须关闭虚拟机。关闭虚拟机 %s，然后重试。"

#: pypowervm/utils/validation.py:215
#, python-format
msgid ""
"The virtual machine must be powered off before changing the expansion "
"factor. Power off virtual machine %s and try again."
msgstr ""
"更改扩展因子之前，"
"必须关闭虚拟机。关闭虚拟机 %s，然后重试。"

#: pypowervm/utils/validation.py:302
msgid "CPUs"
msgstr "CPU 数"

#: pypowervm/utils/validation.py:318
msgid "processing units"
msgstr "处理单元数"

#: pypowervm/utils/validation.py:359
#, python-format
msgid ""
"The virtual machine must be powered off before changing the minimum or "
"maximum processors. Power off virtual machine %s and try again."
msgstr ""
"更改最小内存或最大内存之前，"
"必须关闭虚拟机。关闭虚拟机 %s，然后重试。"

#: pypowervm/utils/validation.py:369
#, python-format
msgid ""
"The virtual machine must be powered off before changing the minimum or "
"maximum processor units. Power off virtual machine %s and try again."
msgstr ""
"更改最小内存或最大内存之前，"
"必须关闭虚拟机。关闭虚拟机 %s，然后重试。"

#: pypowervm/utils/validation.py:385
#, python-format
msgid ""
"The virtual machine must be powered off before changing the processor "
"compatibility mode. Power off virtual machine %s and try again."
msgstr ""
"更改处理器兼容方式之前，"
"必须关闭虚拟机。关闭虚拟机 %s，然后重试。"

#: pypowervm/utils/validation.py:393
#, python-format
msgid ""
"The virtual machine must be powered off before changing the processing mode. "
"Power off virtual machine %s and try again."
msgstr ""
"更改处理方式之前，必须关闭虚拟机。"
"关闭虚拟机 %s，然后重试。"

#: pypowervm/utils/validation.py:422
#, python-format
msgid ""
"The desired processors (%(vcpus)d) cannot be above the maximum allowed "
"processors per partition (%(max_allowed)d) for virtual machine "
"'%(instance_name)s'."
msgstr ""
"所期望的处理器数 (%(vcpus)d)"
"不能超过每个分区允许的 (%(max_allowed)d)，虚拟机"
"'%(instance_name)s'."

#: pypowervm/utils/validation.py:434
#, python-format
msgid ""
"The maximum processors (%(vcpus)d) cannot be above the maximum system "
"capacity processor limit (%(max_allowed)d) for virtual machine "
"'%(instance_name)s'."
msgstr ""
"所期望的处理器数 (%(vcpus)d)"
"不能超过每个分区允许的 (%(max_allowed)d)，虚拟机"
"'%(instance_name)s'."

#: pypowervm/utils/validation.py:506
#, python-format
msgid ""
"The virtual machine must be powered off before changing the simplified "
"remote restart capability. Power off virtual machine %s and try again."
msgstr ""
"更改简化的远程重新启动功能之前，"
"必须关闭虚拟机。关闭虚拟机 %s，然后重试。"

#: pypowervm/wrappers/base_partition.py:424
msgid "Partition does not have an active RMC connection."
msgstr "分区没有活动 RMC 连接。"

#: pypowervm/wrappers/base_partition.py:427
#, python-format
msgid "Partition does not have an active DLPAR capability for %s."
msgstr "分区没有对应 %s 的活动 DLPAR 功能。"

#: pypowervm/wrappers/base_partition.py:439
msgid "I/O"
msgstr "I/O"

#: pypowervm/wrappers/base_partition.py:449
msgid "Memory"
msgstr "内存"

#: pypowervm/wrappers/base_partition.py:459
msgid "Processors"
msgstr "处理器"

#: pypowervm/wrappers/base_partition.py:639
#, python-format
msgid "Invalid KeylockPos '%s'."
msgstr "KeylockPos“%s”无效。"

#: pypowervm/wrappers/base_partition.py:650
#, python-format
msgid "Invalid BootMode '%s'."
msgstr "无效的 BootMode“%s”。"

#: pypowervm/wrappers/base_partition.py:1436
msgid "IOSlot.adapter is deprecated!  Use IOSlot.io_adapter instead."
msgstr "建议不要使用 IOSlot.adapter。请改为使用 IOSlot.io_adapter。"

#: pypowervm/wrappers/enterprise_pool.py:143
#, python-format
msgid ""
"Unable to determine master management console MTMS (machine type, model, "
"serial number) from %(identifier)s because no %(param)s was marked as the "
"master console for the pool."
msgstr ""
"无法根据 %(identifier)s 确定主管理控制台 MTMS（机器类型、型号"
"和序列号），因为没有 %(param)s 标记为"
"池的主控制台。"

#: pypowervm/wrappers/entry_wrapper.py:251
msgid "Cannot set uuid."
msgstr "无法设置 UUID。"

#: pypowervm/wrappers/entry_wrapper.py:443
#, python-format
msgid "Cannot convert %(property_name)s='%(value)s' in object %(pvmobject)s"
msgstr "无法转换对象 %(pvmobject)s 中的 %(property_name)s=“%(value)s”"

#: pypowervm/wrappers/entry_wrapper.py:586
msgid ""
"Refusing set href over multiple links.\n"
"Path: %{path}s\n"
"Number of links found: %{nlinks}d"
msgstr ""
"拒绝设置基于多个链接的 href。\n"
"路径：%{path}s\n"
"发现的链接数：%{nlinks}d"

#: pypowervm/wrappers/entry_wrapper.py:635
msgid "Refusing to construct and wrap an Element without a tag."
msgstr "拒绝构造和合并没有标记的元素。"

#: pypowervm/wrappers/entry_wrapper.py:760
msgid "Response is missing 'entry' property."
msgstr "响应缺少“entry”属性。"

#: pypowervm/wrappers/entry_wrapper.py:774
#, python-format
msgid "Must supply a Response or Entry to wrap.  Got %s"
msgstr "必须提供要合并的响应或条目。获得 %s"

#: pypowervm/wrappers/entry_wrapper.py:861
msgid ""
"Developer error: specify 'parent' or ('parent_type' and 'parent_uuid') to "
"retrieve a CHILD object."
msgstr ""
"开发者错误：指定“parent”或（“parent_type”和“parent_uuid”）"
"以接收 CHILD 对象。"

#: pypowervm/wrappers/entry_wrapper.py:866
msgid "Specify either 'uuid' or 'root_id' when requesting a ROOT object."
msgstr "请求根对象时，请指定“uuid”或“root_id”。"

#: pypowervm/wrappers/entry_wrapper.py:879
msgid ""
"Both parent_type and parent_uuid are required when retrieving a CHILD feed "
"or entry."
msgstr ""
"检索子代订阅源或条目时，需要 parent_type 和"
"parent_uuid。"

#: pypowervm/wrappers/entry_wrapper.py:882
msgid "Specify the parent's UUID via the parent_uuid parameter."
msgstr "通过 parent_uuid 参数来指定父代的 UUID。"

#: pypowervm/wrappers/entry_wrapper.py:886
msgid "Specify either 'uuid' or 'child_id' when requesting a CHILD object."
msgstr "请求子对象时，请指定“uuid”或“child_id”。"

#: pypowervm/wrappers/entry_wrapper.py:1001
msgid "Parent UUID specified without parent type."
msgstr "指定了没有父类型的父 UUID。"

#: pypowervm/wrappers/entry_wrapper.py:1004
msgid "The search() method requires exactly one key=value argument."
msgstr "search() 方法只需要一个 key=value 参数。"

#: pypowervm/wrappers/entry_wrapper.py:1035
#, python-format
msgid "Wrapper class %(class)s does not support search key '%(key)s'."
msgstr "包装器类 %(class)s 不支持搜索键“%(key)s”。"

#: pypowervm/wrappers/entry_wrapper.py:1135
msgid ""
"The 'xag' parameter to EntryWrapper.update is deprecated!  At best, using it "
"will result in a no-op.  At worst, it will give you incurable etag mismatch "
"errors."
msgstr ""
"不推荐对 EntryWrapper.update 使用“xag”参数！使用它的最好的结果是"
"不执行任何操作。使用它的最坏结果是它给出不可恢复的 etag 不匹配"
"错误。"

#: pypowervm/wrappers/entry_wrapper.py:1403
msgid "No such child element."
msgstr "没有这样的子元素。"

#: pypowervm/wrappers/entry_wrapper.py:1464
msgid "Cannot set UUID on Wrapper with no Metadata."
msgstr "在没有元数据的情况下无法在包装器上设置 UUID。"

#: pypowervm/wrappers/entry_wrapper.py:1469
#, python-format
msgid "uuid value not valid: %s"
msgstr "UUID 值无效：%s"

#: pypowervm/wrappers/entry_wrapper.py:1524
msgid "Must specify a Wrapper subclass."
msgstr "必须指定包装器子类。"

#: pypowervm/wrappers/entry_wrapper.py:1533
msgid "Must specify both parent class and parent UUID, or neither."
msgstr "必须同时指定父类和父 UUID，或者两者都不指定。"

#: pypowervm/wrappers/job.py:276
#, python-format
msgid "Job %(job_id)s monitoring for %(time)i seconds."
msgstr "监视作业 %(job_id)s %(time)i 秒。"

#: pypowervm/wrappers/job.py:327
#, python-format
msgid ""
"Issuing cancel request for job %(job_id)s. Will poll the job indefinitely "
"for termination."
msgstr ""
"正对作业 %(job_id)s 发出取消请求。将无限期轮询作业"
"至终止。"

#: pypowervm/wrappers/job.py:343
#, python-format
msgid "Job %s not deleted. Job is in running state."
msgstr "未删除作业 %s。该作业处于正在运行状态。"

#: pypowervm/wrappers/logical_partition.py:169
msgid "LPAR is not in an active state."
msgstr "LPAR 处于不活动状态。"

#: pypowervm/wrappers/logical_partition.py:179
msgid "Target system does not have the IBM i LPAR Mobility Capability."
msgstr "目标系统不具备 IBM i LPAR 移动性能力。"

#: pypowervm/wrappers/logical_partition.py:183
msgid "IBM i LPAR does not have restricted I/O."
msgstr "IBM i LPAR 不具备有限 I/O。"

#: pypowervm/wrappers/logical_partition.py:187
msgid "Source system does not have the IBM i LPAR Mobility Capability."
msgstr "源系统不具备 IBM i LPAR 移动性能力。"

#: pypowervm/wrappers/logical_partition.py:191
msgid "LPAR does not have an active RMC connection."
msgstr "LPAR 没有活动 RMC 连接。"

#: pypowervm/wrappers/logical_partition.py:194
msgid "LPAR is the management partition"
msgstr "LPAR 是管理分区"

#: pypowervm/wrappers/logical_partition.py:198
msgid "LPAR is not available for LPM due to missing DLPAR capabilities."
msgstr "由于缺乏 DLPAR 能力，LPAR 不可用于 LPM。"

#: pypowervm/wrappers/logical_partition.py:215
#: pypowervm/wrappers/logical_partition.py:224
#: pypowervm/wrappers/logical_partition.py:232
msgid ""
"This is not the property you are looking for.  Use srr_enabled in a NovaLink "
"environment."
msgstr ""
"这不是您正在查找的属性。 请在 NovaLink 环境中"
"使用 srr_enabled。"

#: pypowervm/wrappers/logical_partition.py:268
#, python-format
msgid "Invalid IPLSrc '%s'."
msgstr "无效 IPLSrc“%s”。"

#: pypowervm/wrappers/managed_system.py:428
msgid "This property is deprecated!. Use pci_subsys_dev_id instead."
msgstr "建议不要使用此属性！请改为使用 pci_subsys_dev_id。"

#: pypowervm/wrappers/managed_system.py:440
msgid "This property is deprecated!. Use pci_rev_id instead."
msgstr "建议不要使用此属性！请改为使用 pci_rev_id。"

#: pypowervm/wrappers/managed_system.py:456
msgid "This property is deprecated!. Use pci_subsys_vendor_id instead."
msgstr "建议不要使用此属性！请改为使用 pci_subsys_vendor_id。"

#: pypowervm/wrappers/managed_system.py:468
msgid "This property is deprecated!. Use drc_index instead."
msgstr "建议不要使用此属性！请改为使用 drc_index。"

#: pypowervm/wrappers/managed_system.py:480
msgid "This property is deprecated!. Use drc_name instead."
msgstr "建议不要使用此属性！请改为使用 drc_name。"

#: pypowervm/wrappers/storage.py:651
#, python-format
msgid ""
"PV had encoded pg83 descriptor \"%(pg83_raw)s\", but it failed to decode "
"(%(type_error)s)."
msgstr ""
"PV 已对 pg83 描述符“%(pg83_raw)s”进行编码，但未能解码"
"(%(type_error)s)."

#: pypowervm/wrappers/virtual_io_server.py:163
msgid ""
"The 'xags' property of the VIOS EntryWrapper class is deprecated!  Please "
"use values from pypowervm.const.XAG instead."
msgstr ""
"建议不要使用 VIOS EntryWrapper 类的“xags”属性！"
"请改为使用 pypowervm.const.XAG 中的值。"

#: pypowervm/wrappers/virtual_io_server.py:400
msgid "Partition of VIOS type is not LPM capable"
msgstr "VIOS 类型的分区不支持 LPM"

#: pypowervm/wrappers/virtual_io_server.py:655
msgid "Can't specify target device LUA without a backing storage device!"
msgstr "在没有备用存储器设备的情况下，无法指定目标设备 LUA！"

# ENGL1SH_VERS10N 13712_53 DO NOT REMOVE OR CHANGE THIS LINE
# T9N_SRC_ID 23
# T9N_SH1P_STR1NG PV133AAP001 2
