# Translations template for pypowervm.
# Copyright 2015, 2017 IBM Corp.
# This file is distributed under the same license as the pypowervm project.
# Automatically generated, 2017.
#
msgid ""
msgstr ""
"Project-Id-Version: pypowervm 1.1.3.dev1\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2017-04-20 10:36-0400\n"
"PO-Revision-Date: 2017-04-20 10:36-0400\n"
"Last-Translator: Automatically generated\n"
"Language-Team: none\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.4.0\n"

#: pypowervm/adapter.py:131
#, python-format
msgid "Invalid protocol \"%s\""
msgstr "올바르지 않은 프로토콜 \"%s\""

#: pypowervm/adapter.py:137
msgid "Unencrypted communication with PowerVM! Revert configuration to https."
msgstr "PowerVM! Revert 구성을 사용한 https 통신이 암호화되지 않았습니다."

#: pypowervm/adapter.py:151
msgid "Calculating default audit memento failed, using 'default'."
msgstr "기본 auditmemento 계산이 실패함, 'default' 사용 중."

#: pypowervm/adapter.py:192
msgid "Local authentication not supported on HMC."
msgstr "HMC에서 로컬 인증이 지원되지 않습니다."

#: pypowervm/adapter.py:211
#, python-format
msgid "Setting up event listener for %s"
msgstr "%s에 대한 이벤트 리스너 설정 중"

#: pypowervm/adapter.py:281
#, python-format
msgid "Unexpected filehandle on %s request"
msgstr "%s 요청에 예기치 않은 filehandle"

#: pypowervm/adapter.py:327
#, python-format
msgid "Unexpected error for %(meth)s %(url)s"
msgstr "%(meth)s %(url)s에 대한 예기치 않은 오류"

#: pypowervm/adapter.py:329
#, python-format
msgid "Unexpected error: %(class)s for %(method)s %(url)s: %(excp)s"
msgstr "예기치 않은 오류: %(method)s %(url)s에 대한 %(class)s: %(excp)s"

#: pypowervm/adapter.py:367
msgid ""
"Re-login has been deemed unsafe. This Session instance should no longer be "
"used."
msgstr ""
"재로그인이 안전하지 않은 것 같습니다. 이 세션 인스턴스를 더 이상 사용하지 "
"않아야 합니다. "

#: pypowervm/adapter.py:377
#, python-format
msgid "Attempting re-login %s"
msgstr "%s 재로그인 시도 중"

#: pypowervm/adapter.py:388
#, python-format
msgid ""
"Re-login 401, response body:\n"
"%s"
msgstr ""
"401 재로그인, 응답 본문:\n"
"%s"

#: pypowervm/adapter.py:393
#, python-format
msgid ""
"Re-login failed, resp body:\n"
"%s"
msgstr ""
"재로그인 실패, 응답 본문:\n"
"%s"

#: pypowervm/adapter.py:397
#, python-format
msgid ""
"Re-login failed:\n"
"%s"
msgstr ""
"재로그인 실패함:\n"
"%s"

#: pypowervm/adapter.py:416
#, python-format
msgid ""
"Re-attempt failed with another 401, response body:\n"
"%s"
msgstr ""
"다른 401에서 재시도가 실패함, 응답 본문:\n"
"%s"

#: pypowervm/adapter.py:419
#, python-format
msgid ""
"suspicious HTTP 401 response for %(method)s %(path)s: token is brand new"
msgstr ""
"%(method)s %(path)s에 대해 의심스러운 HTTP 401 응답이 있음: 토큰은 새 항목임"

#: pypowervm/adapter.py:461
#, python-format
msgid ""
"Failed to connect to REST server - is the pvm-rest service started?  "
"Retrying %(try_num)d of %(max_tries)d after %(delay)d seconds."
msgstr ""
"REST 서버에 연결하는 데 실패했습니다. pvm-rest 서비스가 시작되었습니까?"
"%(delay)d초 후에 최대 %(max_tries)d번 중 %(try_num)d번 재시도합니다."

#: pypowervm/adapter.py:468
#, python-format
msgid "Session logging on %s"
msgstr "%s에서 세션 로그온 중"

#: pypowervm/adapter.py:532
msgid "Failed to parse a session token from the PowerVM response."
msgstr "PowerVM 응답의 세션 토큰을 구문 분석하는 데 실패했습니다."

#: pypowervm/adapter.py:534 pypowervm/adapter.py:550
#, python-format
msgid " Body= %s"
msgstr "  본문= %s"

#: pypowervm/adapter.py:548
msgid "Failed to parse a session file path from the PowerVM response."
msgstr "PowerVM 응답에서 세션 파일 경로를 구문 분석하는 데 실패했습니다."

#: pypowervm/adapter.py:562
#, python-format
msgid "Token file %s didn't contain a readable session token."
msgstr "토큰 파일 %s에 읽을 수 있는 세션 토큰이 포함되어 있지 않습니다."

#: pypowervm/adapter.py:572
#, python-format
msgid "Session logging off %s"
msgstr "%s에서 세션 로그오프 중"

#: pypowervm/adapter.py:577
msgid "Problem logging off.  Ignoring."
msgstr "로그오프 중에 문제가 발생했습니다. 이를 무시합니다."

#: pypowervm/adapter.py:671
msgid "job must be a JobRequest element"
msgstr "작업은 JobRequest 요소여야 합니다."

#: pypowervm/adapter.py:675
msgid "JobRequest is missing OperationName"
msgstr "JobRequest에 OperationName이 누락되었습니다."

#: pypowervm/adapter.py:689 pypowervm/adapter.py:807 pypowervm/adapter.py:846
#: pypowervm/adapter.py:903
#, python-format
msgid "path=%s is not a PowerVM API reference"
msgstr "path=%s이(가) PowerVM API 참조가 아닙니다."

#: pypowervm/adapter.py:918 pypowervm/adapter.py:935
msgid "Invalid file descriptor"
msgstr "올바르지 않은 파일 디스크립터"

#: pypowervm/adapter.py:1022 pypowervm/adapter.py:1050
#: pypowervm/adapter.py:1065
msgid "Expected root_id"
msgstr "예상한 root_id"

#: pypowervm/adapter.py:1024
msgid "Expected child_type"
msgstr "예상한 child_type"

#: pypowervm/adapter.py:1028 pypowervm/adapter.py:1054
#: pypowervm/adapter.py:1059
#, python-format
msgid "Unexpected suffix_type=%s"
msgstr "예상하지 못한 suffix_type=%s"

#: pypowervm/adapter.py:1031 pypowervm/adapter.py:1062
msgid "Expected suffix_parm"
msgstr "예상한 suffix_parm"

#: pypowervm/adapter.py:1033 pypowervm/adapter.py:1052
#: pypowervm/adapter.py:1067
msgid "Expected child_id"
msgstr "예상한 child_id"

#: pypowervm/adapter.py:1036 pypowervm/adapter.py:1045
msgid "Unexpected child_id"
msgstr "예상하지 못한 child_id"

#: pypowervm/adapter.py:1038 pypowervm/adapter.py:1047
msgid "Unexpected root_id"
msgstr "예상하지 못한 root_id"

#: pypowervm/adapter.py:1069
#, python-format
msgid "Unexpected req_method=%s"
msgstr "예상하지 못한 req_method=%s"

#: pypowervm/adapter.py:1138
#, python-format
msgid "Error parsing XML response from PowerVM: %s"
msgstr "PowerVM에서 XML 응답을 구문 분석하는 중 오류 발생: %s"

#: pypowervm/adapter.py:1151
msgid "Response is not an Atom feed/entry"
msgstr "응답이 Atom 피드/항목이 아님"

#: pypowervm/adapter.py:1162
msgid "Unexpected HTTP 204 for request"
msgstr "요청에 대해 예상하지 못한 HTTP 204"

#: pypowervm/adapter.py:1170
msgid "Unexpectedly empty response body"
msgstr "예상하지 못한 빈 응답 본문"

#: pypowervm/adapter.py:1173
#, python-format
msgid ""
"%(err_reason)s:\n"
"request headers: %(reqheaders)s\n"
"\n"
"request body: %(reqbody)s\n"
"\n"
"response headers: %(respheaders)s\n"
"\n"
"response body: %(respbody)s"
msgstr ""
"%(err_reason)s:\n"
"요청 헤더: %(reqheaders)s\n"
"\n"
"요청 본문: %(reqbody)s\n"
"\n"
"응답 헤더: %(respheaders)s\n"
"\n"
"응답 본문: %(respbody)s"

#: pypowervm/adapter.py:1181
#, python-format
msgid "Atom error for %(method)s %(path)s: %(reason)s"
msgstr "%(method)s %(path)s에 대한 Atom 오류: %(reason)s"

#: pypowervm/adapter.py:1222
msgid "Session must not be None"
msgstr "세션이 없음이어야 합니다."

#: pypowervm/adapter.py:1224
msgid "An event listener is already active on the session."
msgstr "세션에서 이벤트 리스너가 이미 활성화되어 있습니다."

#: pypowervm/adapter.py:1243
#, python-format
msgid "Failed to initialize event feed listener: %s"
msgstr "이벤트 피드 리스너를 초기화하지 못함: %s"

#: pypowervm/adapter.py:1247
#, python-format
msgid "Application id \"%s\" is not unique"
msgstr "애플리케이션 ID \"%s\"이(가) 고유하지 않습니다."

#: pypowervm/adapter.py:1256
msgid "Shutting down"
msgstr "종료 중"

#: pypowervm/adapter.py:1259
msgid "This handler is already subscribed"
msgstr "이 핸들러는 이미 가입되었습니다."

#: pypowervm/adapter.py:1267
msgid "Handler must be an EventHandler"
msgstr "핸들러가 EventHandler여야 합니다."

#: pypowervm/adapter.py:1270
msgid "This handler not found in subscriber list"
msgstr "이 핸들러가 가입자 목록에 없습니다."

#: pypowervm/adapter.py:1278
#, python-format
msgid "Shutting down EventListener for %s"
msgstr "%s에 대한 EventListener 종료 중"

#: pypowervm/adapter.py:1282
#, python-format
msgid "EventListener shutdown complete for %s"
msgstr "%s에 대한 EventListener 종료가 완료되었습니다."

#: pypowervm/adapter.py:1302
#, python-format
msgid ""
"Error while getting PowerVM events: %s.  (Is the pvm-rest service down?)"
msgstr ""
"PowerVM 이벤트를 가져오는 중에 오류 발생: %s.  (pvm-rest 서비스가 중지되었습니까?)"

#: pypowervm/adapter.py:1345
#, python-format
msgid "Unexpected EventType=%s"
msgstr "예상하지 못한 EventType=%s"

#: pypowervm/adapter.py:1373
msgid "Error while processing PowerVM events"
msgstr "PowerVM 이벤트를 처리하는 중에 오류 발생"

#: pypowervm/exceptions.py:117
#, python-format
msgid ""
"Unable to derive the appropriate physical FC port for WWPN %(wwpn)s.  The "
"VIOS Extended Attribute Groups may have been insufficient.  The VIOS URI for "
"the query was %(vio_uri)s."
msgstr ""
"WWPN %(wwpn)s에 대해 적합한 물리적 FC 포트를 유도할 수 없습니다.  "
"VIOS 확장 속성 그룹이 충분하지 않았을 수 있습니다. 조회의 VIOS URI은 "
"%(vio_uri)s이었습니다. "

#: pypowervm/exceptions.py:123
#, python-format
msgid "Element not found: %(element_type)s %(element)s"
msgstr "요소를 찾을 수 없음: %(element_type)s %(element)s"

#: pypowervm/exceptions.py:127
#, python-format
msgid "LPAR not found: %(lpar_name)s"
msgstr "LPAR을 찾을 수 없음: %(lpar_name)s"

#: pypowervm/exceptions.py:131
#, python-format
msgid "The '%(operation_name)s' operation failed. %(error)s"
msgstr "'%(operation_name)s' 조작이 실패했습니다. %(error)s"

#: pypowervm/exceptions.py:135
#, python-format
msgid ""
"The '%(operation_name)s' operation failed. Failed to complete the task in "
"%(seconds)d seconds."
msgstr ""
"'%(operation_name)s' 조작이 실패했습니다. %(seconds)d초에 "
"태스크를 완료하는 데 실패했습니다."

#: pypowervm/exceptions.py:140
#, python-format
msgid ""
"Can not perform OS shutdown on Virtual Machine %(lpar_nm)s because its RMC "
"connection is not active."
msgstr ""
"해당 RMD 연결이 활성이 아니므로 가상 머신 %(lpar_nm)s에서 OS 시스템 종료를 수행할 수 "
"없습니다."

#: pypowervm/exceptions.py:145
#, python-format
msgid "Failed to power off Virtual Machine %(lpar_nm)s: %(reason)s"
msgstr "가상 머신 %(lpar_nm)s의 전원을 끄는 데 실패함: %(reason)s"

#: pypowervm/exceptions.py:149
#, python-format
msgid ""
"Power off of Virtual Machine %(lpar_nm)s timed out after %(timeout)d seconds."
msgstr ""
"가상 머신 %(lpar_nm)s의 전원 차단이 %(timeout)d초 후 제한시간이 초과되었습니다."

#: pypowervm/exceptions.py:154
#, python-format
msgid "Failed to power on Virtual Machine %(lpar_nm)s: %(reason)s"
msgstr "가상 머신 %(lpar_nm)s의 전원을 켜는 데 실패함: %(reason)s"

#: pypowervm/exceptions.py:158
#, python-format
msgid ""
"Power on of Virtual Machine %(lpar_nm)s timed out after %(timeout)d seconds."
msgstr ""
"가상 머신 %(lpar_nm)s의 전원 공급이 %(timeout)d초 후 제한시간이 초과되었습니다."

#: pypowervm/exceptions.py:163
#, python-format
msgid ""
"Unable to remove VLAN %(vlan_id)d as it is the Primary VLAN Identifier on a "
"different Network Bridge."
msgstr ""
"다른 네트워크 브릿지의 1차 VLAN ID이므로 VLAN %(vlan_id)d을(를) "
"제거할 수 없습니다. "

#: pypowervm/exceptions.py:168
#, python-format
msgid ""
"Unable to provision VLAN %(vlan_id)d.  It appears to be contained on device "
"'%(dev_name)s' on Virtual I/O Server %(vios)s.  That device is not connected "
"to any Network Bridge (Shared Ethernet Adapter).  Please manually remove the "
"device or add it to the Network Bridge before continuing."
msgstr ""
"VLAN %(vlan_id)d을(를) 프로비저닝할 수 없습니다. 이는 Virtual I/O Server %(vios)s의 "
"장치 '%(dev_name)s'에 포함된 것 같습니다. 해당 장치는 "
"네트워크 브릿지(공유 이더넷 어댑터)에 연결되지 않았습니다. 계속하기 전에 "
"수동으로 장치를 제거하거나 이를 네트워크 브릿지에 추가하십시오. "

#: pypowervm/exceptions.py:177
#, python-format
msgid ""
"A Logical Unit with name %(lu_name)s already exists on Shared Storage Pool "
"%(ssp_name)s."
msgstr ""
"이름이 %(lu_name)s인 논리 장치가 이미 공유 스토리지 풀에 존재합니다. "
"%(ssp_name)s."

#: pypowervm/exceptions.py:182
msgid ""
"Unable to find a physical port to map a virtual Fibre Channel port to.  This "
"is due to either a Virtual I/O Server being unavailable, or improper port "
"specification for the physical Fibre Channel ports."
msgstr ""
"가상 파이버 채널 포트를 맵핑할 물리적 포트를 찾을 수 없습니다. 이는 "
"Virtual I/O Server가 사용 불가능하거나 물리적 파이버 채널 포트에 대한 포트 스펙이 "
"적절하지 않기 때문입니다."

#: pypowervm/exceptions.py:189
msgid ""
"Unable to start the console to the Virtual Machine.  The pypowervm API is "
"running in a non-local mode.  The console can only be deployed when "
"pypowervm is co-located with the PowerVM API."
msgstr ""
"가상 머신에 대한 콘솔을 시작할 수 없습니다. pypowervm API가 "
"로컬이 아닌 모드에서 실행 중입니다. 콘솔은 pypowervm이 PowerVM API와 "
"공존하는 경우에만 배치될 수 있습니다."

#: pypowervm/exceptions.py:196
#, python-format
msgid "WrapperTask %(name)s has no subtasks!"
msgstr "WrapperTask %(name)s에 하위 태스크가 없습니다!"

#: pypowervm/exceptions.py:200
msgid "FeedTask can't have an empty feed."
msgstr "FeedTask에서는 피드가 비어 있을 수 없습니다."

#: pypowervm/exceptions.py:204
#, python-format
msgid "OS denied access to file %(access_file)s."
msgstr "OS가 %(access_file)s 파일에 대한 액세스를 거부했습니다."

#: pypowervm/exceptions.py:208
#, python-format
msgid ""
"OS encountered an I/O error attempting to read file %(access_file)s: "
"%(error)s"
msgstr ""
"%(access_file)s 파일을 읽는 중에 OS에서 I/O 오류가 발생함: "
"%(error)s"

#: pypowervm/exceptions.py:213
#, python-format
msgid "The migration task failed. %(error)s"
msgstr "마이그레이션 태스크에 실패했습니다. %(error)s"

#: pypowervm/exceptions.py:217
#, python-format
msgid "No load source found for VM %(vm_name)s"
msgstr "VM %(vm_name)s에 대한 로드 소스를 찾을 수 없음"

#: pypowervm/exceptions.py:221
#, python-format
msgid ""
"Unable to derive the pg83 encoding for hdisk %(dev_name)s.  The parent_entry "
"attribute is not set.  This may be due to using a PV obtained through an "
"unsupported property chain.  The PV must be accessed via VIOS.phys_vols, VG."
"phys_vols, or VIOS.scsi_mappings[n].backing_storage."
msgstr ""
"hdisk %(dev_name)s에 대한 pg83 인코딩을 유도할 수 없습니다. parent_entry "
"속성이 설정되지 않았습니다. 이는 미지원 특성 체인을 통해 가져온 PV를 "
"사용 중이기 때문일 수 있습니다. PV는 VIOS.phys_vols, VG.phys_vols 또는 "
"VIOS.scsi_mappings[n].backing_storage를 통해 액세스되어야 합니다. "

#: pypowervm/exceptions.py:229
#, python-format
msgid ""
"Found device %(devname)s %(count)d times; expected to find it at most once."
msgstr ""
"장치 %(devname)s을(를) %(count)d번 찾음: 이를 최대 한 번 찾을 것으로 예상했습니다. "

#: pypowervm/exceptions.py:244
#, python-format
msgid ""
"FeedTask %(ft_name)s experienced multiple exceptions:\n"
"\t%(concat_msgs)s"
msgstr ""
"FeedTask %(ft_name)s에서 여러 예외가 발생했습니다. \n"
"\t%(concat_msgs)s"

#: pypowervm/exceptions.py:254
#, python-format
msgid "Expected to find exactly one management partition; found %(count)d."
msgstr "정확히 하나의 관리 파티션을 찾을 것을 예상했지만 %(count)d개를 찾았습니다."

#: pypowervm/exceptions.py:260
#, python-format
msgid ""
"Expected to find exactly one partition with ID %(lpar_id)d; found %(count)d."
msgstr ""
"ID %(lpar_id)d의 파티션을 정확히 1개 찾을 것으로 예상했습니다. 찾은 개수: %(count)d."

#: pypowervm/exceptions.py:266
#, python-format
msgid "Couldn't find the default Tier on Shared Storage Pool %(ssp_name)s."
msgstr "공유 스토리지 풀 %(ssp_name)s에서 기본 티어를 찾을 수 없었습니다."

#: pypowervm/exceptions.py:275
#, python-format
msgid ""
"The device with UDID %(udid)s was not found on any of the Virtual I/O "
"Servers."
msgstr ""
"Virtual I/O Server에서 UDID가 %(udid)s인 장치를 찾을 수"
"없었습니다."

#: pypowervm/exceptions.py:280
#, python-format
msgid ""
"There are not enough Virtual I/O Servers to support the virtual machine's "
"device with UDID %(udid)s."
msgstr ""
"UDID %(udid)s의 가상 머신 장치를 지원하기에는 Virtual I/O Server가 "
"충분하지 않습니다."

#: pypowervm/exceptions.py:285
#, python-format
msgid ""
"The expected fabrics (%(fabrics)s) were not found on any of the Virtual I/O "
"Servers."
msgstr ""
"Virtual I/O Server에서 예상 패브릭(%(fabrics)s)을 찾을 수 "
"없었습니다."

#: pypowervm/exceptions.py:290
#, python-format
msgid ""
"Can not rebuild the virtual machine.  It is using an I/O type of %(io_type)s "
"which is not supported for VM rebuild."
msgstr ""
"가상 머신을 재빌드할 수 없습니다. %(io_type)s의 I/O 유형을 사용 중이며 "
"이는 VM 재빌드에 지원되지 않습니다. "

#: pypowervm/exceptions.py:295
#, python-format
msgid ""
"The number of VFC slots on the target system (%(rebuild_slots)d) does not "
"match the number of slots on the client system (%(original_slots)d).  Unable "
"to rebuild this virtual machine on this system."
msgstr ""
"대상 시스템의 VFC 슬롯 수(%(rebuild_slots)d)가 "
"클라이언트 시스템(%(original_slots)d)의 슬롯 수와 일치하지 않습니다. 이 시스템에서 "
"이 가상 머신을 재빌드할 수 없습니다. "

#: pypowervm/exceptions.py:302
#, python-format
msgid ""
"To register the slot information of the network device a CNA or VNIC adapter "
"is needed. Instead the following was given: %(wrapper)s."
msgstr ""
"네트워크 장치의 슬롯 정보를 등록하려면 CNA 또는 VNIC 어댑터가 "
"필요합니다. 대신 다음이 제공됨: %(wrapper)s."

#: pypowervm/exceptions.py:308
#, python-format
msgid ""
"There are not enough active Virtual I/O Servers available. Expected %(exp)d; "
"found %(act)d."
msgstr ""
"사용 가능한 활성 Virtual I/O Server가 충분하지 않습니다. 예상됨: %(exp)d. "
"발견됨: %(act)d."

#: pypowervm/exceptions.py:313
#, python-format
msgid ""
"No Virtual I/O Servers are available.  Attempted to wait for a VIOS to "
"become active for %(wait_time)d seconds.  Please check the RMC connectivity "
"between the PowerVM NovaLink and the Virtual I/O Servers."
msgstr ""
"Virtual I/O Server를 사용할 수 없습니다. %(wait_time)d초 동안 VIOS가 "
"활성이 되기를 기다렸습니다. PowerVM NovaLink 및 Virtual I/O Server 간의 "
"RMC 연결을 확인하십시오. "

#: pypowervm/exceptions.py:323
#, python-format
msgid ""
"Could not find any SR-IOV adapters in Sriov mode and Running state.\n"
"Location | Mode | State\n"
"%(sriov_loc_mode_state)s"
msgstr ""
"Sriov 모드에 있고 실행 중 상태인 SR-IOV 어댑터를 찾을 수 없었습니다.\n"
"위치 | 모드 | 상태\n"
"%(sriov_loc_mode_state)s"

#: pypowervm/exceptions.py:328
#, python-format
msgid ""
"Unable to fulfill redundancy requirement of %(red)d.  Found %(found_vfs)d "
"viable backing device(s)."
msgstr ""
"%(red)d의 중복성 요구사항을 수행할 수 없습니다. %(found_vfs)d "
"실행 가능한 백업 장치를 찾았습니다."

#: pypowervm/exceptions.py:333
msgid "The Managed System is not vNIC capable."
msgstr "관리 시스템이 vNIC 가능하지 않습니다. "

#: pypowervm/exceptions.py:337
msgid "There are no active vNIC-capable VIOSes."
msgstr "활성 vNIC 가능 VIOS가 없습니다. "

#: pypowervm/exceptions.py:341
#, python-format
msgid ""
"A redundancy of %(red)d was specified, but the Managed System is not vNIC "
"failover capable."
msgstr ""
"%(red)d의 중복성이 지정되었지만 관리 대상 시스템이 vNIC "
"장애 복구를 사용할 수 없습니다."

#: pypowervm/exceptions.py:346
#, python-format
msgid ""
"A redundancy of %(red)d was specified, but there are no active vNIC failover-"
"capable VIOSes."
msgstr ""
"%(red)d의 중복성이 지정되었지만 활성 vNIC 장애 복구 "
"가능 VIOS가 없습니다. "

#: pypowervm/exceptions.py:351
#, python-format
msgid ""
"Unable to locate the volume group %(vol_grp)s to store the virtual optical "
"media within.  Unable to create the media repository."
msgstr ""
"가상 광학 매체가 저장될 볼륨 그룹 %(vol_grp)s을(를) "
"찾을 수 없습니다. 매체 저장소를 작성할 수 없습니다."

#: pypowervm/exceptions.py:357
#, python-format
msgid ""
"The ManagedSystem update was not attempted because changes were requested to "
"one or more SR-IOV physical ports which are in use by vNICs.\n"
"%(warnings)s"
msgstr ""
"vNIC에서 사용 중인 하나 이상의 SR-IOV 물리적 포트에 대한 변경이 요청되었으므로 "
"관리 시스템 업데이트가 시도되지 않았습니다. \n"
"%(warnings)s"

#: pypowervm/exceptions.py:363
#, python-format
msgid "Unable to create VNC based virtual terminal: %(err)s"
msgstr "VNC 기반 가상 터미널을 작성할 수 없음: %(err)s"

#: pypowervm/exceptions.py:367
msgid "The Adapter cache is not supported."
msgstr "어댑터 캐시가 지원되지 않습니다."

#: pypowervm/exceptions.py:371
#, python-format
msgid ""
"Invalid value '%(value)s' for '%(enum)s'.  Valid values are: %(valid_values)s"
msgstr ""
"'%(enum)s'에 올바르지 않은 값 '%(value)s'입니다. 올바른 값: %(valid_values)s"

#: pypowervm/exceptions.py:376
#, python-format
msgid "No VIOS found with name %(vios_name)s."
msgstr "이름이 %(vios_name)s인 VIOS를 찾을 수 없습니다."

#: pypowervm/exceptions.py:380
#, python-format
msgid "No volume group found with name %(vg_name)s."
msgstr "이름이 %(vg_name)s인 볼륨 그룹을 찾을 수 없습니다."

#: pypowervm/util.py:125
#, python-format
msgid ""
"Proposed extended attribute group '%(arg_xag)s' doesn't match existing "
"extended attribute group '%(path_xag)s'"
msgstr ""
"제안된 확장 속성 그룹 '%(arg_xag)s'이(가) 기존 "
"확장 속성 그룹 '%(path_xag)s'과(와) 일치하지 않습니다."

#: pypowervm/util.py:221
msgid "Certificate has expired."
msgstr "인증서가 만료되었습니다."

#: pypowervm/util.py:371
#, python-format
msgid "Prefix and suffix together may not be more than %d characters."
msgstr "접두부 및 접미부는 모두 %d자를 초과하지 않아야 합니다."

#: pypowervm/util.py:376
msgid "Total length must be at least 1 character."
msgstr "총 길이는 한 문자 이상이어야 합니다."

#: pypowervm/util.py:399
msgid "The name parameter must be at least one character long."
msgstr "이름 매개변수 길이는 한 문자 이상이어야 합니다."

#: pypowervm/util.py:402
#, python-format
msgid ""
"The name parameter must not exceed %d characters when trunk_ok is False."
msgstr ""
"trunk_ok가 false인 경우 이름 매개변수는 %d자를 초과해서는 안됩니다."

#: pypowervm/util.py:500
msgid "Developer error: partial parent specification."
msgstr "개발자 오류: 부분 상위 스펙."

#: pypowervm/util.py:505
msgid ""
"Developer error: parent_type must be either a string schema type or a "
"Wrapper subclass."
msgstr ""
"개발자 오류: parent_type은 문자열 스키마 또는 랩퍼 "
"서브클래스여야 합니다."

#: pypowervm/util.py:602
#, python-format
msgid "Invalid value '%(bad_val)s'.  Expected one of %(good_vals)s, or a list."
msgstr ""
"'%(bad_val)s' 값이 올바르지 않습니다. %(good_vals)s 중 하나 또는 목록을 예상했습니다."

#: pypowervm/helpers/log_helper.py:83
#, python-format
msgid "REQUEST: %s"
msgstr "요청: %s"

#: pypowervm/helpers/log_helper.py:103
#, python-format
msgid "RESPONSE: %s"
msgstr "응답: %s"

#: pypowervm/tasks/cluster_ssp.py:108
#, python-format
msgid "Waiting for in-progress upload(s) to complete.  Marker LU(s): %s"
msgstr "진행 중인 업로드가 완료되기를 기다리는 중입니다. 마커 LU: %s"

#: pypowervm/tasks/cluster_ssp.py:137
msgid "Abdicating in favor of in-progress upload."
msgstr "진행 중인 업로드를 위해 포기하는 중입니다."

#: pypowervm/tasks/cluster_ssp.py:147
#, python-format
msgid "Abdicating upload in favor of marker %s."
msgstr "마커 %s을(를) 위해 업로드를 포기하는 중입니다."

#: pypowervm/tasks/cluster_ssp.py:202
#, python-format
msgid "Using already-uploaded image LU %s."
msgstr "이미 업로드된 이미지 LU %s을(를) 사용 중입니다."

#: pypowervm/tasks/cluster_ssp.py:212
#, python-format
msgid "Creating marker LU %s"
msgstr "마커 LU %s을(를) 작성하는 중"

#: pypowervm/tasks/cluster_ssp.py:228
#, python-format
msgid "Uploading to image LU %(lu)s (marker %(mkr)s)."
msgstr "이미지 LU %(lu)s(마커 %(mkr)s)에 업로드하는 중입니다."

#: pypowervm/tasks/cluster_ssp.py:240
#, python-format
msgid "Removing failed LU %s."
msgstr "실패한 LU %s을(를) 제거하는 중입니다."

#: pypowervm/tasks/cna.py:120
#, python-format
msgid "Unable to find the Virtual Switch %s on the system."
msgstr "시스템에서 가상 스위치 %s을(를) 찾을 수 없습니다."

#: pypowervm/tasks/cna.py:147
#, python-format
msgid "Unable to find a valid VLAN for Virtual Switch %s."
msgstr "가상 스위치 %s에 대한 올바른 VLAN을 찾을 수 없습니다."

#: pypowervm/tasks/memory.py:102
#, python-format
msgid ""
"Error obtaining host memory overhead for host with UUID '%(host)s': "
"%(error)s."
msgstr ""
"UUID가 '%(host)s'인 호스트에 대한 호스트 메모리 오버헤드를 가져오는 중에 오류 발생: "
"%(error)s."

#: pypowervm/tasks/partition.py:312
#, python-format
msgid ""
"Timed out waiting for the RMC state of all the powered on Virtual I/O "
"Servers to be active. Wait time was: %(time)d seconds. VIOSes that did not "
"go active were: %(vioses)s."
msgstr ""
"Virtual I/O Server에서 전원이 켜져 있는 모든 RMC 상태가 활성이 되기를 기다리는 동안"
"제한시간이 초과되었습니다. 대기한 시간: %(time)d초. 활성이 되지 않은 "
"VIOS: %(vioses)s."

#: pypowervm/tasks/partition.py:354
#, python-format
msgid "Assuming description-less slot is physical I/O: %s"
msgstr "설명이 없는 슬롯이 물리적 I/O라고 간주함: %s"

#: pypowervm/tasks/power.py:88
#, python-format
msgid "Partition %s already powered on."
msgstr "파티션 %s이(가) 이미 전원이 공급되었습니다."

#: pypowervm/tasks/power.py:136
#, python-format
msgid "Partition %s already powered off."
msgstr "파티션 %s이(가) 이미 전원이 차단되었습니다."

#: pypowervm/tasks/power.py:199
#, python-format
msgid ""
"Specifying add_parms as a dict is deprecated. Please specify a %s instance "
"instead."
msgstr ""
"사전으로 add_parms을 지정하는 방법은 더 이상 사용되지 않습니다. 대신 %s 인스턴스를 "
"지정하십시오."

#: pypowervm/tasks/power.py:265
#, python-format
msgid ""
"IBMi OS normal shutdown failed.  Trying OS immediate shutdown.  Partition: %s"
msgstr ""
"IBMi OS 정상 시스템 종료에 실패했습니다. OS 즉시 시스템 종료를 시도 중입니다. 파티션: %s"

#: pypowervm/tasks/power.py:275
#, python-format
msgid ""
"IBMi OS immediate shutdown failed.  Trying VSP normal shutdown.  Partition: "
"%s"
msgstr ""
"IBMi OS 즉시 시스템 종료에 실패했습니다. VSP 정상 시스템 종료를 시도 중입니다. 파티션: "
"%s"

#: pypowervm/tasks/power.py:284
#, python-format
msgid ""
"IBMi VSP normal shutdown failed.  Trying VSP hard shutdown.  Partition: %s"
msgstr ""
"IBMi VSP 정상 시스템 종료에 실패했습니다. VSP 하드 시스템 종료를 시도 중입니다. 파티션: %s"

#: pypowervm/tasks/power.py:326
#, python-format
msgid ""
"Non-IBMi OS immediate shutdown timed out.  Trying VSP hard shutdown.  "
"Partition: %s"
msgstr ""
"비IBMi OS 즉시 시스템 종료가 제한시간을 초과했습니다. VSP 하드 시스템 종료를 시도 중입니다. "
"파티션: %s"

#: pypowervm/tasks/power.py:330
#, python-format
msgid ""
"Non-IBMi OS immediate shutdown failed.  Trying VSP normal shutdown.  "
"Partition: %s"
msgstr ""
"비IBMi OS 즉시 시스템 종료에 실패했습니다. VSP 정상 시스템 종료를 시도 중입니다. "
"파티션: %s"

#: pypowervm/tasks/power.py:343
#, python-format
msgid ""
"Non-IBMi VSP normal shutdown failed.  Trying VSP hard shutdown.  Partition: "
"%s"
msgstr ""
"비IBMi VSP 정상 시스템 종료에 실패했습니다. VSP 하드 시스템 종료를 시도 중입니다. 파티션: "
"%s"

#: pypowervm/tasks/power.py:437
#, python-format
msgid "VSP hard shutdown with default timeout.  Partition: %s"
msgstr "기본 제한시간으로 VSP 하드 시스템 종료합니다. 파티션: %s"

#: pypowervm/tasks/scsi_mapper.py:38
msgid "Retrying modification of SCSI Mapping."
msgstr "SCSI 맵핑 수정을 재시도 중입니다."

#: pypowervm/tasks/scsi_mapper.py:98
#, python-format
msgid ""
"Found existing mapping of %(stg_type)s storage element %(stg_name)s from "
"Virtual I/O Server %(vios_name)s to client LPAR %(lpar_uuid)s."
msgstr ""
"Virtual I/O Server %(vios_name)s에서 클라이언트 LPAR %(lpar_uuid)s(으)로 %(stg_type)s 스토리지 요소 %(stg_name)s의 기존 맵핑을 "
"찾았습니다."

#: pypowervm/tasks/scsi_mapper.py:117
#, python-format
msgid ""
"Creating mapping of %(stg_type)s storage element %(stg_name)s from Virtual I/"
"O Server %(vios_name)s to client LPAR %(lpar_uuid)s."
msgstr ""
"Virtual I/O Server %(vios_name)s에서 클라이언트 LPAR %(lpar_uuid)s(으)로 "
"%(stg_type)s 스토리지 요소 %(stg_name)s의 맵핑을 작성 중입니다. "

#: pypowervm/tasks/scsi_mapper.py:433
msgid "Must not specify both match_func and stg_elem."
msgstr "match_func 및 stg_elem을 모두 지정해서는 안됩니다."

#: pypowervm/tasks/slot_map.py:194
msgid ""
"The register_cna method is deprecated! Please use the register_vnet method."
msgstr ""
"register_cna 메소드는 더 이상 사용되지 않습니다! register_vnet 메소드를 사용하십시오. "

#: pypowervm/tasks/slot_map.py:204
msgid "The drop_cna method is deprecated! Please use the drop_vnet method."
msgstr "drop_cna 메소드는 더 이상 사용되지 않습니다. drop_vnet 메소드를 사용하십시오."

#: pypowervm/tasks/sriov.py:379
#, python-format
msgid ""
"SR-IOV Physical Port at location %(loc_code)s is backing a vNIC belonging to "
"LPAR %(lpar_name)s (LPAR UUID: %(lpar_uuid)s; vNIC UUID: %(vnic_uuid)s)."
msgstr ""
"위치 %(loc_code)s의 SR-IOV 물리적 포트가 LPAR %(lpar_name)s에 속하는 vNIC을 "
"백업합니다(LPAR UUID: %(lpar_uuid)s, vNIC UUID: %(vnic_uuid)s)."

#: pypowervm/tasks/sriov.py:496
msgid ""
"Making changes to the following SR-IOV physical port labels even though they "
"are in use by vNICs:"
msgstr ""
"vNIC에서 사용 중이지만 다음 SR-IOV 물리적 포트 레이블을 "
"변경하는 중입니다."

#: pypowervm/tasks/storage.py:96
#, python-format
msgid "Failed to delete vio_file with UUID %s.  It must be manually deleted."
msgstr "UUID %s인 vio_file을 삭제하는 데 실패했습니다. 수동으로 삭제해야 합니다."

#: pypowervm/tasks/storage.py:348
msgid "Encountered an issue while uploading. Will retry."
msgstr "업로드 중에 문제가 발생했습니다. 재시도합니다."

#: pypowervm/tasks/storage.py:522
msgid ""
"The crt_lu_linked_clone method is deprecated!  Please use the crt_lu method "
"(clone=src_lu, size=lu_size_gb)."
msgstr ""
"crt_lu_linked_clone 메소드는 더 이상 사용되지 않습니다! crt_lu 메소드를 사용하십시오. "
"(clone=src_lu, size=lu_size_gb)."

#: pypowervm/tasks/storage.py:573
#, python-format
msgid ""
"Disk Logical Unit %(luname)s has no backing image LU.  (UDID: %(udid)s) "
msgstr ""
"디스크 논리 장치 %(luname)s에 백업 이미지 LU가 없습니다. (UDID: %(udid)s)"

#: pypowervm/tasks/storage.py:654
msgid "Unable to locate new vDisk on file upload."
msgstr "파일 업로드에서 새 vDisk를 찾을 수 없습니다."

#: pypowervm/tasks/storage.py:703
#, python-format
msgid ""
"Ignoring device because it lacks a UDID:\n"
"%s"
msgstr ""
"UDID가 없기 때문에 장치를 무시하는 중:\n"
"%s"

#: pypowervm/tasks/storage.py:709
#, python-format
msgid "Device %s not found in list."
msgstr "%s 장치가 목록에 없습니다."

#: pypowervm/tasks/storage.py:738
#, python-format
msgid "Deleting virtual disk %(vdisk)s from volume group %(vg)s"
msgstr "볼륨 그룹 %(vg)s에서 가상 디스크 %(vdisk)s 삭제 중"

#: pypowervm/tasks/storage.py:761
#, python-format
msgid "Deleting virtual optical device %(vopt)s from volume group %(vg)s"
msgstr "볼륨 그룹 %(vg)s에서 가상 광학 장치 %(vopt)s 삭제 중"

#: pypowervm/tasks/storage.py:817
#, python-format
msgid "Removing LU %(lu_name)s (UDID %(lu_udid)s)"
msgstr "LU %(lu_name)s(UDID %(lu_udid)s) 제거 중"

#: pypowervm/tasks/storage.py:821
#, python-format
msgid ""
"LU %(lu_name)s was not found - it may have been deleted out of band.  (UDID: "
"%(lu_udid)s)"
msgstr ""
"LU %(lu_name)s을(를) 찾을 수 없습니다. 밴드에서 삭제되었을 수 있습니다. (UDID: "
"%(lu_udid)s)"

#: pypowervm/tasks/storage.py:839
#, python-format
msgid ""
"Removing Image LU %(lu_name)s because it is no longer in use.  (UDID: "
"%(lu_udid)s)"
msgstr ""
"이미지 LU %(lu_name)s이(가) 더 이상 사용되지 않으므로 이를 제거하는 중입니다. (UDID: "
"%(lu_udid)s)"

#: pypowervm/tasks/storage.py:844
#, python-format
msgid "Backing LU %(lu_name)s was not found.  (UDID: %(lu_udid)s)"
msgstr "백업 LU %(lu_name)s을(를) 찾을 수 없습니다. (UDID: %(lu_udid)s)"

#: pypowervm/tasks/storage.py:870
msgid "Developer error: Either tier or lufeed is required."
msgstr "개발자 오류: tier 또는 lufeed가 필요합니다."

#: pypowervm/tasks/storage.py:875
msgid ""
"Developer error: The lufeed parameter must comprise LUEnt EntryWrappers."
msgstr ""
"개발자 오류: lufeed 매개변수가 LUEnt EntryWrapper를 구성해야 합니다."

#: pypowervm/tasks/storage.py:882
#, python-format
msgid "Deleting LU %(lu_name)s (UDID: %(lu_udid)s)"
msgstr "LU %(lu_name)s(UDID: %(lu_udid)s) 삭제 중"

#: pypowervm/tasks/storage.py:887
#, python-format
msgid ""
"Ignoring HttpError for LU %(lu_name)s may have been deleted out of band.  "
"(UDID: %(lu_udid)s)"
msgstr ""
"LU %(lu_name)s(이)가 밴드에서 삭제되었을 수 있음에 대한 HttpError를 무시합니다. "
"(UDID: %(lu_udid)s)"

#: pypowervm/tasks/storage.py:940
#, python-format
msgid ""
"Removing %(num_maps)d orphan %(stg_type)s mappings from VIOS %(vios_name)s."
msgstr ""
"VIOS %(vios_name)s에서 %(num_maps)d orphan %(stg_type)s 맵핑을 제거하는 중입니다. "

#: pypowervm/tasks/storage.py:966
#, python-format
msgid "Removing %(num_maps)d port-less VFC mappings from VIOS %(vios_name)s."
msgstr "VIOS %(vios_name)s에서 포트 없는 %(num_maps)d VFC 맵핑을 제거하는 중입니다."

#: pypowervm/tasks/storage.py:993
#, python-format
msgid ""
"Removing %(num_maps)d %(stg_type)s mappings associated with LPAR ID "
"%(lpar_id)d from VIOS %(vios_name)s."
msgstr ""
"LPAR ID %(lpar_id)d과(와) 연관된 %(num_maps)d개의 %(stg_type)s 맵핑을 "
"VIOS %(vios_name)s에서 제거 중입니다."

#: pypowervm/tasks/storage.py:1060
#, python-format
msgid ""
"Not removing storage %(stg_name)s of type %(stg_type)s because it cannot be "
"determined whether it is still in use.  Manual verification and cleanup may "
"be necessary."
msgstr ""
"아직 사용 중인지 여부를 판별할 수 없으므로 유형 %(stg_type)s의 스토리지 %(stg_name)s을(를) "
"제거하지 않습니다. 수동 확인과 정리가 "
"필요할 수 있습니다. "

#: pypowervm/tasks/storage.py:1071
#, python-format
msgid ""
"Storage scrub ignoring storage element %(stg_name)s because it is of "
"unexpected type %(stg_type)s."
msgstr ""
"스토리지 제거에서 %(stg_name)s 스토리지 요소가 예상하지 못한 "
"%(stg_type)s 유형이기 때문에 무시합니다."

#: pypowervm/tasks/storage.py:1089
#, python-format
msgid ""
"Scrubbing the following %(vdcount)d Virtual Disks from VIOS %(vios)s: "
"%(vdlist)s"
msgstr ""
"VIOS %(vios)s에서 다음 %(vdcount)d 가상 디스크 제거 중: "
"%(vdlist)s"

#: pypowervm/tasks/storage.py:1097
#, python-format
msgid ""
"Scrubbing the following %(vocount)d Virtual Opticals from VIOS %(vios)s: "
"%(volist)s"
msgstr ""
"VIOS %(vios)s에서 다음 %(vocount)d 가상 광학 제거 중: "
"%(volist)s"

#: pypowervm/tasks/storage.py:1168
#, python-format
msgid ""
"Skipping scrub of %(stg_type)s mappings from VIOS %(vios_name)s for the "
"following LPAR IDs because those LPARs exist: %(lpar_ids)s"
msgstr ""
"해당 LPAR가 있으므로 LPAR ID %(lpar_ids)s에 대한 VIOS %(vios_name)s에서 "
" %(stg_type)s 맵핑의 제거를 건너뛰는 중입니다."

#: pypowervm/tasks/vfc_mapper.py:529
#, python-format
msgid ""
"Unable to find appropriate VIOS.  The payload provided was likely "
"insufficient.  The payload data is:\n"
" %s)"
msgstr ""
"적절한 VIOS를 찾을 수 없습니다. 제공된 페이로드가 충분하지 "
"않았을 수 있습니다. 페이로드 데이터는 다음과 같습니다.\n"
" %s)"

#: pypowervm/tasks/vfc_mapper.py:558
#, python-format
msgid ""
"The matched VFC port map has no backing port set. Adding %(port)s to mapping "
"for client wwpns: %(wwpns)s"
msgstr ""
"일치하는 VFC 포트 맵에 백업 포트 세트가 없습니다. 클라이언트 wwpns에 대한 맵핑에 %(port)s을(를) "
"추가 중임: %(wwpns)s"

#: pypowervm/tasks/vopt.py:73
msgid ""
"An error occurred querying the virtual optical media repository.  Attempting "
"to re-establish connection with a virtual optical media repository"
msgstr ""
"가상 광학 매체 저장소를 조회하는 중에 오류가 발생했습니다.  "
"가상 광학 매체 저장소와의 연결을 다시 설정하려고 시도 중입니다. "

#: pypowervm/tasks/vterm.py:85
msgid "Unable to close vterm."
msgstr "vterm을 닫을 수 없습니다."

#: pypowervm/tasks/vterm.py:137
#, python-format
msgid "Invalid output on vterm open.  Trying to reset the vterm.  Error was %s"
msgstr ""
"vterm 열기의 출력이 올바르지 않습니다. vterm을 다시 설정하십시오. 오류: %s"

#: pypowervm/tasks/vterm.py:345
#, python-format
msgid "VNCSocket Listener Listening on ip=%(ip)s port=%(port)s"
msgstr "VNCSocket 리스너가 다음을 청취 중임: ip=%(ip)s 포트=%(port)s"

#: pypowervm/tasks/vterm.py:474
#, python-format
msgid "Error negotiating SSL for VNC Repeater: %s"
msgstr "VNC 리피터의 SSL 조정 중에 오류 발생: %s"

#: pypowervm/tasks/hdisk/_fc.py:197
#, python-format
msgid ""
"hdisk discovery failed; will scrub stale storage for LPAR IDs %s and retry."
msgstr ""
"hdisk 검색에 실패했습니다. LPAR ID %s의 시간이 경과된(stale) 스토리지를 제거하고 재시도합니다. "

#: pypowervm/tasks/hdisk/_fc.py:339
#, python-format
msgid "LUA Recovery Successful. Device Found: %s"
msgstr "LUA 복구 성공. 발견된 장치: %s"

#: pypowervm/tasks/hdisk/_fc.py:343
#, python-format
msgid "ITL Error encountered: %s"
msgstr "ITL 오류 발생: %s"

#: pypowervm/tasks/hdisk/_fc.py:345
#, python-format
msgid "%s Device is currently in use."
msgstr "%s 장치가 현재 사용 중입니다."

#: pypowervm/tasks/hdisk/_fc.py:347
#, python-format
msgid "%s Device discovered with unknown UDID."
msgstr "%s 장치가 알 수 없는 UDID로 검색되었습니다."

#: pypowervm/tasks/hdisk/_fc.py:349
#, python-format
msgid "Failed to Discover the Device : %s"
msgstr "장치 검색 실패: %s"

#: pypowervm/tasks/hdisk/_fc.py:419
#, python-format
msgid "CLIRunner Error: %s"
msgstr "CLIRunner 오류: %s"

#: pypowervm/tasks/hdisk/_fc.py:451
msgid ""
"QUERY_INVENTORY LUARecovery Job succeeded, but result contained neither "
"OutputXML nor StdOut."
msgstr ""
"QUERY_INVENTORY LUARecovery 작업이 성공했지만, 결과에 "
"OutputXML 또는 StdOut이 포함되지 않습니다."

#: pypowervm/tasks/hdisk/_fc.py:475
#, python-format
msgid ""
"QUERY_INVENTORY produced invalid chunk of XML (%(chunk)s).  Error: %(err)s"
msgstr ""
"QUERY_INVENTORY에서 XML의 올바르지 않은 청크(%(chunk)s)를 생성했습니다. 오류: %(err)s"

#: pypowervm/tasks/hdisk/_fc.py:483
#, python-format
msgid ""
"Failed to find pg83 descriptor in XML output:\n"
"%s"
msgstr ""
"XML 출력에서 pg83 디스크립터를 찾지 못함:\n"
"%s"

#: pypowervm/tasks/hdisk/_iscsi.py:73
#, python-format
msgid "Invalid device output: %(dev)s"
msgstr "올바르지 않은 장치 출력: %(dev)s"

#: pypowervm/tasks/hdisk/_iscsi.py:78
#, python-format
msgid "Expected IQN: %(IQN)s not found on iscsi target %(host_ip)s"
msgstr "예상한 %(IQN)s IQN을 iscsi 대상 %(host_ip)s에서 찾을 수 없음"

#: pypowervm/tasks/monitor/util.py:421
msgid ""
"Metric data is not available.  This may be due to the metrics being recently "
"initialized."
msgstr ""
"메트릭 데이터를 사용할 수 없습니다. 이는 메트릭이 최근에 초기화되었기 때문일 수 "
"있습니다. "

#: pypowervm/tests/test_i18n.py:33
msgid "This is a test"
msgstr "테스트입니다."

#: pypowervm/tests/test_i18n.py:36
msgid "This is a message for which a translation doesn't exist"
msgstr "다음은 변환되지 않은 메시지입니다."

#: pypowervm/utils/retry.py:203
#, python-format
msgid ""
"Attempt %(retry)d of total %(total)d for URI %(uri)s.  Error was a known "
"retry response code: %(resp_code)s"
msgstr ""
"URI %(uri)s에 대해 총 %(total)d회 중 %(retry)d회를 시도합니다. 오류는 알려진 "
"재시도 응답 코드입니다. %(resp_code)s"

#: pypowervm/utils/retry.py:210
#, python-format
msgid ""
"Attempt %(retry)d of %(total)d failed.  Will retry. The exception was:\n"
" %(except)s."
msgstr ""
"%(total)d번 중 %(retry)d번 시도에 실패했습니다. 재시도합니다. 예외:\n"
" %(except)s."

#: pypowervm/utils/transaction.py:348
msgid "Must supply either EntryWrapper or EntryWrapperGetter."
msgstr "EntryWrapper 또는 EntryWrapperGetter를 제공해야 합니다."

#: pypowervm/utils/transaction.py:374
msgid "Must supply a valid Subtask."
msgstr "올바른 하위 태스크를 제공해야 합니다."

#: pypowervm/utils/transaction.py:378
#, python-format
msgid "Duplicate 'provides' name %s."
msgstr "'provides' 이름 %s이(가) 중복됩니다."

#: pypowervm/utils/transaction.py:453
#, python-format
msgid "WrapperTask %s has no Subtasks; no-op execution."
msgstr "WrapperTask %s에 하위 태스크가 없습니다. 조작이 실행되지 않습니다."

#: pypowervm/utils/transaction.py:585
msgid "Must supply either a list of EntryWrappers or a FeedGetter."
msgstr "EntryWrappers 또는 FeedGetter의 목록을 제공해야 합니다."

#: pypowervm/utils/transaction.py:764
#, python-format
msgid "FeedTask %s has no Subtasks; no-op execution."
msgstr "FeedTask %s에 하위 태스크가 없습니다. 조작이 실행되지 않습니다."

#: pypowervm/utils/transaction.py:789
#, python-format
msgid ""
"FeedTask %s experienced multiple exceptions. They are logged individually "
"below."
msgstr ""
"FeedTask %s에서 여러 예외가 발생했습니다. 이는 아래에 개별적으로 "
"로깅됩니다."

#: pypowervm/utils/validation.py:161
#, python-format
msgid ""
"Insufficient available %(res_name)s on host for virtual machine "
"'%(instance_name)s' (%(requested)s requested, %(avail)s available)"
msgstr ""
"가상 머신 '%(instance_name)s'에 대한 호스트에서 사용 가능한 %(res_name)s이(가) 충분하지 "
"않음(%(requested)s 요청됨, %(avail)s 사용 가능)"

#: pypowervm/utils/validation.py:189
msgid "memory"
msgstr "메모리"

#: pypowervm/utils/validation.py:210
#, python-format
msgid ""
"The virtual machine must be powered off before changing the minimum or "
"maximum memory. Power off virtual machine %s and try again."
msgstr ""
"최소 또는 최대 프로세서를 변경하기 전에 먼저 가상 머신의 전원을 "
"꺼야 합니다. 가상 머신 %s의 전원을 끄고 다시 시도하십시오. "

#: pypowervm/utils/validation.py:215
#, python-format
msgid ""
"The virtual machine must be powered off before changing the expansion "
"factor. Power off virtual machine %s and try again."
msgstr ""
"확장 요인을 변경하기 전에 가상 머신의 전원을 꺼야 합니다."
" 가상 머신 %s의 전원을 끄고 다시 시도하십시오. "

#: pypowervm/utils/validation.py:302
msgid "CPUs"
msgstr "CPU"

#: pypowervm/utils/validation.py:318
msgid "processing units"
msgstr "처리 장치"

#: pypowervm/utils/validation.py:359
#, python-format
msgid ""
"The virtual machine must be powered off before changing the minimum or "
"maximum processors. Power off virtual machine %s and try again."
msgstr ""
"최소 또는 최대 프로세서를 변경하기 전에 먼저 가상 머신의 전원을 "
"꺼야 합니다. 가상 머신 %s의 전원을 끄고 다시 시도하십시오. "

#: pypowervm/utils/validation.py:369
#, python-format
msgid ""
"The virtual machine must be powered off before changing the minimum or "
"maximum processor units. Power off virtual machine %s and try again."
msgstr ""
"최소 또는 최대 프로세서를 변경하기 전에 먼저 가상 머신의 전원을 "
"꺼야 합니다. 가상 머신 %s의 전원을 끄고 다시 시도하십시오. "

#: pypowervm/utils/validation.py:385
#, python-format
msgid ""
"The virtual machine must be powered off before changing the processor "
"compatibility mode. Power off virtual machine %s and try again."
msgstr ""
"프로세서 호환 모드를 변경하기 전에 먼저 가상 머신의 전원을 "
"꺼야 합니다. 가상 머신 %s의 전원을 끄고 다시 시도하십시오. "

#: pypowervm/utils/validation.py:393
#, python-format
msgid ""
"The virtual machine must be powered off before changing the processing mode. "
"Power off virtual machine %s and try again."
msgstr ""
"처리 모드를 변경하기 전에 우선 가상 머신의 전원을 꺼야 합니다. "
"가상 머신 %s의 전원을 끄고 다시 시도하십시오. "

#: pypowervm/utils/validation.py:422
#, python-format
msgid ""
"The desired processors (%(vcpus)d) cannot be above the maximum allowed "
"processors per partition (%(max_allowed)d) for virtual machine "
"'%(instance_name)s'."
msgstr ""
"원하는 프로세서(%(vcpus)d)가 가상 머신 '%(instance_name)s'에 "
"대해 파티션당 허용되는 최대 프로세서 수(%(max_allowed)d)를 "
"'%(instance_name)s'."

#: pypowervm/utils/validation.py:434
#, python-format
msgid ""
"The maximum processors (%(vcpus)d) cannot be above the maximum system "
"capacity processor limit (%(max_allowed)d) for virtual machine "
"'%(instance_name)s'."
msgstr ""
"최대 프로세서(%(vcpus)d)가 가상 머신 '%(instance_name)s'에 대한 "
"최대 시스템 용량 프로세서 한계(%(max_allowed)d)를 "
"'%(instance_name)s'."

#: pypowervm/utils/validation.py:506
#, python-format
msgid ""
"The virtual machine must be powered off before changing the simplified "
"remote restart capability. Power off virtual machine %s and try again."
msgstr ""
"단순 원격 다시 시작 기능을 변경하기 전에 먼저 가상 머신의 전원을 "
"꺼야 합니다. 가상 머신 %s의 전원을 끄고 다시 시도하십시오. "

#: pypowervm/wrappers/base_partition.py:424
msgid "Partition does not have an active RMC connection."
msgstr "파티션에 활성 RMC 연결이 없습니다."

#: pypowervm/wrappers/base_partition.py:427
#, python-format
msgid "Partition does not have an active DLPAR capability for %s."
msgstr "파티션에 %s에 대한 활성 DLPAR 기능이 없습니다."

#: pypowervm/wrappers/base_partition.py:439
msgid "I/O"
msgstr "I/O"

#: pypowervm/wrappers/base_partition.py:449
msgid "Memory"
msgstr "메모리"

#: pypowervm/wrappers/base_partition.py:459
msgid "Processors"
msgstr "프로세서"

#: pypowervm/wrappers/base_partition.py:639
#, python-format
msgid "Invalid KeylockPos '%s'."
msgstr "올바르지 않은 KeylockPos '%s'입니다."

#: pypowervm/wrappers/base_partition.py:650
#, python-format
msgid "Invalid BootMode '%s'."
msgstr "올바르지 않은 BootMode '%s'."

#: pypowervm/wrappers/base_partition.py:1436
msgid "IOSlot.adapter is deprecated!  Use IOSlot.io_adapter instead."
msgstr "IOSlot.adapter가 더 이상 사용되지 않습니다. 대신 IOSlot.io_adapter를 사용하십시오."

#: pypowervm/wrappers/enterprise_pool.py:143
#, python-format
msgid ""
"Unable to determine master management console MTMS (machine type, model, "
"serial number) from %(identifier)s because no %(param)s was marked as the "
"master console for the pool."
msgstr ""
"마스터 관리 콘솔 MTMS(머신 유형, 모델, 일련 번호)를 "
"%(identifier)s에서 확인할 수 없습니다. 풀의 마스터 콘솔로 표시된 %(param)s이(가) "
"없기 때문입니다."

#: pypowervm/wrappers/entry_wrapper.py:251
msgid "Cannot set uuid."
msgstr "UUID를 설정할 수 없습니다."

#: pypowervm/wrappers/entry_wrapper.py:443
#, python-format
msgid "Cannot convert %(property_name)s='%(value)s' in object %(pvmobject)s"
msgstr "오브젝트 %(pvmobject)s의 %(property_name)s='%(value)s'을(를) 변환할 수 없음"

#: pypowervm/wrappers/entry_wrapper.py:586
msgid ""
"Refusing set href over multiple links.\n"
"Path: %{path}s\n"
"Number of links found: %{nlinks}d"
msgstr ""
"다중 링크에서 href 설정 거부 중입니다.\n"
"경로: %{path}s\n"
"찾은 링크 수: %{nlinks}d"

#: pypowervm/wrappers/entry_wrapper.py:635
msgid "Refusing to construct and wrap an Element without a tag."
msgstr "태그가 없는 요소의 구성 및 랩핑을 거부 중입니다."

#: pypowervm/wrappers/entry_wrapper.py:760
msgid "Response is missing 'entry' property."
msgstr "응답에서 'entry' 특성이 누락되었습니다."

#: pypowervm/wrappers/entry_wrapper.py:774
#, python-format
msgid "Must supply a Response or Entry to wrap.  Got %s"
msgstr "랩핑할 응답 또는 항목을 제공해야 합니다. %s을(를) 가져왔습니다."

#: pypowervm/wrappers/entry_wrapper.py:861
msgid ""
"Developer error: specify 'parent' or ('parent_type' and 'parent_uuid') to "
"retrieve a CHILD object."
msgstr ""
"개발자 오류: CHILD 오브젝트를 검색하려면 'parent' 또는 "
"('parent_type' 및 'parent_uuid')를 지정하십시오."

#: pypowervm/wrappers/entry_wrapper.py:866
msgid "Specify either 'uuid' or 'root_id' when requesting a ROOT object."
msgstr "ROOT 오브젝트를 요청할 경우 'uuid' 또는 'root_id'를 지정하십시오."

#: pypowervm/wrappers/entry_wrapper.py:879
msgid ""
"Both parent_type and parent_uuid are required when retrieving a CHILD feed "
"or entry."
msgstr ""
"CHILD 피드 또는 항목을 검색할 경우 parent_type 및 parent_uuid가 "
"모두 필요합니다. "

#: pypowervm/wrappers/entry_wrapper.py:882
msgid "Specify the parent's UUID via the parent_uuid parameter."
msgstr "parent_uuid 매개변수를 통해 상위의 UUID를 지정하십시오."

#: pypowervm/wrappers/entry_wrapper.py:886
msgid "Specify either 'uuid' or 'child_id' when requesting a CHILD object."
msgstr "CHILD 오브젝트를 요청할 경우 'uuid' 또는 'child_id'를 지정하십시오."

#: pypowervm/wrappers/entry_wrapper.py:1001
msgid "Parent UUID specified without parent type."
msgstr "상위 유형이 없이 지정된 상위 UUID입니다."

#: pypowervm/wrappers/entry_wrapper.py:1004
msgid "The search() method requires exactly one key=value argument."
msgstr "search() 메소드에는 정확히 하나의 키=값 인수가 필요합니다."

#: pypowervm/wrappers/entry_wrapper.py:1035
#, python-format
msgid "Wrapper class %(class)s does not support search key '%(key)s'."
msgstr "랩퍼 클래스 %(class)s이(가) 검색 키 '%(key)s'을(를) 지원하지 않습니다."

#: pypowervm/wrappers/entry_wrapper.py:1135
msgid ""
"The 'xag' parameter to EntryWrapper.update is deprecated!  At best, using it "
"will result in a no-op.  At worst, it will give you incurable etag mismatch "
"errors."
msgstr ""
"EntryWrapper.update에 대한 'xag' 매개변수는 더 이상 사용되지 않습니다! 최상의 경우, 이를 사용하면 "
"조작 없음 결과가 발생합니다. 최악의 경우, 교정할 수 없는 etag 불일치 오류가 "
"발생합니다. "

#: pypowervm/wrappers/entry_wrapper.py:1403
msgid "No such child element."
msgstr "해당 하위 요소가 없습니다."

#: pypowervm/wrappers/entry_wrapper.py:1464
msgid "Cannot set UUID on Wrapper with no Metadata."
msgstr "메타데이터가 없는 랩퍼에서 UUID를 설정할 수 없습니다."

#: pypowervm/wrappers/entry_wrapper.py:1469
#, python-format
msgid "uuid value not valid: %s"
msgstr "UUID 값이 올바르지 않음: %s"

#: pypowervm/wrappers/entry_wrapper.py:1524
msgid "Must specify a Wrapper subclass."
msgstr "랩퍼 서브클래스를 지정해야 합니다."

#: pypowervm/wrappers/entry_wrapper.py:1533
msgid "Must specify both parent class and parent UUID, or neither."
msgstr "상위 클래스 및 상위 UUID를 모두 지정하거나 모두 지정하지 않아야 합니다."

#: pypowervm/wrappers/job.py:276
#, python-format
msgid "Job %(job_id)s monitoring for %(time)i seconds."
msgstr "%(time)i초 동안 %(job_id)s 작업 모니터링 중."

#: pypowervm/wrappers/job.py:327
#, python-format
msgid ""
"Issuing cancel request for job %(job_id)s. Will poll the job indefinitely "
"for termination."
msgstr ""
"작업 %(job_id)s에 대한 취소 요청을 실행하는 중입니다. 종료될 때까지 작업이 무한정 "
"폴링됩니다."

#: pypowervm/wrappers/job.py:343
#, python-format
msgid "Job %s not deleted. Job is in running state."
msgstr "%s 작업이 삭제되지 않았습니다. 작업이 실행 중 상태입니다."

#: pypowervm/wrappers/logical_partition.py:169
msgid "LPAR is not in an active state."
msgstr "LPAR이 활성 상태가 아닙니다."

#: pypowervm/wrappers/logical_partition.py:179
msgid "Target system does not have the IBM i LPAR Mobility Capability."
msgstr "대상 시스템에 IBM i LPAR 이동 기능이 없습니다."

#: pypowervm/wrappers/logical_partition.py:183
msgid "IBM i LPAR does not have restricted I/O."
msgstr "IBM i LPAR에서는 I/O가 제한되지 않습니다."

#: pypowervm/wrappers/logical_partition.py:187
msgid "Source system does not have the IBM i LPAR Mobility Capability."
msgstr "소스 시스템에 IBM i LPAR 이동 기능이 없습니다."

#: pypowervm/wrappers/logical_partition.py:191
msgid "LPAR does not have an active RMC connection."
msgstr "LPAR에 활성 RMC 연결이 없습니다."

#: pypowervm/wrappers/logical_partition.py:194
msgid "LPAR is the management partition"
msgstr "LPAR은 관리 파티션임"

#: pypowervm/wrappers/logical_partition.py:198
msgid "LPAR is not available for LPM due to missing DLPAR capabilities."
msgstr "DLPAR 기능이 누락되어 LPAR을 LPM에 사용할 수 없습니다."

#: pypowervm/wrappers/logical_partition.py:215
#: pypowervm/wrappers/logical_partition.py:224
#: pypowervm/wrappers/logical_partition.py:232
msgid ""
"This is not the property you are looking for.  Use srr_enabled in a NovaLink "
"environment."
msgstr ""
"이는 찾고 있는 특성이 아닙니다. NovaLink 환경에서 srr_enabled를 "
"사용하십시오. "

#: pypowervm/wrappers/logical_partition.py:268
#, python-format
msgid "Invalid IPLSrc '%s'."
msgstr "올바르지 않은 IPLSrc '%s'입니다."

#: pypowervm/wrappers/managed_system.py:428
msgid "This property is deprecated!. Use pci_subsys_dev_id instead."
msgstr "이 특성은 더 이상 사용되지 않습니다! 대신 pci_subsys_dev_id를 사용하십시오."

#: pypowervm/wrappers/managed_system.py:440
msgid "This property is deprecated!. Use pci_rev_id instead."
msgstr "이 특성은 더 이상 사용되지 않습니다! 대신 pci_rev_id를 사용하십시오."

#: pypowervm/wrappers/managed_system.py:456
msgid "This property is deprecated!. Use pci_subsys_vendor_id instead."
msgstr "이 특성은 더 이상 사용되지 않습니다! 대신 pci_subsys_vendor_id를 사용하십시오."

#: pypowervm/wrappers/managed_system.py:468
msgid "This property is deprecated!. Use drc_index instead."
msgstr "이 특성은 더 이상 사용되지 않습니다! 대신 drc_index를 사용하십시오."

#: pypowervm/wrappers/managed_system.py:480
msgid "This property is deprecated!. Use drc_name instead."
msgstr "이 특성은 더 이상 사용되지 않습니다! 대신 drc_name을 사용하십시오."

#: pypowervm/wrappers/storage.py:651
#, python-format
msgid ""
"PV had encoded pg83 descriptor \"%(pg83_raw)s\", but it failed to decode "
"(%(type_error)s)."
msgstr ""
"PV가 pg83 디스크립터 \"%(pg83_raw)s\"을(를) 인코딩했지만 디코드하는 데 "
"(%(type_error)s)."

#: pypowervm/wrappers/virtual_io_server.py:163
msgid ""
"The 'xags' property of the VIOS EntryWrapper class is deprecated!  Please "
"use values from pypowervm.const.XAG instead."
msgstr ""
"VIOS EntryWrapper 클래스의 'xags' 특성이 더 이상 사용되지 않습니다. "
"대신 pypowervm.const.XAG의 값을 사용하십시오."

#: pypowervm/wrappers/virtual_io_server.py:400
msgid "Partition of VIOS type is not LPM capable"
msgstr "VIOS 유형의 파티션에서 LPM을 작동할 수 없음"

#: pypowervm/wrappers/virtual_io_server.py:655
msgid "Can't specify target device LUA without a backing storage device!"
msgstr "지원되는 스토리지 장치 없이 대상 장치 LUA를 지정할 수 없습니다."

# ENGL1SH_VERS10N 13712_53 DO NOT REMOVE OR CHANGE THIS LINE
# T9N_SRC_ID 23
# T9N_SH1P_STR1NG PV133AAP001 2
